bigcommerce/checkout-js

- package-lock.json
- package.json
Release bigcommerce/checkout-sdk-js#2126
> chore(payment): PI-489 bump checkout sdk version

- package-lock.json
- package.json
To release this checkout sdk prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/2149
https://github.com/bigcommerce/checkout-sdk-js/pull/2144
https://github.com/bigcommerce/checkout-sdk-js/pull/2113
Unit tests
CI tests
Checkout sdk loader is working as expected:
The actual checkout sdk version was deployed for every env
> chore(payment): PAYPAL-2888 bump checkout sdk version

- packages/core/src/app/customer/CreateAccountForm.tsx
- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
Trigger customer execution method after creation account in create account form for BT AXO
To be able to trigger PayPal Connect authentication flow right after customer creates an account
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-js/assets/25133454/5113eb42-8b07-44ec-8106-e2bdce079a6f
> feat(payment): PAYPAL-2729 trigger customer execution method after creation account in create account form for BT AXO

- packages/core/src/app/customer/CreateAccountForm.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/LoginForm.spec.tsx
- packages/core/src/app/customer/LoginForm.tsx
- packages/core/src/app/payment/index.ts
- packages/core/src/app/payment/isBraintreeConnectPaymentMethod.ts
- change submit button disable state logic in login form;
- added some tests for the CreateAccount and Login forms due to the changes with execution method;
- updated Customer.tsx file with isBraintreeConnectPaymentMethod to avoid logic duplication;
To keep our code as clean as possible
checkout-sdk: https://github.com/bigcommerce/checkout-js/pull/1449
Unit tests
> fix(payment): PAYPAL-2729 added some tests + refactoring and changed the disable button state logic in login form

- packages/core/src/app/payment/paymentMethod/BraintreePaypalCreditDescription.tsx
Warnings fix
To avoid circular dependencies
The following warnings in the screenshot have been fixed:
Final results:
> fix(payment): PAYPAL-0000 warnings fix

- package-lock.json
- package.json
Bump checkout-sdk from `1.436.0` to `1.437.0`
To release all these:
- https://github.com/bigcommerce/checkout-sdk-js/pull/2151
- https://github.com/bigcommerce/checkout-sdk-js/pull/1994
CircleCI + testing section each PR
> chore(payment): INT-5659 Bump checkout-sdk from `1.436.0` to `1.437.0`

- package-lock.json
- package.json
RELEASE OF https://github.com/bigcommerce/checkout-sdk-js/pull/2153
Fixed not working 3ds challenge for the stored card case when new card form was selected previously
Due to the 3ds issue
> feat(payment): PI-747 load bluesnap script ONLY if it wasn't loaded before

- packages/core/src/app/config/config.mock.ts
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/mapToShippingProps.spec.ts
Remove top limit of 50 cart items to show multi-shipping.
Ship to multiple address should be visible if cart items is greater than 1 and no upper limit.
1. Unit test
2. Manual test
**BEFORE**
https://github.com/bigcommerce/checkout-js/assets/141614330/79b5c819-334f-4f75-879c-b8a3d028f861
**AFTER**
https://github.com/bigcommerce/checkout-js/assets/141614330/9da79de4-28a1-48e0-9752-e168aa7fc626
> fix(checkout): CHECKOUT-5966 Enable multishipping for more than 50 items in cart

- package-lock.json
- package.json
- packages/core/src/app/config/config.mock.ts
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/GuestForm.tsx
- packages/core/src/app/customer/StripeGuestForm.tsx
- packages/core/src/app/privacyPolicy/PrivacyPolicyField.spec.tsx
- packages/core/src/app/privacyPolicy/PrivacyPolicyField.test.tsx
- packages/core/src/app/privacyPolicy/PrivacyPolicyField.tsx
- packages/core/src/scss/components/checkout/customer/_customer.scss
- packages/locale/src/translations/en.json
- packages/test-framework/src/react-testing-library-support/API.mock.ts
- packages/test-utils/src/config.mock.ts
Display automated consent for privacy policy based on the checkout settings.
Reduce friction and provides a better UX for stores using an accelerated checkout product such as PayPal Connect.
https://github.com/bigcommerce/checkout-sdk-js/pull/2155
https://github.com/bigcommerce/checkout-js/assets/88361607/79f04576-187e-468d-82c7-de754667ac68
https://github.com/bigcommerce/checkout-js/assets/88361607/515fd346-e398-434c-8439-ec004cdad09f
https://github.com/bigcommerce/checkout-js/assets/88361607/881883c7-317d-44f6-8f90-2a18096c1831
https://github.com/bigcommerce/checkout-js/assets/88361607/5004b4df-5766-4aa7-9654-ab55aab2ae3a
> feat(checkout): CHECKOUT-7648 Add automated consent for privacy policy

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2163
https://github.com/bigcommerce/checkout-sdk-js/pull/2131
https://github.com/bigcommerce/checkout-sdk-js/pull/2158
https://github.com/bigcommerce/checkout-sdk-js/pull/2161
https://github.com/bigcommerce/checkout-sdk-js/pull/2159
https://github.com/bigcommerce/checkout-sdk-js/pull/2160
Unit tests
Manual tests
Here is a screenshot of working checkout sdk loader cdn:
> chore(payment): PAYPAL-2908 bump checkout sdk version

- package-lock.json
- package.json
Bump sdk version for bluesnap 3ds fix for stored card, billing/shipping state mapping
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2157
> chore(release): PI-747 bump sdk version for bluesnap 3ds fix for stored card, billing/shipping state mapping

- package-lock.json
- package.json
- packages/core/src/app/address/PayPalAxo/usePayPalConnectAddress.ts
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingForm.spec.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/getShippingMethodId.test.tsx
- packages/core/src/app/shipping/getShippingMethodId.ts
- packages/core/src/app/shipping/shippingOption/ShippingOptions.tsx
Create shipping strategy for Braintree Accelerated checkout
To check logged in user and show OTP modal for PayPal Connect users
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/dfb0a7d0-8186-4744-bccc-f8a41b765652
> feat(payment): PAYPAL-2728 create shipping strategy for Braintree AXO

- package-lock.json
- package.json
…with Stripe is resulting in error.
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2148
Merchant reported an error in Stripe Dashboard "You cannot confirm this PaymentIntent because it has already succeeded after being previously confirmed". The error occurred as result of try to confirm already confirmed payment.
tested manually
> chore(payment): PI-626 bump checkout-sdk

- packages/core/src/app/customer/CheckoutButtonContainer.spec.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.tsx
- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
In short: Fixed the issue with wallet buttons on top rendering process.
We had a condition to remove (instead of hiding) all buttons containers to avoid some issues with PayPal Commerce  conflicts between paywall and buttons. This is related for cases when PayPalCommerce enabled on the store. 
So we updated the logic and we remove only PayPal Commerce buttons instead of removing whole container.
Some customers get an error like: '**Unable to create sign-in button without valid container ID**'. 
The error occurs in one scenario:
When the store has PayPalCommerce enabled on the store and the customer goes to payment step and refresh the page.
Unit tests
Manual tests
Before:
https://github.com/bigcommerce/checkout-js/assets/25133454/8d257565-e346-4142-96db-f0f540a3486c
After: …
> fix(payment): PAYPAL-2859 fixed the issue with wallet buttons on top rendering process

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2089
For better separation between payment integrations and core Checkout SDK
tested manually
> chore(payment): PI-516 bump checkout-sdk

- package-lock.json
- package.json
- packages/bluesnap-direct-integration/src/BlueSnapDirectAlternativePaymentMethod.tsx
- packages/core/src/app/payment/Payment.tsx
BluesnapDirect APMs via redirect
https://github.com/bigcommerce/checkout-sdk-js/pull/2171
Additionaly release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2172
Because some of the BluesnapDirect APMs can't work via iframe. so we decided to make APMs payments via redirect
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/fe701760-e40b-448e-b2ae-ab0247a499c1
> feat(checkout): PI-623 BluesnapDirect APMs via redirect

- packages/core/src/app/payment/storedInstrument/mapFromInstrumentCardType.spec.ts
- packages/core/src/app/payment/storedInstrument/mapFromInstrumentCardType.ts
- packages/instrument-utils/src/storedInstrument/mapFromInstrumentCardType/mapFromInstrumentCardType.spec.ts
- packages/instrument-utils/src/storedInstrument/mapFromInstrumentCardType/mapFromInstrumentCardType.ts
Fix of the Diners club logo in the stored cards selector
Due to the absence of the Diners club logo in the stored cards selector
Before fix:
After fix:
> fix(checkout): PI-78 fixed credit card issuer mapping for stored diners club cards

- package-lock.json
- package.json
To deliver checkout-sdk-js code changes
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2142
> feat(payment): PAYPAL-2632 bump checkout-sdk-js version

- package-lock.json
- package.json
PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2177](https://github.com/bigcommerce/checkout-sdk-js/pull/2177)
Preset billing address fields from PP card info
To setup correct billing address for preset payment instrument
Manually tested and unit test
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/2c14a897-b3e7-412a-bb33-4a5759a6ccf7
> chore(payment): PAYPAL-2932 add PayPal billing addresses

- package-lock.json
- package.json
PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2165
> chore(payment): PAYPAL-2843 bump checkout-sdk version

- package-lock.json
- package.json
As part of release checkout-sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/2188
https://github.com/bigcommerce/checkout-sdk-js/pull/2185
https://github.com/bigcommerce/checkout-sdk-js/pull/2184
https://github.com/bigcommerce/checkout-sdk-js/pull/2182
https://github.com/bigcommerce/checkout-sdk-js/pull/2183
Unit tests
Manual tests
CI
Here is a screenshot of checkout-sdk loader:
Also checked that checkout sdk loader was deployed to all envs.
> chore(payment): PAYPAL-2979 bump checkout sdk version

- package-lock.json
- package.json
To apply changes
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2192
> feat(payment): PAYPAL-2947 bump checkout-sdk-js

- webpack.config.js
Fixed the issue with webpack watch failed on linked checkout sdk watch recompilation.
We have a problem with webpack watcher command run with linked checkout-sdk dependency. The webpack command fails all the time on checkout-sdk recompilation and we didn't have any idea why this happens.
By making more digging into the issue we have found that webpack command fails because of the second recompilation what tries to reset global variables with DefinePlugin on app:done event. This happens due to the change in file dependencies change after checkout-sdk recompilation.
When the checkout sdk is unlinked or there are no changes there, the watcher command works good.
Manual tests
Before:
https://github.com/bigcommerce/checkout-js/assets/25133454/6b9091d0-41ba-4813-8615-9efff2de8b87
After: …
> fix(other): PAYPAL-2891 fixed the issue with webpack watch failed on linked checkout sdk watch recompilation

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2191
all tests have paassed
> feat(payment): PI-567 bump checkout-sdk version

- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
Remove wallet buttons in customer step if payment is not required for an order
Presence of wallet buttons in checkout flow if payment is not required for an order causes confusion and causes errors. Hence remove wallet buttons from customer step if payment is not required for an order.
https://github.com/bigcommerce/checkout-js/assets/7134802/6f960cd2-cb0e-42cd-9948-86ae293efb4b
> fix(payment): CHECKOUT-7761 Remove wallet buttons if no payment is required

- package-lock.json
- package.json
Bump checkout-sdk `v1.455.0`.
* https://github.com/bigcommerce/checkout-sdk-js/pull/2180
* CI checks.
> chore(checkout): CHECKOUT-7141 Bump checkout-sdk v1.455

- package-lock.json
- package.json
As part of release checkout sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/2204
Unit tests
Manual tests
> chore(payment): PAYPAL-3061 bump checkout-sdk version

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2199
Klarna started working through redirect again
> chore(payment): PI-569 bump checkout-sdk

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.test.tsx
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.tsx
Fixed the issue with BT AXO payment strategy initializing in the flow with storecredits
Because the strategy was not initialized for cases when the storecredit amount is the same or higher than cart amount, so the strategy just skip the initialization process - this is a right behaviour. But, the strategy does not reinitialize when customer uncheck the storecredit checkbox.
Unit tests
Manual tests
Before:
https://github.com/bigcommerce/checkout-js/assets/25133454/de1780b8-b6f0-45d2-bceb-0c24093852ea
After:
https://github.com/bigcommerce/checkout-js/assets/25133454/8174cb19-5e5a-4904-af32-ee718c31c6ec
> fix(payment): PAYPAL-3060 fixed the issue with BT AXO payment strategy initializing in the flow with storecredits

- package-lock.json
- package.json
Releases:
https://github.com/bigcommerce/checkout-sdk-js/pull/2207
https://github.com/bigcommerce/checkout-sdk-js/pull/2203
> chore(payment): PAYPAL-2926 bump checkout-sdk version

- packages/core/src/app/order/MandateTextComponent.test.tsx
- packages/core/src/app/order/MandateTextComponent.tsx
- packages/core/src/app/order/OrderStatus.spec.tsx
- packages/core/src/app/order/OrderStatus.tsx
- packages/core/src/app/order/PaymentsWithMandates.test.tsx
- packages/core/src/app/order/PaymentsWithMandates.tsx
- packages/locale/src/translations/en.json
Added MandateTextComponent
To show mandate text when it is needed
checkouts-sdk-js PR with adding field to interface https://github.com/bigcommerce/checkout-sdk-js/pull/2192
> feat(payment): PAYPAL-2947 added MandateTextComponent

- package-lock.json
- package.json
Releases: https://github.com/bigcommerce/checkout-sdk-js/pull/2186
> chore(payment): PAYPAL-2844 bump checkout-sdk version

- package-lock.json
- package.json
- packages/locale/src/translations/en.json
Added texts for the adyen boleto ticket
[SDK PR](https://github.com/bigcommerce/checkout-sdk-js/pull/2147)
additionally https://github.com/bigcommerce/checkout-sdk-js/pull/2208
Due to the Adyen-Boleto integration
manually
> feat(checkout): PI-741 added texts for the adyen boleto ticket

- package-lock.json
- package.json
As part of release process: 
https://github.com/bigcommerce/checkout-sdk-js/pull/2206
Unit tests
Manual tests
> chore(payment): PAYPAL-2984 bump checkout sdk version

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeAcceleratedCheckoutCreditCardForm.scss
Updated BT AXO CC component styling
PayPal updated default styles for their component, so it looks a bit odd on BC checkout.
Unit tests
Manual tests
> fix(payment): PAYPAL-2984 updated BT AXO CC component styling

- packages/adyen-integration/src/adyenv2/__snapshots__/AdyenV2PaymentMethod.test.tsx.snap
- packages/adyen-integration/src/adyenv3/__snapshots__/AdyenV3PaymentMethod.test.tsx.snap
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.spec.tsx
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.tsx
Remove sign out link from hosted widget payment component.
[PI-833](https://bigcommercecloud.atlassian.net/browse/PI-833)
Sign out link was showing up for every payment method, but it should only be visible for GooglePay. As GooglePay implementation already contains sign out link, it can be removed from hosted widget payment component.
Before:
After:
[PI-833]: https://bigcommercecloud.atlassian.net/browse/PI-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(payment): PI-833 remove sign out link from hosted widget payment component

- package-lock.json
- package.json
Bump chekout-sdk version
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2196
> chore(payment): PAYPAL-2845 bump chekout-sdk version

- package-lock.json
- package.json
To deploy:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2201](https://github.com/bigcommerce/checkout-sdk-js/pull/2201)
manually tested and unit tests
> chore(payment): PI-758 bump checkout-sdk-js version

- packages/core/src/scss/components/bigcommerce/loading/_loading.scss
- packages/core/src/scss/settings/global/overlay/_overlay.scss
- packages/paypal-commerce-integration/src/PaypalCommerceRatePayPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PaypalCommerceRatePayPaymentMethod.tsx
- packages/ui/src/index.ts
Added loading spinner to ratepay init options
To show loading process when polling mechanism is occurs
@bigcommerce/team-checkout @bc-peng @animesh1987
> feat(payment): PAYPAL-2946 added loading spinner to ratepay init options

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2167
> chore(payment): PAYPAL-2910 bump checkout-sdk version

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/mapToCheckoutProps.ts
- packages/core/src/app/customer/Customer.spec.tsx
We utilized CHECKOUT-4941.account_creation_in_checkout feature to determine if a checkout page allows in-page signup or redirects to a signup page.
Removing this old feature flag
This feature has been fully rolled out, cleaning up.
Existing tests / CI
> refactor(checkout): CHECKOUT-7772 Remove fully rolled out feature account_creation_in_checkout

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2217
https://github.com/bigcommerce/checkout-sdk-js/pull/2216
Unit tests
Manual tests
QA tests
> chore(payment): PAYPAL-3098 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk `v1.467.0`.
* https://github.com/bigcommerce/checkout-sdk-js/pull/2187
* CI checks.
> chore(checkout): checkout-7733 Bump checkout-sdk v1.467.0

- package-lock.json
- package.json
Bump checkout-sdk to v1.468.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2219
Unit tests
Manual tests
> chore(payment): PAYPAL-3099 bump checkout-sdk to v1.468.0

- packages/core/src/app/checkout/Checkout.spec.tsx
- packages/core/src/app/checkout/Checkout.test.tsx
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/CheckoutApp.tsx
- packages/core/src/app/checkout/mapToCheckoutProps.ts
- packages/core/src/app/common/error/SentryErrorLogger.spec.ts
- packages/core/src/app/common/error/SentryErrorLogger.ts
- packages/core/src/app/order/OrderConfirmation.spec.tsx
- packages/core/src/app/order/OrderConfirmation.tsx
- packages/core/src/app/order/OrderConfirmationApp.tsx
- Remove `convertcart` filter for Sentry logging.
- Revert back to the previous structure of `ErrorBoundary`.
- Read sentry sample rate from BCapp template.
We are using [Sentry server side filter ](https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#5-applying-workflows)to discard unwanted issues now.
> If you ["Delete & Discard"](https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#delete--discard) an issue, then future error events with the same fingerprint will not count toward your quota.
- CI checks.
> feat(checkout): CHECKOUT-7763 Remove convertcart filter

- package-lock.json
- package.json
- packages/google-pay-integration/e2e/GooglePayBraintreeInPaymentStep.spec.ts
- Bump checkout-sdk
- skipping the e2e test to avoid blocking the release
Failed e2e test: https://app.circleci.com/pipelines/github/bigcommerce/checkout-js/8215/workflows/8a2dda50-012b-4191-b698-e9538034d7c7/jobs/28189/parallel-runs/0/steps/0-110
There will be another PR prepared with the fixed e2e test. Need to figure out why with e2e test passed successfully with `MODE=RECORD ...` and failed with `MODE=REPLAY ...`. Work on it.
> chore(payment): PAYPAL-3056 bump checkout-sdk

- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
- packages/core/src/scss/components/checkout/customer/_customer.scss
Updated GooglePay and ApplePay button height to be the same as in all other wallet buttons
Google Pay and Apple Pay button have more than 36px height, that differ to other buttons on checkout page
Manual tests
> fix(payment): PAYPAL-3090 updated wallet buttons height to remove differences in styling

- package-lock.json
- package.json
Bump checkout-sdk version to v1.470.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2226
Unit tests
Manual tests
QA tests
> chore(payment): PAYPAL-3090 bump checkout-sdk version to v1.470.1

- packages/core/src/app/address/mapAddressToFormValues.ts
Changed the format of date provided to `new Date(dateString)` function to be separated by year, month and day, i.e. `new Date(year, monthIndex, day)`
As the `new Date(dateString)` gives the time in UTC timezone it displays incorrectly (1 day back) in some timezones, so the change is to display correct date in those timezones.
**Manual test**
**BEFORE**
https://github.com/bigcommerce/checkout-js/assets/141614330/17d569d1-c561-44bd-ba3b-0ecb6fff308d
**AFTER**
https://github.com/bigcommerce/checkout-js/assets/141614330/268a1774-a311-4d78-a78b-ec55fec986b3
> fix(checkout): CHECKOUT-5833 fix date issue in different timezones

- package-lock.json
- package.json
to deploy:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2236](https://github.com/bigcommerce/checkout-sdk-js/pull/2236)
unit tests and manually tested
> chore(payment): PI-976 bump checkout-sdk-js version

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeAcceleratedCheckoutForm.tsx
The easiest way to fix that is to add dependencies to useEffect second parameter, so when there is new instrument list passed in component props, then component will trigger handle select method to autofill instrument select with first PayPal Connect instrument.
When the customer reloads a page in Payment step of checkout page, the component did not fill up the instrument field with first PayPal Connect instrument (did not auto fill it), so the customer needs to select the instrument by himself. However, if the customer fills up a form for the first time starting from customer step, everything works as expected. There was an issue with component update method: there was no dependency in  useEffect method, so component didn’t update after new instruments list pass to component props.
Steps …
> fix(payment): PAYPAL-3143 fixed the issue with PayPal Connect instrument autoselect after page reload

- packages/core/src/app/shipping/StaticConsignment.scss
- packages/paypal-connect-integration/src/PoweredByPaypalConnectLabel.tsx
There was an issue with custom theme that affects PayPal Connect logo styling with display flex
PayPal Connect brainding elements looks wrong on merchants checkout page
Unit tests
Manual tests
Before:
After:
Nothing changed for default Cornerstone Checkout page:
> fix(payment): PAYPAL-3144 fixed the issue with PayPal Connect logo style glitch

- package-lock.json
- package.json
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2239
> feat(payment): PAYPAL-3146 bump checkout-sdk-js

- package-lock.json
- package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2234
https://github.com/bigcommerce/checkout-sdk-js/pull/2237
> chore(payment): PAYPAL-3133 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout sdk version to v1.478.0
As part of checkout sdk release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2240
Unit tests
Manual tests
> chore(payment): PAYPAL-3156 bump checkout sdk version to v1.478.0

- package-lock.json
- package.json
to deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2242](https://github.com/bigcommerce/checkout-sdk-js/pull/2242)
Unit tests and manual testing
> chore(payment): PI-924 bump checkout-sdk-js version

- packages/core/src/app/common/error/ErrorModal.spec.tsx
- packages/core/src/app/common/error/ErrorModal.tsx
- packages/core/src/app/common/error/isHtmlError.tsx
- packages/locale/src/translations/en.json
- packages/payment-integration-api/src/errors/custom-error-types.ts
- packages/payment-integration-api/src/errors/index.ts
- packages/payment-integration-api/src/index.ts
- packages/paypal-commerce-integration/src/PaypalCommerceRatePayPaymentMethod.tsx
Added ability to show ratepay specific errors
To display specific errors for ratepay
> feat(payment): PAYPAL-2975 added ability to show ratepay specific errors

- package-lock.json
- package.json
Bump checkout sdk version to v1.479.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2243
Unit tests
Manual tests
QA test
> chore(payment): PAYPAL-3164 bump checkout sdk version to v1.479.1

- .github/CODEOWNERS
Add localization team as codeowner for translations
So that the localization team can review translation changes made by the translation delivery bot
> chore(other): CHECKOUT-0 Add localization team as codeowner for translations

- package-lock.json
- package.json
bump checkout-sdk version to v1.479.2
https://github.com/bigcommerce/checkout-sdk-js/pull/2245
Unit tests
Manual tests
QA test
> chore(payment): PAYPAL-3190 bump checkout-sdk version to v1.479.2

- packages/checkout-extension/src/ExtensionService.test.tsx
- packages/checkout-extension/src/ExtensionService.ts
- packages/core/src/app/checkout/Checkout.tsx
Optimize Extension Loading with Preloading via `<link>` tag
In the extension project context, we can add all extension URLs to `<head>` within `<link>` tag as soon as we finish loading extensions so that we can shorten the time it takes to display an extension.
https://github.com/bigcommerce/checkout-js/assets/141614330/16f7df69-112d-43d9-8510-305bb74ba492
> feat(checkout): CHECKOUT-7838 preload extension with link tag

- packages/core/src/app/checkout/Checkout.spec.tsx
- packages/core/src/app/checkout/Checkout.tsx
- packages/test-framework/src/fixture/pageObject/playwright/PlaywrightHelper.ts
Remove `isExtensionEnabled` flag and load extensions in parallel to load checkout.
Since the extension is rolled out to 100% now and extensions can be now loaded concurrently to checkout settings.
- CI checks
> feat(checkout): CHECKOUT-7837 Optimize `loadCheckout` and `loadExtensions` for Parallel Execution

- packages/core/src/app/cart/Redeemable.spec.tsx
- packages/core/src/app/cart/Redeemable.tsx
- packages/core/src/app/payment/storeCredit/StoreCreditField.spec.tsx
- packages/core/src/app/payment/storeCredit/StoreCreditField.tsx
Disable inputs for store credits and gift certificates while order is submitting.
To prevent order amount changing while it is submitting, because in such cases we have different amount for payment provider and for Bigcommerce.
Before:
https://github.com/bigcommerce/checkout-js/assets/9430298/283c9558-48b4-417f-a3b6-c94a5038d3d1
https://github.com/bigcommerce/checkout-js/assets/9430298/78915709-173c-4885-8352-c32147fa47e7
> fix(payment): PI-617 prevent certificates applying while order submitting

- package-lock.json
- package.json
Bump checkout-sdk from `1.481.0` to `1.482.0`
> feat(payment): PAYPAL-3175 bump checkout-sdk

- packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
- packages/core/src/app/payment/storedInstrument/isInstrumentFeatureAvailable.spec.ts
- packages/core/src/app/payment/storedInstrument/isInstrumentFeatureAvailable.ts
Now for StripeLink when customer is logged in BC account, the "save this card for future transaction" is not displayed.
Shopper should not have ability to save Stripe Link instruments to BC. Remove checkbox.
Before changes
After changes
> feat(payment): PI-875 [Stripe] Error while try to save Stripe Link stored card as BC vaulted instrument

- package-lock.json
- package.json
- packages/core/src/app/customer/customWalletButton/AmazonPayV2Button.tsx
- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
AmazonPay button width is adjusted properly.
AmazonPay button width in Customer checkout step was not adjusted properly.
1.Before changes 1
2. After changes 1
And 
3. Before changes 2
4. After changes  2
> feat(payment): PI-921 Amazon Pay Button needs to be changed to one with WITHOUT microtext

- packages/core/src/app/checkout/getCheckoutStepStatuses.spec.ts
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/instrument-utils/src/guards/index.ts
- packages/instrument-utils/src/guards/shouldUseStripeLinkByMinimumAmount.spec.ts
- packages/instrument-utils/src/guards/shouldUseStripeLinkByMinimumAmount.ts
- packages/instrument-utils/src/index.ts
Removed Stripe link inititializations for not supported cart amounts
Because with Stripe Link will crash checkout when amount of the card is smaller then Stripe minimum supported value
Before:
After:
https://github.com/bigcommerce/checkout-js/assets/79574476/a9f75d5e-7398-4aa8-b60f-5520061c7428
> feat(payment): PI-1036 removed Stripe link inititializations for not supported cart amounts

- package.json
Delete e2e test report folder before running `build` command.
`webpack` lints the e2e test report file by default, resulting in building failure. 
Therefore, any existing e2e test report should be removed.
Before:
After:
> fix(checkout): CHECKOUT-0000 Avoid linting e2e test report

- package-lock.json
- package.json
- packages/apple-pay-integration/e2e/applepay.spec.ts
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/mapToCheckoutProps.ts
- packages/core/src/app/customer/CheckoutButtonContainer.tsx
Fetch button config when checkout loads
In order to load button payment configs in parallel, move logic to fetch button configs to checkout component.
- CI
- Manual
> feat(payment): CHECKOUT-7901 Fetch button config when checkout loads

- packages/locale/src/translations/en.json
- packages/paypal-commerce-integration/src/PaypalCommerceRatePayPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PaypalCommerceRatePayPaymentMethod.tsx
Added ratepay error for digital item
To show error that digital item can't be payed by ratepay
> feat(payment): PAYPAL-3178 added ratepay error for digital item

- package-lock.json
- package.json
- packages/analytics/src/AnalyticsContext.ts
- packages/analytics/src/AnalyticsProvider.mock.tsx
- packages/analytics/src/AnalyticsProvider.spec.tsx
- packages/analytics/src/AnalyticsProvider.tsx
- packages/checkout-button-integration/src/CheckoutButton.spec.tsx
- packages/checkout-button-integration/src/CheckoutButton.tsx
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/customer/CheckoutButton.spec.tsx
- packages/core/src/app/customer/CheckoutButton.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.spec.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.tsx
- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/WalletButtonV1Resolver.spec.tsx
- packages/core/src/app/customer/WalletButtonV1Resolver.tsx
- packages/core/src/app/customer/customWalletButton/ApplePayButton.spec.tsx
- packages/core/src/app/customer/customWalletButton/ApplePayButton.tsx
- packages/core/src/app/customer/customWalletButton/PayPalCommerceButton.spec.tsx
- packages/core/src/app/customer/customWalletButton/PayPalCommerceButton.tsx
- packages/core/src/app/payment/Payment.tsx
- packages/payment-integration-api/src/CheckoutButtonProps.tsx
P.s.: CI builds fail because related checkout-sdk PR is not in master yet
- added BraintreeConnectTracker implementation to Analytics Provider
- passed onClick callback to all wallet buttons on checkout page (button on top and in customer step)
To be able to track customer events and send some Analytic data to Braintree
checkout-sdk: https://github.com/bigcommerce/checkout-sdk-js/pull/2276
Unit tests
Manual tests
Some screenshots:
> feat(payment): PAYPAL-3229 added BraintreeConnectTracker implementation

- packages/core/src/app/checkout/Checkout.tsx
Filter wallet button providers to get supported methods
Providers like afterpay also implement Remote checkout interface, which can cause issues. Hence filter providers against the list of supported methods.
- CI
> fix(payment): CHECKOUT-7901 Filter button providers

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2257
> feat(payment): PAYPAL-2616 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout js version
As part of release: https://github.com/bigcommerce/checkout-sdk-js/pull/2255
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-2936 bump checkout js version

- package-lock.json
- package.json
to deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2275](https://github.com/bigcommerce/checkout-sdk-js/pull/2275)
unit tests and manually tested
> chore(payment): PI-1148 bump checkout-sdk-js version

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2279
All test passed
> feat(payment): PAYPAL-2612 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk version.
Related PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/2247
> feat(payment): PAYPAL-3124 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk version to v1.499.2
As part of release checkout sdk.
Release contains:
https://github.com/bigcommerce/checkout-sdk-js/pull/2285
https://github.com/bigcommerce/checkout-sdk-js/pull/2288
https://github.com/bigcommerce/checkout-sdk-js/pull/2286
Unit tests
Manual tests
> chore(payment): PAYPAL-3360 bump checkout-sdk version to v1.499.2

- packages/core/src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.spec.tsx
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.tsx
- packages/hosted-credit-card-integration/src/components/HostedCreditCardFieldset/HostedCreditCardFieldset.spec.tsx
- packages/hosted-credit-card-integration/src/components/HostedCreditCardFieldset/HostedCreditCardFieldset.tsx
Add ability to hide card holder name field when payment provider doesn't use it
For new TD Bank integration we don't need this field and should not show unused fields
• When options for specific fields wasn't set
• When card holder name field was enabled manually
• When only card holder name field was disabled
• When card holder name was disabled and card code field was disabled
card holder name field enabled manually or it's value wasn't set
> feat(payment): PI-1148 Hide card holder name from hosted fields form

- packages/analytics/src/AnalyticsProvider.spec.tsx
- packages/analytics/src/AnalyticsProvider.tsx
Removed unnecessary Braintree tracking event (trackStepViewed)
We don't need to track this event for Braintree Connect anymore
Unit tests
CI
> refactor(payment): PAYPAL-3660 removed unnecessary Braintree tracking event (trackStepViewed)

- package-lock.json
- package.json
Bump checkout-sdk version to 1.499.3
https://github.com/bigcommerce/checkout-sdk-js/pull/2291
Unit tests 
Manual tests
> chore(payment): PAYPAL-3660 bump checkout-sdk version to 1.499.3

- package-lock.json
- package.json
Bump checkout sdk version to 1.501.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2292
Unit tests
Manual tests
> chore(payment): PAYPAL-3382 bump checkout sdk version to 1.501.1

- package-lock.json
- package.json
Bump checkout-sdk to v.1.502.0.
As part of release https://github.com/bigcommerce/checkout-sdk-js/pull/2295
Unit tests
Manual tests
> chore(payment): PI-1076 bump checkout-sdk to 1.502.0

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2289
> feat(payment): PAYPAL-2617 bump checkout-sdk version

- packages/core/src/app/customer/CheckoutButtonContainer.tsx
- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
- packages/core/src/scss/components/checkout/customer/_customer.scss
- Remove `initializedMethodIds`.
- Autamatically changing wallet buttons layout based on the number of button divs by using a pure CSS method.
The checkout UI can present the buttons based on the actual div containers, not internal state.
- Desktop auto layout.
https://github.com/bigcommerce/checkout-js/assets/88361607/120f9051-e68e-4771-a869-20ea8f0e3f59
- Desktop responsive layout.
https://github.com/bigcommerce/checkout-js/assets/88361607/9daa4d31-d74f-45f7-9a95-d8ee1eed03ca
- Mobile browser.
> refactor(checkout): CHECKOUT-7948 Wallet Buttons Auto Layout

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2294](https://github.com/bigcommerce/checkout-sdk-js/pull/2294)
unit test and manually tested
> chore(payment): PI-1126 bump checkout-sdk-js version

- packages/payment-integration-api/src/PaymentMethodId.ts
Added PayPalCommerceAcceleratedCheckout to PaymentMethodId enum
As part of PayPal Commerce Accelerated Checkout implementation
> feat(payment): PAYPAL-3404 added PayPalCommerceAcceleratedCheckout to PaymentMethodId enum

- packages/paypal-connect-integration/src/index.ts
- packages/paypal-connect-integration/src/is-braintree-connect-method.test.ts
- packages/paypal-connect-integration/src/is-braintree-connect-method.ts
- packages/paypal-connect-integration/src/is-paypal-commerce-connect-method.test.ts
- packages/paypal-connect-integration/src/is-paypal-commerce-connect-method.ts
- packages/paypal-connect-integration/src/is-paypal-connect-method.test.ts
- packages/paypal-connect-integration/src/is-paypal-connect-method.ts
Added isPayPalCommerceConnect method to paypal-connect-integration package
To be able to run some functionality only for paypal commerce accelerated checkout provider
Unit tests
CI tests
Manual tests
> feat(payment): PAYPAL-3404 added isPayPalCommerceConnect method to paypal-connect-integration package

- package-lock.json
- package.json
bump checkout-sdk version to v1.505.2
https://github.com/bigcommerce/checkout-sdk-js/pull/2300
https://github.com/bigcommerce/checkout-sdk-js/pull/2282
https://github.com/bigcommerce/checkout-sdk-js/pull/2299
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3408 bump checkout-sdk version to v1.505.2

- packages/core/src/app/customer/Customer.tsx
Updated some conditions to call customer execute method after sign in/up only for Braintree AXO in Customer component
Execution method should not be called for PPCP AXO (PayPal Commerce Connect / PayPal Commerce Accelerated Checkout) after sign in/up
Manual tests
CI tests
> feat(payment): PAYPAL-3404 updated some conditions to call customer execute method after sign in/up only for Braintree AXO in Customer component

- package-lock.json
- package.json
To deploy PRs:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2296](https://github.com/bigcommerce/checkout-sdk-js/pull/2296)
[https://github.com/bigcommerce/checkout-sdk-js/pull/2302](https://github.com/bigcommerce/checkout-sdk-js/pull/2302)
manually tested and unit test
> chore(payment): PI-1318 bump checkout-sdk-js version

- packages/core/src/scss/components/checkout/ratepayForm/_ratepayForm.scss
Fixed ratepay fields layout
To render ratepay fields properly on every screen size
https://github.com/bigcommerce/checkout-js/assets/56301104/0281d711-33b8-463b-8d69-8c5b6bd235e3
> feat(payment): PAYPAL-3391 fixed ratepay fields layout

- package-lock.json
- package.json
Bump checkout sdk version to v1.511.0
As part of release checkout-sdk pr:
https://github.com/bigcommerce/checkout-sdk-js/pull/2308
Unit tests
CI
> chore(payment): PAYPAL-3418 bump checkout sdk version to v1.511.0

- package-lock.json
- package.json
Bump checkout-sdk to v1.152.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2306
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3409 bump checkout-sdk to v1.152.0

- package-lock.json
- package.json
Bump checkout-sdk to v1.513.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2105
> chore(payment): PAYPAL-2800 bump checkout-sdk to v1.513.0

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2304
> feat(payment): PAYPAL-3300 bump checkout-sdk version

- package-lock.json
- package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2315
For better separation between payment integrations and core Checkout SDK
Unit tests
Manual tests
> chore(payment): PI-1328 bump checkout-sdk

- package-lock.json
- package.json
As part of checkout sdk release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2312
https://github.com/bigcommerce/checkout-sdk-js/pull/2317
https://github.com/bigcommerce/checkout-sdk-js/pull/2316
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3405 bump checkout-sdk version

- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
Refetch available payment methods list after total amount change
Some providers have available payment methods based on total amount of the cart
For example:
For Mollie we get list of available payment methods from Mollie API (on BigPay side)
and for different amount we can get different payment methods list
• amount [0.01...10000] we will receive [card, APM1, APM2, ...]
• amount 0 -> [card]
• amount more then 10000$ will return [APM1, APM2 ...]
thats why we need to refresh available payment providers  list each time when total amount changes
https://github.com/bigcommerce/checkout-js/assets/9430298/78097dff-b3b8-4ad1-8c10-734f331b298c
> fix(payment): PI-1329 update payment methods after total amount change

- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/payment/getProviderWithCustomCheckout.test.ts
- packages/core/src/app/payment/getProviderWithCustomCheckout.ts
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/getShippingMethodId.ts
Added getProviderWithCustomCheckout method to be able to change `paypalcommerce` method id to `paypalcommerceacceleratedcheckout`. This change fixes an issue with initialising PPCP AXO customer strategy for a control group that makes PPCP Connect initialisation.
For PPCP AXO A/B testing we manipulating with `providerWithCustomCheckout` checkout config and switch ppcp payment methods based on PPCP AXO BE module state (on/off). So in both cases we should initialise PPCP AXO customer strategy using `paypalcommerceacceleratedcheckout`, because `paypalcommerce` is responsible for rendering wallet button in customer step.
Unit tests
CI tests
> feat(payment): PAYPAL-3468 added providerWithCustomCheckout mapper

- package-lock.json
- package.json
Bump checkout-sdk version to 1.517.6
To keep checkout-sdk dependency up to date.
The release contains: 
https://github.com/bigcommerce/checkout-sdk-js/pull/2324 and revert for it https://github.com/bigcommerce/checkout-sdk-js/pull/2332
https://github.com/bigcommerce/checkout-sdk-js/pull/2325
https://github.com/bigcommerce/checkout-sdk-js/pull/2326
https://github.com/bigcommerce/checkout-sdk-js/pull/2323 and revert for it https://github.com/bigcommerce/checkout-sdk-js/pull/2329
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-000 bump checkout-sdk version to 1.517.6

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2327
> feat(payment): PAYPAL-3470 bump checkout-sdk version

- package-lock.json
- package.json
Revert "feat(payment): PI-429 [Adyen] Improve FE validation for APMs on checkout"
Due to the issue with https://github.com/bigcommerce/checkout-sdk-js/pull/2260
Credit card payment was broken for Adyen
> Revert "feat(payment): PI-429 [Adyen] Improve FE validation for APMs on checkout"

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/hooks/useBraintreeAcceleratedCheckoutInstruments.ts
- packages/paypal-commerce-integration/src/PayPalCommerceAcceleratedCheckout/hooks/usePayPalCommerceAcceleratedCheckoutInstruments.ts
- packages/paypal-connect-integration/.eslintrc.json
- packages/paypal-connect-integration/src/index.ts
- packages/paypal-connect-integration/src/is-paypal-connect-payment-provider-customer.test.ts
- packages/paypal-connect-integration/src/is-paypal-connect-payment-provider-customer.ts
- packages/paypal-connect-integration/src/usePayPalConnectAddress.ts
Fixed the issue with updated checkout sdk types by adding typeguards in different places
To be able to bump checkout sdk version, remove typescript errors and get sucessful CI build
Unit tests
Manual tests
Checkout-js local build success screenshot:
> fix(payment): PAYPAL-3466 fixed the issue with updated checkout sdk types by adding typeguards in different places

- package-lock.json
- package.json
Bump checkout sdk version to 1.519.2
To keep checkout-sdk dependency up to date:
https://github.com/bigcommerce/checkout-sdk-js/pull/2330
https://github.com/bigcommerce/checkout-sdk-js/pull/2334
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3466 bump checkout sdk version to 1.519.2

- package-lock.json
- package.json
do deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2331](https://github.com/bigcommerce/checkout-sdk-js/pull/2331)
> chore(payment): PI-1309 bump checkout-sdk-js version

- packages/instrument-utils/src/storedInstrument/InstrumentSelect/InstrumentSelect.tsx
Fix credit cards brands mapper function
To use correct [mapper function](https://github.com/bigcommerce/checkout-js/blob/master/packages/instrument-utils/src/storedInstrument/mapFromInstrumentCardType/mapFromInstrumentCardType.ts) from current package with actual brands list.
Fix icon for Diners Club cards
Before:
After:
> fix(payment): PI-1256 fix icon for diners_club stored card

- package-lock.json
- package.json
- packages/analytics/src/AnalyticsProvider.spec.tsx
- packages/analytics/src/AnalyticsProvider.tsx
Added PayPalCommerceConnect analytic implementation
To be able to track paypal connect related events on UI side
https://github.com/bigcommerce/checkout-sdk-js/pull/2333
Manual tests
Unit tests
CI
Payment method selected event (on a paywall):
Wallet button selected event:
Email submitted event:
Order placed event:
> feat(payment): PAYPAL-3423 added PayPalCommerceConnect analytic implementation

- packages/core/src/app/shipping/SingleShippingForm.spec.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Added `shouldHaveCustomValidation` function to define the validation flow
Accelerated Checkout should use the default validation flow
Manual testing
> feat(payment): PAYPAL-3446 Shipping address form isn't validated when Accelerated Checkout is enabled

- packages/core/src/app/shipping/getShippingMethodId.test.tsx
- packages/core/src/app/shipping/getShippingMethodId.ts
Added PayPalCommerceAcceleratedCheckout method id to shipping strategy method id mapper
To be able to initialise PayPalCommerceAcceleratedCheckout shipping strategy when providerWithCustomCheckout is `paypalcommerceacceleratedcheckout`
Unit tests
Manual tests
> feat(payment): PAYPAL-3419 added PPCP AXO method id to shipping strategy method id mapper

- packages/paypal-commerce-integration/src/PaypalCommerceRatePayPaymentMethod.tsx
Enabled submit button after error
To enable submit button for another try
**Before**
https://github.com/bigcommerce/checkout-js/assets/56301104/f8cf6a34-aa14-44aa-a1cd-59e0627c569e
**After**
https://github.com/bigcommerce/checkout-js/assets/56301104/2fddce09-563f-46ae-8150-d1d2104cea6e
> feat(payment): PAYPAL-3469 enable submit button after error

- package-lock.json
- package.json
- packages/core/src/app/payment/hostedCreditCard/HostedCreditCardValidation.spec.tsx
- packages/core/src/app/payment/hostedCreditCard/HostedCreditCardValidation.tsx
- packages/core/src/app/payment/hostedCreditCard/getHostedInstrumentValidationSchema.spec.ts
- packages/core/src/app/payment/hostedCreditCard/getHostedInstrumentValidationSchema.ts
- packages/core/src/app/payment/hostedCreditCard/withHostedPayPalCommerceCreditCardFieldset.spec.tsx
- packages/core/src/app/payment/hostedCreditCard/withHostedPayPalCommerceCreditCardFieldset.tsx
- packages/core/src/app/payment/paymentMethod/PaypalCommerceCreditCardPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/PaypalCommerceCreditCardPaymentMethod.tsx
A specific form for PPCP Credit Card  with untrusted shipping address. Added an additional `expiry` field.
Because there are three required fields (number, cvv, expiry) needed for PPCP Card Fields API. 
> feat(payment): PAYPAL-3373 created a specific form for PPCP Credit Card strategy

- package-lock.json
- package.json
Bump ckeckout-sdk version
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2301
> feat(payment): PAYPAL-3113 bump ckeckout-sdk version

- package-lock.json
- package.json
bump checkout sdk version to 1.530.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2339
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3419 bump checkout sdk version to 1.530.0

- packages/core/src/app/customer/Customer.tsx
Added PP Connect user authentication for cases when customer sign in or sign up on checkout page
For PP Connect customer's to be able to prefill checkout form with PP Connect data
Unit tests
Manual tests
CI
Here is a screen record for sign in flow:
https://github.com/bigcommerce/checkout-js/assets/25133454/2c8faa00-4b47-4ed9-9a80-e379de4c4d60
Also a screenshot of working sign up flow:
> feat(payment): PAYPAL-3499 authenticate user with PayPal Connect after sing in/up

- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
Fixed the issue with analytic tracking of selected payment method on payment step load
When the form is loaded we have different payment method selected by default, but it is not the same that provided to analytics tracking method on payment step first load. This issue occurs because prev default payment method provided to tracking method instead of actual one.
Manual tests
CI
Before:
After:
> fix(payment): PAYPAL-3519 fixed the issue with analytic tracking of selected payment method on payment step load

- .github/CODEOWNERS
Extend codeownership of package.json and package-lock.json file
In order for payment integration teams to become autonomous it will be nice for teams to own checkout SDK bumps.
- CI
> chore(others): CHECKOUT-000 Extend codeownership of package json

- package-lock.json
- package.json
Bump checkout sdk version to 1.533.0
As part of checkout sdk release:
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3560 bump checkout sdk version to 1.533.0

- packages/paypal-connect-integration/src/is-paypal-commerce-connect-method.test.ts
- packages/paypal-connect-integration/src/is-paypal-commerce-connect-method.ts
Updated paypal commerce connect method mapping
To be able to show address select with addresses from PP Connect for customer in shipping and billing steps
Unit tests
Manual tests
CI
> fix(payment): PAYPAL-3560 updated paypal commerce connect method mapping

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2350](https://github.com/bigcommerce/checkout-sdk-js/pull/2350)
manually tested and unit tetst
> chore(payment): PI-1487 bump checkout-sdk-js version

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2354
> feat(payment): PAYPAL-3405 bump checkout-sdk version

- packages/core/src/app/orderComments/OrderComments.tsx
Added the missing ID attribute to the Order Comment input
To match the label and fix accessibility issues
> fix(checkout): Add missing Order Comments input id

- README.md
Update Readme to reflect that UNIX-based operating systems, for a Windows user means Windows Subsystem for Linux.
It often comes up in issues, thus it seems we could be more explicit about what that means for Windows users
N/A
> chore(others): CHECKOUT-000 Update README.md

- package-lock.json
- package.json
Bump checkout sdk version to 1.540.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2362
https://github.com/bigcommerce/checkout-sdk-js/pull/2361
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3573 bump checkout sdk version to 1.540.0

- package-lock.json
- package.json
Bump checkout-sdk version to 1.543.0
As part of checkout sdk release. The release contains:
https://github.com/bigcommerce/checkout-sdk-js/pull/2364
https://github.com/bigcommerce/checkout-sdk-js/pull/2366
https://github.com/bigcommerce/checkout-sdk-js/pull/2363
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3574 bump checkout-sdk version to 1.543.0

- packages/core/src/app/customer/CreateAccountForm.tsx
- packages/core/src/app/customer/Customer.tsx
Fix issue with subscription checkbox not selected.
In the account create form the value passed for newsletter checkbox field is not respected. Since we never used to read that value, it's addressed in this PR to set value for form field from the setting
- Screencast
https://github.com/bigcommerce/checkout-js/assets/7134802/0f703c68-7204-49d4-b23d-a1b2a110e00e
https://github.com/bigcommerce/checkout-js/assets/7134802/7917cc61-8764-48c1-98a9-23dfb499f3e4
> fix(customer): CHECKOUT-8033 Fix issue with subscription checkbox not selected

- .github/CODEOWNERS
- packages/core/src/app/customer/EmailLoginForm.spec.tsx
- packages/core/src/app/customer/EmailLoginForm.tsx
- packages/locale/src/translations/en.json
Remove email address from sign in link on passwordless login form.
The customer’s passwordless login error message reveals whether or not a user has an account with the BC store. This might give an attacker insight to customers emails in the store allowing for potential other attack vectors.
- CI
> fix(customer): CHECKOUT-8073 Remove email address from message on sign in link

- package-lock.json
- package.json
bump checkout-sdk version to 1.545.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2377
https://github.com/bigcommerce/checkout-sdk-js/pull/2376
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3646 bump checkout-sdk version to 1.545.0

- package-lock.json
- package.json
Bump checkout sdk version to 1.546.0
As part of checkout sdk release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2380
https://github.com/bigcommerce/checkout-sdk-js/pull/2379
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3683 bump checkout sdk version to 1.546.0

- packages/instrument-utils/src/storedInstrument/InstrumentStoreAsDefaultField/InstrumentStoreAsDefaultField.test.tsx
- packages/instrument-utils/src/storedInstrument/InstrumentStoreAsDefaultField/InstrumentStoreAsDefaultField.tsx
Fixed vaulting checkboxes
To make vaulting checkboxes work properly
**BEFORE**
https://github.com/bigcommerce/checkout-js/assets/56301104/0898f422-1799-4a88-b99c-f725e790cb77
**AFTER**
https://github.com/bigcommerce/checkout-js/assets/56301104/e62e0a36-b137-42d5-aaa6-ddaf0d626c62
> fix(payment): PAYPAL-3566 fixed vaulting checkboxes

- package-lock.json
- package.json
- packages/analytics/src/AnalyticsProvider.spec.tsx
- packages/analytics/src/AnalyticsProvider.tsx
Renamed PayPalCommerceConnectTracker with PayPalCommerceAnalyticTracker
Due to the changes on checkout sdk side:
https://github.com/bigcommerce/checkout-sdk-js/pull/2385
Unit tests
Local project commands run
CI
> refactor(payment): PAYPAL-3602 renamed PayPalCommerceConnectTracker with PayPalCommerceAnalyticTracker

- packages/bluesnap-direct-integration/jest.config.js
- packages/bluesnap-direct-integration/src/validation-schemas/getEcpValidationSchema.ts
- packages/locale/src/translations/en.json
Fixed bluesnap direct ecp validation, fixed package test coverage
Due to the wrong bluesnap direct validation, [Bluesnap doc ](https://developers.bluesnap.com/v8976-JSON/reference/ecp-transaction#request)
Coverage:
> fix(payment): PI-1656 fixed bluesnap direct ecp validation, fixed package test coverage

- package-lock.json
- package.json
Bump checkout-sdk version to `1.550.0`
Release contains: https://github.com/bigcommerce/checkout-sdk-js/pull/2386
> feat(payment): PAYPAL-3705 bump checkout-sdk version

- package-lock.json
- package.json
To update code
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2388
> feat(payment): PAYPAL-3585 bumped checkout-sdk-js version

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeAcceleratedCheckoutInstrumentSelect.test.tsx
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeAcceleratedCheckoutInstrumentSelect.tsx
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/__snapshots__/BraintreeAcceleratedCheckoutInstrumentSelect.test.tsx.snap
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/hooks/useBraintreeAcceleratedCheckoutInstruments.ts
- packages/core/src/app/address/AddressSelect.spec.tsx
- packages/core/src/app/address/AddressSelect.tsx
- packages/core/src/app/address/StaticAddress.spec.tsx
- packages/core/src/app/address/StaticAddress.tsx
- packages/core/src/app/billing/BillingForm.spec.tsx
- packages/core/src/app/billing/BillingForm.tsx
- packages/core/src/app/billing/StaticBillingAddress.spec.tsx
- packages/core/src/app/billing/StaticBillingAddress.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/shipping/ShippingForm.spec.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/StaticConsignment.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneInstrumentsForm.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/hooks/usePayPalCommerceFastlaneInstruments.ts
- packages/paypal-fastlane-integration/src/index.ts
- packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.ts
Renamed different PayPal Connect methods from paypal-fastlane-integration package
As part of PayPal Connect to Fastlane rebranding
Unit tests
CI
> refactor(payment): PAYPAL-3597 renamed different paypal connect methods from paypal-fastlane-integration package

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2390](https://github.com/bigcommerce/checkout-sdk-js/pull/2390)
manually tested and unit test
> chore(payment): PI-1679 bump checkout-sdk-js

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/GuestForm.tsx
- packages/core/src/app/customer/SubscribeSessionStorage.test.ts
- packages/core/src/app/customer/SubscribeSessionStorage.ts
Use session storage to save subscription status.
Once a user checks/unchecks the subscription checkbox and move and moves to next step. We send the relevant call to subscription API, but if the page refreshes we lose the state of subscription.
If the user goes back to customer step the state of checkbox is defaults to initial settings, which can be confusing for the user. 
- CI 
- Screencast 
https://github.com/bigcommerce/checkout-js/assets/7134802/77923f83-73cb-4212-b0ea-a6c97b862a16
> fix(checkout): CHECKOUT-8049 Use session storage to save subscription status in frontend

- package-lock.json
- package.json
Bump checkout sdk version to 1.557.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2393
https://github.com/bigcommerce/checkout-sdk-js/pull/2392
https://github.com/bigcommerce/checkout-sdk-js/pull/2395
Unit tests
CI
> chore(payment): PAYPAL-3743 bump checkout sdk version to 1.557.1

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2397](https://github.com/bigcommerce/checkout-sdk-js/pull/2397)
> chore(payment): PI-1736 bump checkout-sdk-js version

- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
Allow editing of Billing Address for eWallet Buttons flow
Because of PayPal is not returning all required billing information for buyer accounts and hence upon order placement shoppers receive an error as they can’t return to the billing step and edit the billing information
> feat(payment): PAYPAL-3447 Allow editing of Billing Address for eWallet Buttons flow

- package-lock.json
- package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2319
> fix(payment): PI-1287 bump checkout-sdk version

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2411](https://github.com/bigcommerce/checkout-sdk-js/pull/2411)
Manually tested and unit test
> chore(payment): PI-1138 bump checkout-sdk-js

- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneInstrumentsForm.scss
Updated paypal commerce fastlane instrument details css class name
Previously we updated PayPal Commerce related component style class names but forgot to update naming in scss file
Manual tests
Before:
After:
> fix(payment): PAYPAL-3849 updated paypal commerce fastlane instrument details css class name

- package-lock.json
- package.json
Bump checkout-sdk version to 1.563.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2413
https://github.com/bigcommerce/checkout-sdk-js/pull/2416
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3774 bump checkout-sdk version to 1.563.0

- package-lock.json
- package.json
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.test.tsx
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.tsx
Updated Braintree Accelerated Checkout payment strategy to support Fastlane + Connect
To integrate BT Fastlane
> feat(payment): PAYPAL-3586 Update Braintree Accelerated Checkout payment strategy to support Fastlane + Connect

- .circleci/config.yml
Adding GItleaks (secret scanner).
For secrets detection to prevent accidental commits of secrets
Passing of existing CI builds with gitleaks succesfully running as part of the process.
> chore(checkout): CHECKOUT-0 - Add Gitleaks to CircleCI

- .circleci/config.yml
Fixing config for secret scanning
So it doesn't break a scan on a fork
Check CI results below
> chore(checkout): CHECKOUT-0 Don't scanned forked

- package-lock.json
- package.json
- packages/credit-card-integration/src/CreditCardPaymentMethodComponent.tsx
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.tsx
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.tsx
- packages/instrument-utils/src/guards/isInstrumentCardCodeRequired/isInstrumentCardCodeRequired.spec.ts
- packages/instrument-utils/src/guards/isInstrumentCardCodeRequired/isInstrumentCardCodeRequired.ts
- packages/instrument-utils/src/guards/isInstrumentCardNumberRequired/isInstrumentCardNumberRequired.spec.ts
- packages/instrument-utils/src/guards/isInstrumentCardNumberRequired/isInstrumentCardNumberRequired.ts
- packages/instrument-utils/src/guards/isInstrumentCardNumberRequiredSelector.ts
Remove unused vaulted cards validation fields
Some payment providers like TDBank generate single one time token based on whole credit card fields. In this case we can't get token for card verification based on only one or two card fields and then can't verify card without token or data from provider iFrames.
So in this case we need to hide card verification fields to not show unused fields and to not confuse shoppers.
Provider without fields properties in initialisation data, both fields should be shown by default:
Provider with only Card Code validation field (Card number field disabled):
Provider with only Card Number validation field (Card Code field disabled):
Provider with both fields disabled:
Provider with both fields enabled:
> feat(payment): PI-1841 removed unused card validation fields

- package-lock.json
- package.json
Bump checkout-sdk from 1.568.3 to 1.570.0
Related prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/2429
https://github.com/bigcommerce/checkout-sdk-js/pull/2431
> feat(payment): PAYPAL-3910 PAYPAL-3881 bump checkout-sdk version

- package-lock.json
- package.json
to deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2396](https://github.com/bigcommerce/checkout-sdk-js/pull/2396)
unit test and manually tested
> chore(payment): PI-1726 bump checkout-sdk-js

- package-lock.json
- package.json
to deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2436](https://github.com/bigcommerce/checkout-sdk-js/pull/2436)
> chore(payment): PI-1899 bump checkout-sdk-js

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2434
All test passed
> feat(payment): PAYPAL-3850 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout sdk version to 1.575.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2443
https://github.com/bigcommerce/checkout-sdk-js/pull/2441
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3896 bump checkout sdk version to 1.575.0

- package-lock.json
- package.json
Bumped checkout-js version
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2437
Tested on dev, unit tests
> feat(payment): PAYPAL-3587 bumped checkout-js version

- package-lock.json
- package.json
Release of the checkout-sdk revert https://github.com/bigcommerce/checkout-sdk-js/pull/2449
Due to the revert
> chore(checkout): PI-1558 revert checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk version to 1.577.2
https://github.com/bigcommerce/checkout-sdk-js/pull/2448
https://github.com/bigcommerce/checkout-sdk-js/pull/2447
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3736 bump checkout-sdk version to 1.577.2

- package-lock.json
- package.json
As above
Release https://github.com/bigcommerce/checkout-sdk-js/pull/2440
- CI
> chore(other): CHECKOUT-8132 Update checkout-sdk version

- scripts/sdk-live-checker.sh
Improve output of scripts/sdk-live-checker.sh
Currently, when this fails, it doesn't show any meaningful output. That means you have to go to the script itself and check what it might have done and where it failed
While running, `npm ci` still shows the following:
The result shown:
CI output on this PR:
> chore(other): CHECKOUT-8177 Improve output of scripts/sdk-live-checker.sh

- package-lock.json
- package.json
Bump checkout-sdk version to 1.579.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2456
Unit tests
Manual tests
CI
PayPal Commerce Fastlane:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/df1808a7-64aa-42be-9749-2b8f55837bbc
Braintree Fastlane:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/e42a1a38-284b-4445-ab13-4a8462b5b025
> chore(payment): PAYPAL-4001 bump checkout-sdk version to 1.579.0

- package-lock.json
- package.json
Bump checkout-sdk version to `1.580.0`
Release contains: https://github.com/bigcommerce/checkout-sdk-js/pull/2457
> feat(payment): PAYPAL-3997 bump checkout-sdk to version 1.580.0

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2455
> feat(payment): PAYPAL-3850 bump checkout-sdk

- package-lock.json
- package.json
As part of the release: https://github.com/bigcommerce/checkout-sdk-js/pull/2453
Unit + manual tests
> chore(payment): PI-1606 bump checkout-sdk version

- packages/braintree-integration/src/BraintreeAch/components/BraintreeAchPaymentForm.tsx
- packages/braintree-integration/src/BraintreeAch/hooks/useBraintreeAchValidation.ts
Fix of Braintree ACH validation
To be able place an order using a vaulted ACH account
https://github.com/bigcommerce/checkout-js/assets/99336044/e6c4db5f-70bd-4643-927d-6893af78fb42
> feat(payment): Placing order with Vaulted ACH account on checkout doesn't work

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2458
> feat(payment): PAYPAL-4032 bump checkout-sdk version

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2452
Due to the google pay refactoring
[Testing section](https://github.com/bigcommerce/checkout-sdk-js/pull/2452) 
> chore(payment): PI-650 bump checkout-sdk version

- package-lock.json
- package.json
Revert SDK to 1.582.2.
Using an older SDK version to determine if the problem is with the SDK release. 
CI checks.
> fix(checkout): CHECKOUT-0000 Revert SDK to 1.582.2

- package-lock.json
- package.json
Bump checkout sdk version to 1.585.2
https://github.com/bigcommerce/checkout-sdk-js/pull/2468
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-000 bump checkout version to 1.585.2

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2477](https://github.com/bigcommerce/checkout-sdk-js/pull/2477)
Manually tested and unit tests
> chore(payment): PI-1925 bump checkout-sdk-js

- package-lock.json
- package.json
Part of release: https://github.com/bigcommerce/checkout-sdk-js/pull/2446
Unit + manual testing
> chore(payment): PI-1606 bump checkout-sdk

- package-lock.json
- package.json
Bump checkout-sdk version to 1.591.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2479
https://github.com/bigcommerce/checkout-sdk-js/pull/2480
Unit tests
Manual tests
CI
All proofs video proofs can be found in both checkout-sdk PRs
> chore(payment): PAYPAL-4082 bump checkout-sdk version to 1.591.0

- packages/core/src/app/payment/hostedCreditCard/withHostedPayPalCommerceCreditCardFieldset.spec.tsx
- packages/core/src/app/payment/hostedCreditCard/withHostedPayPalCommerceCreditCardFieldset.tsx
Separate flags for rendering verification fields replaced by one `shouldRenderHostedFieldsWithInstrument`
Because PPCP Card Fields will work only if we have all three containers for fields (number, cvv, expiry).
> feat(payment): PAYPAL-4081 PPCP Credit Card verification fields fix

- package-lock.json
- package.json
Bump checkout-sdk version to 1.592.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2490
https://github.com/bigcommerce/checkout-sdk-js/pull/2481
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4088 bump checkout-sdk version to 1.592.1

- packages/core/src/app/payment/PaymentSubmitButton.test.tsx
- packages/core/src/app/payment/PaymentSubmitButton.tsx
Updated submit button text with Place order while customer pays with PPCP account vaulted instrument
To avoid customer confusion while pays with PayPal stored instrument
Unit tests
Manual tests
CI
Before:
After:
> fix(payment): PAYPAL-4090 updated submit button text with Place order while customer pays with PPCP account vaulted instrument

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2433
For better separation between payment integrations and core Checkout SDK
Manually tested 
https://github.com/bigcommerce/checkout-js/assets/130039975/ab1aafc6-b760-43b3-aa91-e45f189520f2
> chore(payment): PI-1831 bump checkout-sdk

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2484
https://github.com/bigcommerce/checkout-sdk-js/pull/2483
Due to the GooglePay refactoring
https://github.com/bigcommerce/checkout-sdk-js/pull/2484
https://github.com/bigcommerce/checkout-sdk-js/pull/2483
> refactor(payment): PI-1901 release of checkout-sdk

- package-lock.json
- package.json
As a part of the release: https://github.com/bigcommerce/checkout-sdk-js/pull/2491
Unit + manual testing
> chore(payment): PI-000 bump checkout sdk to v1.596.0

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2501
> feat(payment): PAYPAL-4111 bump checkout-sdk version

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2496
Due to the google pay refactoring
[Testing proof](https://github.com/bigcommerce/checkout-sdk-js/pull/2496) 
> refactor(payment): PI-1558 release checkout-sdk

- package-lock.json
- package.json
To release: 
https://github.com/bigcommerce/checkout-sdk-js/pull/2506
https://github.com/bigcommerce/checkout-sdk-js/pull/2469
> feat(payment): PAYPAL-4123 bump sdk version

- packages/core/src/app/address/StaticAddress.tsx
- packages/core/src/app/address/index.ts
- packages/locale/src/address.mock.ts
- packages/locale/src/countries.mock.ts
- packages/locale/src/index.ts
- packages/locale/src/localizeAddress.test.ts
- packages/locale/src/localizeAddress.ts
localizeAddress moved from `core` to shared `locale` package
Because we need to use this method out of `core` package
> feat(payment): PAYPAL-4066 localizeAddress moved to shared package

- package-lock.json
- package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2503
> feat(payment): PAYPAL-2624 bump checkout-sdk version

- packages/locale/src/translations/en.json
Update the “Pay in 4 installments” language to “Pay in installments” (removing the 4) for US merchants at checkout
before:
after:
> feat(payment): PI-2090 Zip (Quadpay) - Change Checkout Button Language

- packages/core/src/app/payment/getProviderWithCustomCheckout.test.ts
- packages/core/src/app/payment/getProviderWithCustomCheckout.ts
Added extra mapping for `paypalcommercecreditcards` methodId to convert it to `paypalcommerceacceleratedcheckout`
During PPCP Fastlane Shipping Component testing we faced with the issue, that component does not render for cases when the page was loaded for unrecognised user. In this case BE sets paypalcommercecreditcards as providerWithCustomCheckout what does not have a right mapping to match the condition for component rendering.
So the solution is to add right methodId mapping to be able to render shipping component.
Unit tests
CI
> fix(payment): PAYPAL-4208 added extra mapping for paypalcommercecreditcards methodId

- package-lock.json
- package.json
To update code 
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2517
https://github.com/bigcommerce/checkout-js/assets/56301104/f37cd4de-c60b-4d59-903e-66c1ec8c03e1
> feat(payment): PAYPAL-4173 bumped checkout-sdk-js version

- packages/core/src/app/customer/GuestForm.tsx
- packages/core/src/app/customer/StripeGuestForm.tsx
- packages/core/src/app/customer/__snapshots__/Customer.spec.tsx.snap
- packages/core/src/app/customer/__snapshots__/GuestForm.spec.tsx.snap
- packages/core/src/app/customer/__snapshots__/StripeGuestForm.test.tsx.snap
Add `tabIndex` and `role="button"` to `#checkout-customer-index`
As proposed in #1412 adding these properties will allow screen readers and keyboard users to focus the 'Sign in now` Link
> fix(checkout): CHECKOUT-000 Add focus to checkout-customer-login

- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.spec.tsx
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.tsx
Fixed hosted input styling for providers that doesn't need cvv verification
Due to our mechanics to get Stencil styles in the checkout we need to mount hidden input and from that we're taking styles.
We use cvv input as an element where we should mount that hidden input for the stored card .
Some providers like BluesnapDirect don't have such input so we should mount it near the card number input.
Before fix:
After fix:
> fix(payment): PI-2103 fix bluesnap direct styling

- package-lock.json
- package.json
Part of the release: https://github.com/bigcommerce/checkout-sdk-js/pull/2529
Unit + manual tests
> chore(payment): PI-1596 bump checkout sdk

- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
Removed unnecessary `executePaymentMethodCheckout` on sign in and sign up related to Fastlane experience
PayPal Fastlane does not support store members experience, so there is no need to call `executePaymentMethodCheckout` anymore
Unit tests
Manual tests
CI
The result of the work:
On sign up and sign in customer does not get Fastlane experience
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/2f182853-f98d-4d0a-b0fa-cbc54a689ccf
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/bcaf0e59-29b0-4752-b86f-503e22f41b8e
> refactor(payment): PAYPAL-4283 removed unnecessary executePaymentMethodCheckout on sign in and sign up

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeFastlaneInstrumentsForm.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneInstrumentsForm.tsx
Fixed the issue with MasterCard card icon display in PPCP and BT FastlaneInstrumentsForm
There was an issue with card icon mapping because PayPal returns `MASTER_CARD` key
Manual tests
Before:
After:
> fix(payment): PAYPAL-4139 fixed the issue with mastercard card icon dispay in Fastlane Instruments Form

- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/PayPalCommerceFastlanePaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/PayPalCommerceFastlanePaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneForm.tsx
Removed unnecessary PayPal Connect code form PPCP payment method
As part of PayPal Connect cleanup
Unit tests
CI
> refactor(payment): PAYPAL-3599 removed unnecessary PayPal Connect code form PPCP payment method

- package-lock.json
- package.json
Bump checkout sdk version to 1.618.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2537
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4294 bump checkout sdk version to 1.618.1

- package-lock.json
- package.json
Mollie ApplePay fix
release of https://github.com/bigcommerce/checkout-sdk-js/pull/2543
Mollie ApplePay works via Mollie Redirect, so our ApplePay implementation is not working with Mollie.
I've changed Mollie payment strategy resolver to fix this problem
Before fix:
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/88e7c41a-6853-4283-8870-bdf3498d73cb
After fix:
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/d865b987-307a-4457-8afd-2adcbd3781f6
> fix(payment): PI-831 fixed mollie ApplePay redirect

- package-lock.json
- package.json
Release https://github.com/bigcommerce/checkout-sdk-js/pull/2540
Unit + manual testing
> chore(payment): PI-2161 bump checkout sdk

- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
Updated customer step loading state to be able to continue with checkout even if wallet button is in loading state
Some users have pretty bad internet connection which might increase time for waiting on wallet buttons initialization. Therefore, it might be better to make wallet buttons loading state as an optional, to avoid blocking user from checkout.
Manual tests was made with Network throttling 3g slow to emulate slow internet connection
CI
[Before] Continue button is disabled until wallet buttons finish their initialisation process: 
https://github.com/bigcommerce/checkout-js/assets/25133454/00b9c3e5-1965-4824-9231-2fbdf9b7839d
[After] Continue button is not disabled and can be used by customer even if wallet buttons still initialising on the page: …
> fix(payment): PAYPAL-4248 updated customer step loading state to be able to continue with checkout even if wallet button is in loading state

- package-lock.json
- package.json
Bump checkout-sdk version to 1.620.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2542
https://github.com/bigcommerce/checkout-sdk-js/pull/2541
https://github.com/bigcommerce/checkout-sdk-js/pull/2538
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3273 bump checkout-sdk version to 1.620.0

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2545
> feat(payment): PAYPAL-4292 bump checkout-sdk version

- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
Adjusted AmazonPay button styling.
After changing button design back to one with microtext, at Customer step the microtext is overlaping the button. This only occurs in Customer step as here we are setting all accelerated checkout buttons (paypal, gpay, amazonPay) height to 36px. 
**Before:**
**After:**
> feat(payment): PI-2177 Pay with Amazon Button display issues at checkout

- package-lock.json
- package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2527
Removed all code related to the GooglePay from the core package in the Checkout-sdk
test section in the https://github.com/bigcommerce/checkout-sdk-js/pull/2527
> refactor(checkout): PI-2169 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk version to 1.622.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2546
https://github.com/bigcommerce/checkout-sdk-js/pull/2533
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-3600 bump checkout-sdk version to 1.622.1

- packages/core/src/app/checkout/Checkout.test.tsx
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
- packages/core/src/app/common/utility/index.ts
- packages/core/src/app/common/utility/isCustomShippingEnabled.ts
- packages/core/src/app/common/utility/isExperimentEnabled.ts
- packages/core/src/app/shipping/hasSelectedShippingOptions.ts
- packages/test-framework/src/react-testing-library-support/API.mock.ts
- packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
Display custom shipping method created by manual order UI on the storefront checkout page.
Support the use of a custom shipping method.
Opening a draft order with a custom shipping method will jump to the payment step directly.
https://github.com/bigcommerce/checkout-js/assets/88361607/78e2ac4b-1245-41d4-9897-d39b820e6cc3
The edit button of the shipping step appears on the page.
> feat(checkout): CHECKOUT-2368 Display Custom Shipping Method

- .github/CODEOWNERS
- packages/ui/src/loading/LoadingSpinner.tsx
- packages/wallet-button-integration/.eslintrc.json
- packages/wallet-button-integration/README.md
- packages/wallet-button-integration/jest.config.js
- packages/wallet-button-integration/project.json
- packages/wallet-button-integration/src/WalletButtonPaymentMethodComponent.test.tsx
- packages/wallet-button-integration/src/WalletButtonPaymentMethodComponent.tsx
- packages/wallet-button-integration/src/index.ts
- packages/wallet-button-integration/src/normalizeWalletPaymentData.ts
- packages/wallet-button-integration/src/types.ts
- packages/wallet-button-integration/tsconfig.json
- packages/wallet-button-integration/tsconfig.lib.json
- packages/wallet-button-integration/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
Moved WalletButton Component to the separate package.
I haven't removed WalletButton Component from the core yet. It will be removed after the refactoring of the "core" payment methods that use him.
It's easier to review when you compare new module with [older one](https://github.com/bigcommerce/checkout-js/blob/master/packages/core/src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx)
Due to the monorepo refactoring, it needed for further GooglePay, VisaCheckout, etc refactoring.
> refactor(checkout): PI-2297 moved WalletButton component to separate package

- package-lock.json
- package.json
To deploy PRs:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2551](https://github.com/bigcommerce/checkout-sdk-js/pull/2551)
[https://github.com/bigcommerce/checkout-sdk-js/pull/2550](https://github.com/bigcommerce/checkout-sdk-js/pull/2550)
[https://github.com/bigcommerce/checkout-sdk-js/pull/2553](https://github.com/bigcommerce/checkout-sdk-js/pull/2553)
> chore(payment): STRIPE-385 bump checkout-sdk-js

- package-lock.json
- package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2555
https://github.com/bigcommerce/checkout-sdk-js/pull/2552
> feat(payment): PAYPAL-2613 bump checkout-sdk

- package-lock.json
- package.json
- packages/google-pay-integration/src/GooglePayButton.tsx
checkout-sdk part: https://github.com/bigcommerce/checkout-sdk-js/pull/2557
Add Google Pay on TD Online Mart in button payment step
As a merchant I want to be able to offer my shoppers Google Pay wallet through TD Online Mart
Work on backend part of this project is not started yet. Therefore added part of the code will not execute before BE part will be ready.
> feat(payment): PI-2284 Add Google Pay on TD Online Mart - checkout customer step

- package-lock.json
- package.json
Bump checkout-sdk to latest version.
Release https://github.com/bigcommerce/checkout-sdk-js/pull/2566
- CI
> chore(other): CHECKOUT-8392 Update checkout sdk

- package-lock.json
- package.json
Bump checkout-sdk version to 1.630.1
Due to: https://github.com/bigcommerce/checkout-sdk-js/pull/2568
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4379 bump checkout-sdk version to 1.630.1

- packages/core/src/app/cart/CartSummary.tsx
- packages/core/src/app/cart/mapToCartSummaryProps.ts
- packages/core/src/app/cart/withRedeemable.tsx
- packages/core/src/app/order/OrderConfirmation.tsx
- packages/core/src/app/order/OrderSummaryDrawer.spec.tsx
- packages/core/src/app/order/OrderSummaryDrawer.tsx
- packages/core/src/app/order/OrderSummaryModal.spec.tsx
- packages/core/src/app/order/OrderSummaryModal.tsx
- packages/core/src/app/order/OrderSummarySubtotals.tsx
- packages/core/src/app/order/__snapshots__/OrderSummaryModal.spec.tsx.snap
- Fix item count display on order summary modal in small screens.
- Remove experiment `CHECKOUT-7403.updated_cart_summary_modal`
- To fix the  item count display on order summary modal on small screens for bundled items.
- `CHECKOUT-7403.updated_cart_summary_modal` is rolled out 100% from a year
**BEFORE**
**AFTER**
> CHECKOUT-8434: Fix item count display for bundled items

- package-lock.json
- package.json
Bump checkout sdk version to 1.633.0
As part of release checkout-sdk prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/2576
https://github.com/bigcommerce/checkout-sdk-js/pull/2575
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4441 bump checkout sdk version to 1.633.0

- package-lock.json
- package.json
Bump checkout-sdk version to `1.633.1`
As part of the release https://github.com/bigcommerce/checkout-sdk-js/pull/2573
> feat(payment): STRIPE-329 bump checkout-sdk version

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2548](https://github.com/bigcommerce/checkout-sdk-js/pull/2548)
Manual tested and unit test
> chore(payment): STRIPE-378 bump checkout-sdk-js

- packages/adyen-integration/src/adyenv3/AdyenV3PaymentMethod.test.tsx
Fix blocked pipeline
Due to the colision between previous releases
-
> chore(checkout): PI-0000 fix blocked pipeline

- packages/core/src/app/customer/EmailWatermark.test.tsx
- packages/core/src/app/customer/EmailWatermark.tsx
- packages/core/src/app/customer/GuestForm.spec.tsx
- packages/core/src/app/customer/GuestForm.tsx
- packages/core/src/app/customer/index.ts
- packages/core/src/scss/components/checkout/customer/_customer.scss
- packages/paypal-fastlane-integration/src/index.ts
- packages/paypal-fastlane-integration/src/is-fastlane-window.test.ts
- packages/paypal-fastlane-integration/src/is-fastlane-window.ts
Added Fastlane Privacy Settings component
To display fastlane privacy settings
https://github.com/user-attachments/assets/23f5eea9-699c-43fd-9a90-49e5b27eaeb1
With Fastlane Privacy Settings Feature Torned Off
> feat(payment): PAYPAL-4406 added Fastlane Privacy Settings

- package-lock.json
- package.json
Bump checkout sdk version to 1.636.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2578
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4488 bump checkout sdk version to 1.636.0

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2586
> feat(payment): PAYPAL-4524 bump checkout-sdk

- packages/core/src/app/billing/Billing.tsx
- packages/core/src/app/shipping/Shipping.tsx
Remove experiment wrapping for code to add autocomplete for UK addresses.
We have rolled out google maps support for UK addresses for one year now, so seems like a good opportunity for removing the experiment code wrapping the change.
- CI 
> chore(other): CHECKOUT-8509 Remove experiment wrapping code for CHECKOUT-4183.checkout_google_address_autocomplete_uk

- packages/core/src/app/shipping/ItemAddressSelect.tsx
- packages/core/src/app/shipping/MultiShippingForm.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
Remove experiment wrapping for adding new address for multi shipping
We added support for adding addresses in multi shipping mode https://github.com/bigcommerce/checkout-js/pull/501 3 years ago, and have since rolled out the experiment. Hence removing the experiment wrapping code.
- CI
> chore(other): CHECKOUT-8513 Remove experiment wrapping for adding new address for multi shipping

- package-lock.json
- package.json
- packages/core/src/app/shipping/itemsRequireShipping.spec.ts
- packages/core/src/app/shipping/itemsRequireShipping.ts
- Remove experiment code related to enabling shipping for custom items
- Bump SDK with related change https://github.com/bigcommerce/checkout-sdk-js/pull/2595
- Release https://github.com/bigcommerce/checkout-sdk-js/pull/2594 which was bumped before
Remove experiment code related to enabling shipping for custom items, feature flag has been ramped up across platform for a while.
- CI
> chore(common): CHECKOUT-8523 Remove experiment code for CHECKOUT-4936_enable_custom_item_shipping

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2599](https://github.com/bigcommerce/checkout-sdk-js/pull/2599)
manually tested and unit test
> chore(payment): STRIPE-421 bump checkout-sdk-js

- .github/CODEOWNERS
- package-lock.json
- package.json
- packages/stripe-integration/src/stripe/StripeUPEPaymentMethod.tsx
Added Klarna id to the Stripe gateway.
Related PR: https://github.com/bigcommerce/checkout-js/pull/1956
Because we cannot open Klarna tab without this fix.
Before:
https://github.com/user-attachments/assets/d09e87c1-d413-461b-b583-516177ab2680
After:
https://github.com/user-attachments/assets/c5159738-c8f3-4f5b-b103-c2d4dd936e92
> fix(payment): STRIPE-384 added Klarna id to the Stripe gateway

- package-lock.json
- package.json
- packages/stripe-integration/e2e/support/stripeUPE.mock.js
Bump checkout-sdk-version
Add mock for stripe events payload
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2611](https://github.com/bigcommerce/checkout-sdk-js/pull/2611)
> chore(payment): STRIPE-422 bump checkout-sdk-js

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2606
> feat(payment): PAYPAL-4550 bump checkout-sdk

- package-lock.json
- package.json
Bump checkout-sdk version to 1.645.2
https://github.com/bigcommerce/checkout-sdk-js/pull/2613
https://github.com/bigcommerce/checkout-sdk-js/pull/2614
Manual tests
Unit tests
CI
> chore(payment): PAYPAL-000 bump checkout-sdk version to 1.645.2

- packages/core/src/app/shipping/ShippingForm.spec.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
Fixed the issue with using addresses from address book for logged in shoppers when Fastlane is enabled
Fastlane is a feature which should be available for Guest shoppers only. Therefore for Logged in shoppers the checkout flow should have default (core) behaviour.
Manual tests
Unit tests
CI
Before:
https://github.com/user-attachments/assets/61970d9d-4b04-478d-bd37-77cb381711c6
After:
https://github.com/user-attachments/assets/5dda1a03-555c-4506-9594-ac253888faa7
> fix(payment): PAYPAL-4582 fixed the issue with using addresses from address book for logged in shoppers when Fastlane is enabled

- packages/core/src/app/customer/CreateAccountForm.spec.tsx
- packages/locale/src/translations/en.json
Remove string override for regex validation
We return the correct translated message as part of password requirements from checkout settings API, and the translation in checkout app can be incorrect so it's better to use API message. Merchants can still override theme files.
- CI
> fix(customer): CHECKOUT-8559 Remove string override for customer password validation error

- packages/core/src/app/common/form/index.ts
- packages/core/src/app/common/form/withFormikExtended.test.tsx
- packages/core/src/app/common/form/withFormikExtended.tsx
- packages/core/src/app/shipping/MultiShippingForm.spec.tsx
- packages/core/src/app/shipping/MultiShippingForm.tsx
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingForm.spec.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/ShippingFormFooter.tsx
- packages/core/src/app/shipping/SingleShippingForm.test.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
- packages/core/src/app/shipping/shippingOption/ShippingOptions.tsx
- packages/core/src/app/shipping/shippingOption/ShippingOptionsForm.spec.tsx
- packages/core/src/app/shipping/shippingOption/ShippingOptionsForm.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingForm.tsx
Add the `withFormikExtended` HOC, which extends the behaviour of the default `withFormik` HOC. This enhancement allows a Formik form to be reset once its initial value is loaded, enabling it to render even before the initial value is ready. Without this functionality, the form might not be able to submit if its `isInitialValid` check requires the initial value to be present.
This is necessary because some checkout extensions are located inside Formik forms. To render these extensions before their parent forms are fully loaded, we need a way to reinitialise the forms once the required data is ready, as explained above.
This video shows that the shopper cannot submit the form because it is rendered before the initial value is loaded. Consequently, the `isInitialValid` check marks the form …
> CHECKOUT-8300: Reset Formik form once initial value is loaded in the shipping step

- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
Disable steps on checkout page when order is being submitted
On the checkout page, selecting “Place Order” and then immediately attempting to edit the Billing details will result in the payment gateway infinitely attempting to load, which causes confusion. Hence disable clicking on fields and sections while an order is being submitted.
- Screencast
- CI
https://github.com/user-attachments/assets/15916767-c804-4228-bec3-93ea49138a79
> fix(checkout): CHECKOUT-8503 Disable steps on checkout page when order is being submitted

- package-lock.json
- package.json
Bump checkout sdk version to 1.653.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2635
https://github.com/bigcommerce/checkout-sdk-js/pull/2636
https://github.com/bigcommerce/checkout-sdk-js/pull/2634
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4645 bump checkout sdk version to 1.653.0

- package-lock.json
- package.json
Bump checkout-sdk to 1.655.1
As part of release checkout-sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/2638
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4662 bump checkout-sdk to 1.655.1

- package-lock.json
- package.json
Bump checkout-sdk version to 1.655.2
https://github.com/bigcommerce/checkout-sdk-js/pull/2641
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4649 bump checkout-sdk version to 1.655.2

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2640](https://github.com/bigcommerce/checkout-sdk-js/pull/2640)
> chore(payment): PI-2548 bump checkout-sdk-js

- package-lock.json
- package.json
To update code
checkout-sdk-js PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/2645
https://github.com/bigcommerce/checkout-sdk-js/pull/2644
Unit tests
> chore(payment): PAYPAL-4594 bumped checkout-sdk-js version

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2642](https://github.com/bigcommerce/checkout-sdk-js/pull/2642)
> chore(payment): PI-2549 bump checkout-sdk-js

- package-lock.json
- package.json
To deliver artifacts:
https://github.com/bigcommerce/checkout-sdk-js/pull/2632
> chore(payment): PAYPAL-4610 bump checkout-sdk version

- package-lock.json
- package.json
Fixed submit payment for the Digital River
[SDK PR](https://github.com/bigcommerce/checkout-sdk-js/pull/2649)
Due to the issue with Payment execution
Before the fix:
https://github.com/user-attachments/assets/abdbaf71-5cf1-4c56-9af2-f6fc56a3f850
After the fix:
https://github.com/user-attachments/assets/b96eb4d5-ca87-449f-92d9-9ba99fbc2f3c
> fix(checkout): PI-2623 fixed submit payment for the Digital River

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2647](https://github.com/bigcommerce/checkout-sdk-js/pull/2647)
> chore(payment): PI-2550 bump checkout-sdk-js

- packages/core/src/app/shipping/ShippingForm.spec.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.ts
Removed unnecessary Fastlane shipping strategy initialization
Recently for Fastlane we supported 2 different shipping flow:
1. Fastlane user uses core checkout shipping component (when experiment is disabled);
2. Fastlane user uses Fastlane shipping component (when experiment is enabled);
Since testing passed successfully and the feature was rolled out to all tiers couple months ago, we to cleanup some code just to keep feature working as it should.
Unit tests
Manual tests
CI
https://github.com/user-attachments/assets/789b20fc-4ac3-473c-abe6-2d900b61cc23
> refactor(payment): PAYPAL-4157 removed unnecessary Fastlane shipping strategy initialization

- package-lock.json
- package.json
Bump checkout-sdk version - 1.658.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2652
Unit tests
CI
> chore(payment): PAYPAL-4580 bump checkout-sdk version - 1.658.1

- package-lock.json
- package.json
To update code
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2654
Unit tests
> chore(payment): PAYPAL-4591 bumped checkout-sdk-js version

- packages/checkout-button-integration/src/CheckoutButton.tsx
- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
- packages/core/src/scss/components/checkout/customer/_customer.scss
- packages/google-pay-integration/src/GooglePayButton.scss
- packages/google-pay-integration/src/GooglePayButton.spec.tsx
- packages/google-pay-integration/src/GooglePayButton.tsx
- packages/payment-integration-api/src/CheckoutButtonProps.tsx
Fixed the issue with Google Pay button styling on top of checkout page
Because Google Pay button had different to other buttons style what did not match overall buttons styling on checkout page
Manual tests
1 button:
2 buttons:
3 buttons:
4 buttons:
5 buttons:
6 buttons:
> fix(payment): PAYPAL-4646 fixed the issue with Google Pay button styling on top of checkout page

- package-lock.json
- package.json
Bump checkout sdk version to 1.659.1
As part of revert:
https://github.com/bigcommerce/checkout-sdk-js/pull/2656
CI
> chore(payment): PAYPAL-4591 bump checkout sdk version to 1.659.1

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2653
> chore(payment): PAYPAL-4611 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk version to 1.661.1
To release the revert: 
https://github.com/bigcommerce/checkout-sdk-js/pull/2663
Manual tests
> chore(payment): PAYPAL-4716 bump checkout-sdk version to 1.661.1

- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/SingleShippingForm.test.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Moved the shipping address form value change detection into the debounce function.
This ensures that the API call to fetch available shipping options is only triggered when the form values (like the postcode) have been updated and the user has stopped typing.
Turn off experiment `CHECKOUT-8006.move_check_updated_address_value_within_debounced`
- PostCode: `2000` - Free Shipping  
- PostCode: `20001` - Flat rate $6.65  
When changing the postcode and switching back quickly, different shipping options were displayed due to immediate API calls.  
https://github.com/user-attachments/assets/54b3ec36-88dd-46ee-ba16-8ff692cb0e5c  
Now, the shipping options only update after typing has stopped, ensuring accuracy in the options displayed. Additionally, while the shipping options are refreshing, …
> fix(checkout): CHECKOUT-8006 Optimise Shipping Option Updates

- packages/core/src/app/loader.spec.ts
- packages/core/src/app/loader.ts
- scripts/webpack/index.js
- scripts/webpack/merge-manifests.js
- scripts/webpack/transform-manifest.js
- webpack.config.js
Include integrity hashes in `manifest.json` to be added to the scripts and stylesheets used during checkout. Any script or stylesheet that doesn't match its corresponding subresource integrity hash ([SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)) will not be executed.
To comply with the script integrity requirement ([6.4.3](https://www.pcisecuritystandards.org/wp-content/uploads/2023/09/05.Scaling-6.4.3-and-11.6.1-Browser-Script-Management-and-The-Large-Enterprise-Journey-to-Compliance.pdf)) of PCI4, which ensures that scripts executed during checkout have not been tampered with by a malicious attacker.
> CHECKOUT-8519: Load scripts with integrity hashes to meet PCI4 requirements

- package-lock.json
- package.json
Bump checkout-sdk `v1.661.6`.
* https://github.com/bigcommerce/checkout-sdk-js/pull/2668
* CI checks.
> chore(checkout): CHECKOUT-8653 Bump checkout-sdk

- packages/core/src/app/loader.spec.ts
- packages/core/src/app/loader.ts
Enable integrity hashes when `CHECKOUT-8519.add_integrity_hash_and_csp_nonce_to_checkout` experiment is on
I realised this change (#2020) is not gated by the experiment.
Scripts are loaded with integrity hashes
Scripts are not loaded with integrity hashes
> CHECKOUT-8519: Enable integrity hashes when experiment is on

- package-lock.json
- package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2669
> chore(payment): PAYPAL-4681 bump checkout-sdk

- webpack.config.js
Skip merging manifest files if the build is unsuccessful. Otherwise, compilation errors will not be displayed in the console during development.
> CHECKOUT-8519: Skip merging manifest files if the build is unsuccessful so Webpack can output compilation error

- package-lock.json
- package.json
Bumped chechout-sdk-js version
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2670
Unit tests
> chore(payment): PAYPAL-4704 bumped checkout-sdk-js version

- packages/core/src/app/payment/paymentMethod/PaymentMethodList.spec.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodList.tsx
- packages/core/src/app/ui/form/CustomChecklistItem.test.tsx
- packages/core/src/app/ui/form/CustomChecklistItem.tsx
- packages/core/src/app/ui/form/index.ts
Add Custom Checklist item.
To use it on payments step. For payment methods that don't need checklist header and all logic for checklist selection, and have all this logic on provider side. For example new Stripe implementation.
https://github.com/user-attachments/assets/e79bfd32-e011-4649-9c7e-c78763b57fad
Unit tests and manually tested.
> feat(payment): STRIPE-460 Add custom list item

- package-lock.json
- package.json
Bump checkout-sdk to `1.668.0`
As part of the release https://github.com/bigcommerce/checkout-sdk-js/pull/2692
> feat(payment): STRIPE-473 bump checkout-sdk to 1.668.0

- package-lock.json
- package.json
- packages/core/src/app/loader.spec.ts
- packages/core/src/app/loader.ts
Switch the translation library used by `checkout-sdk` from `messageformat` to `intl-messageformat` when `isCspNonceExperimentEnabled` is true.
So that it could be compatible with a stricter CSP header. See https://github.com/bigcommerce/checkout-sdk-js/pull/2674 for more details.
See related PR
> CHECKOUT-8519: Switch `messageformat` library when experiment is enabled

- package-lock.json
- package.json
- packages/core/src/app/formFields/getCustomFormFieldsValidationSchema.ts
Upgrade `yup` to a version that doesn't trigger CSP error.
`yup` depends on an old version of `property-expr`, which evaluates arbitrary strings as JavaScript. The newer version of `yup` uses a version of `property-expr` that doesn't use `eval` anymore (see https://github.com/jquense/expr/pull/11).
I decided not to upgrade to the latest version of `yup` for now because it has several breaking changes (see https://github.com/jquense/yup/blob/master/CHANGELOG.md)
This screenshot shows that `property-expr` package triggers CSP error when there is`script-src` policy.
This screenshot shows that `property-expr` package no longer triggers CSP error when there is `script-src` policy.
> CHECKOUT-8519: Upgrade yup to a version that does not trigger CSP error

- package-lock.json
- package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2691
https://github.com/bigcommerce/checkout-sdk-js/pull/2687
> chore(payment): PAYPAL-4700 bump checkout-sdk

- packages/core/src/app/cart/CartSummary.spec.tsx
- packages/core/src/app/cart/CartSummary.tsx
- packages/core/src/app/cart/CartSummaryAndDrawer.test.tsx
- packages/core/src/app/cart/CartSummaryDrawer.spec.tsx
- packages/core/src/app/cart/CartSummaryDrawer.tsx
- packages/core/src/app/cart/EditLink.tsx
- packages/core/src/app/cart/__snapshots__/CartSummary.spec.tsx.snap
- packages/core/src/app/cart/__snapshots__/CartSummaryDrawer.spec.tsx.snap
- packages/core/src/app/cart/mapToCartSummaryProps.ts
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/scss/components/foundation/modal/_modal.scss
- packages/locale/src/translations/en.json
- packages/ui/src/index.ts
- packages/ui/src/modal/ConfirmationModal.tsx
- packages/ui/src/modal/index.ts
Show the warning popup before redirecting to cart page when multi-address shipping is enabled along with the new UI.
*The modal is expected to be reused when switching from multi-shipping to single shipping.
Improving multi-shipping UX.
https://github.com/user-attachments/assets/eaeb6c43-92e7-40de-9112-5c5fc6cfb920
https://github.com/user-attachments/assets/90aed54a-de69-4e68-b727-8448624c5457
> feat(checkout): CHECKOUT-8599 Add Confirmation Modal for Multi-shipping

- packages/core/src/app/shipping/AllocateItemsModal.tsx
- packages/core/src/app/shipping/ConsignmentAddressSelector.tsx
- packages/core/src/app/shipping/ConsignmentLineItem.tsx
- packages/core/src/app/shipping/ConsignmentListItem.tsx
- packages/core/src/app/shipping/LeftToAllocateItemsTable.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.tsx
- packages/core/src/app/shipping/MultishippingV2Type.ts
- packages/core/src/app/shipping/NewConsignment.tsx
- packages/core/src/app/shipping/hooks/useMultishippingConsignmentItems.ts
- Add allocate items modal for new SF multishipping UI
- So that products can be assigned to an address in the new multi shipping experience.
- CI checks
https://github.com/user-attachments/assets/149bcfc2-58ba-4941-b3a6-5147dbbd3244
> CHECKOUT-8596 Add product allocation modal

- package-lock.json
- package.json
Bump checkout-sdk to 1.674.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2657
https://github.com/bigcommerce/checkout-sdk-js/pull/2659
Unit tests
Manual tests
CI
Verified by QA/SDET
> chore(payment): PAYPAL-4697 bump checkout-sdk to 1.674.0

- packages/core/src/app/address/getAddressFormFieldsValidationSchema.ts
- packages/core/src/app/formFields/getCustomFormFieldsValidationSchema.ts
- packages/core/src/app/formFields/getFormFieldsValidationSchema.spec.tsx
- packages/core/src/app/formFields/getFormFieldsValidationSchema.ts
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Add validation of form field for max length for google autocomplete
Add validation of form field for max length for google autocomplete since if a max length is set for address field then it is not respected for google autocomplete
- CI
- Screencast
https://github.com/user-attachments/assets/157a4457-fd9e-49ff-b99d-e2c231ee8805
https://github.com/user-attachments/assets/d463b3b3-8de1-4088-8232-746aa73ddf2f
https://github.com/user-attachments/assets/5b292cc5-521c-4813-81bb-dc62b47aa2b3
> fix(shipping): CHECKOUT-8776 Add validation of form field for max length for google autocomplete

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2710](https://github.com/bigcommerce/checkout-sdk-js/pull/2710)
> chore(payment): STRIPE-461 bump checkout-sdk-js

- package-lock.json
- package.json
Bump checkout-sdk to 1.675.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2717 - unit tests update
Unit tests
CI
> chore(payment): PAYPAL-4810 bump checkout-sdk to 1.675.1

- packages/core/src/app/shipping/AllocateItemsModal.tsx
- packages/core/src/app/shipping/LeftToAllocateItem.tsx
- packages/core/src/app/shipping/LeftToAllocateItemsTable.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/core/src/app/shipping/hooks/useMultishippingConsignmentItems.ts
- packages/locale/src/translations/en.json
Implement validation and validation error display on the allocate items modal for new SF mulshipping UI.
Display validation errors for both physical and custom items quantity field on the allocate items modal and prevent form getting submitted.
- CI checks
https://github.com/user-attachments/assets/171ae0eb-7db6-41e6-8000-ed350e7828f0
> CHECKOUT-8602: Add validation and error handling for allocate items modal

- package-lock.json
- package.json
Bump checkout-sdk version to 1.677.0
As part of the release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2707
https://github.com/bigcommerce/checkout-sdk-js/pull/2718
All tests have been passed / manual testing
> feat(payment): STRIPE-476 bump checkout-sdk version to 1.676.0

- packages/stripe-integration/src/stripe-upe/StripeUPEPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-upe/StripeUPEPaymentMethod.tsx
Add accordion toggle events handlers to Stripe element
To synchronise toggle of BC and Stripe accordion items
Stripe UPE
https://github.com/user-attachments/assets/2b137a4f-123b-43f7-b807-fb3a20e68f00
Stripe OCS
https://github.com/user-attachments/assets/227bfb88-a6eb-4638-8c1b-fa35e61d384f
> feat(payment): STRIPE-489 Stripe accordion toggle

- package-lock.json
- package.json
Revert Stripe UPE GPay with 3ds changes.
Because of issue with Stripe V3 GPay with 3ds
Unit tests
> chore(payment): STRIPE-476 bump checkout sdk version

- packages/core/src/app/shipping/AllocateItemsModal.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/locale/src/translations/en.json
Add digital item no shipping banner
To show no shipping for digital item when a cart contains digital item
> feat(checkout): CHECKOUT-8600 Add digital item no shipping banner

- packages/core/src/app/shipping/ConsignmentListItem.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/core/src/app/shipping/Shipping.tsx
Introduce a button to allow the deletion of a consignment.
Able to delete a consignment in new multi consignment UI
https://github.com/user-attachments/assets/734d78ca-8a7d-4afe-abc9-f5f521013bea
> feat(checkout): CHECKOUT-8777 Delete a consignment

- package-lock.json
- packages/core/src/app/cart/Redeemable.spec.tsx
- packages/core/src/app/cart/Redeemable.tsx
- packages/core/src/app/payment/storedInstrument/__snapshots__/ManageCardInstrumentsTable.spec.tsx.snap
- packages/instrument-utils/src/storedInstrument/ManageCardInstrumentsTable/__snapshots__/ManageCardInstrumentsTable.spec.tsx.snap
return and show detailed error message when applying coupon fails on checkout page
now if coupon apply error is not on two specific error code, it always display "The gift certificate or coupon code is invalid".
This confuses our shoppers as they don’t always understand why a coupon code doesn’t apply, e.g because of currency not support it.
**case 1: apply a coupon not for current cart currency**
before change:
🚫 too generic and not reflect the reason of failure
after change:
✅ which matches the server side detailed message ()
**case 2: apply a coupon that does not exists**
befor change:
after change:
✅ similar, but after change it fully reflect the error message service side send, not fixed.
**case 3: if apply coupon response has no detailed message or empty string**
after change:
✅ …
> feat(checkout): CHECKOUT-8790 Display detailed error when applying coupon fails on checkout

- package-lock.json
- package.json
To deploy PRs:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2732](https://github.com/bigcommerce/checkout-sdk-js/pull/2732)
[https://github.com/bigcommerce/checkout-sdk-js/pull/2730](https://github.com/bigcommerce/checkout-sdk-js/pull/2730)
unit tests and manually tested
> chore(payment): STRIPE-484 bump checkout sdk version

- package-lock.json
- package.json
To update code
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2720
Unit tests
> chore(payment): PAYPAL-4783 bumped checkout-sdk-js version

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2734](https://github.com/bigcommerce/checkout-sdk-js/pull/2734)
> chore(payment): STRIPE-496 bump checkout sdk version

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2736](https://github.com/bigcommerce/checkout-sdk-js/pull/2736)
> chore(payment): STRIPE-509 bump checkout sdk version

- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
- packages/core/src/app/shipping/AllocatedItemsList.tsx
- packages/core/src/app/shipping/ConsignmentLineItem.tsx
- packages/core/src/app/shipping/ConsignmentLineItemDetail.tsx
- packages/core/src/app/shipping/ConsignmentListItem.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/core/src/app/shipping/NewConsignment.tsx
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.test.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingHeader.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShipping.spec.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
- packages/locale/src/translations/en.json
- packages/ui/src/form/LoadingSkeleton/LoadingSkeleton.tsx
Handle actions when toggling from multi shipping to single shipping and vice versa
1. **When moving from single shipping to multi shipping in SF checkout**
- Delete the consignment so that multi shipping consignments can be freshly started.
2. **When moving from multi shipping to single shipping in SF checkout**
- Show the warning popup that all the consignments will be lost.
To improve the multi shipping user experience
- CI checks
https://github.com/user-attachments/assets/0ac0148c-7f7c-4986-8b7b-75cc7482bbef
> CHECKOUT-8775: Toggle from multi shipping to single shipping and vice versa

- packages/core/src/app/shipping/ConsignmentListItem.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.tsx
- packages/core/src/app/shipping/MultiShippingV2.test.tsx
- packages/core/src/app/shipping/shippingOption/MultiShippingOptionsV2.tsx
- packages/locale/src/translations/en.json
Show a message when a shopper is trying to create another one but an existing consignment is not finished yet.
Also, hide the message when the previous consignment is done.
Improve UX.
https://github.com/user-attachments/assets/bef22cab-47b2-4ce6-9ccf-6aa6680a3956
https://github.com/user-attachments/assets/13da5a50-9ebb-4e75-ab69-e8be66fef13a
https://github.com/user-attachments/assets/7bbaff3d-1dcb-4c3e-ba92-078e003c2379
https://github.com/user-attachments/assets/e6616f9f-c9eb-43bf-b1b9-44ab271e9428
> feat(checkout): CHECKOUT-8824 Add Consignment Not Completed Message

- packages/core/src/app/shipping/AllocateItemsModal.tsx
- packages/core/src/app/shipping/AllocatedItemsList.tsx
- packages/core/src/app/shipping/ConsignmentLineItem.tsx
- packages/core/src/app/shipping/ItemSplitTooltip.scss
- packages/core/src/app/shipping/ItemSplitTooltip.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
- packages/core/src/app/shipping/MultiShippingFormV2.test.tsx
- packages/core/src/app/shipping/MultishippingV2Type.ts
- packages/core/src/app/shipping/hooks/useMultishippingConsignmentItems.ts
- packages/core/src/app/shipping/utils/generateItemHash.tsx
- packages/core/src/app/shipping/utils/index.ts
- packages/locale/src/translations/en.json
Display item split tooltip when items split into individual item.
To improve user experience
> feat(checkout): CHECKOUT-8774 Display item split tooltip

- packages/core/src/app/shipping/hasSelectedShippingOptions.spec.ts
- packages/core/src/app/shipping/hasSelectedShippingOptions.ts
Remove available shipping option check when determining if a consignment has selected a shipping method..
This change will avoid always loading available shipping methods after a checkout page refresh.
CI.
> feat(checkout): CHECKOUT-8869 Remove Available Shipping Option Check

- package-lock.json
- package.json
- packages/core/src/app/payment/hostedCreditCard/withHostedCreditCardFieldset.tsx
- packages/core/src/app/payment/hostedCreditCard/withHostedPayPalCommerceCreditCardFieldset.tsx
- packages/credit-card-integration/src/CreditCardPaymentMethodComponent.tsx
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.tsx
- packages/hosted-credit-card-integration/src/hooks/useHostedCreditCard.tsx
- packages/mollie-integration/src/MolliePaymentMethod.tsx
===> MERGE TOGETHER WITH CHECKOUT-SDK-JS PART https://github.com/bigcommerce/checkout-sdk-js/pull/2741
After renaming `HostedFormOptions` to `LegacyHostedFormOptions` in task https://bigcommercecloud.atlassian.net/browse/PI-2943 it is necessary to update its usage in checkout-js
Because of changes in https://bigcommercecloud.atlassian.net/browse/PI-2943
> feat(checkout): PI-2944 Update HostedFormOptions usage in checkout-js after renaming

- packages/core/src/app/address/AddressFormModal.tsx
- packages/core/src/app/address/AddressSelect.tsx
- packages/core/src/app/address/AddressSelectButton.tsx
- packages/core/src/app/shipping/AllocateItemsModal.tsx
- packages/core/src/app/shipping/ConsignmentAddressSelector.tsx
- packages/core/src/app/shipping/ConsignmentLineItem.tsx
- packages/core/src/app/shipping/ConsignmentListItem.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
- packages/core/src/app/shipping/MultiShippingFormV2.tsx
- packages/core/src/app/shipping/MultiShippingFormV2Footer.tsx
- packages/core/src/app/shipping/MultiShippingV2.test.tsx
- packages/core/src/app/shipping/NewConsignment.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/locale/src/translations/en.json
1. Add loader to `Allocate` button in the allocate items modal.
2. In the address selector, the placeholder text should be 'Choose a shipping address'
3. For the 'Add New Address' modal, let's use the 'Cancel' button style from the consignment modal for consistency
4. Show cart has changed popup if the cart is changed via some external sources.
To improve the UI/UX for checkout multishipping 
**Manual testing** 
https://github.com/user-attachments/assets/345dc2d2-b470-4314-8d4a-ff190f1daf84
> CHECKOUT-8850 address design comments for new multishipping UI

- packages/core/src/app/address/AddressFormModal.tsx
- packages/core/src/app/address/AddressSelectButton.tsx
- packages/core/src/app/address/SingleLineStaticAddress.test.tsx
- packages/core/src/app/address/SingleLineStaticAddress.tsx
- packages/core/src/app/address/StaticAddress.test.tsx
- packages/core/src/app/address/StaticAddress.tsx
- packages/core/src/app/address/getAddressFormFieldsValidationSchema.ts
- packages/core/src/app/address/isValidAddress.test.ts
- packages/core/src/app/address/isValidAddress.ts
- packages/core/src/app/address/isValidCustomerAddress.ts
- packages/core/src/app/address/isValidStaticAddress.tsx
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
- packages/core/src/app/formFields/getCustomFormFieldsValidationSchema.ts
- packages/core/src/app/formFields/getFormFieldsValidationSchema.spec.tsx
- packages/core/src/app/formFields/getFormFieldsValidationSchema.ts
- packages/core/src/app/shipping/ConsignmentAddressSelector.tsx
- packages/core/src/app/shipping/MultiShippingForm.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingAddress.tsx
- packages/core/src/app/shipping/ShippingAddressForm.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Add validation of form field for max length for address fields. Do not allow to continue shipping if address fields are invalid.
**To fix:** You are able to bypass the Address line character limit on Checkout if a customer already has a saved address
- CI checks
- Manual testing 
**Experiment off**
https://github.com/user-attachments/assets/a690bf08-9fa0-46c8-ae36-dc0ccf0c50fc
**Experiment on**
https://github.com/user-attachments/assets/a23af2c0-e5c8-42d6-8cc5-650e251d98dd
> fix(shipping): CHECKOUT-7560 add max length validation for address fields

- packages/core/src/app/shipping/ConsignmentAddressSelector.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
- packages/core/src/app/shipping/MultiShippingFormV2.tsx
- packages/core/src/app/shipping/MultiShippingSelectShippingOption.ts
- packages/core/src/app/shipping/MultiShippingV2.test.tsx
- packages/core/src/app/shipping/NewConsignment.tsx
- packages/core/src/app/shipping/shippingOption/MultiShippingOptionsListItemV2.tsx
- packages/core/src/app/shipping/shippingOption/MultiShippingOptionsListV2.tsx
- packages/core/src/app/shipping/utils/index.ts
- packages/core/src/app/shipping/utils/setRecommendedOrMissingShippingOption.ts
- packages/test-framework/src/react-testing-library-support/API.mock.ts
1.Selecting a shipping method for one consignment no longer updates the shipping method of another consignment.
2.When creating a new consignment, the selected shipping methods of existing consignments will no longer be randomly lost.
1.The recommended shipping method is now automatically selected at the time of consignment creation, moving the trigger from the display of shipping methods.
Address existing API limitations and fix bugs.
https://github.com/user-attachments/assets/fb6fa579-9c4e-4ce0-9826-80524ec1ee07
https://github.com/user-attachments/assets/983e7956-c039-4936-9910-44802dcb413d
https://github.com/user-attachments/assets/1f41695a-835d-424a-aa06-4462fa1a3669
> fix(shipping): CHECKOUT-8872 Fix Missing Shipping Option

- packages/core/src/app/address/SingleLineStaticAddress.test.tsx
- packages/core/src/app/address/SingleLineStaticAddress.tsx
- packages/core/src/app/address/StaticAddress.test.tsx
- packages/core/src/app/address/StaticAddress.tsx
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
- packages/core/src/app/shipping/ConsignmentAddressSelector.tsx
- packages/core/src/app/shipping/Shipping.tsx
Update experiment name from 
`CHECKOUT-7560_address_fields_max_length_validation` to 
`CHECKOUT-7560.address_fields_max_length_validation`
To fix experiment name so that it picks up the value from LD.
CI checks
> fix(checkout): CHECKOUT-7560 fix experiment name

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2740
Unit tests
Several sessions of manual tests
> chore(payment): PAYPAL-4884 bump checkout-sdk version

- package-lock.json
- package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2744
https://github.com/bigcommerce/checkout-sdk-js/pull/2751
> chore(payment): PAYPAL-4869 bump checkout-sdk

- packages/core/src/app/shipping/Shipping.test.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingHeader.tsx
- packages/core/src/app/shipping/hasPromotionalItems.tsx
- packages/locale/src/translations/en.json
- packages/ui/src/modal/ConfirmationModal.tsx
- Do not allow multiple shipping if the cart contains promotional items. Show the multi shipping unavailable modal.
- Switch to single shipping if customer edits cart after creating multi shipping consignments and adds a promotional item to the cart.
This is because all free items are automatically assigned to the first address. This inflexibility in the underlying consignments api leads to a sub-optimal UX which results to a perception of poor quality.
- CI checks
https://github.com/user-attachments/assets/f639071a-aae2-418a-b08d-4b58f1629463
> feat(shipping): CHECKOUT-8861 Handle promotional item in multishipping

- package-lock.json
- package.json
- packages/locale/src/translations/en.json
Added new code error.
Related PR: https://github.com/bigcommerce/bigpay/pull/8654
Bump checkout-sdk version:
https://github.com/bigcommerce/checkout-sdk-js/pull/2746
Because we need to show the user an appropriate error if the first payment attempt fails.
> feat(payment): STRIPE-488 add Google pay error text

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2739](https://github.com/bigcommerce/checkout-sdk-js/pull/2739)
Unit, functional tests and manually tested, results in related PR
> chore(payment): STRIPE-525 bump checkout sdk version

- packages/core/src/app/order/__snapshots__/OrderSummaryItems.spec.tsx.snap
- packages/core/src/app/order/mapFromDigital.tsx
Update the price mapping for digital items to ensure the pre-tax price is not shown as the pre-discount price. 
This PR also aligns digital items with physical items by using same pricing property names.
Reduce shopper confusion.
> fix(checkout): CHECKOUT-8892 Update Digital Item Price Mapping

- packages/core/src/app/shipping/PayPalFastlaneShippingAddress.test.tsx
- packages/core/src/app/shipping/PayPalFastlaneShippingAddress.tsx
- packages/core/src/app/shipping/ShippingAddress.spec.tsx
- packages/core/src/app/shipping/ShippingAddress.tsx
- packages/core/src/app/shipping/ShippingForm.spec.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.test.tsx
- packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.tsx
Fixed Paypal Fastlane bug when edit card and return back to checkout page
To fix unexpected behaviour
**BEFORE**
https://github.com/user-attachments/assets/b207e3de-df2e-4c4f-943b-8e0acd006c75
**AFTER**
https://github.com/user-attachments/assets/83d51566-5a56-4d1e-ae80-1dc1e7c43e7c
> feat(payment): PAYPAL-4827 Fixed Paypal Fastlane bug when edit card and return back to checkout page

- package-lock.json
- package.json
- packages/core/src/app/checkout/checkouts.mock.ts
- packages/core/src/app/checkout/getCheckoutStepStatuses.spec.ts
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
Allow billing address editing for all Google Pay providers.
Related PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/2747
Because sometimes the locality field from GP is empty, we will add stateOrProvinceCode instead, and also allow the user to edit the billing address if needed.
Manual testing.
Before:
After:
Stripe Google Pay
https://github.com/user-attachments/assets/9ed50aac-ea91-4dad-9c0c-1e4d5d4dd655
PPCP Google Pay
https://github.com/user-attachments/assets/a9f35bad-d32f-4f24-9ace-13e9e5b99882
> feat(payment): STRIPE-546 allow billing address editing for all Google Pay providers

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2755](https://github.com/bigcommerce/checkout-sdk-js/pull/2755)
> chore(payment): STRIPE-414 bump checkout-sdk-js

- packages/core/src/app/shipping/Shipping.test.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/getShippableItemsCount.ts
Do not present the shopper with the option to select multi-shipping on the checkout when their is one bundle product in the cart.
Since it is a bundled product, so even if there are 2 products in the cart they will be shipped together to same destination, so multiple addresses should not be allowed.
- CI checks
**BEFORE**
https://github.com/user-attachments/assets/981fa802-0bb3-4fae-9d2e-d37db78f39ae
**AFTER (Experiment On - New Multi shipping UI)**
https://github.com/user-attachments/assets/9d107496-e7b3-40e4-ba99-b26dcc5d1ea7
**AFTER (Experiment Off - Old Multi shipping UI)**
https://github.com/user-attachments/assets/ee75db72-2f09-4234-b77e-9f4e6daed76c
> CHECKOUT-8917 Do not allow multi-shipping if the cart contains one bundle product

- packages/core/src/app/payment/paymentMethod/CreditCardPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/CreditCardPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
Fixed credit card loading glitch
To fix bug
**Before**
https://github.com/user-attachments/assets/25a03563-93a7-4bd9-8109-639b1d459c8e
**After**
https://github.com/user-attachments/assets/da30da82-e4e3-42ec-b3bc-fbfbf73ec09f
> feat(payment): PAYPAL-4692 fixed credit card loading glitch

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2757
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4952 bump checkout sdk version

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2758
https://github.com/bigcommerce/checkout-sdk-js/pull/2759
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-4705 bump checkout sdk version

- packages/core/src/app/shipping/AllocateItemsModal.tsx
- packages/core/src/app/shipping/LeftToAllocateItem.tsx
- packages/core/src/app/shipping/MultiShippingFormV2.scss
Fix following UI issues 
- The variants/options font style should be different to the  item name's, so it provides a hierarchy and easy to read. Please refer to the design file for the font style.
- Implement a hover state for the "x" un-allocate button in the allocation modal so it looks more accessible. 
- The label for "shipping method" should be the same font size as "x item allocated" because we are not implicating one is more important than another in the hierarchy and looks cleaner with same label font.
- When the allocation modal is loading, the cancel button should not use the  "primary" button style.
- Keep "Cancel" but make "Save" enabled in Reallocate items modal.
For better user experience.
https://github.com/user-attachments/assets/c4bd2e26-fc06-4a84-8daa-6af …
> fix(checkout): CHECKOUT-8919 resolve cosmetic ui issues for new multishipping

- packages/paypal-fastlane-integration/src/index.ts
Updated import source for isPayPalCommerceFastlaneMethod method
To fix the issue with Braintree Fastlane shipping option selection
Manual tests
CI
https://github.com/user-attachments/assets/b8a6a67e-2773-4f1a-a992-b57c6f4097d4
> fix(payment): PAYPAL-5026 updated import source for isPayPalCommerceFastlaneMethod method

- package-lock.json
- package.json
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2760
> chore(payment): PAYPAL-4995 bump checkout-sdk

- package-lock.json
- package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2761
Tested Manually
> chore(payment): PI-3029 bump checkout-sdk

- packages/bluesnap-direct-integration/e2e/bluesnapdirect.spec.ts
- packages/checkout-extension/src/handlers/createReloadCheckoutHandler.ts
Update reload checkout extension command handler.
To include shipping options.
Changing the shipping option on the right and clicking the emoji on the left triggers a reload checkout,
causing the shipping option extension to re-render,
but the selected option remains unchanged due to the known Formik behavior. 
https://github.com/user-attachments/assets/d1de74ee-716b-4d72-825b-0fe40baac7d2
> feat(checkout): CHECKOUT-8959 Update Reload Checkout Handler

- .github/CODEOWNERS
- packages/checkoutcom-integration/src/CheckoutcomCustomPaymentMethod.spec.tsx
- packages/checkoutcom-integration/src/CheckoutcomCustomPaymentMethod.tsx
iDEAL have updated their central technical infrastructure.
It requires from us to stop calling GET /issuers endpoint on checkout.
The change is under the experiment because according to this [comment](https://bigcommercecloud.atlassian.net/browse/PI-2979?focusedCommentId=1902071)
we're waiting for official information from Checkoutcom team.
According to the CheckoutCOM team, the new changes will take effect on April 1, 2025.
We should be informed and then projected rollout of an experiment is 100%.
revert,
disable experiment [PI-2979.checkoutcom_enable_ideal_hosted_page](https://app.launchdarkly.com/projects/default/flags/PI-2979.checkoutcom_enable_ideal_hosted_page/targeting?env=development&env=integration&env=production&selected-env=development)
Before:
After: …
> feat(payment): PI-3048 [Checkout.com] Remove issuers dropdown and sending BIC

- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
Fixed credit card duplication when initialize BT LPM
To avoid duplication of credit card 
https://github.com/user-attachments/assets/a105c222-f67e-47ef-8be5-3e1f0a691bb1
> fix(payment): PAYPAL-4987 fixed credit card duplication when initialize BT LPM

- package-lock.json
- package.json
- packages/checkout-extension/src/ExtensionService.test.tsx
- packages/checkout-extension/src/handlers/createGetConsignmentHandler.ts
- packages/checkout-extension/src/handlers/handlers.test.ts
- packages/checkout-extension/src/handlers/index.ts
Handle a new checkout extension command, `GetConsignments`
https://github.com/bigcommerce/checkout-sdk-js/pull/2766
* Will include the SDK bump in this PR.
To pass consignment data to a checkout extension.
> feat(extension): CHECKOUT-8964 Introduce GetConsignment Command

- package-lock.json
- package.json
Due to fix https://github.com/bigcommerce/checkout-sdk-js/pull/2771
Look at the https://github.com/bigcommerce/checkout-sdk-js/pull/2771
> fix(payment): PI-3102 bump checkout-sdk version

- package-lock.json
- package.json
To release https://github.com/bigcommerce/checkout-sdk-js/pull/2772
> chore(payment): PI-3099 bump checkout-sdk version

- package-lock.json
- package.json
Due to the [release](https://github.com/bigcommerce/checkout-sdk-js/pull/2775)
[testing](https://github.com/bigcommerce/checkout-sdk-js/pull/2775)
> chore(payment): PI-77 bump checkout-sdk version

- package-lock.json
- package.json
bump checkout sdk version (1.700.2)
As part of release: https://github.com/bigcommerce/checkout-sdk-js/pull/2774
Unit tests
CI
> chore(payment): PAYPAL-5020 bump checkout sdk version (1.700.2)

- package-lock.json
- package.json
- packages/checkout-extension/src/ExtensionService.test.tsx
- packages/checkout-extension/src/ExtensionService.ts
- packages/checkout-extension/src/handler/commandHandlers/CommandHandler.ts
- packages/checkout-extension/src/handler/commandHandlers/commandHandlers.test.ts
- packages/checkout-extension/src/handler/commandHandlers/createReloadCheckoutHandler.ts
- packages/checkout-extension/src/handler/commandHandlers/createSetIframeStyleHandler.ts
- packages/checkout-extension/src/handler/commandHandlers/createShowLoadingIndicatorHandler.ts
- packages/checkout-extension/src/handler/commandHandlers/index.ts
- packages/checkout-extension/src/handler/index.ts
- packages/checkout-extension/src/handler/queryHandlers/QueryHandler.ts
- packages/checkout-extension/src/handler/queryHandlers/createGetConsignmentHandler.ts
- packages/checkout-extension/src/handler/queryHandlers/index.ts
- packages/checkout-extension/src/handler/queryHandlers/queryHandlers.test.ts
Introduce a new `query` concept that allows an extension to fetch any data from the checkout object by using a simple query key. 
https://github.com/bigcommerce/checkout-sdk-js/pull/2769
An extension can fetch checkout data immediately.
After the extension service initialization, clicking the emoji will run:
```
console.log(await service.getConsignments(useCache));
```
`useCache` is set to `true` at first. On the second time of clicking the emoji, `useCache` will be `false`, therefore, a `GET` checkout call is made.
https://github.com/user-attachments/assets/8e87cdfb-103c-4338-bf1b-73bf2f1d2e28
> feat(extension): CHECKOUT-8974 Introduce Query Handler

- package-lock.json
- package.json
Bump checkout-sdk 
Release https://github.com/bigcommerce/checkout-sdk-js/pull/2776
- CI
- Attached to SDK linked PR
> chore(other): CHECKOUT-8264 Bump checkout sdk

- packages/core/src/app/payment/paymentMethod/BraintreeCreditCardPaymentMethod.tsx
Added `onUnhandledError` function to open a modal window when an error occurs during the payment initialization process
For correct errors handling
Manual testing
> feat(payment): PAYPAL-5038 Added onUnhandledError function to open a modal window when an error occurs during the payment initialization process

- package-lock.json
- package.json
- packages/checkout-extension/src/ExtensionProvider.tsx
- packages/checkout-extension/src/ExtensionReducer.ts
- packages/checkout-extension/src/ExtensionService.test.tsx
- packages/checkout-extension/src/ExtensionService.ts
- packages/checkout-extension/src/handler/commandHandlers/CommandHandler.ts
- packages/checkout-extension/src/handler/commandHandlers/commandHandlers.test.ts
- packages/checkout-extension/src/handler/commandHandlers/createReRenderShippingFormHandler.ts
- packages/checkout-extension/src/handler/commandHandlers/index.ts
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/ShippingFormFooter.tsx
- packages/core/src/app/shipping/SingleShippingForm.test.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
- packages/core/src/app/shipping/shippingOption/ShippingOptions.tsx
- packages/core/src/app/shipping/shippingOption/ShippingOptionsForm.spec.tsx
- packages/core/src/app/shipping/shippingOption/ShippingOptionsForm.tsx
Introduce a new checkout extension command.
To support the force re-rendering of the shipping form.
Displaying an external change to the Google AutoComplete address field (address line one when enabled) is not supported, as its value is managed by the Downshift library.
*Clicking on the emoji triggers the `ReRenderShippingForm` command.
The update to the delivery date form field on another page is applied once the command is triggered.
https://github.com/user-attachments/assets/3113abbf-a662-4a22-bae5-c7f779266b75
https://github.com/user-attachments/assets/063640fc-0a7d-4c8f-bbbe-a492476df4c0
The update to the shipping option on another page is applied once the command is triggered.
https://github.com/user-attachments/assets/39d4f152-f549-41f3-854b-c53b8bfab41a
> feat(extension): CHECKOUT-8959 Introduce ReRenderShippingForm Command

- package-lock.json
- package.json
To deliver following PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/2779
https://github.com/bigcommerce/checkout-sdk-js/pull/2784
> chore(payment): PAYPAL-5044 bump checkout-sdk

- package-lock.json
- package.json
To deliver:
https://github.com/bigcommerce/checkout-sdk-js/pull/2793
https://github.com/bigcommerce/checkout-sdk-js/pull/2790
https://github.com/bigcommerce/checkout-sdk-js/pull/2788
> chore(payment): PAYPAL-0 bump checkout-sdk version

- packages/core/src/app/checkout/index.ts
- packages/core/src/app/shipping/Shipping.test.tsx
- packages/core/src/app/shipping/ShippingComponent.test.tsx
- packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
- packages/test-framework/src/react-testing-library-support/mocks/checkout.mock.ts
- packages/test-framework/src/react-testing-library-support/mocks/countries.ts
Add a test for the happy path of the Guest Checkout Shipping step.
Test path:
- Entering the shipping step as a guest.
- Filling in essential address details.
- Triggering two API calls: a POST call to create a consignment and a PUT call to select the default shipping option.
- Asserting that “billing address is the same as shipping” is checked.
- Clicking “Entering” goes to the payment step.
Enable us to upgrade to react 18.
CI.
> test(checkout): CHECKOUT-9007 Guest Checkout Shipping Step Happy Path

- jest.preset.js
- packages/core/src/app/shipping/Shipping.test.tsx
- packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
- packages/test-framework/src/react-testing-library-support/mocks/checkout.mock.ts
Add RTL test for single shipping for logged in customer with no saved addresses. 
**Test path:**
- Enter the shipping step as a logged in customer.
- Fill in essential address details in the form.
- Verify the `Save this address in my address book` checkbox is present and selected.
- Click “Continue” to proceed to the payment step.
In order to be able to move all the enzyme tests to RTL which enables us to move to React 18
- CI checks
> test(checkout): CHECKOUT-9030 Single Shipping for customer with no saved addresses

- packages/core/src/app/shipping/Shipping.test.tsx
- packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
- packages/test-framework/src/react-testing-library-support/mocks/checkout.mock.ts
Create Tests for Customer's Single Shipping Use Cases with Saved Addresses.
In order to be able to move all the enzyme tests to RTL which enables us to move to React 18.
- CI checks
> test(checkout): CHECKOUT-8932 Add tests for single shipping form for customer with saved addresses

- package-lock.json
- package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2798
https://github.com/bigcommerce/checkout-sdk-js/pull/2791
> chore(payment): PAYPAL-5201 Bump checkout-sdk version

- package-lock.json
- package.json
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.spec.ts
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.ts
- packages/locale/src/translations/en.json
Display correct error heading for missing shipping method.
Display correct error heading for missing shipping method if shipping method is invalid.
- CI 
- Screenshot
> chore(checkout): CHECKOUT-9052 Display correct error heading

- package-lock.json
- package.json
As part of release: https://github.com/bigcommerce/checkout-sdk-js/pull/2801
Unit tests
Manual tests
US VPN location:
Non US VPN location:
> chore(payment): PAYPAL-5213 bump checkout-sdk version (1.714.0)

- packages/locale/src/translations/en.json
Small fix of missing shipping method error heading
from "Missing shipping method" to "Shipping method unavailable"
to make it more clear shipping method is unavailable even shopper selected it before.
vm:
> chore(checkout): CHECKOUT-9032 Small fix of missing shipping method error heading

- packages/core/src/app/payment/storeCredit/StoreCreditField.test.tsx
- packages/core/src/app/payment/storeCredit/StoreCreditOverlay.test.tsx
Convert Enzyme Tests in `Payment/creditCard` folder.
Coverage 100%
Enable us to upgrade to react 19.
CI.
> test(checkout): CHECKOUT-8931 Convert Enzyme Tests in storeCredit

- package-lock.json
- package.json
bump checkout-sdk to 1.715.0
As part of release: https://github.com/bigcommerce/checkout-sdk-js/pull/2808
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-5097 bump checkout-sdk to 1.715.0

- packages/core/src/app/shipping/MultiShippingForm.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
- packages/core/src/app/shipping/index.ts
- packages/core/src/app/shipping/isSelectedShippingOptionValid.ts
Fix: If checkout has selected shipping method, but the shipping option id is not in available shipping methods list, on the UI the there is no shipping method selected, but shopper can just ignore and continue to the next step.
We should block shopper continue to the next step if selected shipping option is not present in the list of available shipping options.
- CI checks
- Manual testing proof [(here)](https://github.com/bigcommerce/checkout-js/pull/2213#issuecomment-2742011710)
> fix(checkout): CHECKOUT-9086 add available shipping option check

- packages/core/src/app/payment/Payment.tsx
Remove browser confirmation alert before redirect to Stripe UPE iDEAL confirmation page.
Browser alert is causing confusion and customer churn when using redirect-based Stripe UPE iDEAL APM.
Before:
https://github.com/user-attachments/assets/95c55e57-8c80-4bc6-9c59-3752c7961a3b
After:
https://github.com/user-attachments/assets/872bf0be-7002-417e-8335-3758ebef6650
> fix(payment): STRIPE-696 Remove browser alert before Stripe UPE iDEAL redirect

- package-lock.json
- package.json
As part of the release https://github.com/bigcommerce/checkout-sdk-js/pull/2787
Manual testing
Covered by experiment:
`PI-2875.googlepay_coupons_handling 
`
> feat(payment): PI-2875 Google Pay promo codes handling

- package-lock.json
- package.json
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.test.ts
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.ts
- packages/locale/src/translations/en.json
Parse custom error and map title to error for invalid shipping address
To display a better and more informed error heading to shopper map api error to custom error
Release https://github.com/bigcommerce/checkout-sdk-js/commit/57d00879ffaff768ba2a00da8cb3e9b52a897334
- CI
- Screenshot
> chore(shipping): CHECKOUT-9114 Parse custom error and map title to error for invalid shipping address

- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Added Afterpay new logo for US stores
Due to the Afterpay request
Old logo:
New logo:
> feat(payment): PI-3089 Added Afterpay new logo for US stores

- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingComponent.test.tsx
Disable Continue Button During Checkout Reload to Prevent Data Discrepancy
To keep checkout data in sync and do not allow other checkout update calls when some are already in process.
**Without extension local testing**
https://github.com/user-attachments/assets/aab87547-6720-41d2-b46c-fd1e5c3fe85c
**With extension**
https://github.com/user-attachments/assets/0d9bafee-84d9-40cd-a601-259026997ee6
> feat(checkout): CHECKOUT-9107 disable continue button when checkout is reloading

- package-lock.json
- package.json
- packages/test-mocks/src/config.mock.ts
- Release https://github.com/bigcommerce/checkout-sdk-js/pull/2823 and https://github.com/bigcommerce/checkout-sdk-js/pull/2819
- To fix failing release pipeline ([tag issue](https://app.circleci.com/pipelines/github/bigcommerce/checkout-js/12054/workflows/72bbec72-2f95-427e-a185-03ae1013c722/jobs/54440)) 
- CI checks
> chore(checkout): CHECKOUT-000 bump sdk version

- package-lock.json
- package.json
- packages/test-mocks/src/config.mock.ts
Bump checkout-sdk version to `1.721.0`
As part of the release: https://github.com/bigcommerce/checkout-sdk-js/pull/2813
Manual testing
> feat(payment): PI-3539 sdk version bump

- packages/core/src/app/customer/Customer.test.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/GuestForm.tsx
- packages/test-framework/src/react-testing-library-support/mocks/checkout-settings.mock.ts
If setting `shouldRedirectToStorefrontForAuth` is true then redirect shopper to login from storefront login page.
As part of headless offering, redirect shoppers to storefront login page to login.
- CI
- Screencast
https://github.com/user-attachments/assets/4f52378f-b0c5-46f6-900a-2f848b45ce2c
https://github.com/user-attachments/assets/e0173c2c-a104-4c4f-8720-0b082b05087d
https://github.com/user-attachments/assets/54c650ea-4284-4b9a-9d99-14e02e6f2460
> feat(customer): CHECKOUT-9138 Redirect to storefront login page based on settings

- packages/checkoutcom-integration/src/CheckoutcomCustomPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
Remove the leftover code of Checkout.com credit card in paymentMethod
To finish the extraction of Checkout.com to the new package
https://github.com/user-attachments/assets/10168e17-6b66-443d-a980-5a8760deacdc
https://github.com/user-attachments/assets/ac0bf510-92c0-4767-ae6e-fc7999b6b23d
https://github.com/user-attachments/assets/9322abb4-a0ad-4924-9f96-eae200b8d8ca
> feat(payment): PI-3533 Remove the leftover code of Checkout.com credit card in paymentMethod

- package-lock.json
- package.json
- packages/braintree-integration/src/BraintreeFastlane/BraintreeFastlanePaymentMethod.test.tsx
- packages/braintree-integration/src/BraintreeFastlane/BraintreeFastlanePaymentMethod.tsx
Added onError Handling for BT FL
To throw an error when needed
https://github.com/user-attachments/assets/e20d8e77-1fc9-4628-95fb-66b0097942f6
https://github.com/user-attachments/assets/4fc33fa2-baba-49c0-9402-ff1783d0c408
> feat(payment): PAYPAL-5197 added error handler to BT FL

- package-lock.json
- package.json
- packages/core/src/app/config/config.mock.ts
- packages/core/src/app/customer/CustomerInfo.test.tsx
- packages/core/src/app/customer/CustomerInfo.tsx
- packages/test-mocks/src/config.mock.ts
Redirect to storefront logout when shouldRedirectToStorefrontForAuth is true and sign out link is provided
As part of headless offering, redirect shoppers to storefront logout page to logout
https://github.com/user-attachments/assets/5775a180-4308-4d7d-b068-19de81e8714e
> feat(checkout): CHECKOUT-9167 Redirect to storefront logout

- package-lock.json
- package.json
To update code 
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2822
Unit tests
> chore(payment): PAYPAL-5258 bumped checkout-sdk-js version

- package-lock.json
- package.json
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.test.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
- packages/core/src/app/shipping/stripeUPE/StripeStateMapper.ts
Remove experiment for Stripe Link Spain state mapping
PRs:
checkout-sdk-js: [https://github.com/bigcommerce/checkout-sdk-js/pull/2828](https://github.com/bigcommerce/checkout-sdk-js/pull/2828)
Fix was successfully rolled out and experiment can be removed
Rollback this PR
Stripe Link add new address
https://github.com/user-attachments/assets/daef8aac-e8d5-4c1e-942a-5a03b63778c2
Stripe Link change existing address
https://github.com/user-attachments/assets/bcb6f646-b9a3-4e4a-a408-4a003e252544
Stripe Link pay with existing address
https://github.com/user-attachments/assets/79fc8fe8-82ec-49a6-85bb-c153a107b92f
> feat(payment): STRIPE-667 remove experiment for Stripe Link Spain state mapping

- package-lock.json
- package.json
Bump checkout-sdk version to `1.726.0`
As part of the release: https://github.com/bigcommerce/checkout-sdk-js/pull/2827
Manual Testing
> feat(payment): PI-3669 bump checkout-sdk version

- packages/ui/src/form/CheckboxInput/CheckboxInput.test.tsx
- packages/ui/src/form/ChecklistItemInput/ChecklistItemInput.test.tsx
- packages/ui/src/form/Fieldset/Fieldset.test.tsx
- packages/ui/src/form/Input/Input.test.tsx
- packages/ui/src/form/Label/Label.test.tsx
- packages/ui/src/form/Legend/Legend.test.tsx
- packages/ui/src/form/RadioInput/RadioInput.test.tsx
- packages/ui/src/form/TextArea/TextArea.test.tsx
- packages/ui/src/form/TextInput/TextInput.test.tsx
- packages/ui/src/form/TextInputIframeContainer/TextInputIframeContainer.test.tsx
Remove enzyme tests from `packages/ui/src/form/`
1. Input
2. Label
3. Legend
4. RadioInput
5. TextArea
6. TextInput
7. TextInputIframeContainer
Enable us to upgrade to React 19.
- CI checks
**Coverage Before**
**Coverage After**
> test(checkout): CHECKOUT-9145 convert ui/form tests enzyme to RTL - Part 3

- packages/core/src/scss/components/checkout/checklist/_checklist.scss
Fix styling for custom hosted payment element.
Original PR: [https://github.com/bigcommerce/checkout-js/pull/2036](https://github.com/bigcommerce/checkout-js/pull/2036)
To keep custom check list container clear, remove unnecessary paddings.
Before:
After:
> fix(payment): STRIPE-725 Fix styling for custom hosted payment element

- package-lock.json
- package.json
Bump checkout-sdk with AmazonPay fix
Due to the release of https://github.com/bigcommerce/checkout-sdk-js/pull/2838
Look testing proof section [here](https://github.com/bigcommerce/checkout-sdk-js/pull/2838) 
> fix(payment): Bump checkout-sdk with AmazonPay fix

- packages/stripe-integration/src/index.ts
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.tsx
- packages/stripe-integration/src/stripe-upe/StripeUPEPaymentMethod.tsx
Add container for Stripe OCS payment method
To develop and render new Stripe implementation in the new separate container
https://github.com/user-attachments/assets/5290afe8-fe8e-4217-a389-ea0b980a6813
https://github.com/user-attachments/assets/0c75c329-96fe-45b4-ab0f-e7d2c23ac1ec
> feat(payment): create container for Stripe OCS payment method

- package-lock.json
- package.json
As part of the release https://github.com/bigcommerce/checkout-sdk-js/pull/2847
Manual tests
> feat(payment): bump checkout-sdk

- package-lock.json
- package.json
- packages/core/project.json
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/scss/settings/global/layout/_layout.scss
- webpack.config.js
Update webpack config to cache to filesystem, speeding up subsequent builds
As part of work on optimizing builds: 
- add caching
- remove source map generation for node_modules
- suppress warnings for scss node_modules deprecation warnings. (This should be removed once we update citadel package or find a replacement)
- CI
> chore(checkout): Update webpack config

- jest-setup.ts
- package-lock.json
- package.json
- packages/core/.eslintrc.json
- packages/core/src/app/common/form/ConnectFormikProps.ts
- packages/core/src/app/common/form/connectFormik.test.tsx
- packages/core/src/app/common/form/withFormikExtended.test.tsx
- packages/core/src/app/common/form/withFormikExtended.tsx
- packages/core/src/app/customer/SubscribeField.tsx
- packages/core/src/app/customer/__snapshots__/StripeGuestForm.test.tsx.snap
- packages/core/src/app/payment/Payment.test.tsx
- packages/core/src/app/payment/PaymentForm.tsx
- packages/core/src/app/payment/createPaymentFormService.ts
- packages/core/src/app/payment/creditCard/CreditCardNumberField.tsx
- packages/core/src/app/shipping/SingleShippingForm.test.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingForm.test.tsx
- packages/core/src/app/ui/form/BasicFormField.tsx
- packages/instrument-utils/src/creditCard/CreditCardExpiryField.tsx
- packages/instrument-utils/src/creditCard/CreditCardNumberField/CreditCardNumberField.tsx
- packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.tsx
- packages/instrument-utils/src/storedInstrument/InstrumentSelect/InstrumentSelect.tsx
- packages/mollie-integration/src/MollieAPMCustomForm.tsx
- packages/test-framework/src/fixture/pageObject/Checkout.ts
- packages/ui/src/form/BasicFormField/BasicFormField.tsx
- packages/ui/src/form/Form/Form.test.tsx
Upgrade Formik from `v1.5.8` to `v2`.
I’ve made some comments in the PR to explain the breaking changes.
Formik `v1.5.8` has dependency conflicts with React 18. Therefore, Formik `v2` is necessary.
CI.
> chore(checkout): Upgrade Formik 2

- packages/core/src/app/shipping/Shipping.test.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
- packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
- packages/test-framework/src/react-testing-library-support/mocks/countries.ts
- packages/test-framework/src/react-testing-library-support/mocks/form-fields.ts
Refactor Formik logic to ensure proper handling of the province form field.
To resolve the issue where shoppers are unable to select a province value when returning to the shipping step.
CI.
> fix(checkout): Update formik logic

- package-lock.json
- package.json
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.tsx
- packages/stripe-integration/src/stripe-ocs/getStripeOCSStyles.test.ts
- packages/stripe-integration/src/stripe-ocs/getStripeOCSStyles.ts
Add basic customization options for Stripe OCS accordion
checkout-js PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2853](https://github.com/bigcommerce/checkout-sdk-js/pull/2853)
To get ability for customization new Stripe accordion elememnt
https://github.com/user-attachments/assets/394a94bd-9d99-4239-b596-64f3190cf0e4
> feat(payment): Stripe OCS accordion element styling

- package.json
Updated `npm run release:alpha` command by updating by changing `npm run build` with `npm run nx:build`
Because prev variant does not apply env variable and throws an error
Before:
After:
> fix(common): fixed npm run release:alpha command run

- packages/core/src/app/customer/GuestForm.tsx
- packages/core/src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
- packages/core/src/scss/components/checkout/customer/_customer.scss
- packages/core/src/scss/components/foundation/forms/_forms.scss
Update padding for customer steps and step sections.
In order to remove empty white space and clean styles, reduce padding.
- CI
- Screenshots
> chore(customer): CHECKOUT-7961 Update padding for steps and customer step

- packages/instrument-utils/src/storedInstrument/InstrumentStoreAsDefaultField/InstrumentStoreAsDefaultField.tsx
Fix consistent re-renders on payment step
Because it was a blocker for payment UI
Before changes:
https://github.com/user-attachments/assets/aaccb0a7-e389-4cad-bfa3-80a4b9746868
After changes Stripe UPE behaviour:
https://github.com/user-attachments/assets/38086683-1c5b-416b-a26a-12f86c034694
After changes Adyen behaviour:
https://github.com/user-attachments/assets/f72639ca-ae3b-4b5b-9f6d-5548e41192b3
> fix(payments) fix consistent re-renders on payment step

- packages/core/src/app/customer/StripeGuestForm.tsx
Fix Formik issues with Stripe Link.
Stripe Link does not set a `validationSchema` by default. As a result, Formik throws validation errors, as shown in the screenshot.
The Stripe Link guest form cannot be submitted because the email value is not propagated to the Formik context, and as a result, the validation fails.
To ensure shoppers can successfully use Stripe Link during checkout.
https://github.com/user-attachments/assets/02a1d7c3-c34c-45db-a3e7-a67918610bb3
> fix(payment): Fix Stripe Link Formik Issues

- package-lock.json
- package.json
As part of the release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2856
Manual tests
> feat(payment): bump checkout-sdk version

- packages/core/src/app/customer/CheckoutButtonList.test.tsx
- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/google-pay-integration/src/GooglePayButton.scss
Checkout has 2 places where wallet buttons can be rendered based on settings selected by merchant:
1. Wallet buttons on top of checkout page;
2. Wallet buttons in customer step under the form where customer enters guest email address;
Both implementations has different approaches. The first one has an ability to use generated files (components from integration packages), to render wallet buttons, however second approach did not have such thing. 
So this PR contains changes:
- updated CheckoutButtonList component with ResolvedCheckoutButton implementation;
- removed Amazon Pay button component from core package, since there is the same component present in amazon integration package;
- updated google pay styles to fix style glitch with button height when button renders in customer step; …
> feat(payment): updated CheckoutButtonList component to use Wallet Buttons components directly from generated files

- package-lock.json
- package.json
- webpack.config.js
Enable Subresource Integrity (SRI) using the webpack-subresource-integrity plugin.
To comply with PCI requirements by ensuring the integrity of dynamically loaded scripts.
The shipping chunk file has been injected with with SRI.
> Pass SRI using webpack-subresource-integrity

- packages/paypal-commerce-integration/src/PayPalCommerce/PayPalCommerceButton.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerce/PayPalCommerceButton.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCredit/PayPalCommerceCreditButton.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCredit/PayPalCommerceCreditButton.tsx
- packages/paypal-commerce-integration/src/index.ts
Created PayPalCommerceButton and PayPalCommerceCreditButton components in paypal-commerce-integration package
As part of paypal commerce specific code migration from core to integration package. This change allows us to remove PayPalCommerceButton component from core package
Unit tests
Manual tests
PayPalCommerceButton and PayPalCommerceCreditButton components are used for both "wallet buttons on top of checkout page" and "wallet buttons in customer step"
> refactor(payment): created PayPalCommerceButton and PayPalCommerceCredit components in paypal-commerce-integration package

- packages/braintree-integration/src/BraintreeAch/components/BraintreeAchPaymentForm.tsx
Fixed BT ACH Payment Form
BT ACH Payment form had infinite rerendering that makes checkout page freeze. Now everything works as expected
https://github.com/user-attachments/assets/51e7efee-d032-4b65-a52f-680d91b23d0c
> fix(payment): Fixed BT ACH Payment Form 

- packages/core/src/app/order/getOrderSummaryItemImage.test.tsx
- packages/core/src/app/order/getOrderSummaryItemImage.tsx
Fixed redundant alt text on product images in the checkout sidebar to comply with EAA (European Accessibility Act) standards.
Resolves #2332
The current implementation uses the product name as alt text, which is redundant since the product name is already displayed next to the image in the UI. This creates a repetitive experience for screen reader users who will hear the same information twice.
According to accessibility best practices, when an image is purely decorative and its content is already conveyed through nearby text, an empty alt attribute (`alt=""`) should be used to prevent screen readers from announcing redundant information.
- Unit tests have been updated to reflect the new implementation
- Manually verified with screen readers that the product information is properly …
> fix(core): CHECKOUT-000 Fix redundant alt text on checkout sidebar product images

- packages/core/src/scss/settings/global/color/_color.scss
Improved the contrast ratio of error messages by darkening the error color from `#ed6a6a` to `#d12727`, and adjusted related error color shades for consistency.
Resolves #2339
The previous error text color (`#ed6a6a`) on a white background (`#ffffff`) had a contrast ratio of approximately 3.05:1, which failed to meet WCAG AA requirements of 4.5:1 for normal text. This was an accessibility issue affecting users with visual impairments.
The new error color (`#d12727`) provides a contrast ratio of 5.21:1 against a white background, which successfully meets the WCAG AA requirement of 4.5:1 for normal text and 3:1 for large text.
- Verified the new contrast ratio using the WebAIM Contrast Checker
- Improved the contrast ratio from 3.05:1 to 5.21:1, which successfully meets WCAG AA requirements …
> fix(core): CHECKOUT-000 Improve error message contrast for accessibility

- packages/core/src/app/shipping/ConsignmentAddressSelector.tsx
- packages/core/src/app/shipping/MultiShipping.test.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/instrument-utils/src/storedInstrument/ManageInstrumentsModal/ManageInstrumentsModal.test.tsx
- packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
- packages/test-framework/src/react-testing-library-support/mocks/checkout-settings.mock.ts
- packages/test-framework/src/react-testing-library-support/mocks/checkout.mock.ts
Enable guest multi-shipping.
The feature is behind the experiment, `CHECKOUT-9161.enable_storefront_guest_multi_shipping`.
Enhancing the multi-shipping experience for both registered and guest users will contribute to increased satisfaction among BC merchants.
https://github.com/user-attachments/assets/eb2b432a-5859-40e9-ac96-02303c08a0d0
> feat(checkout): Enable Guest Multi-shipping

- packages/core/src/app/customer/CustomerGuest.test.tsx
- packages/core/src/app/customer/GuestForm.tsx
- packages/core/src/app/customer/StripeGuestForm.test.tsx
- packages/core/src/app/customer/StripeGuestForm.tsx
Fix the issue where the newsletter subscription checkbox does not reflect the merchant's selected option.
Improve shopper experience.
Email setting
Default guest form
Default stripelink guest form
> fix(checkout): Fix Newsletter Subscription Checkbox

- package-lock.json
- package.json
- packages/stripe-integration/.eslintrc.json
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.tsx
- packages/stripe-integration/src/stripe-ocs/getStripeOCSStyles.test.ts
- packages/stripe-integration/src/stripe-ocs/getStripeOCSStyles.ts
Move all styling options for Stripe OCS to checkoput-js side.
Checkout-sdk PR:  [https://github.com/bigcommerce/checkout-sdk-js/pull/2891](https://github.com/bigcommerce/checkout-sdk-js/pull/2891)
To make Stripe widget more flexible for merchants with custom checkout. 
https://github.com/user-attachments/assets/7a59c334-04aa-4a3c-b3c5-d51dba8de69b
> feat(payment): Move all Stripe OCS styling configs to checkout-js side

- package-lock.json
- package.json
Bump checkout-sdk version to 1.747.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2849
https://github.com/bigcommerce/checkout-sdk-js/pull/2894
Unit tests
Manual tests
CI
> chore(payment): bump checkout-sdk version to 1.747.0

- package-lock.json
- package.json
- packages/core/src/app/customer/getSupportedMethods.ts
- packages/google-pay-integration/src/GooglePayButton.tsx
- packages/google-pay-integration/src/GooglePayPaymentMethod.tsx
- packages/payment-integration-api/src/PaymentMethodId.ts
Added Stripe OCS Google pay
Related PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/2897
Customer step button:
https://github.com/user-attachments/assets/663d922a-057c-47a8-b3a0-09bda3c3eca2
PDP page:
https://github.com/user-attachments/assets/08bce79f-50ea-4de5-a049-0fa167789ff4
Manual testing
> feat(payment): StripeOCS Google Pay added

- .github/workflows/lighthouse-audit.yml
- .gitignore
- package-lock.json
- package.json
- scripts/lighthouse/format-results.js
- scripts/lighthouse/lighthouserc-desktop.json
- scripts/lighthouse/lighthouserc-mobile.json
- scripts/lighthouse/setup.js
Add Github action to run Lighthouse audit against a staging store on every release.
To monitor end-to-end performance degradation using an industry-standard metric.
> CHECKOUT-9275: Add Github action to run Lighthouse audit on every release

- .github/workflows/lighthouse-audit.yml
Currently commenting doesn't work because `gh-find-current-pr` is unable to derive the PR number. Trying `github.event.issue.number` instead.
I will need to test it in the default branch.
> CHECKOUT-9275: Fix Lighthouse audit not posting results back to PR

- package-lock.json
- package.json
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2904
> chore(payment): bump checkout-sdk version

- .circleci/config.yml
- package.json
- packages/checkout-extension/src/handler/commandHandlers/commandHandlers.test.ts
- playwright.config.ts
- scripts/nx/collect-test-results.js
- scripts/nx/run-tests.js
* Instead of re-running the entire test suite, `circleci tests run` command allows you to re-run just the failed tests, significantly reducing the time required for a re-run. See https://circleci.com/docs/rerun-failed-tests/
* Enable parallelism by splitting the tests across multiple containers using timing data. See https://circleci.com/blog/a-guide-to-test-splitting/
* Reduce test flakiness by ensuring that tests run sequentially within each container, since individual tests may have side effects.
When a test job fails, we can now click on the "Rerun failed tests" to re-run the failed tests instead of the entire test suite.
> CHECKOUT-9307: Re-run only the failed CI tests instead of the whole suite in case of transient failures

- packages/core/src/scss/settings/global/color/_color.scss
Update alert and success messages' color contrast.
To meet WCAG 2.1 standards.
> feat(checkout): CHECKOUT-9314 Improve Color Contrast to Meet WCAG 2.1 Standards

- packages/paypal-commerce-integration/src/PayPalCommerce/PayPalCommerceButton.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerce/PayPalCommerceButton.tsx
- packages/paypal-commerce-integration/src/PayPalCommerce/PayPalCommercePaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerce/PayPalCommercePaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerce/hooks/usePaypalCommerceInstruments.ts
- packages/paypal-commerce-integration/src/PayPalCommerceAPMs/PayPalCommerceAPMsPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceAPMs/PayPalCommerceAPMsPaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCredit/PayPalCommerceCreditButton.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCredit/PayPalCommerceCreditButton.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCredit/PayPalCommerceCreditPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCredit/PayPalCommerceCreditPaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/PayPalCommerceFastlanePaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneCreditCardForm.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneForm.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneForm.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneInstrumentsForm.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceFastlane/components/PayPalCommerceFastlaneInstrumentsForm.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceRatepay/PaypalCommerceRatePayPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceRatepay/PaypalCommerceRatePayPaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceRatepay/validation-schema/getPaypalCommerceRatePayValidationSchema.ts
- packages/paypal-commerce-integration/src/PayPalCommerceVenmo/PayPalCommerceVenmoPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceVenmo/PayPalCommerceVenmoPaymentMethod.tsx
- packages/paypal-commerce-integration/src/components/PayPalCommercePaymentMethodComponent.test.tsx
Fixed eslint warnings and errors in paypal-commerce-integration package
To keep paypal-commerce-integration codebase as clean as possible
Unit tests
CI
Before:
After:
> fix(payment): fixed eslint errors in paypal-commerce-integration package

- .circleci/config.yml
Before this change, `collect-test-results.js` wouldn't run if the preceding step failed. As a result, CircleCI could not upload the test results, and was unable to re-run failed tests. Adding `when: always` ensures that this step is always executed regardless of the outcome of previous steps.
This screenshot shows the test results were collected even though the preceding step failed.
These screenshots show that the failed test can be re-run independently.
> CHECKOUT-9307: Always collect test results even if there are test failures

- packages/paypal-commerce-integration/src/PayPalCommerceCreditCards/PayPalCommerceCreditCardsPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCreditCards/PayPalCommerceCreditCardsPaymentMethod.tsx
- packages/paypal-commerce-integration/src/index.ts
Created PayPalCommerceCreditCardsPaymentMethod in paypal-commerce-integration package
To remove the same component from core in the future
Unit tests
Manual tests
CI
Place order with credit card:
https://github.com/user-attachments/assets/a2e11db7-528b-44aa-992b-ea86df9ce27d
Place order with vaulted instrument:
https://github.com/user-attachments/assets/3557c495-ad1b-4780-a8ea-a14c6cb4df94
Place order with new card and coupon code:
https://github.com/user-attachments/assets/377dd617-a8de-4442-8354-7ce481dbc283
> refactor(payment): created PayPalCommerceCreditCardsPaymentMethod in paypal-commerce-integration package to remove the same component from core

- package-lock.json
- package.json
bump checkout-sdk version to 1.755.2
to release https://github.com/bigcommerce/checkout-sdk-js/pull/2905
all tests passed
> chore(payment): bump checkout-sdk version (1.755.2)

- package-lock.json
- package.json
Bump checkout-sdk version to 1.756.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2911
> chore(payment): bump checkout-sdk version to 1.756.1

- package-lock.json
- package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2915](https://github.com/bigcommerce/checkout-sdk-js/pull/2915)
> chore(payment): bump checkout-sdk-js version

- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- packages/paypal-utils/src/PaypalCommerceCreditBanner.test.tsx
- packages/paypal-utils/src/PaypalCommerceCreditBanner.tsx
Updated `PaymentMethodTitle` with providing banner initialization to PayPal Payment Section
Depends on: https://github.com/bigcommerce/checkout-sdk-js/pull/2919
To be able render BNPL banner component
**With Fastlane disabled**
Pay Later is disabled
Pay Later is enabled
**With Fastlane enabled**
Pay Later is disabled
Pay Later is enabled
> feat(payment): New logic for PayPal BNPL banner on checkout page

- packages/core/src/app/customer/Customer.tsx
Reverted back changes related to continue button text in suggest login form
"Continue as guest" button text is better for understanding then "Continue", so the customers would not be confused what to do next when the "suggest to login" form shows up on the screen.
This behaviour could be reproduced with Braintree Fastlane or PPCP Fastlane providers enabled.
Manual tests
CI
Before:
After:
> refactor(payment): reverted back changes related to continue button text in suggest login form

- packages/core/src/app/address/googleAutocomplete/AddressSelectorAU.test.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelectorAU.ts
This PR updates the autocomplete rules for Australian addresses. 
When a user selects an address that includes a unit number (e.g., "4/28 Beach St"), the unit number should appear in  Address Line 1 only.
Improve Austrlian shopper experience.
https://github.com/user-attachments/assets/133a543c-cea5-4863-9c57-4fadfa5443f8
> feat(checkout): CHECKOUT-9376 Update Autocomplete for Australian Addresses

- packages/core/src/app/billing/BillingForm.tsx
Updated billing form to show fastlane addresses only for guest users
Fastlane is not supported for BC logged in customers, so logged in customers should be able to use addresses from their address book in billing step
Manual tests
CI
Before:
After:
> fix(payment): updated billing form to show fastlane addresses only for guest users

- package-lock.json
- package.json
Bump checkout-sdk-js - 1.767.1
https://github.com/bigcommerce/checkout-sdk-js/pull/2930
CI
> chore(payment): bump checkout-sdk-js - 1.767.1

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/mapToCheckoutProps.ts
- packages/core/src/app/shipping/Shipping.test.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Render checkout steps only after checkout, checkout-settings and extensions have been loaded to avoid conflict in the formik state.
To fix issue where "My Billing address is the same as my Shipping address" remains checked disregarding Checkout settings
- CI checks
**BEFORE**
https://github.com/user-attachments/assets/c01c21a6-a898-41e9-86ef-0be81408d184
**AFTER**
https://github.com/user-attachments/assets/0b747746-90cf-4751-9ddb-afe88e0567f1
> Fix billing same as shipping checkbox to honour checkout settings

- package-lock.json
- package.json
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.tsx
Add `linkInAccordion` option to Stripe OCS accordion config
This feature will be added by stripe team to manage STRIPE OCS Link logic as accordion section with additional radio button
PR with related changes: [https://github.com/bigcommerce/checkout-sdk-js/pull/2935](https://github.com/bigcommerce/checkout-sdk-js/pull/2935)
In related PR
> feat(payment): Stripe OCS radio button for Link

- package-lock.json
- package.json
Bump checkout-sdk-js version - 1.768.1
A part of release https://github.com/bigcommerce/checkout-sdk-js/pull/2933
Unit tests
Manual tests
CI
> chore(payment): bump checkout-sdk-js version - 1.768.1

- packages/core/src/app/address/googleAutocomplete/AddressSelectorAU.test.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelectorAU.ts
Add `/` to an AU address when subprimise is applicable.
Improve checkout experience.
https://github.com/user-attachments/assets/32f3e446-00c0-48a1-8dd2-4cc388e942bd
> feat(checkout): CHECKOUT-9376 Update Autocomplete for AU Address II

- packages/core/src/scss/components/bigcommerce/forms/_forms.scss
- packages/core/src/scss/components/foundation/forms/_forms.scss
- packages/core/src/scss/settings/foundation/forms/_settings.scss
- packages/core/src/scss/settings/foundation/global/_settings.scss
Update all form fields's color from `#fcfcfc` to `white`.
Continue to evolve Optimized One Page Checkout to keep the design modern, light and fresh.
> feat(checkout): CHECKOUT-9301 Update Form Field Background Color

- packages/payment-integration-api/src/contexts/checkout-context/CheckoutProvider.tsx
Convert class component `CheckoutProvider` into function component.
CI.
> refactor(checkout): CHECKOUT-9375 Convert CheckoutProvider into Function Component

- packages/core/src/app/payment/creditCard/CreditCardNumberField.tsx
Convert class component `CreditCardNumberInput` into function component.
CI.
> refactor(checkout): CHECKOUT-9375 Convert CreditCardNumberInput

- packages/core/src/app/ui/modal/ModalTrigger.tsx
Convert class component `ModalTrigger` into function component.
CI.
> refactor(checkout): CHECKOUT-9375 Convert ModalTrigger

- packages/core/src/app/checkout/CheckoutApp.tsx
Convert class component `CheckoutApp` into function component.
CI.
> refactor(checkout): CHECKOUT-9375 Convert CheckoutApp

- package-lock.json
- package.json
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.tsx
Add loading animation for Stripe OCS accordion
Related PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2959](https://github.com/bigcommerce/checkout-sdk-js/pull/2959)
To show shopper that some payment methods are loading
Before:
https://github.com/user-attachments/assets/bb3f6d81-f55f-4f94-a838-353905832f3d
After:
https://github.com/user-attachments/assets/4b84fabb-6bcc-4031-af19-6dbcdd6fac95
> feat(payment): Stripe OCS preloader

- package.json
- packages/core/src/app/customer/Customer.test.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/LoginForm.tsx
- packages/core/src/app/customer/RedirectToStorefrontLogin.tsx
Redirect to storefront for auth when setting is on for doing auth in storefront login/logout. This is especially for catalyst stores.
- CI
- Screencast
https://github.com/user-attachments/assets/e175ba8e-d67e-4a0e-9a2a-644a8b1c88c5
> feat(customer): CHECKOUT-9390 Redirect to storefront for auth when setting is on

- packages/core/src/app/checkout/CheckoutPage.tsx
- packages/core/src/app/order/OrderConfirmation.tsx
- packages/core/src/scss/components/checkout/loadingSkeleton/_loadingSkeleton.scss
- packages/ui/src/form/LoadingSkeleton/CheckoutPageSkeleton.test.tsx
- packages/ui/src/form/LoadingSkeleton/CheckoutPageSkeleton.tsx
- packages/ui/src/form/LoadingSkeleton/OrderConfirmationPageSkeleton.test.tsx
- packages/ui/src/form/LoadingSkeleton/OrderConfirmationPageSkeleton.tsx
- packages/ui/src/form/LoadingSkeleton/index.ts
- packages/ui/src/form/index.ts
- packages/ui/src/index.ts
Add loading skeletons for the mobile version of checkout and order confirmation pages.
Revert.
https://github.com/user-attachments/assets/6a0b133a-1412-4763-b18b-7029a2baed40
https://github.com/user-attachments/assets/88a059c0-baac-46fd-b15a-1962aedd1788
> feat(checkout): CHECKOUT-9389 Add Mobile Loading Skeletons

- webpack.config.js
Prefer ESM entry points over CommonJS (CJS) when resolving external packages. ESM supports tree-shaking, reducing bundle size by removing unused code, whereas CJS does not. The previous preference for CJS was a workaround for a Formik bug, which has been resolved with the recent [Formik upgrade](https://github.com/bigcommerce/checkout-js/pull/2286), making it safe to revert.
Revert
> CHECKOUT-9423: Prefer ESM entry points over CJS for external packages

- packages/core/src/app/checkout/renderCheckout.test.tsx
- packages/core/src/app/order/renderOrderConfirmation.test.tsx
For some reason, some of the tests for `renderCheckout` and `renderOrderConfirmation` (https://app.circleci.com/pipelines/github/bigcommerce/checkout-js/13802/workflows/1cfe030f-392e-47b8-bb03-5d11644f9f98/jobs/68536) started failing consistently after merging #2493 and #2489 due to the way the `configurePublicPath` mock was set up. This PR updates the mock setup to resolve the issue.
Revert
CircleCI
> CHECKOUT-9416: Fix the failed tests for `renderCheckout` and `renderOrderConfirmation`

- package-lock.json
- package.json
- packages/core/src/app/customer/Customer.test.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/LoginForm.tsx
- packages/core/src/app/customer/RegisteredCustomer.test.tsx
- packages/locale/src/getDefaultTranslations.test.ts
- packages/locale/src/getDefaultTranslations.ts
Remove option for passwordless login for buy now carts
- CI
- Screencast
https://github.com/user-attachments/assets/c8aaf257-7517-4dfb-81fa-fd15c5640c43
> feat(customer): CHECKOUT-9403 Hide passwordless login option for buy now cart

- packages/checkout-button-integration/src/CheckoutButton.tsx
- packages/core/auto-export.config.json
- packages/core/src/app/common/resolver/index.ts
- packages/core/src/app/common/resolver/resolveLazyComponent.test.tsx
- packages/core/src/app/common/resolver/resolveLazyComponent.ts
- packages/core/src/app/common/utility/isExperimentEnabled.ts
- packages/core/src/app/customer/CheckoutButton.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.tsx
- packages/core/src/app/customer/CheckoutButtonList.test.tsx
- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/customer/WalletButtonV1Resolver.test.tsx
- packages/core/src/app/customer/WalletButtonV1Resolver.tsx
- packages/core/src/app/customer/resolveCheckoutButton.ts
- packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodV2.tsx
- packages/core/src/app/payment/resolvePaymentMethod.ts
- packages/core/src/app/payment/storedInstrument/ManageInstrumentsModal.test.tsx
- packages/workspace-tools/.eslintrc.json
- packages/workspace-tools/src/generators/auto-export/__fixtures__/component-a/index.ts
- packages/workspace-tools/src/generators/auto-export/__fixtures__/component-b/index.ts
- packages/workspace-tools/src/generators/auto-export/__fixtures__/shared.ts
- packages/workspace-tools/src/generators/auto-export/__snapshots__/auto-export.test.ts.snap
- packages/workspace-tools/src/generators/auto-export/auto-export-config.ts
- packages/workspace-tools/src/generators/auto-export/auto-export.test.ts
- packages/workspace-tools/src/generators/auto-export/auto-export.ts
- packages/workspace-tools/src/generators/auto-export/is-auto-export-config.ts
Optimized bundle size by implementing lazy loading for payment method and checkout button components. Previously, `checkout-js` bundled all components for every payment provider regardless of whether they were enabled by the merchant, leading to unnecessary bloat and slower performance.
To enable lazy loading, a custom build script was added that extracts the payment method each component resolves to at build time, allowing them to be dynamically loaded only when needed at runtime.
To reduce risk, I’ve wrapped the change in an experiment. As a result, there won’t be any performance benefits until the experiment is removed, since the old code path is still being bundled. I plan to remove the experiment one week after the change is released.
Revert or turn off …
> CHECKOUT-9432: Lazy load payment method & checkout button components to reduce bundle size

- package-lock.json
- package.json
Bump checkout SDK to release https://github.com/bigcommerce/checkout-sdk-js/compare/7ed5eb742e2f...a8ed9fa6a38f
- revert
- CI
> chore(other): CHECKOUT-9448 bump sdk

- packages/core/src/app/ui/tooltip/TooltipTrigger.tsx
- packages/ui/src/dropdown/DropdownTrigger.tsx
- packages/ui/src/form/BasicFormField/BasicFormField.tsx
- packages/ui/src/modal/ModalTrigger.tsx
Convert class components `TooltipTrigger, ModalTrigger, DropdownTrigger, BasicFormField`  into function component.
- CI checks
> feat(checkout): CHECKOUT-9385 Convert ui package class components

- packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.tsx
- packages/instrument-utils/src/storedInstrument/InstrumentSelect/InstrumentSelect.tsx
Convert class components `AccountInstrumentSelect, InstrumentSelect`  into function component.
- CI checks
> feat(checkout): CHECKOUT-9385 Convert instrument utils package class components 

- packages/apple-pay-integration/src/ApplePayPaymentMethod.tsx
- packages/bigcommerce-payments-integration/src/BigCommercePaymentCreditCards/BigCommercePaymentsCreditCardsPaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCreditCards/PayPalCommerceCreditCardsPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCreditCards/PayPalCommerceCreditCardsPaymentMethod.tsx
- packages/workspace-tools/src/generators/auto-export/auto-export.ts
Some payment method components couldn’t be lazy loaded because their names didn’t match the re-exported names at the root package level (e.g.: `PayPalCommerceCreditCardPaymentMethod` vs `PayPalCommerceCreditCardsPaymentMethods). I’ve renamed them for consistency and added a validation step in the auto-export build script to ensure the build fails if inconsistent naming occurs in the future.
Revert
The screenshot shows that `PayPalCommerceCreditCardsPaymentMethod` could not be resolved. As a result, the fallback component `HostedCreditCardPaymentMethod` was used, which led to an error due to missing required options.
The screenshot shows `PayPalCommerceCreditCardsPaymentMethod` could now be resolved after renaming.
> CHECKOUT-9432: Fix inconsistent component names to allow lazy loading

- packages/core/src/app/shipping/PayPalFastlaneShippingAddress.test.tsx
- packages/core/src/app/shipping/PayPalFastlaneShippingAddress.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/ShippingAddress.tsx
- packages/core/src/app/shipping/ShippingAddressForm.tsx
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Convert class component `ShippingAddressForm` into function component.
Revert.
CI.
> refactor(checkout): CHECKOUT-9384 Convert ShippingAddressForm

- packages/wallet-button-integration/src/PaymentView.tsx
- packages/wallet-button-integration/src/SignInView.tsx
- packages/wallet-button-integration/src/WalletButtonPaymentMethodComponent.test.tsx
- packages/wallet-button-integration/src/WalletButtonPaymentMethodComponent.tsx
Convert class component `WalletButtonPaymentMethodComponent` into function component.
- CI checks
> feat(checkout): CHECKOUT-9385 Convert WalletButtonPaymentMethodComponent

- packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
Removed BT venmo initialization from core
Revert PR
https://github.com/user-attachments/assets/ae6d6fe1-625a-42b8-9e7a-5bbeda7723a5
> refactor(payment): PAYPAL-5710 Removed init braintree venmo from core

- .circleci/config.yml
- packages/apple-pay-integration/e2e/applepay.spec.ts
It appears that the current glob pattern is incorrect. As a result, the e2e tests are not executed as part of the CI run.
Revert
CircleCI
> fix(common): CHECKOUT-9307 Fix e2e test glob pattern

- package-lock.json
- package.json
Bump checkout-sdk version.
To deliver:
https://github.com/bigcommerce/checkout-sdk-js/pull/2986
https://github.com/bigcommerce/checkout-sdk-js/pull/2987
Related PR:
https://github.com/bigcommerce/bigcommerce/pull/64783
Revert this PR
Manual testing
> feat(payment): checkout-sdk version bump

- .circleci/config.yml
- Using an existing docker image with playwright to skip installing playwright on every run.
- Reuse the `/dist` artifacts from the `build` job, therefore, only build once, `e2e` job will start following a successful `build` run.
Revert.
Running time before
Running time after
> refactor(checkout): CHECKOUT-9386 Improve e2e CI Job Performance

- packages/checkoutcom-integration/src/CheckoutcomCustomPaymentMethod.tsx
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.tsx
to make it possible to use KNET and all the checkoutcom APMs, without using their id directly
For now the Knet redirect link is not working, we're in touch with their support to find the solution
Revert this PR
Before:
it was displayed as a credit card instead of redirecting to the redirect url
After:
to make sure credit card is still working:
https://github.com/user-attachments/assets/24c5dbc9-de7e-4cfa-92f4-53bc9bab03f5
> feat(payment): Add Knet to new NAS Checkout.com and make it possible to transact via other APMs

- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.test.tsx
- packages/stripe-integration/src/stripe-ocs/StripeOCSPaymentMethod.tsx
• Fix Stripe accordion toggle action, for show correct selected payment method method.
• Increase unit test coverage
Rollback this PR
Before:
https://github.com/user-attachments/assets/1cf709fa-9604-4275-9346-1a0b2d2239f8
After:
https://github.com/user-attachments/assets/b49539c0-4629-4eb9-b96d-725c8a0eee7f
https://github.com/user-attachments/assets/fc3b7b61-328c-438c-b8e9-69b42cb2bdb5
Unit test coverage:
> fix(payment): Stripe OCS fix accordion item toggle

- packages/core/src/app/shipping/stripeUPE/StripeShippingAddressDisplay.tsx
StripeShippingAddress migrated to the functional
Revert this PR
Manual testing
https://github.com/user-attachments/assets/b0a50e7b-fc65-4e53-a97d-b2a73d8f22ee
> feat(payment): Stripe Shipping Address component migrated to functional component

- packages/core/src/scss/components/foundation/modal/_modal.scss
Remove unnecessary scroll bars from the checkout page's generic error modal.
Please note: in MacOS, scroll bars only always show up when "Show scroll bars" is set to "Always".
CI.
> feat(checkout): CHECKOUT-9428 Remove Scroll Bars from Error Modal

- packages/stripe-integration/src/stripe-ocs/getStripeOCSStyles.test.ts
- packages/stripe-integration/src/stripe-ocs/getStripeOCSStyles.ts
Update Stripe OCS radio buttons to match checkout themeV2 style
Rollback this PR
Existing checkout theme:
https://github.com/user-attachments/assets/615b1df3-ec36-4531-a5f4-8baf2fc4da22
ThemeV2
https://github.com/user-attachments/assets/534310b4-a54f-4126-ab15-05b842509dbf
> fix(payment): update Stripe OCS radio buttons to match checkout themeV2

- package-lock.json
- package.json
Bump checkout-sdk version. To release: https://github.com/bigcommerce/checkout-sdk-js/pull/3014
Revert this PR
Manual testing
> feat(payment): checkout-sdk bump version

- packages/instrument-utils/src/storedInstrument/ManageInstrumentsModal/ManageInstrumentsModal.test.tsx
- packages/instrument-utils/src/storedInstrument/ManageInstrumentsModal/ManageInstrumentsModal.tsx
Convert class component `ManageInstrumentsModal` into function component.
Revert.
https://github.com/user-attachments/assets/6715b9a6-ed05-4046-96fd-5ce1b7964ae1
https://github.com/user-attachments/assets/429bc8d5-1feb-497a-a626-258f347cccd4
> refactor(checkout): CHECKOUT-9386 Convert ManageInstrumentsModal

- packages/core/src/app/checkout/CheckoutPage.tsx
- packages/core/src/app/checkout/mapErrorMessage.test.ts
- packages/core/src/app/checkout/mapErrorMessage.ts
- packages/core/src/app/customer/Customer.test.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/mapErrorMessage.ts
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.test.ts
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.ts
- packages/core/src/app/shipping/Shipping.tsx
- packages/locale/src/translations/en.json
Catch empty cart error message and display a valid modal. 
At times if the cart only has one product and that product is made purchasable throughout checkout journey. The cart is removed on server side, we need to catch the error returned from server and display the message to shopper.
- CI
- Screencast
https://github.com/user-attachments/assets/95a433f2-9347-4321-83f2-34527c4e536a
https://github.com/user-attachments/assets/c39ced65-d665-4244-9024-12c6c6f0ab88
https://github.com/user-attachments/assets/a3fc2b21-2b3d-4b08-91ba-37227776d56b
> fix(checkout): CHECKOUT-9506 Catch empty cart error message

- packages/core/src/app/shipping/Shipping.tsx
Convert class component `Shipping` into function component.
Revert.
CI.
> feat(checkout): CHECKOUT-9477 Convert Shipping component (Part 1)

- packages/credit-card-integration/.eslintrc.json
- packages/credit-card-integration/src/CreditCardPaymentMethodComponent.test.tsx
- packages/credit-card-integration/src/CreditCardPaymentMethodComponent.tsx
- packages/credit-card-integration/src/CreditCardPaymentMethodType.ts
- packages/credit-card-integration/src/index.ts
Re-release https://github.com/bigcommerce/checkout-js/pull/2530 with updated dependencies due to an incident.
Convert class component `CreditCardPaymentMethodComponent` into function component.
Revert.
Bluesnap (The CC form fields freezing is a known issue)
https://github.com/user-attachments/assets/086eeaac-da33-42ae-bbcd-c8bb98df76ad
Access Worldpay
https://github.com/user-attachments/assets/5dd9e06a-8f5e-4637-9a63-58c23edfcc4c
> refactor(checkout): CHECKOUT-9386 Convert CreditCardPaymentMethodComponent
