package-lock.json, package.json
See https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#1980-2020-09-08
CircleCI
=> fix(payment): INT-3027 INT-3112 Bump checkout-sdk

package-lock.json, package.json
See https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#1990-2020-09-10
CircleCI
=> feat(payment): INT-3061 Bump checkout-sdk

package-lock.json, package.json
See
https://github.com/bigcommerce/checkout-sdk-js/pull/982
https://github.com/bigcommerce/bigpay-client-js/pull/108
CirleCI
=> chore(payment): PAYMENTS-5833 Bump checkout-sdk

README.md
Update typo
To avoid confusion
n/a
=> fix(common): CHECKOUT-5173 update typo

package-lock.json, package.json
Bump checkout-sdk version 
1.101.0 checkout-sdk version has been released
=> feat(payment): PAYPAL-705 bump checkout-sdk version

package-lock.json, package.json
See https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md
CircleCI
=> feat(payment): INT-3086 Bump checkout-sdk

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/988
Manual, unit
=> feat(payment): PAYPAL-553 bump checkout-sdk

package-lock.json, package.json
bump checkout sdk
Released https://github.com/bigcommerce/checkout-sdk-js/pull/986
Manual, unit
=> feat(payments): PAYPAL-675 bump checkout sdk

package-lock.json, package.json
bump checkout sdk
Released https://github.com/bigcommerce/checkout-sdk-js/pull/992
Manual, unit
=> feat(payment): PAYPAL-726 bump checkout sdk

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/995
Manual, unit
=> feat(payment): PAYPAL-202 bump checkout sdk

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/994
Manual, unit
=> feat(payment): PAYPAL-734 bump checkout sdk

package-lock.json, package.json, src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
Add validate before using spb
Related task: https://github.com/bigcommerce/checkout-sdk-js/pull/996
We should validate form before submit
https://www.loom.com/share/94ffcc2a7bc04fb8942ad4732746fc4a
=> feat(payment): PAYPAL-706 Add validate before using spb

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#11061-2020-10-12
ci
=> CHECKOUT-4639 Bump checkout-sdk

package-lock.json, package.json, src/app/order/OrderStatus.spec.tsx, src/app/order/OrderStatus.tsx
Renamed mandate field to mandateUrl on confrmation page
In order to match the persistence and communicate the intended usage.
[Checkout-sdk-js #1002](https://github.com/bigcommerce/checkout-sdk-js/pull/1002)
=> feat(payments): INT-3061 renamed mandate field to mandateUrl on confrmation page

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/1003
Manual, unit
=> feat(payment): PAYPAL-766 bump checkout sdk

package-lock.json, package.json
Bump checkout sdk and bigpay client
Released https://github.com/bigcommerce/checkout-sdk-js/pull/1006
Unit, manual
=> feat(payment): PAYPAL-702 Bump checkout sdk and bigpay client

src/app/customer/GuestForm.spec.tsx
Add email formatting unit tests
So we can remove them from our E2E tests
ci
=> CHECKOUT-5266 Add unit tests for Email Address validation

package-lock.json, package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/998
Circle.
=> feat(payment): INT-3174 Bump SDK.

package-lock.json, package.json
Raise the version of the SDK in use.
To benefit from https://github.com/bigcommerce/checkout-sdk-js/pull/1007.
CircleCI.
=> fix(payment): INT-3311 Bump SDK.

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/1008
Manual, unit
=> feat(payment): PAYPAL-759 bump checkout sdk

package-lock.json, package.json, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts, src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Add alternative payment methods
Related task https://github.com/bigcommerce/checkout-sdk-js/pull/1005
New implementation 
https://www.loom.com/share/f334356c99064d899bf3a7cddba999cb
https://www.loom.com/share/623788b3b9a64034a02b0f184d970e34
=> feat(payment): PAYPAL-702 Add alternative payment methods

src/app/customer/LoginForm.spec.tsx
Add negative unit tests to login form.
So we can remove them from BC App functional test suite.
unit
=> CHECKOUT-5368 Add negative unit tests to login form

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/1011
Manual, unit
=> feat(payment): PAYPAL-800 Bump checkout sdk

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/1014
Manual, unit
=> feat(payment): PAYPAL-837 Bump checkout sdk

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/commit/d1bd652f0a25340abf4c16751b9955bf993ba148
Manual, unit
=> feat(payment): PAYPAL-839 Bump checkout sdk

package-lock.json, package.json
Raise the SDK version in use.
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1019.
Circle, manual by QE team.
=> feat(payment): INT-3237 Bump SDK.

package-lock.json, package.json
Released https://github.com/bigcommerce/checkout-sdk-js/pull/1016
Manual, unit
=> feat(payment): PAYPAL-848 Bump checkout-sdk

package-lock.json, package.json
Bump checkout-sdk 1.118.1
Fixes order confirmation page
CI
=> CHECKOUT-4941 Bump checkout-sdk 1.118.1

package-lock.json, package.json
According to task PAYPAL-787
Tested on dev
@bigcommerce/checkout @davidchin @BC-ACherednichenko
=> feat(payments): PAYPAL-787 bump checkout-sdk

src/app/address/getAddressFormFieldsValidationSchema.ts, src/app/billing/Billing.tsx, src/app/billing/BillingForm.tsx, src/app/formFields/getCustomFormFieldsValidationSchema.spec.tsx, src/app/formFields/getCustomFormFieldsValidationSchema.ts, src/app/formFields/getFormFieldsValidationSchema.ts, src/app/shipping/Shipping.tsx, src/app/shipping/ShippingForm.tsx, src/app/shipping/SingleShippingForm.tsx
Remove experiment
It's been fully rolled out for 2 months
unit
=> CHECKOUT-5327 Clean up fully rolled out experiment

package-lock.json, package.json
Bump checkout SDK
See https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#11240-2021-01-28
CI
=> INT-3537 Bump checkout SDK

package-lock.json, package.json, src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
PAYPAL-876 added onError handler
According to task PAYPAL-876. Added onError handler to display error popup when polling timer expired
tested on dev
@bigcommerce/checkout @davidchin
=> feat(payment): PAYPAL-876 added onError handler

package-lock.json, package.json
Bump SDK
https://github.com/bigcommerce/checkout-sdk-js/commit/7b4b38892bfccf59fb54a7151530c1a447fa532a
CI
=> INT-3659 Bump checkout sdk

package-lock.json, package.json
See https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md
CircleCI
=> feat(payment): INT-3418 Bump checkout-sdk-js

package-lock.json, package.json
According to task PAYPAL-876
Testend on dev
@bigcommerce/checkout @davidchin
=> feat(payment): PAYPAL-876 bump checkout-sdk

package-lock.json, package.json
Bump the version of the Checkout SDK in use.
Releasing:
* https://github.com/bigcommerce/checkout-sdk-js/pull/1072
* https://github.com/bigcommerce/checkout-sdk-js/pull/1052
Circle.
=> feat(payment): INT-3610 INT-3408 Bump SDK.

src/app/payment/Payment.tsx, src/app/payment/paymentMethod/MollieCustomCardForm.tsx, src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx, src/app/payment/paymentMethod/MolliePaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts, src/app/payment/paymentMethod/PaymentMethodTitle.tsx, src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
Create Custom Card for Mollie payment method on checkout and PaymentMethod
In order to be able to purchase through Mollie
[Video](https://drive.google.com/file/d/1ZYGejKPOXk_jhI99w0pdcIA_vIFd7FwN/view?usp=sharing)
[SDK](https://github.com/bigcommerce/checkout-sdk-js/pull/1052)
=> feat(payments): INT-3610 added Mollie Checkout

src/app/locale/translations/en.json, src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Changed paypal credit to pay later logo
According to task PAYPAL-922
Tested on dev
@bigcommerce/checkout @davidchin
=> feat(payment): PAYPAL-922 changed paypal credit to pay later logo

package-lock.json, package.json
See https://github.com/bigcommerce/checkout-sdk-js/pull/1078
CircleCI + screenshots here: https://github.com/bigcommerce/checkout-js/pull/519
=> feat(payment): INT-2546 Bump checkout-sdk-js

package-lock.json, package.json
Raise the version of the SDK in use.
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1086
Circle.
=> feat(payment): INT-3947 Bump SDK.

src/app/payment/paymentMethod/MasterpassPaymentMethod.spec.tsx, src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
Added masterpass SRC experiment
Added masterpass SRC experiment
1-  [Bigcommerce #40008](https://github.com/bigcommerce/bigcommerce/pull/40008)
2- [checkout-sdk-js #1094](https://github.com/bigcommerce/checkout-sdk-js/pull/1094)
3- [Checkout-js #540](https://github.com/bigcommerce/checkout-js/pull/540)
=> fix(payment): INT-3408 added masterpass SRC experiment

package-lock.json, package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1087.
Circle, in linked PR.
=> feat(payment): INT-3905 Bump SDK.

package-lock.json, package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1089.
Circle, in linked PR.
=> fix(payment): INT-3571 Bump SDK.

package-lock.json, package.json
Fixing https://github.com/bigcommerce/checkout-sdk-js/pull/1094.
=> fix(payment): INT-3408 Bump SDK.

package-lock.json, package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1102 out
CircleCI and screenshots here: https://github.com/bigcommerce/checkout-sdk-js/pull/1102
=> feat(payment): INT-4021 Bump checkout-sdk-js

package-lock.json, package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1082 and https://github.com/bigcommerce/checkout-sdk-js/pull/1080 out
See screenshots in the above mentioned PRs
=> feat(payment): INT-2503 INT-3611 Bump checkout-sdk-js

package-lock.json, package.json, src/app/checkout/Checkout.tsx, src/app/common/error/ConsoleErrorLogger.spec.ts, src/app/common/error/ConsoleErrorLogger.ts, src/app/common/error/ErrorLogger.ts, src/app/common/error/SentryErrorLogger.ts, src/app/common/error/index.ts, src/app/common/error/isCartChangedError.ts, src/app/payment/Payment.tsx
Log extra debug data related to cart changed error
Note: depends on https://github.com/bigcommerce/checkout-sdk-js/pull/1114
So that we can have better visibility around why this error is happening
unit
=> CHECKOUT-5747 Log extra debug data related to cart changed error

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1104
https://github.com/bigcommerce/checkout-sdk-js/pull/1113
=> feat(payment): INT-3702 INT-4063 Bump checkout-sdk-js

src/app/checkout/Checkout.tsx
Clean up debugging logs
No longer in use.
CI
=> fix(common): CHECKOUT-5747 Cleanup debugging logs

package-lock.json, package.json
As per title.
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1118.
See linked PR.
=> feat(payment): INT-4150 Bump SDK.

package-lock.json, package.json
Bump checkout SDK
cshigh INT-4267
CI
=> chore(common): INT-4267 Bump checkout-sdk

package-lock.json, package.json
Raise the version of the SDK in use.
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1127
=> feat(payment): INT-4258 Bump SDK.

package-lock.json, package.json
Releasing:
* https://github.com/bigcommerce/checkout-sdk-js/pull/1126
* https://github.com/bigcommerce/checkout-sdk-js/pull/1121
Circle, linked PRs.
=> feat(payment): INT-4237 INT-4071 Bump SDK.

package-lock.json, package.json, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
Added APM fields to checkout
Due to https://jira.bigcommerce.com/browse/PAYPAL-976
=> feat(payment): PAYPAL-976 Order placement v2

package-lock.json, package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1141
=> feat(payment): INT-4197 Bump SDK.

package-lock.json, package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1129
=> feat(payment): INT-4242 Bump SDK.

src/app/payment/paymentMethod/MonerisPaymentMethod.spec.tsx, src/app/payment/paymentMethod/MonerisPaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts
Create Moneris payment method component which is a customized Hosted Widget Payment Method
The Hosted Widget Payment Method mounts a container in which Moneris iframe can be mounted for its use as suggested on [their documentation](https://developer.moneris.com/Documentation/NA/E-Commerce%20Solutions/Hosted%20Solutions/Hosted%20Tokenization)
depends on https://github.com/bigcommerce/checkout-sdk-js/pull/1119
=> feat(payment): INT-4205 Create Moneris payment Method

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1149
https://github.com/bigcommerce/checkout-sdk-js/pull/1150
See these PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1149
https://github.com/bigcommerce/checkout-sdk-js/pull/1150
@bigcommerce/checkout @bigcommerce/apex-integrations @bigcommerce/payments
=> chore(payment): PAYMENTS-6807 INT-4266 Bump checkout-sdk

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1156
https://github.com/bigcommerce/checkout-sdk-js/pull/1160
=> chore(payment): INT-4309 INT-4423 Bump checkout-sdk

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1167
https://github.com/bigcommerce/checkout-sdk-js/pull/1162
=> chore(payment): INT-4448 PAYMENTS-6805 Bump checkout-sdk

package-lock.json, package.json
What?
Why?
bigcommerce/checkout-sdk-js#1176
bigcommerce/checkout-sdk-js#1169
Testing / Proof
=> chore(payment): PAYMENTS-6812 PAYPAL-1026 Bump checkout-sdk

package-lock.json, package.json
What?
Why?
bigcommerce/checkout-sdk-js#1176
bigcommerce/checkout-sdk-js#1169
Testing / Proof
=> feat(payment): PAYMENTS-6812 PAYPAL-1026 Bump checkout-sdk

src/app/payment/paymentMethod/MonerisPaymentMethod.spec.tsx, src/app/payment/paymentMethod/MonerisPaymentMethod.tsx
Add credit card validation component to Moneris Payment Method
So the TSV validation for CVV and Card Number is displayer properly when required while using Moneris vaulted cards.
=> feat(payment): INT-4222 Vaulting for Moneris

package-lock.json, package.json
According to task https://jira.bigcommerce.com/browse/PAYPAL-1090
Testend on dev
=> feat(payment): PAYPAL-1090 bump checkout-sdk-js version

bower.json
=> chore(common): CHECKOUT-0000 Update homepage URL

package-lock.json, package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1200 out
CircleCI and see video on https://github.com/bigcommerce/checkout-sdk-js/pull/1200
@bigcommerce/checkout @bigcommerce/apex-integrations @bigcommerce/payments
=> chore(payment): INT-4685 Bump checkout-sdk

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1172
https://github.com/bigcommerce/checkout-sdk-js/pull/1174
See screenshots on above PRs
=> chore(payment): INT-4144 INT-4481 Bump checkout-sdk

package-lock.json, package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1197 out
CircleCI + see screenshot on above PR
=> chore(payment): INT-3946 Bump checkout-sdk

package-lock.json, package.json
=> chore(payment): BOLT-30 Bump checkout-sdk

package-lock.json, package.json
Bump up checkout sdk with BOLT-47
=> chore(checkout): BOLT-47 bump up checkout sdk

package-lock.json, package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1223 out
CircleCI + see the videos on above PR
=> chore(payment): INT-4798 Bump checkout-sdk

package-lock.json, package.json
=> fix(payment): INT-4900 bump version sdk

package-lock.json, package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1196 and https://github.com/bigcommerce/checkout-sdk-js/pull/1202 out
See video/screenshot on the PRs listed above
=> chore(payment): INT-4087 INT-4489 Bump checkout-sdk

src/app/payment/paymentMethod/AffirmPaymentMethod.spec.tsx
Added Affirm Payment Method Test suite 
To Increase code coverage 
@bigcommerce/checkout. @bigcommerce/apex-integrations
=> test(payment): INT-4851 Added Affirm Payment Method Test suite

src/app/payment/paymentMethod/AmazonPaymentMethod.spec.tsx
Add AmazonPaymentMethod missing code coverage
To Increase code coverage
@bigcommerce/apex-integrations
=> test(payment): INT-4852 Increase AmazonPaymentMethod code coverage

package-lock.json, package.json
Bump up checkout-sdk-js version
Due the task: https://jira.bigcommerce.com/browse/BOLT-100
Unit tests
Manual tests
=> chore(payment): BOLT-100 bump checkout-sdk-js version

package-lock.json, package.json
To release https://github.com/bigcommerce/checkout-sdk-js/pull/1302
=> chore(payment): INT-5166 Bump checkout-sdk

package-lock.json, package.json, src/app/payment/paymentMethod/AdyenV2CardValidation.spec.tsx, src/app/payment/paymentMethod/AdyenV2CardValidation.tsx, src/app/payment/paymentMethod/AdyenV2PaymentMethod.spec.tsx, src/app/payment/paymentMethod/AdyenV2PaymentMethod.tsx
Fix validation for Adyen card fields
because of task: [https://jira.bigcommerce.com/browse/ADYEN-296](https://jira.bigcommerce.com/browse/ADYEN-296)
Tests:
=> fix(payment): ADYEN-296 Card fields validation

package-lock.json, package.json
Fix bug that iDEAL button does not direct to bank login at checkout
PR in checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/1317
Because of task: [https://jira.bigcommerce.com/browse/ADYEN-373](https://jira.bigcommerce.com/browse/ADYEN-373)
=> fix(payment): ADYEN-373 fix iDEAL payment

src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx, src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Replaced paypal credit logo
According to task https://jira.bigcommerce.com/browse/PAYPAL-1257
...
=> feat(payment): PAYPAL-1257 replaced paypal credit logo

src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts, src/app/payment/paymentMethod/PaymentMethodTitle.tsx, src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx, src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
What? [INT-5031](https://jira.bigcommerce.com/browse/INT-5031)
Stripe Payment Element with credit card support
Why?
To create the payment method for stripeUPE
https://github.com/bigcommerce/checkout-sdk-js/pull/1295
=> feat(provider) INT-5031: Stripe UPE Payment Method

package-lock.json, package.json
What?
Why?
To release [bigcommerce/checkout-sdk-js#1319](https://github.com/bigcommerce/checkout-sdk-js/pull/1319)
Testing / Proof
=> chore(payment): INT-5402 Bump checkout-sdk

package-lock.json, package.json
Bump checkout-sdk.
Many `"dev": true` were added to the `package-lock.json`. Tried to get them off, but not working.
Get recent updates out.
CircleCI
=> chore(checkout): checkout-6071 Bump checkout-sdk v1.215.1

src/app/payment/paymentMethod/SquarePaymentMethod.spec.tsx, src/app/payment/paymentMethod/SquarePaymentMethod.tsx
Remove Masterpass for SquareV2
The project has been canceled and will not be developed or launched.
https://github.com/bigcommerce/bigpay/pull/4470
https://github.com/bigcommerce/ng-payments/pull/1437
https://github.com/bigcommerce/bigcommerce/pull/43061
https://github.com/bigcommerce/checkout-sdk-js/pull/1263
Based on tests, the order to merge the PR’s avoiding problems should be the following:
1.- Ng-payments https://github.com/bigcommerce/ng-payments/pull/1437 and bump
2.- Bcapp: https://github.com/bigcommerce/bigcommerce/pull/43061
3.- SDK and bump  
4.- JS using SDK bump
5.- bump JS into BCAPP
6.- Bigpay https://github.com/bigcommerce/bigpay/pull/4470
=> feat(payment): INT-4282 remove masterpass for Square

src/app/customer/CheckoutButtonList.tsx, src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx, src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts
Add GooglePay for Stripe UPE to the list of payment methods
To be able to pay using GooglePay via Stripe UPE
=> feat(payment): INT-5467 Stripe UPE GooglePay

package-lock.json, package.json, src/app/locale/translations/en.json, src/app/payment/PaymentSubmitButton.spec.tsx, src/app/payment/PaymentSubmitButton.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts, src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx, src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Braintree venmo spb integration
According to task https://jira.bigcommerce.com/browse/PAYPAL-1151
=> feat(payment): PAYPAL-1151 venmo spb integration

src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
Quick Fix
According to task https://jira.bigcommerce.com/browse/PAYPAL-1282
=> fix(payment): PAYPAL-1282 quick fix

package-lock.json, package.json, src/app/payment/Payment.tsx, src/app/payment/paymentMethod/AdyenV3CardValidation.spec.tsx, src/app/payment/paymentMethod/AdyenV3CardValidation.tsx, src/app/payment/paymentMethod/AdyenV3PaymentMethod.spec.tsx, src/app/payment/paymentMethod/AdyenV3PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts, src/app/payment/paymentMethod/PaymentMethodTitle.tsx, src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
AdyenV3 module creation. This module mostly duplicates Adyen V2 integration, but has some improvements.
In future PRs we could possibly rewrite APMs integrations and make types cleaner.
It's better to review this PR comparing AdyenV3 strategy files to  AdyenV2. There are fewer changes.
[SDK PR](https://github.com/bigcommerce/checkout-sdk-js/pull/1343)
Due to the Adyen new integration.
Units/tested manually
=> feat(checkout): ADYEN-378 AdyenV3 module creation

package-lock.json, package.json, src/app/customer/CheckoutButtonList.tsx, src/app/payment/Payment.tsx, src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx, src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodId.ts
AdyenV3 googlepay integration
sdk pr: https://github.com/bigcommerce/checkout-sdk-js/pull/1380
Due to the https://jira.bigcommerce.com/browse/ADYEN-399
https://user-images.githubusercontent.com/79574476/158869219-46034ccb-9f97-4b79-b017-ace23d1fac1a.mov
=> feat(payment): ADYEN-399 adyenv3 googlepay

src/app/locale/translations/en.json, src/app/payment/PaymentForm.tsx, src/app/payment/PaymentSubmitButton.tsx, src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
Correct checkout branding (PPC & BT)
According to task https://jira.bigcommerce.com/browse/PAYPAL-1327
=> feat(payment): PAYPAL-1327 added branding name to Submit button

package-lock.json, package.json, src/app/payment/paymentMethod/AdyenV2PaymentMethod.spec.tsx, src/app/payment/paymentMethod/AdyenV2PaymentMethod.tsx
AdyenV2 initialize interface fix
SDK PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1394
Due to the https://jira.bigcommerce.com/browse/ADYEN-454
Units
=> fix(checkout): ADYEN-454 AdyenV2 initialize interface fix

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/commit/658d28af3ab42c451b19fa62a369f26d9a4af32c
=> chore(common): CHECKOUT-6071 Bump checkout-sdk

package-lock.json, package.json, src/app/payment/paymentMethod/AdyenV3CardValidation.tsx
In this PR was implemented AdyenV3 component state fix.
Previously data was received directly from the adyen sdk componentState object but it was a mistake because Adyen SDK modifies this data before submitting. ComponentState data gets on onChange event via Adyen SDK API.
[SDK PR](https://github.com/bigcommerce/checkout-sdk-js/pull/1409)
Due to the fix of https://jira.bigcommerce.com/browse/ADYEN-431
Manually/Units
=> fix(checkout): ADYEN-431 AdyenV3 component state fix

package-lock.json, package.json
To release some changes with Braintree 3DS verification
Unit tests
Manual tests
=> feat(payment): PAYPAL-1177 bump checkout sdk version

package-lock.json, package.json
Bump Checkout SDK v1.244.0
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1435 out.
CI and above PR
=> chore(checkout): INT-5963 Bump Checkout SDK v1.244.0

package-lock.json, package.json, src/app/locale/translations/en.json
Add OXXO barcode url to the order confirmation page
We need to add OXXO barcode url to the order confirmation email. As a possible example, and for the consistency reasons we might want to use the code that was implemented by the INT team in Stripe -> OXXO method 
https://github.com/bigcommerce/bigcommerce/pull/46274
https://github.com/bigcommerce/bigpay/pull/5358
=> feat(payment): PAYPAL-1416 Add oxxo ticket for PPCP

package-lock.json, package.json
=> chore(payment): PAYPAL-1463 Bump checkout-sdk

package-lock.json, package.json
Bump for add delay between calls for 3ds
Is necessary to add some functionality for MPGS 
https://github.com/bigcommerce/checkout-sdk-js/pull/1428
=> fix(checkout): INT-5126 [MPGS] Bump for add delay between calls for 3d

src/app/payment/PaymentSubmitButton.tsx, src/app/payment/paymentMethod/PaymentMethod.tsx, src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Updated BraintreeVenmo to show it correctly in payment section
We have some updates on backend side, that can brake prev UX. This pr should fix this issue.
Unit tests
Manual tests
=> feat(payment): PAYPAL-1380 updated BraintreeVenmo to show it correctly in payment section

src/app/ui/form/DynamicFormField.tsx, src/app/ui/form/FormField.tsx, src/app/ui/form/FormFieldError.tsx
Reverts bigcommerce/checkout-js#876
=> Revert "feat(checkout): CHECKOUT-6655 Make screen reader say each shipping fo…"

package-lock.json, package.json
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1549
Unit tests
Manual tests
=> chore(payment): PAYPAL-1549 bump up checkout sdk version

package-lock.json, package.json
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1560
Unit tests 
Manual tests
=> chore(payment): PAYPAL-1560 bump checkout sdk version

packages/apple-pay-integration/src/ApplePayPaymentMethod.spec.tsx
Fix `ApplePay` package unit tests.
Payment Integration JS API changes have just borken `ApplePay` unit tests.
CI
=> fix(checkout): CHECKOUT-0000 fix ApplePay unit tests

package-lock.json, package.json
Update checkout sdk
Update to latest version of checkout sdk
- circle
=> chore(common): CHECKOUT-0000 update checkout sdk

.github/CODEOWNERS
Update codeowner file
So each package can be owned by different teams
N/A
=> CHECKOUT-0000: Update codeowner file

package-lock.json, package.json
Update Checkout SDK to 1.279.2
Update to latest version of checkout sdk
- Circle CI
=> chore(common): INT-0000 Update Checkout SDK

.github/CODEOWNERS
As above
Update codeowners file in order to sentry to pick up and assign issues to relevant teams
- Circle
=> chore(common): CHECKOUT-6273 Update codeowners file

packages/core/src/app/checkout/CheckoutStepHeader.spec.tsx, packages/core/src/app/checkout/CheckoutStepHeader.tsx, packages/core/src/app/order/OrderConfirmation.spec.tsx, packages/core/src/app/order/OrderConfirmation.tsx, packages/core/src/app/order/OrderSummaryItem.tsx, packages/core/src/app/order/__snapshots__/OrderSummaryItem.spec.tsx.snap, packages/core/src/app/shipping/ItemAddressSelect.tsx, packages/core/src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss, packages/core/src/scss/components/foundation/type/_type.scss
Orignial requirements doc ([link](https://docs.google.com/spreadsheets/d/19NjngW7dapPcaqFcgBXF0q2ofjqVESdX/edit?usp=sharing&ouid=105120289126066958944&rtpof=true&sd=true)).
This PR contains 4 out of 9 sub tasks that will break `BCapp` UI tests.
Will update `BCapp` UI tests and bump `checkout-js` in this PR.
https://github.com/bigcommerce/bigcommerce/pull/48253
BC merchants can benefit from the ADA-compliant native checkout and order confirmation pages.
- BCapp UI tests after update:
- [integration_bcapp_release_blocking_UI_test](https://app.circleci.com/pipelines/github/bigcommerce/bigcommerce/229818/workflows/e8a5401f-5a33-447a-af36-8ee488adcb7f): success
- [integration_bcapp_checkout_test](https://app.circleci.com/pipelines/github/bigcommerce/bigcommerce/229820/workflows/3abfe03b-ed06-47 …
=> feat(checkout): CHECKOUT-6875 Improve accessibility part I

packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx, packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Test cases added to improve code coverage
Code coverage was fulfilling expectations for the strategy.
[Coverage](https://drive.google.com/file/d/1oDyqc9gqL91HP2iRKlA1N8_8-czS9VY0/view?usp=sharing)
=> feat(payment): INT-6482 | Worldpay - Increase coverage in WorldpayCreditCardPaymentMethod

package-lock.json, package.json, packages/core/src/scss/components/foundation/modal/_modal.scss
Fixed adyen 3ds2 challenge window size
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-545
Before: 
After:
=> fix(payment): ADYEN-545 fixed adyen 3ds2 challenge window size

packages/core/src/app/customer/LoginForm.tsx, packages/core/src/app/customer/__snapshots__/Customer.spec.tsx.snap, packages/core/src/app/customer/__snapshots__/LoginForm.spec.tsx.snap, packages/core/src/app/locale/translations/da.json, packages/core/src/app/locale/translations/de.json, packages/core/src/app/locale/translations/en.json, packages/core/src/app/locale/translations/es-419.json, packages/core/src/app/locale/translations/es-AR.json, packages/core/src/app/locale/translations/es-CL.json, packages/core/src/app/locale/translations/es-CO.json, packages/core/src/app/locale/translations/es-MX.json, packages/core/src/app/locale/translations/es-PE.json, packages/core/src/app/locale/translations/es.json, packages/core/src/app/locale/translations/fr.json, packages/core/src/app/locale/translations/it.json, packages/core/src/app/locale/translations/nl.json, packages/core/src/app/locale/translations/no.json, packages/core/src/app/locale/translations/pt-BR.json, packages/core/src/app/locale/translations/pt.json, packages/core/src/app/locale/translations/sv.json
Remove floating period.
The period is unnecessary and is causing a minor visual issue.
CI.
=> fix(checkout): CHECKOUT-0000 Remove floating period

package-lock.json, package.json
Update sdk 
Releasing following commits
- https://github.com/bigcommerce/checkout-sdk-js/commit/93bfa5c411bd20b014559fe6d1014c029f738048
- https://github.com/bigcommerce/checkout-sdk-js/commit/066e9da58531be9ae65d07ce53b39a07ec28a051
- https://github.com/bigcommerce/checkout-sdk-js/commit/1b523f429e589f5de49126053d24e3bc351cf2c3
- Circle
=> chore(common): CHECKOUT-000 update sdk version

package.json, packages/core/src/app/customer/Customer.spec.tsx, packages/core/src/app/customer/Customer.tsx, packages/core/src/app/customer/StripeGuestForm.spec.tsx, packages/core/src/app/customer/StripeGuestForm.tsx, packages/core/src/app/payment/Payment.tsx, packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.tsx, packages/core/src/app/shipping/Shipping.tsx, packages/core/src/app/shipping/stripeUPE/StripeShipping.spec.tsx, packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx, packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx, packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx, packages/core/src/app/shipping/stripeUPE/StripeShippingForm.spec.tsx, packages/core/src/app/shipping/stripeUPE/StripeShippingForm.tsx, packages/core/src/app/shipping/stripeUPE/StripeStateMapper.spec.ts, packages/core/src/app/shipping/stripeUPE/StripeupeShippingAddress.spec.tsx, packages/ui/src/index.ts
Automatic code formatting improvement by `prettier`.
These auto fixes constantly show up when we run `npm run lint` because we never commit them into the repo.
CI.
=> feat(checkout): CHECKOUT-0000 Merge prettier auto fixes

package-lock.json, package.json
Bump checkout SDK
To release https://github.com/bigcommerce/checkout-sdk-js/commit/5ff448dbdbbade2c3e088762bdbb3b5c3c94e220
- cirlce
=> chore(common): CHECKOUT-000 Bump checkout sdk

package-lock.json, package.json
Bump @bigcommerce/checkout-sdk to 1.317.1
Staying up to date
CI
=> chore(common): BIG-0 Bump @bigcommerce/checkout-sdk to 1.317.1

packages/offline-payment-integration/e2e/OfflinePaymentMethod.spec.ts, packages/offline-payment-integration/e2e/__har__/Cash-on-Delivery_227544541/recording.har, packages/offline-payment-integration/e2e/__har__/Pay-in-Store_2088335945/recording.har, packages/payment-integration-test-framework/src/fixture/pageObject/playwright/senstiveDataConfig.ts
Added two e2e tests to ensure all `offline` components of Checkout SDK/JS are working together.
Two tested payment methods are:
- Cash on delivery.
- Pay in store.
Reduce the chance of introducing a regression.
CI checks.
=> feat(checkout): CHECKOUT-6480 Offline payment method e2e tests

package-lock.json, package.json, packages/core/src/app/customer/CheckoutButtonList.tsx
Create Braintree PayPal Credit customer button strategy
Related PRs:
checkout-sdk-js: [https://github.com/bigcommerce/checkout-sdk-js/pull/1787](https://github.com/bigcommerce/checkout-sdk-js/pull/1787)
BCapp: [https://github.com/bigcommerce/bigcommerce/pull/50845](https://github.com/bigcommerce/bigcommerce/pull/50845)
Because of task: [https://bigcommercecloud.atlassian.net/browse/PAYPAL-1840](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1840)
Checkout-sdk-js unit test:
BCapp unit tests:
=> feat(payment): PAYPAL-1840 Create braintreepaypalcredit customer button strategy

packages/hosted-dropin-integration/.eslintrc.json, packages/hosted-dropin-integration/README.md, packages/hosted-dropin-integration/jest.config.js, packages/hosted-dropin-integration/project.json, packages/hosted-dropin-integration/src/HostedDropInPaymentMethodComponent.spec.tsx, packages/hosted-dropin-integration/src/HostedDropInPaymentMethodComponent.tsx, packages/hosted-dropin-integration/src/index.ts, packages/hosted-dropin-integration/tsconfig.json, packages/hosted-dropin-integration/tsconfig.spec.json, packages/test-utils/src/index.ts, tsconfig.base.json, workspace.json
Refactor the existing `HostedDropIn` component into a shared monorepo package.
Lay the foundation work for restructuring `checkout-js` into a monorepo.
- CI checks.
=> refactor(checkout): CHECKOUT-6437 Build HostedDropIn component package

packages/hosted-credit-card-integration/.eslintrc.json, packages/hosted-credit-card-integration/src/components/HostedCreditCardCodeField/HostedCreditCardCodeField.tsx, packages/hosted-credit-card-integration/src/components/HostedCreditCardFieldset/HostedCreditCardFieldset.spec.tsx
Fix lint isses in master
There are lint issues in master branch that need to be fixed correctly.
- Circle
=> fix(common): CHECKOUT-000 Fix lint issues

.circleci/config.yml, packages/core/src/app/customer/Customer.spec.tsx
- Fix failing test
- Fix file glob to run tsx tests
We have a failing unit test in master branch and was reported in [issue](https://github.com/bigcommerce/checkout-js/issues/1219) that our glob doesn't pick up files with tsx. 
- Circle
=> chore(other): CHECKOUT-000 Fix customer failing test

packages/core/src/app/customer/CheckoutButtonContainer.spec.tsx, packages/core/src/app/customer/CheckoutButtonContainer.tsx, packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
Place other Paypal wallet buttons at the beginning.
Ensure the PayPal checkout experience is consistent across the platform.
- Modified a unit test.
- CI.
=> feat(checkout): CHECKOUT-0000 Update wallet buttons order

package-lock.json, package.json
As above
Update sdk to latest version
- CI
=> chore(other): CHECKOUT-000 Update checkout sdk

package-lock.json, package.json
To keep checkout js project dependencies up to date
CI tests
=> chore(payment): PAYPAL-000 bump up checkout sdk version

package-lock.json, package.json
As above
Release https://github.com/bigcommerce/checkout-sdk-js/pull/1946
- CI
=> chore(other): CHECKOUT-000 Update sdk

package-lock.json, package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1963
https://github.com/bigcommerce/checkout-sdk-js/pull/1891
...
=> feat(payment): PAYPAL-1713 bump checkout-sdk-js version

packages/core/src/app/order/OrderModalSummarySubheader.tsx, packages/core/src/app/payment/Payment.tsx, packages/core/src/app/shipping/mapToShippingProps.spec.ts, packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.tsx, packages/instrument-utils/src/creditCard/getCreditCardValidationSchema/getCreditCardValidationSchema.ts, packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.tsx, packages/instrument-utils/src/storedInstrument/InstrumentSelect/InstrumentSelect.tsx, packages/instrument-utils/src/storedInstrument/ManageCardInstrumentsTable/ManageCardInstrumentsTable.tsx, packages/instrument-utils/src/storedInstrument/ManageInstrumentsAlert/ManageInstrumentsAlert.tsx, packages/instrument-utils/src/storedInstrument/ManageInstrumentsModal/ManageInstrumentsModal.tsx, packages/instrument-utils/src/storedInstrument/SignOutLink/SignOutLink.tsx, packages/instrument-utils/src/storedInstrument/getInstrumentValidationSchema/getInstrumentValidationSchema.ts, packages/test-framework/src/fixture/pagePreset/ApiRequestsSender.ts, packages/ui/src/form/BasicFormField/BasicFormField.tsx, packages/ui/src/form/DynamicFormField/DynamicFormField.spec.tsx, packages/ui/src/utils/dom/getAppliedStyles.spec.ts
Use `npx nx run-many --target=lint --all --fix` to auto fix some code style issues.
Maintain code cleanliness.
CI.
=> refactor(checkout): CHECKOUT-0000 lint auto fix

package-lock.json, package.json
Bump Braintree sdk version.
All tests have been passed.
=> feat(payment): PAYPAL-2502 bump checkout-sdk-js version

.github/CODEOWNERS, package-lock.json, package.json, packages/bluesnap-direct-integration/src/BlueSnapDirectAlternativePaymentMethod.tsx, packages/bluesnap-direct-integration/src/index.ts, packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.tsx, packages/core/src/scss/components/foundation/modal/_modal.scss
Bluesnapdirect APMs implementation
Due to the feature request
Units/manual
SDK PR https://github.com/bigcommerce/checkout-sdk-js/pull/2021
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/caf99ea3-12e7-45c1-a304-806ae43d279c
=> feat(checkout): PI-168 bluesnapdirect APMs

packages/test-utils/src/payment-methods.mock.ts
Updated getBraintreeAchPaymentMethod method in test-utils package
There was a mistake in data shape
Unit tests
=> refactor(payment): PAYPAL-000 updated getBraintreeAchPaymentMethod method in test-utils package

packages/locale/src/translations/en.json
Added braintree ach vaulting instrument confirmation description text translation
To use translation in braintree ach component in future pr
CI
=> feat(payment): PAYPAL-000 added braintree ach vaulting instrument confirmation description text translation

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2045
Due to the release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2045
manually/units
=> fix(checkout): PI-00 fix pending promise for bluesnapdirect APMs iframe

packages/test-utils/src/index.ts
Updated test-utils index file with imports of mock methods
To have an ability to use those methods while writing tests in different packages
CI tests
=> test(other): PAYPAL-000 updated test-utils index file with imports of mock methods

.github/CODEOWNERS, package-lock.json, package.json, packages/fortis-integration/.eslintrc.json, packages/fortis-integration/README.md, packages/fortis-integration/jest.config.js, packages/fortis-integration/project.json, packages/fortis-integration/tsconfig.json, packages/fortis-integration/tsconfig.spec.json, tsconfig.base.json, workspace.json
New Fortis package
Create new package for future Fortis integration
unit tests
=> feat(payment): PI-502 Fortis package

packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.test.tsx, packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.tsx, packages/braintree-integration/src/index.ts
Added BraintreeAcceleratedCheckout payment method
To render Braintree PayPal Connect component in paywall
Unit tests
Manual tests
=> feat(payment): PAYPAL-2726 added BraintreeAcceleratedCheckout payment method

packages/locale/src/translations/en.json
Added translation for PaypalCommerce RatePay payment component
To translate RatePay component form fields strings
=> feat(payment): PAYPAL-1545 added translation for PaypalCommerce RatePay payment component

packages/core/src/app/address/PayPalAxo/PoweredByPaypalConnectLabel.scss, packages/core/src/app/address/PayPalAxo/PoweredByPaypalConnectLabel.test.tsx, packages/core/src/app/address/PayPalAxo/PoweredByPaypalConnectLabel.tsx, packages/locale/src/translations/en.json
Creation of one "Powered by PP connect" label
To mark addresses which provided by PayPal Connect
Unit test and manually testing
=> feat(payment): PAYPAL-2732 PayPalAxo Powered By component

packages/core/src/app/address/AddressSelect.tsx, packages/core/src/app/billing/BillingForm.spec.tsx, packages/core/src/app/shipping/MultiShippingForm.spec.tsx, packages/core/src/app/shipping/ShippingAddress.spec.tsx, packages/core/src/app/shipping/ShippingAddressForm.spec.tsx, packages/core/src/app/shipping/ShippingForm.spec.tsx, packages/core/src/app/shipping/ShippingForm.tsx
Migrate some class components to functional components
To get ability using hooks inside
=> feat(payment): PAYPAL-2732 migrate some components to functional

packages/core/src/app/billing/BillingForm.tsx
Transform BillingForm to functional component
To get ability to use hooks inside it
https://github.com/bigcommerce/checkout-js/assets/9430298/456e9e25-7876-4806-9093-c9678e2f284e
=> feat(payment): PAYPAL-2733 Transform BillingForm to functional component

packages/locale/src/getDefaultTranslations.spec.ts, packages/locale/src/getDefaultTranslations.ts
Add polish language support
As we add Polish language support to platform add tranlations file to map json file to locale
- Tests
=> feat(other): CHECKOUT-7677 Add polish language translation support

.circleci/config.yml, scripts/sdk-live-checker.sh
Add check to ensure SDK version is on CDN
Automation
CI on this PR
=> chore(other): CHECKOUT-0 Add check to ensure SDK version is on CDN

packages/core/src/app/checkout/Checkout.spec.tsx, packages/core/src/app/checkout/Checkout.test.tsx, packages/core/src/app/checkout/Checkout.tsx, packages/core/src/app/checkout/CheckoutApp.tsx, packages/core/src/app/checkout/mapToCheckoutProps.ts, packages/core/src/app/common/error/SentryErrorLogger.ts, packages/core/src/app/order/OrderConfirmation.spec.tsx, packages/core/src/app/order/OrderConfirmation.tsx, packages/core/src/app/order/OrderConfirmationApp.tsx, packages/error-handling-utils/src/ErrorLogger.ts
Update the sentry config so that we can turn on 100% Sentry logging for certain brands.
To track all issues for certain stores, so we can get better visibility on issues.
- https://github.com/bigcommerce/bigcommerce/pull/54892
- CI checks.
=> feat(checkout): CHECKOUT-7763 Update Sentry config

package-lock.json, package.json
Bump checkout-sdk version.
Related PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/2210
=> feat(payment): PAYPAL-2507 bump checkout-sdk version

package-lock.json, package.json, packages/core/src/app/customer/CheckoutButtonList.tsx, packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx, packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx, packages/google-pay-integration/src/GooglePayButton.tsx, packages/payment-integration-api/src/PaymentMethodId.ts
PPCP GooglePay payment strategy 
related PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/2198
=> feat(payment): PAYPAL-2930 PPCP GooglePay payment strategy

package-lock.json, package.json
Bumped checkout-sdk-js
To update code
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2235
=> feat(payment): PAYPAL-0 bump checkout-sdk-js

.github/CODEOWNERS, package-lock.json, package.json, packages/td-bank-integration/.eslintrc.json, packages/td-bank-integration/README.md, packages/td-bank-integration/jest.config.js, packages/td-bank-integration/project.json, packages/td-bank-integration/tsconfig.json, packages/td-bank-integration/tsconfig.spec.json, tsconfig.base.json, workspace.json
New TD Bank package for future integration
For adding strategies for new TD Bank integration
Manually tested
=> feat(payment): PI-1004 Create a new package for TD Bank integration

packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.test.tsx, packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx, packages/locale/src/translations/de.json, packages/locale/src/translations/en.json, packages/payment-integration-api/src/PaymentMethodId.ts
Added text label for ratepay
To show text label next to logo
=> feat(payment): PAYPAL-3279 added text label for ratepay

package-lock.json, package.json, packages/core/src/app/customer/getSupportedMethods.ts
PPCP Google Pay top of checkout support
=> feat(payment): PAYPAL-2954 PPCP Google Pay top of checkout support

package-lock.json, package.json, packages/bluesnap-direct-integration/e2e/__har__/External-APM-with-BlueSnap-in-Payment-Step_1599217875/recording.har, packages/bluesnap-direct-integration/e2e/__har__/SEPA-with-BlueSnap-in-Payment-Step_2879624599/recording.har, packages/bluesnap-direct-integration/e2e/bluesnapdirect.spec.ts, packages/bluesnap-direct-integration/e2e/support/bluesnap.ejs, packages/bluesnap-direct-integration/src/BlueSnapDirectSepaPaymentMethod.test.tsx, packages/bluesnap-direct-integration/src/BlueSnapDirectSepaPaymentMethod.tsx, packages/bluesnap-direct-integration/src/BlueSnapDirectTextField.tsx, packages/bluesnap-direct-integration/src/index.ts, packages/bluesnap-direct-integration/src/mocks/bluesnapdirect-method.mock.ts, packages/bluesnap-direct-integration/src/validation-schemas/getSepaValidationSchema.ts, packages/locale/src/translations/en.json, packages/test-framework/src/fixture/pagePreset/ApiRequestsSender.ts, packages/test-framework/src/fixture/pagePreset/PaymentStepAsGuestEU.ts, packages/test-framework/src/fixture/pagePreset/index.ts
BluesnapDirect SEPA implemantation
https://github.com/bigcommerce/checkout-sdk-js/pull/2256
Due the Bluesnap requirement
=> feat(payment): PI-853 BluesnapDirect added Sepa fieldset

packages/locale/src/translations/en.json
Added 'Change' translation
This translation will be used in one of future PRs related to PPCP AXO feature
=> feat(payment): PAYPAL-3403 added 'Change' translation

packages/core/src/app/payment/Payment.spec.tsx, packages/core/src/app/payment/Payment.tsx
Refetch available payment methods list after total amount change
Some providers have available payment methods based on total amount of the cart
For example:
For Mollie we get list of available payment methods from Mollie API (on BigPay side)
and for different amount we can get different payment methods list
• amount [0.01...10000] we will receive [card, APM1, APM2, ...]
• amount 0 -> [card]
• amount more then 10000$ will return [APM1, APM2 ...]
thats why we need to refresh available payment providers  list each time when total amount changes
https://github.com/bigcommerce/checkout-js/assets/9430298/78097dff-b3b8-4ad1-8c10-734f331b298c
=> fix(payment): PI-1329 update payment methods after total amount change

packages/core/src/app/payment/Payment.spec.tsx, packages/core/src/app/payment/Payment.tsx
Reverts bigcommerce/checkout-js#1651
Because of failing BCapp release test
=> Revert "fix(payment): PI-1329 update payment methods after total amount change"

package-lock.json, package.json
Bump checkout-sdk-js 
To deploy PRs:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2340](https://github.com/bigcommerce/checkout-sdk-js/pull/2340)
[https://github.com/bigcommerce/checkout-sdk-js/pull/2343](https://github.com/bigcommerce/checkout-sdk-js/pull/2343)
=> chore(payment): PI-1368 bump checkout-sdk-js version

package-lock.json, package.json, packages/locale/src/translations/en.json, packages/paypal-commerce-integration/src/components/PayPalCommercePaymentMethodComponent.test.tsx, packages/paypal-commerce-integration/src/components/PayPalCommercePaymentMethodComponent.tsx
Added translation for paypal INSTRUMENT_DECLINED error
To show corresponding text
=> feat(payment): PAYPAL-3439 added error translation

package-lock.json, package.json, packages/bluesnap-direct-integration/e2e/__har__/Credit-Card-with-BlueSnap-in-Payment-Step_2136680895/recording.har, packages/bluesnap-direct-integration/e2e/bluesnapdirect.spec.ts, packages/bluesnap-direct-integration/src/BlueSnapDirectEcpPaymentMethod.test.tsx, packages/bluesnap-direct-integration/src/BlueSnapDirectEcpPaymentMethod.tsx, packages/bluesnap-direct-integration/src/fields/BlueSnapDirectEcpFieldset.test.tsx, packages/bluesnap-direct-integration/src/fields/BlueSnapDirectEcpFieldset.tsx, packages/bluesnap-direct-integration/src/fields/__snapshots__/BlueSnapDirectEcpFieldset.test.tsx.snap, packages/bluesnap-direct-integration/src/hooks/useEcpInstruments.ts, packages/bluesnap-direct-integration/src/validation-schemas/getEcpValidationSchema.ts, packages/instrument-utils/src/guards/isAchInstrument/isAchInstrument.test.ts, packages/instrument-utils/src/guards/isAchInstrument/isAchInstrument.ts, packages/instrument-utils/src/guards/isBankInstrument/isBankInstrument.ts, packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.test.tsx, packages/instrument-utils/src/storedInstrument/ManageAchInstrumentsTable/ManageAchInstrumentsTable.test.tsx, packages/instrument-utils/src/storedInstrument/ManageAchInstrumentsTable/__snapshots__/ManageAchInstrumentsTable.test.tsx.snap, packages/test-mocks/src/instruments.mock.ts
[Linked SDK PR](https://github.com/bigcommerce/checkout-sdk-js/pull/2345)
Implementation of the stored ACH/ECP for Bluesnap Direct
Due to the product requirements
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/957f4cbf-67a2-4a06-8f52-d1738457cd8e
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/6f7fe20d-27df-4577-90e7-51c9eaa04494
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/b57589ea-701f-42e5-8691-22bd8ed5e3a7
=> feat(payment): PI-1313 stored ecp for bluesnap

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2358
=> chore(payment): PI-1604 bump checkout-sdk

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2348
=> chore(payment): PI-1369 bump checkout-sdk

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2365
Manually tested
=> chore(payment): PI-1648 bump checkout-sdk

packages/adyen-integration/e2e/__har__/ACH-in-Payment-Step_2952102266/recording.har, packages/adyen-integration/e2e/__har__/Adyenv3-ACH-in-Payment-Step_873791026/recording.har, packages/adyen-integration/e2e/__har__/Adyenv3-Credit-Card-in-Payment-Step_3229115791/recording.har, packages/adyen-integration/e2e/__har__/Credit-Card-in-Payment-Step_894189239/recording.har, packages/adyen-integration/e2e/adyenv2.spec.ts, packages/adyen-integration/e2e/adyenv3.spec.ts, packages/adyen-integration/e2e/support/adyen.ejs, packages/adyen-integration/e2e/support/hostedField.ejs, packages/adyen-integration/src/index.ts
Added E2E tests for Adyen integration on Checkout JS
https://bigcommercecloud.atlassian.net/browse/PI-1366
All tests have passed 
=> feat(payment): PI-1366 e2e tests for Adyen integration on Checkout JS

package-lock.json, package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2373
Manually tested
=> chore(payment): PI-1502 bump checkout-sdk

package-lock.json, package.json
Bumped checkout-sdk-js version 
To update code
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2407
=> fix(payment): PAYPAL-0000 bumped checkout-sdk-js version

package-lock.json, package.json, packages/analytics/src/AnalyticsProvider.spec.tsx, packages/analytics/src/AnalyticsProvider.tsx
Updated `braintreeConnectTracker` with `braintreeAnalyticTracker`
As part of Braintree Analytic refactoring (Connect -> Fastlane rebranding)
Unit tests
CI
=> refactor(Payment): PAYPAL-3603 updated braintreeConnectTracker with braintreeAnalyticTracker

package-lock.json, package.json
To deploy PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2424](https://github.com/bigcommerce/checkout-sdk-js/pull/2424)
Unit and manual tests
=> chore(payment): PI-1835 bump checkout-sdk-js

.github/CODEOWNERS, packages/bluesnap-direct-integration/.eslintrc.json, packages/bluesnap-direct-integration/src/BlueSnapV2PaymentMethod.test.tsx, packages/bluesnap-direct-integration/src/BlueSnapV2PaymentMethod.tsx, packages/bluesnap-direct-integration/src/index.ts, packages/core/src/app/payment/Payment.tsx, packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
Refactor the existing bluesnapv2 payment strategy in Checkout-js
=> feat(payment): PI-1537 Refactor the existing bluesnapv2 payment strategy in Checkout-js

packages/bluesnap-direct-integration/e2e/__har__/ACH-with-BlueSnapv2-in-Payment-Step_1030426958/recording.har, packages/bluesnap-direct-integration/e2e/__har__/Bank-Transfer-with-BlueSnapv2-in-Payment-Step_3241051483/recording.har, packages/bluesnap-direct-integration/e2e/__har__/Credit-Card-with-BlueSnapv2-in-Payment-Step_2247692055/recording.har, packages/bluesnap-direct-integration/e2e/__har__/Moneybookers-with-BlueSnapv2-in-Payment-Step_558909199/recording.har, packages/bluesnap-direct-integration/e2e/__har__/Paysafecard-with-BlueSnapv2-in-Payment-Step_448808695/recording.har, packages/bluesnap-direct-integration/e2e/__har__/Wire-with-BlueSnapv2-in-Payment-Step_3120654321/recording.har, packages/bluesnap-direct-integration/e2e/bluesnapv2.spec.ts, packages/bluesnap-direct-integration/e2e/support/bluesnapv2.ejs
Add E2E tests for `bluesnapv2` components
=> feat(payment): PI-1550 integration tests for bluesnapv2

packages/core/src/app/address/mapAddressToFormValues.ts
Set default values obtained from API for system/builtin address from fields
Fix: Default values of Form Fields are being applied incorrectly #1743 
- CI checks
**BEFORE:**
https://github.com/bigcommerce/checkout-js/assets/141614330/eb5b96b8-9eaa-44a9-a2f9-7a470d88eb44
**AFTER:**
https://github.com/bigcommerce/checkout-js/assets/141614330/d8c5402b-8c26-4013-a1c6-ac7a09fd0047
=> fix(checkout): ISSUE-1743 fix system address field default value issue

package-lock.json, package.json, packages/core/e2e/__har__/Multi-Shipping-with-Customer-checkout_2370051488/recording.har, packages/core/src/app/shipping/shipping-addresses.mock.ts
bump checkout sdk to include
https://github.com/bigcommerce/checkout-sdk-js/pull/2462
include the changes of sdk to set shouldSaveAddress flag to false if it's from selected address
=> fix(checkout): CHECKOUT-8183 set shouldSaveAddress flag to false if it's from selected address

package-lock.json, package.json
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2464
Unit tests
=> feat(payment): PAYPAL-4048 bumped checkout-sdk-js version

package-lock.json, package.json
Reverts bigcommerce/checkout-js#1813
=> Revert "chore(payment): PI-650 bump checkout-sdk version"

packages/bluesnap-direct-integration/src/BlueSnapV2PaymentMethod.test.tsx
remove spaces
To check unit test on git
unit test
=> chore(payment): PI-0000 remove spaces

packages/core/src/app/shipping/shipping-addresses.mock.ts
fix the mock of getShippingAddress
fix test
...
=> fix(checkout): CHECKOUT-0000 fix a mock of getShippingAddress

package-lock.json, package.json
Reverts bigcommerce/checkout-js#1829
=> Revert "fix(checkout): CHECKOUT-0000 Revert SDK to 1.582.2"

packages/core/src/app/shipping/SingleShippingForm.spec.tsx
Increase timeout from 1870ms to 18700ms.
Test CI on the main branch.
CI checks.
=> fix(checkout): CHECKOUT-0000 Increase timeout

packages/core/src/app/shipping/SingleShippingForm.spec.tsx
Reverts bigcommerce/checkout-js#1831
=> Revert "fix(checkout): CHECKOUT-0000 Increase timeout"

packages/checkoutcom-integration/e2e/__har__/Credit-Card-with-Checkoutcom-in-Payment-Step_3718073430/recording.har, packages/checkoutcom-integration/e2e/__har__/Fawry-with-Checkoutcom-in-Payment-Step_4061538748/recording.har, packages/checkoutcom-integration/e2e/checkoutcom.spec.ts, packages/checkoutcom-integration/e2e/support/checkoutcom.ejs, packages/checkoutcom-integration/e2e/support/hostedField.ejs, packages/test-framework/src/fixture/pagePreset/PaymentStepAsGuest.ts
E2E tests for `checkoutcom` integration
tests
=> feat(payment): PI-1961 E2E tests for `checkoutcom` integration

package-lock.json, package.json
=> feat(payment): PI-1581 bump checkout-sdk version

package-lock.json, package.json
To update code
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2498
Unit tests
=> feat(payment): PAYPAL-4108 bumped checkout-sdk-js version

package-lock.json, package.json
Release https://github.com/bigcommerce/checkout-sdk-js/pull/2495
Unit + manual testing
=> chore(payment): PI-1584 bump checkout sdk

packages/core/src/app/payment/getProviderWithCustomCheckout.ts, packages/core/src/app/shipping/ShippingAddress.spec.tsx, packages/core/src/app/shipping/ShippingAddress.tsx, packages/core/src/app/shipping/ShippingForm.spec.tsx, packages/core/src/app/shipping/ShippingForm.tsx, packages/core/src/app/shipping/stripeUPE/StripeShippingForm.spec.tsx, packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.test.tsx, packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.tsx, packages/paypal-fastlane-integration/src/index.ts, packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.ts
Created a PayPal Fastlane shipping component. The main goal of this PR is to render a separate shipping component if Fastlane is enabled. 
Please note that `feat(payment): PAYPAL-4066 localizeAddress moved to shared package` commit will be merged as a separate PR here: https://github.com/bigcommerce/checkout-js/pull/1841
https://github.com/bigcommerce/checkout-js/assets/130665807/bd6a1453-9401-4463-838f-98318f98fb66
Manual tests
=> feat(payment): PAYPAL-4066 PayPal Fastlane shipping component

package-lock.json, package.json, packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.tsx
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2493
Unit tests
=> feat(payment): PAYPAL-4068 bumped checkout-sdk-js version

package-lock.json, package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2509
Testing section [here](https://github.com/bigcommerce/checkout-sdk-js/pull/2509)
=> feat(payment): PI-2061 Added Amazon Pay button hidden microtext feature flag

packages/core/src/app/shipping/AmazonPayShippingAddress.tsx, packages/core/src/app/shipping/PayPalFastlaneShippingAddress.tsx, packages/core/src/app/shipping/ShippingAddress.tsx
Created a shipping address mapper.
=> feat(payment): PAYPAL-4066 shippingAddress moved to shared package

.github/CODEOWNERS
CODEOWNERS file update
Setting affirm package as team-integrations responsibility
...
=> chore(payment): codeowners file update

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2523
=> chore(payment): PI-2132 bump checkout-sdk

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2511
=> chore(payment): PI-1578 bump checkout-sdk

package-lock.json, package.json
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2530
Unit tests
=> feat(payment): PAYPAL-4138 bumped checkout-sdk-js version

package-lock.json, package.json, packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.scss, packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.tsx, packages/paypal-commerce-integration/src/PayPalCommerceFastlane/PayPalCommerceFastlanePaymentMethod.scss, packages/paypal-commerce-integration/src/PayPalCommerceFastlane/PayPalCommerceFastlanePaymentMethod.tsx
Updated PayPal Fastlane form styling for guest credit card form
To make PayPal Fastlane experience better for our customers
Unit tests
Manual tests
CI
Before:
After:
=> fix(payment): PAYPAL-4307 updated PayPal Fastlane form styling for guest credit card form

packages/core/src/app/billing/BillingForm.spec.tsx, packages/core/src/app/billing/BillingForm.tsx, packages/core/src/app/shipping/ShippingForm.spec.tsx, packages/core/src/app/shipping/ShippingForm.tsx, packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.test.tsx, packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.ts
Removed unnecessary code related to Fastlane store member flow (which is deprecated)
To keep checkout project as clean as possible
Manual tests
Unit tests
https://github.com/bigcommerce/checkout-js/assets/25133454/949c372a-1e79-4a86-b0b8-1bc207bbf3b8
=> refactor(payment): PAYPAL-4382 removed unnecessary code related to Fastlane store member flow (which is deprecated)

packages/mollie-integration/e2e/__har__/Bancontact-with-Mollie-in-Payment-Step_2670522601/recording.har, packages/mollie-integration/e2e/__har__/CC-with-Mollie-in-Payment-Step_668330648/recording.har, packages/mollie-integration/e2e/__har__/Klarnapaylater-with-Mollie-in-Payment-Step_2902091219/recording.har, packages/mollie-integration/e2e/__har__/Klarnapaynow-with-Mollie-in-Payment-Step_802259869/recording.har, packages/mollie-integration/e2e/__har__/Klarnasliceit-with-Mollie-in-Payment-Step_2481485656/recording.har, packages/mollie-integration/e2e/__har__/Sofort-with-Mollie-in-Payment-Step_2796910677/recording.har, packages/mollie-integration/e2e/mollie.spec.ts, packages/mollie-integration/e2e/support/hostedField.ejs, packages/mollie-integration/e2e/support/mollie.mock.js
Write integration tests for `Mollie`
To verify all `Mollie` components of Checkout SDK/JS are working together
All tests have passed
=> feat(payment): PI-1540 Mollie integration tests

packages/core/src/app/checkout/Checkout.tsx
Remove stepnumbers experiment code.
This experiment has been rolled out for more than 1 year.
- CI
- Screenshot
=> chore(other): CHECKOUT-7255 Remove stepnumbers experiment

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2570
=> chore(payment): PI-2285 bump checkout-sdk

packages/core/src/app/customer/getSupportedMethods.ts
Fixed problem with rendering of GooglePay button in Customer Checkout step for TD Online Mart.
Tested Manually
=>  feat(payment): PI-2428 Google Pay on TD Online Mart - check if FE is working correctly, adjust communication FE -> BE

package-lock.json, package.json
To release:
https://github.com/bigcommerce/checkout-sdk-js/pull/2581
https://github.com/bigcommerce/checkout-sdk-js/pull/2581
=> feat(payment): PAYPAL-4519 bump checkout-sdk

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2594
=> chore(payment): PI-2428 bump checkout-sdk

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2596
=> chore(payment): PI-2493 bump checkout-sdk-js

packages/digitalriver-integration/e2e/__har__/Digital-River-Credit-Card-in-Payment-Step_3405653337/recording.har, packages/digitalriver-integration/e2e/__har__/Digital-River-wire-transfer-in-Payment-Step_3932186716/recording.har, packages/digitalriver-integration/e2e/digitalriver.spec.ts, packages/digitalriver-integration/e2e/support/hostedField.ejs
Integration tests for Digital River strategy
To make sure the integration in checkout-sdk and checkout-js work well together
=> feat(checkout): PI-1555 Integration tests for Digital River

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2598
=> chore(payment): PI-2467 bump checkout-sdk-js

packages/bluesnap-direct-integration/e2e/__har__/Pay-by-Bank-with-BlueSnap-in-Payment-Step_241965973/recording.har, packages/bluesnap-direct-integration/e2e/bluesnapdirect.spec.ts, packages/bluesnap-direct-integration/src/BlueSnapDirectPayByBankPaymentMethod.test.tsx, packages/bluesnap-direct-integration/src/BlueSnapDirectPayByBankPaymentMethod.tsx, packages/bluesnap-direct-integration/src/index.ts, packages/bluesnap-direct-integration/src/mocks/bluesnapdirect-method.mock.ts, packages/bluesnap-direct-integration/src/validation-schemas/getPayByBankValidationSchema.ts, packages/locale/src/translations/en.json
Pay By Bank is a supported payment method - [Pay by Bank (Open Banking)](https://developers.bluesnap.com/reference/pay-by-bank) 
Allow shoppers to input IBAN in the Pay By Bank payment step
To implement Pay by Bank method
...
=> feat(payment): PI-2403 Pay by Bank integration

package-lock.json, package.json, packages/hosted-credit-card-integration/src/hooks/index.ts, packages/hosted-credit-card-integration/src/hooks/useHostedCreditCard.spec.tsx, packages/hosted-credit-card-integration/src/hooks/useHostedCreditCard.tsx, packages/hosted-credit-card-integration/src/index.ts
Created useHostedCreditCard hook.
Because we have duplicated code in some payment providers, so it could be useful to avoid code duplication
Manual tests
Example of usage is here: https://github.com/bigcommerce/checkout-js/pull/1964
=> refactor(payment): STRIPE-423 created useHostedCreditCard hook

packages/stripe-integration/src/stripev3/StripePaymentMethod.test.tsx, packages/stripe-integration/src/stripev3/StripeV3CustomCardForm.test.tsx
StripeV3 unit testing changed from Enzyme to react testing-library
=> refactor(payment): STRIPE-434 StripeV3 unit testing update

packages/stripe-integration/src/stripe-upe/StripeUPEPaymentMethod.test.tsx
Stripe UPE unit testing changed from Enzyme to react testing-library
=> refactor(payment): STRIPE-439 StripeUPE unit testing update

package-lock.json, package.json
To deploy PRs:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2637](https://github.com/bigcommerce/checkout-sdk-js/pull/2637)
[https://github.com/bigcommerce/checkout-sdk-js/pull/2639](https://github.com/bigcommerce/checkout-sdk-js/pull/2639)
=> chore(payment): PI-1617 bump checkout-sdk-js

package-lock.json, package.json
Update typescript from 4.7.4 to 4.9.5
Update to newer typescript version.
- CI checks
https://github.com/user-attachments/assets/1fc83bb2-34c8-40e5-9d8a-c2bbf4b60e7d
=> chore(checkout): CHECKOUT-8562 Update typescript from 4.7.4 to 4.9.5

package-lock.json, package.json
To release: https://github.com/bigcommerce/checkout-sdk-js/pull/2673
=> chore(payment): PAYPAL-4744 bump checkout-sdk

packages/core/src/app/shipping/Shipping.tsx, packages/core/src/app/shipping/ShippingForm.tsx, packages/core/src/app/shipping/SingleShippingForm.test.tsx, packages/core/src/app/shipping/SingleShippingForm.tsx
Revert the change as this approach is causing issues with some merchants' customisations.
Revert
---
=> Revert "fix(checkout): CHECKOUT-8006 Optimise Shipping Option Updates"

package-lock.json, package.json, packages/apple-pay-integration/e2e/__har__/ApplePay-in-Payment-Step_2100856370/recording.har
Bump SDK.
- https://github.com/bigcommerce/checkout-sdk-js/pull/2705
- https://github.com/bigcommerce/checkout-sdk-js/pull/2699
- https://github.com/bigcommerce/checkout-sdk-js/pull/2708
- https://github.com/bigcommerce/checkout-sdk-js/pull/2688
- https://github.com/bigcommerce/checkout-sdk-js/pull/2700
- https://github.com/bigcommerce/checkout-sdk-js/pull/2696
- https://github.com/bigcommerce/checkout-sdk-js/pull/2706
- https://github.com/bigcommerce/checkout-sdk-js/pull/2704
Relese recent changes.
- CI.
=> chore(shipping): SHIPPING-3311 Bump SDK

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2709
=> chore(payment): PI-1647 bump checkout-sdk

packages/core/src/app/shipping/AllocateItemsModal.tsx, packages/core/src/app/shipping/MultiShippingFormV2.scss, packages/core/src/app/shipping/MultiShippingFormV2.test.tsx, packages/core/src/app/shipping/MultiShippingFormV2.tsx, packages/locale/src/translations/en.json
Display Items Allocated Banner
To show information about the item allocation status
=> feat(checkout): CHECKOUT-8598 Display Items Allocated Banner

webpack.config.js
Disable integrity check for local development environment.
Improve developer experience.
Manually tested: The integrity check is disabled in the local environment
=> feat(checkout): CHECKOUT-8786 Disable Integrity for Local Dev

SECURITY.md
Add SECURITY.md.
Helps researchers/Github users report security bugs to us.
NA
=> chore(checkout): APPSEC-705 Add SECURITY.md

packages/core/src/app/shipping/MultiShippingV2.test.tsx, packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
Improve the test `Multi-shipping V2 renders multi-shipping v2 component and finishes the shipping step` so that it is not flaky.
Improve CI workflow.
CI.
=> feat(checkout): CHECKOUT-8597 Improve tests

packages/core/src/app/checkout/Checkout.tsx, packages/core/src/app/checkout/mapToCheckoutProps.ts, packages/core/src/app/shipping/AllocateItemsModal.tsx, packages/core/src/app/shipping/ConsignmentLineItemDetail.tsx, packages/core/src/app/shipping/ConsignmentListItem.tsx, packages/core/src/app/shipping/MultiShippingFormV2.test.tsx, packages/core/src/app/shipping/NewConsignment.tsx, packages/core/src/app/shipping/ShippingSummary.tsx, packages/core/src/app/shipping/StaticMultiConsignment.scss, packages/core/src/app/shipping/StaticMultiConsignment.tsx, packages/core/src/app/shipping/index.ts, packages/locale/src/translations/en.json
Introduce a new Multi-address Shipping summary view.
Improve shopper experience.
=> feat(checkout): CHECKOUT-8601 Enhanced Multi-Address Shipping Summary View

packages/core/src/app/shipping/MultiShippingV2.test.tsx
Fix test.
To reflect the recent name change and restore CI.
CI.
=> test(checkout): CHECKOUT-8872 Fix test

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2716
=> chore(payment): PI-1546 bump checkout sdk version

packages/core/src/app/shipping/MultiShippingFormV2.test.tsx, packages/core/src/app/shipping/MultiShippingFormV2.tsx
Fix the issue that when the first multi-shipping consignment is not done, the error message is missing.
Improve UX.
https://github.com/user-attachments/assets/1b734d38-86cb-49cf-b37a-f07424bcc647
=> fix(checkout): CHECKOUT-8824 Fix Error Message for First Consignment

packages/core/src/app/checkout/Checkout.test.tsx, packages/core/src/app/shipping/ConsignmentAddressSelector.tsx, packages/core/src/app/shipping/MultiShippingFormV2.test.tsx, packages/core/src/app/shipping/MultiShippingFormV2.tsx, packages/core/src/app/shipping/MultiShippingV2.test.tsx, packages/test-framework/src/index.ts, packages/test-framework/src/react-testing-library-support/API.mock.ts
- Fix reordering of consignments in new multi-shipping UI.
- Fix issue with `Add new destination` button
For better user experience.
- CI checks
**BEFORE**
https://github.com/user-attachments/assets/a0e7b191-b5df-43f8-b414-93382619d4e9
**AFTER**
https://github.com/user-attachments/assets/8bd8b7f5-f17f-4f39-8359-43f0223f76ca
=> fix(checkout): CHECKOUT-8803 fix reordering of consignments in multishipping

package-lock.json, package.json
=> chore(payment): PAYPAL-5047 bumped checkout-sdk-js version

package-lock.json, package.json, packages/core/src/app/checkout/Checkout.test.tsx, packages/core/src/app/checkout/Checkout.tsx, packages/core/src/app/common/utility/index.ts, packages/core/src/app/common/utility/should-filter-apple-pay.ts, packages/core/src/app/customer/CheckoutButtonContainer.tsx, packages/core/src/app/customer/CheckoutButtonList.spec.tsx, packages/core/src/app/customer/CheckoutButtonList.tsx, packages/core/src/app/customer/Customer.tsx, packages/core/src/app/customer/canSignOut.ts, packages/core/src/app/customer/getSupportedMethods.spec.ts, packages/core/src/app/customer/getSupportedMethods.ts, packages/core/src/app/customer/index.ts
Added experiment for switching Apple Pay implementation
Fixed test related to apple pay on Customer Step
Updated checkout-sdk-js
For supporting third party browsers
Local testing, take a look here https://github.com/bigcommerce/checkout-js/pull/2154
=> feat(payment): PAYPAL-4324 Added experiment for Apple Pay

package-lock.json, package.json
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2785
=> chore(payment): PAYPAL-5067 bump checkout-sdk

packages/core/src/app/customer/RegisteredCustomer.test.tsx
Add test for customer sign in link for customer section.
As part of moving tests for RTL add tests for sign in link
- CI
=> chore(customer): CHECKOUT-8995 Add test for customer sign in link

package-lock.json, package.json
Release https://github.com/bigcommerce/checkout-sdk-js/pull/2794
- CI
=> feat(shipping): CHECKOUT-8999 Bump checkout sdk

packages/core/src/app/shipping/Shipping.test.tsx
Add a second test for the happy path of the Guest Checkout Shipping step.
Test path:
- Enter the shipping step as a guest.
- Fill in essential address details.
- Uncheck the option `billing address is the same as shipping`.
- Click “Continue” to proceed to the billing step.
Enable us to upgrade to react 18.
CI.
=> test(checkout): CHECKOUT-9006 Guest Checkout Shipping Step Happy Path 2

packages/core/src/app/shipping/Shipping.test.tsx
Add tests for shipping options:
- After filling the shipping form, shopper should be able to select a different option.
- If no options are available, show a warning message.
Enable us to remove enzyme tests.
CI.
=> test(checkout): CHECKOUT-9008 Add Tests for Shipping Options

package-lock.json, package.json
To update code 
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2796
Unit tests
=> chore(payment): PAYPAL-5187 bumped checkout-sdk-js

package-lock.json, package.json, packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.test.tsx, packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx, packages/core/src/app/shipping/stripeUPE/StripeStateMapper.ts
Disable state code mapping for Spain in Stripe Link Address component
Checkout-sdk-js: [https://github.com/bigcommerce/checkout-sdk-js/pull/2797](https://github.com/bigcommerce/checkout-sdk-js/pull/2797)
To fix issue with unavailable state specific shipping options for Spain shoppers
Unit tests results:
Available shipping options:
https://github.com/user-attachments/assets/6f83cc5a-ad22-4a2c-8960-216065d6fe37
Stripe dashboard:
BC control panel:
https://github.com/user-attachments/assets/01f265ac-697d-470b-b43d-eb1d259a78c3
Stripe dashboard:
BC control panel:
https://github.com/user-attachments/assets/eeac716f-5965-4ab0-ab62-ec45f8adec7a
Stripe dashboard:
BC control panel:
https://github.com/user-attachments/assets/b512d8b6-04a8-4f4c-a5cd-371e1000d355
Stripe dashboard:
BC control panel: …
=> fix(payment): STRIPE-660 Disable state code mapping for Spain in Stripe Link Address component

packages/core/src/app/billing/Billing.test.tsx, packages/core/src/app/shipping/Shipping.test.tsx, packages/test-framework/src/react-testing-library-support/CheckoutPageNodeObject.ts
Create Tests for Guest Customer's Billing step use cases.
In order to be able to move all the enzyme tests to RTL which enables us to move to React 18.
- CI checks
=> test(checkout): CHECKOUT-8929 add tests for billing step for guest customer

.github/dependabot.yml
Add dependabot config
Add dependabot config for security scanning
- CI
=> chore(others): CHECKOUT-000 Add dependabot config

packages/core/src/app/customer/Customer.spec.tsx
Migrate `packages/core/src/app/customer/Customer.spec.tsx` enzyme tests to RTL.
=> feat(payment): STRIPE-761 migrate StripeGuestForm enzyme tests to RTL

packages/ui/src/form/Form/Form.test.tsx, packages/ui/src/form/FormField/FormField.test.tsx, packages/ui/src/form/FormFieldContainer/FormFieldContainer.test.tsx, packages/ui/src/form/FormFieldError/FormFieldError.test.tsx, packages/ui/src/form/LoadingSkeleton/AddressFormSkeleton.test.tsx, packages/ui/src/form/LoadingSkeleton/CheckListSkeleton.test.tsx, packages/ui/src/form/LoadingSkeleton/CustomerSkeleton.test.tsx, packages/ui/src/form/LoadingSkeleton/WalletButtonContainerSkeleton.test.tsx
Add tests in form folder
- Form
- FormField
- FormFieldContainer
- FormFieldError
- LoadingSkeleton
As part of migrating to react 18, increase code coverage and update tests.
- CI
=> chore(checkout): CHECKOUT-9144 Add tests in form folder

.circleci/config.yml, package-lock.json, package.json
- update node to 22
- remove commit validation CI step
N/A
- CI
=> chore(other): update node to 22

README.md
Update readme file with node version
N/A
- CI
=> chore(other): Update README.md

package-lock.json, package.json, packages/google-pay-integration/src/GooglePayPaymentMethod.test.tsx, packages/google-pay-integration/src/GooglePayPaymentMethod.tsx
As part of the functionality:
https://github.com/bigcommerce/checkout-sdk-js/pull/2841
Manual tests
=> feat(payment): PI-3225 pass loadingContainerId to the GooglePay payment step

package-lock.json, package.json
=> chore(payment): bump checkout-sdk version

package-lock.json, package.json
To update code with new changes
Unit tests
=> chore(payment): Bumped checkout-sdk-js version

packages/core/src/app/shipping/isSelectedShippingOptionValid.test.ts, packages/core/src/app/shipping/isSelectedShippingOptionValid.ts
Update valid option check for custom method.
Update valid option check for custom method in order for continue button to be active and user can proceed to next checkout step.
- CI
- Screenshot
=> fix(shipping): Update valid option check for custom method

.github/CODEOWNERS
Added codeowners for bigcommerce-payments-utils package
To set codeowners
Not needed
=> feat(payment): Added codeowners for bigcommerce-payments-utils package

.github/CODEOWNERS, packages/clearpay-integration/.eslintrc.json, packages/clearpay-integration/README.md, packages/clearpay-integration/jest.config.js, packages/clearpay-integration/project.json, packages/clearpay-integration/src/ClearpayPaymentMethod.test.tsx, packages/clearpay-integration/src/ClearpayPaymentMethod.tsx, packages/clearpay-integration/src/index.ts, packages/clearpay-integration/tsconfig.json, packages/clearpay-integration/tsconfig.lib.json, packages/clearpay-integration/tsconfig.spec.json, packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx, tsconfig.base.json, workspace.json
Move Clearpay to a separate package
For clear structure of checkout-js repo
https://github.com/user-attachments/assets/5540a8bc-8a0c-4505-882b-5fc03eafb736
=> feat(payment): move Clearpay to a separate package

packages/core/src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss, packages/core/src/scss/components/foundation/forms/_forms.scss
Update padding in shipping step and billing
Update padding in shipping step as per updated designs.
- CI
- screenshot 
https://github.com/user-attachments/assets/94651388-0c73-4dbd-a6d1-a45915012e9e
https://github.com/user-attachments/assets/5d869c97-5447-431a-b2d5-c0ca63e7e1f7
=> chore(shipping): update padding in shipping step

packages/core/src/app/customer/CustomerInfo.test.tsx, packages/core/src/app/customer/CustomerInfo.tsx
Fix redirect to logout link from catalyst
Fix redirect to checkout from catalyst storefronts on logout
- CI
=> chore(fix): fix redirect to logout link

packages/core/src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
Update the style of the step's Edit button to match the link style of the Edit cart.
Improve checkout UX.
https://github.com/user-attachments/assets/27e30860-c46c-4a2a-b3c0-cb198f043163
=> feat(checkout): CHECKOUT-7960 Update step button style

package-lock.json, package.json, packages/bigcommerce-payments-integration/src/BigCommercePayments/BigCommercePaymentsButton.test.tsx, packages/bigcommerce-payments-integration/src/BigCommercePayments/BigCommercePaymentsButton.tsx, packages/bigcommerce-payments-integration/src/BigCommercePayments/BigCommercePaymentsPaymentMethod.test.tsx, packages/bigcommerce-payments-integration/src/BigCommercePayments/BigCommercePaymentsPaymentMethod.tsx, packages/bigcommerce-payments-integration/src/components/BigCommercePaymentsPaymentMethodComponent.test.tsx, packages/bigcommerce-payments-integration/src/components/BigCommercePaymentsPaymentMethodComponent.tsx, packages/bigcommerce-payments-integration/src/index.ts, packages/bigcommerce-payments-integration/src/mocks/paymentMethods.mock.ts
Updated BigCommercePaymentsPayPal naming with BigCommercePayments
To have the same naming as in checkout sdk
Unit tests
CI
=> refactor(payment): updated BigCommercePaymentsPayPal naming with BigCommercePayments

packages/core/src/app/address/AddressSelectButton.tsx
Fix billing address's aria label.
Improve checkout page's accessiblity.
CI.
=> fix(checkout): CHECKOUT-9311 Fix Billing Address Aria Label

packages/hosted-credit-card-integration/src/components/HostedCreditCardValidation/HostedCreditCardValidation.test.tsx, packages/hosted-credit-card-integration/src/components/HostedCreditCardValidation/HostedCreditCardValidation.tsx, packages/hosted-credit-card-integration/src/components/getHostedInstrumentValidationSchema/getHostedInstrumentValidationSchema.test.ts, packages/hosted-credit-card-integration/src/components/getHostedInstrumentValidationSchema/getHostedInstrumentValidationSchema.ts, packages/hosted-credit-card-integration/src/types/HostedCreditCardFiledsetValues.ts
INFO: This logic presents in hosted credit card components in core package.
Updated hosted credit card integration with card expiry field logic. 
So components from hosted credit card integration package can be used in migration of paypal commerce credit card component from core package to paypal-commerce-integration package.
Unit tests
Manual tests
Automation tests run
CI
=> feat(payment): updated hosted credit card integration with card expiry field logic

packages/paypal-fastlane-integration/.eslintrc.json, packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.test.tsx, packages/paypal-fastlane-integration/src/PayPalFastlaneShippingAddressForm.tsx, packages/paypal-fastlane-integration/src/PayPalFastlaneWatermark.test.tsx, packages/paypal-fastlane-integration/src/PayPalFastlaneWatermark.tsx, packages/paypal-fastlane-integration/src/is-fastlane-window.test.ts, packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.test.tsx, packages/paypal-fastlane-integration/src/usePayPalFastlaneAddress.ts
fixed eslint errors and warnings in paypal-fastlane-integration package
As part of tech dept removal
Unit tests
Manual tests
CI
=> fix(payment): fixed eslint errors and warnings in paypal-fastlane-integration package

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2939
CI
=> feat(payment): Address is not populated to Klarna modal

packages/core/src/app/checkout/hooks/useLoadCheckout.test.ts, packages/core/src/app/checkout/hooks/useLoadCheckout.ts, packages/core/src/scss/themeV2/font/_font.scss
Implemented a retry mechanism for loading checkout, with a maximum of 3 attempts before failing.
Improve shopper experience.
=> feat(checkout): CHECKOUT-9395 Add Retry to LoadCheckout

packages/core/src/app/common/error/ErrorModal.tsx
Convert class component `ErrorModal` into function component.
CI.
=> refactor(checkout): CHECKOUT-9375 Convert ErrorModal

package-lock.json, package.json
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2957
=> feat(payment): PAYPAL-5690 bump checkout-sdk

packages/core/src/app/checkout/CheckoutStep.tsx
Convert class component `CheckoutStep` into function component.
CI.
=> refactor(checkout): CHECKOUT-9375 Convert CheckoutStep

package-lock.json, package.json
Checkout-sdk bump
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2975
Revert
=> chore(payment): PAYPAL-5712 checkout-sdk bump

packages/core/src/app/shipping/StaticAddressEditable.tsx
Convert class component `StaticAddressEditable` into function component.
Revert.
CI.
=> refactor(checkout): CHECKOUT-9384 Convert StaticAddressEditable

packages/locale/src/LocaleProvider.tsx
Convert class component `LocaleProvider` into function component.
- CI checks
=> feat(checkout): CHECKOUT-9385 Convert LocaleProvider

packages/core/src/app/order/OrderSummaryItems.tsx
Convert class component `OrderSummaryItems` into function component.
Revert.
CI.
=> refactor(checkout): CHECKOUT-9384 Convert OrderSummaryItems

packages/hosted-payment-integration/src/components/HostedPaymentComponent.tsx
Convert class component `HostedPaymentMethodComponent` into function component.
- CI checks
=> feat(checkout): CHECKOUT-9385 Convert HostedPaymentMethodComponent

package-lock.json, package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2982
Revert this PR
Tests passed
=> chore(payment): PI-4266 bump checkout-sdk

packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx, packages/hosted-payment-integration/src/HostedPaymentMethod.tsx
Switch Sezzle to generic component
Revert this PR
https://github.com/user-attachments/assets/42a62fbc-6772-48a5-b903-ace8fa644c21
=> feat(checkout): Switch Sezzle to generic component

package-lock.json, package.json
Checkout-sdk bump
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2988
=> chore(payment): PAYPAL-5740 checkout-sdk bump

package-lock.json, package.json
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/2990
Revert
All test passed
=> chore(payment): PAYPAL-5741 checkout-sdk bump

packages/core/src/app/shipping/Shipping.tsx, packages/core/src/app/shipping/stripeUPE/StripeShipping.test.tsx, packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
`packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx` migrated to functional component
Revert this PR
Manual testing
https://github.com/user-attachments/assets/b0cfb355-232f-41ac-8565-ac62f377640f
=> feat(payment): StripeShipping migrated to functional component

packages/core/src/app/order/OrderConfirmation.test.tsx, packages/core/src/app/order/OrderConfirmationApp.tsx
Convert class component `OrderConfirmationApp` into function component.
- CI checks
=> feat(checkout): CHECKOUT-9467 Convert OrderConfirmationApp component

packages/core/src/app/order/OrderConfirmation/OrderConfirmation.tsx
Missed two lint issues while working on https://github.com/bigcommerce/checkout-js/pull/2577. 
This PR fixes those and restores the CI pipeline.
CI.
CI.
=> refactor(checkout): CHECKOUT-9475 Fix lint issues

package-lock.json, package.json
=> chore(payment): PAYPAL-5809 bumped checkout-sdk-js version

package-lock.json, package.json
To deliver: https://github.com/bigcommerce/checkout-sdk-js/pull/3006
Revert
=> feat(payment): PAYPAL-5730 bump checkout-sdk

packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
Reverts bigcommerce/checkout-js#2593
=> Revert "refactor(payment): PAYPAL-1322 remove BT CC from core"

packages/core/src/app/shipping/ShippingForm.tsx, packages/core/src/app/shipping/SingleShippingForm.tsx
Revert the SingleShippingForm class component due to unwanted side effects that lead to incident 
https://bigcommercecloud.atlassian.net/browse/CHECKOUT-9548
Revert this PR
- CI checks
**BEFORE**
https://github.com/user-attachments/assets/87d4ba6a-eadf-4166-99c5-e10bb7a4559e
**AFTER**
https://github.com/user-attachments/assets/3a24b668-29d2-4b96-8315-ff603b07337e
=> Revert single shipping form conversion

packages/core/src/app/customer/Customer.tsx, packages/core/src/app/customer/GuestFormContainer.tsx
Refactor and create a `GuestFormContainer` to replace the render method.
- CI
=> chore(customer): CHECKOUT-9474 Move guest customer form out of customer component

packages/core/src/app/customer/Customer.tsx, packages/core/src/app/customer/CustomerGuest.test.tsx, packages/core/src/app/customer/LoginForm.tsx
Refactor LoginForm to reduce prop drilling.
- CI
=> chore(customer): CHECKOUT-9474 Refactor loginform to reduce prop drilling

packages/core/src/app/customer/Customer.test.tsx, packages/core/src/app/customer/Customer.tsx, packages/core/src/app/customer/CustomerGuest.test.tsx, packages/core/src/app/customer/RegisteredCustomer.test.tsx, packages/core/src/app/customer/useCustomer.ts
Convert customer component to functional component
- CI
=> chore(customer): CHECKOUT-9474 Convert customer component to functional component

package-lock.json, package.json, packages/test-mocks/src/config.mock.ts
Bump checkout-sdk + fix TS errors that lead to failed tests
Revert
=> chore(payment): PAYPAL-2615 bump checkout-sdk

packages/core/src/app/customer/Customer.tsx
Refactor and use jsx directly in customer component.
- CI
=> chore(customer): CHECKOUT-9474 Refactor and use jsx directly in customer component
