- README.md
Update the README to include a link to a DevDoc article on how to install a Custom Checkout.
I forgot to replace the old/temporary instruction with the new one.
None
> CHECKOUT-5143: Update README to include instructions on custom checkout installation

- src/app/locale/translations/en.json
- src/app/payment/PaymentSubmitButton.spec.tsx
- Update the '_Continue with Amazon_' text to '_Continue with Amazon Pay_'
- Fixed the related test
It's a 'nice to have' change requested by the Amazon Pay team.
> refactor(payment): INT-3105 Update submit button text for AmazonPayV2

- src/app/payment/Payment.spec.tsx
- src/app/payment/Payment.tsx
Remove Bolt form payment methods if showInChekout is false , to prevent it from being rendered as payment method.
To prevent Bolt's payment method from being rendered, but still usable from the Bolt app and manual orders.
https://github.com/bigcommerce/bigcommerce/pull/36855
Demo video recorded using this Draft PR as base https://github.com/bigcommerce/bigcommerce/pull/36925, actual behavior depends on the sibling PR
[Demo Video](https://drive.google.com/file/d/1u5Y3AxqKN32uYfx-cflInQjLgd23iCAB/view?usp=sharing)
> fix(checkout): INT-3116 Hide Bolt on checkout

- src/app/locale/translations/en.json
- src/app/order/OrderStatus.spec.tsx
- src/app/order/OrderStatus.tsx
Added mandate link on confirmation page.
In order to show sepa mandate link to the customer.
[Bigpay #2906](https://github.com/bigcommerce/bigpay/pull/2906)
[BigCommerce #36755](https://github.com/bigcommerce/bigcommerce/pull/36755)
[Checkout-sdk-js #966](https://github.com/bigcommerce/checkout-sdk-js/pull/966)
> feat(payments): INT-3061 added mandate link on confirmation page

- package-lock.json
- package.json
- src/app/payment/Payment.spec.tsx
- src/app/payment/Payment.tsx
- src/app/payment/hostedCreditCard/withHostedCreditCardFieldset.spec.tsx
- src/app/payment/hostedCreditCard/withHostedCreditCardFieldset.tsx
Fix the error handler form Braintree hosted payment form.
Related PR: https://github.com/bigcommerce/checkout-sdk-js/pull/981
Otherwise the inline error message doesn't show up.
> CHECKOUT-5135: Fix error handler for Braintree hosted form

- src/app/payment/paymentMethod/CreditCardPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/CreditCardPaymentMethod.tsx
- src/app/payment/storedInstrument/CardInstrumentFieldset.tsx
- src/app/payment/storedInstrument/ManageInstrumentsModal.tsx
Re-initialise the credit card form after deleting the last stored card.
Otherwise, you can be in a situation where you can't enter a new card because there's no form for you to enter your details.
CircleCI + Manual
> CHECKOUT-5161: Re-initialise credit card form after deleting last stored card

- README.md
- package.json
Fix server commands
`npm run dev` creates `build` folder,  so `npm run dev:server` should serve `build` folder.
Also provides server command for `npm run build:server`
manual
> CHECKOUT-5173 Fix server commands

- package-lock.json
- package.json
Bump `checkout-sdk` version
https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md
CircleCI
> CHECKOUT-5135: Bump `checkout-sdk` version

- package-lock.json
- package.json
- src/app/payment/Payment.tsx
- src/app/payment/PaymentContext.tsx
- src/app/payment/PaymentForm.spec.tsx
- src/app/payment/PaymentForm.tsx
- src/app/payment/PaymentSubmitButton.tsx
- src/app/payment/hostedCreditCard/withHostedCreditCardFieldset.spec.tsx
- src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.spec.tsx
- src/app/payment/paymentMethod/BoltPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/BraintreeCreditCardPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/CreditCardPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethod.spec.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodList.tsx
- src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
- src/app/payment/paymentMethod/WalletButtonPaymentMethod.spec.tsx
- src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Smart payment buttons were added to checkout page. 
Adding an embedded button instead of the submit button
Relevant [PR](https://github.com/bigcommerce/checkout-sdk-js/pull/980)  on the checkout-sdk 
PPCP pop up is blocked on the BC hosted checkout page and Embedded checkout. Pop ups work for SPB at the shopping cart page.
> [WIP] feat(payments): PAYPAL-654 Embedded Submit button

- src/app/payment/paymentMethod/WalletButtonPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx
[INT-3140](https://jira.bigcommerce.com/browse/INT-3140)
- Validate if shopper use store credit to enable the checkout button whit wallet
- Shopper can place a order when use store credit and googlepay is enabled.
Unit test
> fix(payments): INT-3140 Enable checkout button with googlepay when use store credit - StripeV3

- src/app/locale/translations/en.json
[INT-3198](https://jira.bigcommerce.com/browse/INT-3198)
Update the Affirm verbiage
Affirm has updated their solution to support a biweekly payment so it's necessary to change it to avoid any confusion.
[Video](https://drive.google.com/file/d/1nFrECpm020zbkZfITPVY54GQ2uL_wSgL/view?usp=sharing)
> fix(checkout): INT-3198 Update Affirm verbiage

- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- src/app/payment/paymentMethod/StripePaymentMethod.spec.tsx
- src/app/payment/paymentMethod/StripePaymentMethod.tsx
- src/app/payment/paymentMethod/StripeV3CustomCardForm.spec.tsx
- src/app/payment/paymentMethod/StripeV3CustomCardForm.tsx
- src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
- src/scss/components/checkout/widget/_widget.scss
Added optional render individual credit card fields on StripeV3
So that merchants have the ability to display single card component or independent for each field.
[Checkout-sdk #985](https://github.com/bigcommerce/checkout-sdk-js/pull/985)
> feat(payments): INT-3086 added optional custom render fields on StripeV3

- src/scss/components/checkout/widget/_widget.scss
- src/scss/settings/global/screensizes/_screensizes.scss
Added style to avoid overlapping Cards fields with Postcode label on it on stripeV3
In order to avoid overlapping fields when Postcode label is showed on StripeV3.
[Testing Proof video INT-2902](https://drive.google.com/file/d/1QylTdxD2BPOTW-0bpcjVI6silm1R919e/view?usp=sharing)
> fix(payment): INT-3308 added style to avoid overlapping cards fields with Postcode label on it on stripeV3

- src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
Adding padding between wallet buttons that appear on the first step of checkout.
There's no space between the buttons currently.
Before:
After:
> fix(checkout): BCTHEME-287 Add padding between wallet buttons

- src/app/customer/CheckoutButtonList.spec.tsx
- src/app/customer/CheckoutButtonList.tsx
Default to empty array if no payments are set
Because some merchants are testing out installing a custom checkout without having any payment set up and it fails:
manual + unit
> CHECKOUT-5263 Default to empty array if no payments are set

- package-lock.json
- package.json
- src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
Change style for sbp on checkout
Related task: https://github.com/bigcommerce/checkout-sdk-js/pull/1001
The merchant should be able to change the styles in theme customization for spb on the checkout page
> feat(payment): PAYPAL-746 Change style for sbp on checkout

- src/app/checkout/Checkout.spec.tsx
- src/app/checkout/Checkout.tsx
- src/app/common/error/CustomError.ts
Allows create customized errors
with that we are able to change the title
https://drive.google.com/file/d/1ftq1CteeynosKSd1roKwBKE5_JGvtbHi/view?usp=sharing
https://github.com/bigcommerce/checkout-sdk-js/pull/998
https://github.com/bigcommerce/bigcommerce/pull/37501
> fix(checkout): INT-3174 Allows create customized error modal

- src/app/payment/Payment.spec.tsx
- src/app/payment/Payment.tsx
Filter out `amazon` and `amazonpay` from payment methods when there are multiple consignments.
Because those payment providers only support one single consignment.
unit
> CHECKOUT-5295 Hide AmazonPay when multi-shipping

- src/app/checkout/Checkout.spec.tsx
- src/app/checkout/Checkout.tsx
- src/app/checkout/mapToCheckoutProps.ts
- src/app/shipping/Shipping.spec.tsx
- src/app/shipping/Shipping.tsx
Hide multi-shipping UI if it is not enabled. If there are multiple consignments, then an empty shipping form will be shown.
Checkout UI should honour the Checkout Settings. If it's not enabled, it shouldn't render the multi-shipping UI.
In some cases, some shoppers have been presented with a multi-shipping UI despite the setting being disabled.
Still not sure how they ended up with more than one shipping address in the first place, but this at least will prevent the shopper paying for shipping twice.
> CHECKOUT-5346 Hide multishipping if not enabled

- src/app/address/getAddressCustomFieldsValidationSchema.spec.tsx
- src/app/address/getAddressCustomFieldsValidationSchema.ts
- src/app/address/getAddressValidationSchema.ts
- src/app/billing/Billing.tsx
- src/app/billing/BillingForm.tsx
- src/app/locale/translations/en.json
- src/app/shipping/Shipping.tsx
- src/app/shipping/ShippingForm.tsx
- src/app/shipping/SingleShippingForm.tsx
Validate that provided values are considered "safe", that means, does not contain any of the following:
```
< >
```
To avoid fraudulent/suspicious activity.
Experiment ON:
Experiment OFF:
> CHECKOUT-5327 Validate checkout safe values 

- src/app/common/error/SentryErrorLogger.spec.ts
- src/app/common/error/SentryErrorLogger.ts
Only send errors that originated from application code and its dependencies.
We're not responsible for errors that are caused by code that is external to the application.
At the moment, we are seeing some errors in our log that are caused by third party scripts, such as [Klaviyo](https://sentry.io/organizations/bigcommerce/issues/1904396678) and [Poptin](https://sentry.io/organizations/bigcommerce/issues/2050108407). We realised that `whitelistUrls` and `blacklistUrls` config provided by Sentry client only checks the topmost frame in the stack trace. This means that it won't filter out those exception events if they are caused by problems deeper in the stack trace. i.e.:
We can't filter them using Sentry's server-side config because it can only filter out exceptions by error messages, not …
> fix(common): CHECKOUT-5332 Only send in-app errors to Sentry

- src/app/payment/Payment.tsx
Added googlepayadyenv2 not to ask to redirect
In order to have 3DS working for google pay on AdyenV2
[BigCommerce PR](https://github.com/bigcommerce/bigcommerce/pull/38152)
[BigPay PR](https://github.com/bigcommerce/bigpay/pull/3190)
[Checkout-SDK](https://github.com/bigcommerce/checkout-sdk-js/pull/1009)
> feat(payment): INT-2816 Added 3DS to googlepay adyenv2

- src/app/checkout/Checkout.spec.tsx
- src/app/checkout/navigateToOrderConfirmation.spec.tsx
- src/app/checkout/navigateToOrderConfirmation.tsx
At the moment, the redirect to the order confirmation page fails if the current page URL contains a query param, e.g.: `/embedded-checkout?setCurrencyId=1`. This PR fixes the issue by discarding the query param when constructing the redirect URL.
This PR addresses #446.
Otherwise, the redirection doesn't work (see the below & after screenshots below).
Please note that embedded-checkout is supposed to load inside an iframe. But for the purpose of demonstration, I loaded it directly in the browser so that the URL could be visible.
> CHECKOUT-5300: Fix order confirmation page redirection fails if existing url contains query param

- README.md
Update OS requirement, as per https://github.com/bigcommerce/checkout-js/issues/475
So devs know that Unix-like is supported. In order to use Windows, they might need a Unix simulator tool.
n/a
> docs(common): ISSUE-475 Update OS requirement

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Added translation method on credit debit card title on adyenv2.
So that title payment method could be translated on adyenv2.
[Checkout-sdk-js #1031](https://github.com/bigcommerce/checkout-sdk-js/pull/1031)
> feat(payment): INT-3538 Added translation method on  credit debit card title on adyenv2

- package-lock.json
- package.json
Bump checkout-sdk-js 1.118.2
Fixed Braintree integration
...
> chore(common): PAYPAL-767 Bump checkout-sdk-js 1.118.2

- src/app/checkout/Checkout.spec.tsx
- src/app/checkout/Checkout.tsx
- src/app/checkout/mapToCheckoutProps.ts
Check if multi-shipping is enabled once checkout has loaded.
At the moment we check if the setting is enabled before the config is loaded, which will result in always false, causing single-shipping mode to always be loaded after a new address is added via the account settings page.
> CHECKOUT-5477 Check if multi-shipping is enabled once config is loaded

- src/app/payment/paymentMethod/StripePaymentMethod.spec.tsx
- src/app/payment/paymentMethod/StripePaymentMethod.tsx
- src/app/payment/paymentMethod/StripeV3CustomCardForm.spec.tsx
- src/app/payment/paymentMethod/StripeV3CustomCardForm.tsx
Removed Zip code from individual fields form on StripeV3
Removed the zip code field from payment step to reduce the redundancy of having to enter zip code twice in checkout.
Before:
After:
> feat(payments): INT-3637 removed Zip code from individual fields form on StripeV3

- src/app/order/OrderSummaryItem.spec.tsx
- src/app/order/OrderSummaryItem.tsx
- src/app/order/mapFromPhysical.tsx
- src/scss/components/checkout/productList/_productList.scss
Render gift wrapping as product description
Because currently we do not render this information, and totals won't match
> CHECKOUT-5529 Render gift wrapping in cart summary

- package-lock.json
- package.json
Bump checkout-sdk to v1.121.1
To include https://github.com/bigcommerce/checkout-sdk-js/pull/1054
Circle CI, Manual
> fix(payment): INT-3717 Bump checkout-sdk

- package-lock.json
- package.json
- src/app/cart/mapToOrderSummarySubtotalsProps.ts
- src/app/checkout/checkouts.mock.ts
- src/app/locale/translations/en.json
- src/app/order/OrderSummaryDrawer.tsx
- src/app/order/OrderSummarySubtotals.tsx
- src/app/order/__snapshots__/OrderSummary.spec.tsx.snap
- src/app/order/__snapshots__/OrderSummaryModal.spec.tsx.snap
- src/app/order/mapFromPhysical.tsx
- src/app/order/mapToOrderSummarySubtotalsProps.ts
- src/app/order/orders.mock.ts
Show gift wrapping cost in order summary. Also "tag" items that contains gift wrapping
Note: depends on SDK Changes and API changes
https://github.com/bigcommerce/bigcommerce/pull/39048
https://github.com/bigcommerce/checkout-sdk-js/pull/1058
So totals add up and shoppers can understand the difference between the subtotal and the grand total.
unit
Tested in conjunction with the API changes, see screenshots in https://github.com/bigcommerce/bigcommerce/pull/39048
>  CHECKOUT-2322 Show gift wrapping cost

- package-lock.json
- package.json
Bump checkout-sdk-js version 
https://github.com/bigcommerce/checkout-sdk-js/pull/1051
Manual testing of checkout-sdk release https://github.com/bigcommerce/checkout-sdk-js/pull/1051 + unit tests
> feat(payment): ADYEN-8  bump checkout-sdk

- src/app/ui/form/CheckboxGroupFormField.tsx
Updating `handleSelectNone` to use `remove(0)` instead of `pop()`
I am not sure why `pop()` does not uncheck the UI elements but, using `remove()` with the 0 index works.
before: 
after:
> fix(checkout): CHECKOUT-5505 When using a Custom Address Form Field Checkbox selecting None does not remove selections

- package-lock.json
- package.json
Upgrade `checkout-sdk` version to `1.124.1`.
https://github.com/bigcommerce/checkout-sdk-js/compare/v1.124.0...v1.124.1
See the related PRs.
> CHECKOUT-5324: Upgrade `checkout-sdk` version

- src/app/address/AddressForm.scss
- src/app/customer/CreateAccountForm.scss
Add missing dynamic-form-field margin to create-account-form
Because it was causing all fields to be too close together. This only happens in production because in dev we don't lazy load each component, so styles were being shared from the shipping form.
Reported:
After:
> CHECKOUT-5531 Fix spacing in account creation form

- src/app/customer/CreateAccountForm.spec.tsx
- src/app/customer/CreateAccountForm.tsx
- src/app/locale/translations/en.json
Show email already in use error
So customers know why they can't create an account.
> CHECKOUT-5530 Show email already in use error

- src/app/customer/CheckoutButtonList.tsx
- src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
Added googlepay on cybersourcev2 option.
In order to show google pay like an option when cybersource is enabled on checkout.
> feat(payment): INT-3418 added GooglePay for CybersourceV2

- src/app/payment/hostedCreditCard/withHostedCreditCardFieldset.spec.tsx
- src/app/payment/hostedCreditCard/withHostedCreditCardFieldset.tsx
Pass `accessibilityLabel` property to hosted payment form so that the fields can have the appropriate `aria-label`.
Without `aria-label`, screen readers won't be able to read them.
I tested using [Google Chrome Screen Reader extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en).
Here are some screenshots showing that the `aria-label` attribute is now set.
> CHECKOUT-5610: Pass accessibility labels to payment form

- src/app/payment/storedInstrument/ManageAccountInstrumentsTable.tsx
- src/app/payment/storedInstrument/ManageInstrumentsModal.spec.tsx
- src/app/payment/storedInstrument/ManageInstrumentsModal.tsx
Added bankAccount option in order to render account Instrument Table
In order to allow deleting vaulted bank account instruments from account Instrument Table Modal
[Bigpay #3442](https://github.com/bigcommerce/bigpay/pull/3442)
[TESTING PROOF VIDEO](https://drive.google.com/file/d/16EWwuaIa2TpKmWnG9kGD2KVtIgMA5FNe/view?usp=sharing)
> fix(payment): INT-3813  added bankAccount in order to render account Instrument Table

- src/app/customer/Customer.spec.tsx
- src/app/customer/Customer.tsx
- src/app/customer/LoginForm.tsx
- src/app/customer/__snapshots__/LoginForm.spec.tsx.snap
Hide create account link/form if account creation is disabled
To honour the Store setting.
> CHECKOUT-5612 Hide create account link/form if account creation is disabled

- src/app/address/isEqualAddress.spec.ts
- src/app/address/isEqualAddress.ts
Ignore `country` when checking if two addresses are equal
We already rely on `countryCode`, so we can safely ignore `country`. 
The request payload doesn't have `country`, that's why when comparing the request address to the response address, they wouldn't match
> CHECKOUT-5618 Update address in dropdown when multishipping

- src/app/locale/translations/en.json
- src/app/payment/PaymentForm.tsx
- remove the label "Payment Methods" in the checkout 
- it not needed
> feat(payment): PAYMENTS-6576 remove the label "Payment Methods" in checkout

- src/app/payment/paymentMethod/MasterpassPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
Added new URL script and source button on masterpass
In order to be able to continue using Masterpass (now "SRC") when shoppers checkout
So that they can continue accepting payment via Masterpass (SRC).
1# [BIGCOMMERCE #39508](https://github.com/bigcommerce/bigcommerce/pull/39508)
2#[CHECKOUT-SDK-JS #1072](https://github.com/bigcommerce/checkout-sdk-js/pull/1072)
[TESTING PROOF VIDEO](https://drive.google.com/file/d/13DRZY92NnGDP1q-_t9hHnetXGfgZmVak/view?usp=sharing)
@bigcommerce/apex-integrations  @bigcommerce/payments
> fix(payment): INT-3408 migrated masterpass to SRC

- package-lock.json
- package.json
Bump the version of Checkout SDK in use.
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1066
Circle, performed manually.
> feat(payment): INT-3700 Bump SDK.

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- Create the Digital River payment strategy and make it available on the checkout page. 
- Removes the general place order button to Digital River.
- Add events such as errors and submit to control it on the SDK.
A new payment method is required to support Digital River which will only be displayed when there is no other payment provider configured.
https://github.com/bigcommerce/checkout-sdk-js/pull/1076
**must be merged first** 
> feat(payment): INT-3840 Add DigitalRiver payment method

- package-lock.json
- package.json
Bump the version of the SDK in use.
Releasing:
* https://github.com/bigcommerce/checkout-sdk-js/pull/1075
* https://github.com/bigcommerce/checkout-sdk-js/pull/1076
See linked PRs.
> feat(payment): INT-3896 INT-3840 Bump SDK.

- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Made logos for Klarna methods on checkout consistent.
According to task https://jira.bigcommerce.com/browse/ADYEN-38
Logos for Klarna methods on checkout seem inconsistent. 
> fix(checkout): ADYEN-38 Fix Adyen icons on checkout page

- src/app/address/isEqualAddress.spec.ts
- src/app/address/isEqualAddress.ts
Check state code for address equality, and any combination between `stateOrProvince` and `stateOrProvinceCode`
Sometimes, when comparing if two addresses are equal, we might be comparing a request payload and a response payload. Request payloads may only contain `stateOrProvince` or `stateOrProvinceCode`, and for consignments, the `stateOrProvince` also accepts state codes as values.
Unit
> CHECKOUT-5618 Check also `stateOrProvinceCode` for address equality

- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
[INT-3969](https://jira.bigcommerce.com/browse/INT-3969)
Use logos for multiple APMs of checkout.com payment method instead of names
In order to replace text and use the images for the multiple APMs that checkout.com let use
- bigcommerce/bigcommerce#39812
> feat(payment): INT-3969 Use APMs logos instead names in checkout accordion for Checkout.com

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Suppress PayPal and Klarna for DigitalRiver from being renderer. Digital provides us a new param called `disabledPaymentMethods` to do that.
Because Digital River needs to obtain permission from PayPal and Klarna before BigCommerce can support any of these payment methods within our Digital River integration
https://github.com/bigcommerce/checkout-sdk-js/pull/1086
**Before:**
**After:**
> feat(payment): INT-3947 Suppress PayPal and Klarna for DigitalRiver

- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Changed pay later logo to svg
According to task PAYPAL-973
Tested on dev
@bigcommerce/checkout @davidchin
> feat(payment): PAYPAL-973 changed pay later logo to svg

- package-lock.json
- package.json
Raise the version of the SDK in use.
Releasing [checkout-sdk-js/pull/1097](https://github.com/bigcommerce/checkout-sdk-js/pull/1097)
Circle
> feat(payment): PAYPAL-965 Bump SDK.

- package-lock.json
- package.json
Bump `checkout-sdk` version
https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md
See above
> CHECKOUT-5740: Bump checkout-sdk version

- package-lock.json
- package.json
Release of new version checkout-sdk 
Due to https://jira.bigcommerce.com/browse/PAYPAL-970
> fix(payment): PAYPAL-970 update version of checkout-sdk

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Added ability to translate SEPA display name
So that merchants are able to translate  SEPA checkout experience for their shoppers.
> fix(payment): INT-4100 added ability to translate SEPA display name

- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Change logo file extension to `*.svg` instead of `*.png` and use method name in all cases.
As requested by checkout.com on JIRA issue [INT-4180](https://jira.bigcommerce.com/browse/INT-4180)
> fix(checkout): INT-4180 Display method name along with the icon for checkout.com

- package-lock.json
- package.json
According to task PAYPAL-982
tested on dev
@bigcommerce/checkout @davidchin @capsula4
> feat(payment): PAYPAL-982 bump checkout-sdk

- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- src/app/payment/paymentMethod/MollieCustomCardForm.tsx
- src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
- src/app/payment/paymentMethod/MolliePaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
added vaulted methods in order to save cc, modify html and css to stylish Mollie Components, added selectdIntrumentId 
We want the user to be able to save cc and use them later when logged in 
Build is failing because of this dependency
[SDK](https://github.com/bigcommerce/checkout-sdk-js/pull/1113)
> feat(payment): INT-3702 Added vaulted credit card support for Mollie

- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Add 'checkoutcom' validation for the payment method logo
So credit card method does not display logo when on phase 1.
Requires https://github.com/bigcommerce/checkout-js/pull/552 to be merged
With Phase 2 disabled
With Phase 2 enabled
> fix(checkout): INT-4229 Fix checkout.com logo for credit card on phase 1

- src/app/payment/Payment.tsx
Parent ticket: [INT-3825](https://jira.bigcommerce.com/browse/INT-3825)
[INT-4150](https://jira.bigcommerce.com/browse/INT-4150)
I added zip as an option within the handlebeforeunload function
We're implementing a full redirect in new refactor for zip and during the redirect a `Leaving site` pop up alert was interrupting the redirection. 
https://drive.google.com/file/d/1PsMQ111k9rtq6RjgBkdJcbeffcBln2yu/view?usp=sharing
@bigcommerce/checkout @bigcommerce/apex-integrations 
Sibling PR Sdk: https://github.com/bigcommerce/checkout-sdk-js/pull/1118
> feat(payment): INT-4150 adding zip to handlebeforeunload function 

- src/app/locale/translations/en.json
- src/app/order/OrderStatus.tsx
[INT-4193](https://jira.bigcommerce.com/browse/INT-4193)
Add Url for OXXO/Boleto ticket for checkout.com
So customer can check its ticket through order confirmation and email
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/40524)
~~[BIGPAY](https://github.com/bigcommerce/bigpay/pull/3700)~~
[Demo](https://drive.google.com/file/d/1ZbjvnviN8GF_kbzWDLF-hsHSTG7EzatK/view?usp=sharing)
> feat(payment): INT-4193 Add ticket url for OXXO/Boleto on checkout.com

- src/app/payment/Payment.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/getPaymentMethodName.spec.ts
- src/app/payment/paymentMethod/getPaymentMethodName.ts
Create the Clearpay form that will be displayed on the checkout page.
We need Clearpay to be displayed as payment option when merchants have enabled it
https://drive.google.com/file/d/1zoG-uAWQ0LSMogJGCi1vBSpNPXh180KZ/view?usp=sharing
> feat(payment): INT-4071 Clearpay - Create payment method

- package-lock.json
- package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1130
> fix(payment): INT-3941 Bump SDK.

- src/app/order/OrderStatus.spec.tsx
- src/app/order/OrderStatus.tsx
Fix mailto: links on order confirmation page if payment is still pending or order is incomplete
There's HTML in these strings which is being escaped
Before
After
> fix(checkout): CHECKOUT-5037 Fix mailto: links on order confirmation page if payment is still pending or when order is incomplete

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
- src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Add the missing payment type line to SEPA on checkout.com
These changes were missing on https://github.com/bigcommerce/checkout-js/pull/571
> fix(payment): INT-4184 Add missing payment type to SEPA

- src/app/payment/paymentMethod/MollieAPMCustomForm.spec.tsx
- src/app/payment/paymentMethod/MollieAPMCustomForm.tsx
- src/app/payment/paymentMethod/MollieCustomCardForm.spec.tsx
- src/app/payment/paymentMethod/MollieCustomCardForm.tsx
- src/app/payment/paymentMethod/MolliePaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/scss/components/checkout/instrumentSelect/_instrumentSelect.scss
List Issuing Banks In Dropdown on Payment Step, adding a component for APMs where this issuers are listed in a dropdown
Some APMs such as Ideal have bank from where to choose, 
[SDK](https://github.com/bigcommerce/checkout-sdk-js/pull/1126)
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/40630)
[BIGPAY](https://github.com/bigcommerce/bigpay/pull/3748)
ping @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/checkout
> feat(payment): INT-4237 Add issuer for Mollie APMs

- package-lock.json
- package.json
- src/app/payment/paymentMethod/PPSDKPaymentMethod/NoUI.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/PPSDKPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/PPSDKPaymentMethod.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/Wrapper.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/index.ts
- src/app/payment/paymentMethod/PPSDKPaymentMethod/initializationComponentMap.ts
- src/app/payment/paymentMethod/PPSDKPaymentMethod/usePropsToOnMount.ts
- src/app/payment/paymentMethod/PaymentMethod.spec.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodProviderType.ts
- Add a new `PPSDKPaymentMethod`
- Add a map of initialisation strategies to Functional Components which will render the UI
- Add mounting logic to call init/deinit strategy methods upon rendering a valid initialisation strategy
- Have the `PPSDKPaymentMethod` return no visuals and call the error handler on an initialisation strategy mismatch
- Add a `NoUI` component for PPSDK initialisation strategies that require no initial UI (e.g. payment methods which redirect offsite on a user click of "place order")
- Guard all the above with a experiment feature toggle which will not allow the selection of `PPSDKPaymentMethod` when off
- To allow for correct rendering of new PPSDK Payment Methods (at first, ones with no visuals)
- New tests
> feat(payment): PAYMENTS-6813 add wip ppsdk payment method

- package-lock.json
- package.json
Update checkout-sdk-js version
[checkout-sdk-js PR](https://github.com/bigcommerce/checkout-sdk-js/pull/1142)
Due to https://jira.bigcommerce.com/browse/PAYPAL-1024
> feat(checkout): PAYPAL-1024 bump chechkout-sdk-js version

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
[INT-4289](https://jira.bigcommerce.com/browse/INT-4289): Suppress payment methods out of scope on Digital River.
On BigCommerce we will not be supporting all the alternative [payment methods provided by Digital River](https://jira.bigcommerce.com/browse/INT-4289) by default.
Checkout screen without unsupported methods as Alipay and Wire Transfer:
> feat(payment): INT-4289 Suppress payment methods out of scope on Digital River

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
- src/app/payment/paymentMethod/HostedDropInPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedDropInPaymentMethod.tsx
Proposal to create a HostedDropInPaymentMethod to support the Digital River Drop In component.
This new PaymentMethod allow us to hide the checkboxes to save cards since the drop in component have them in their own logic.
Also allow us to hide/show the submitPaymentButton depends on the element that is rendered (Drop In or CardInstrumentFieldset) using the paymentContext.
Right now there isn't a payment method that supports this type of component and behavior.
Demo: https://drive.google.com/file/d/1ws428vHXhPTeaIqy4PlDdiaxM3_sfLRr/view?usp=sharing
Note: Avoid Circle CI, I didn't complete the unit testing until get approval
> feat(payment): INT-4310 Create HostedDropInPaymentMethod

- package-lock.json
- package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1145
Circle, linked PR.
> feat(payment): INT-4310 Bump SDK.

- src/app/locale/translations/en.json
- src/app/payment/Payment.tsx
- src/app/payment/PaymentSubmitButton.spec.tsx
- src/app/payment/PaymentSubmitButton.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Add **Quadpay** payment method.
To make **Quadpay** available at checkout.
This PR depends on https://github.com/bigcommerce/checkout-sdk-js/pull/1129 to pay.
This PR depends on https://github.com/bigcommerce/bigcommerce/pull/40762 to display the Quadpay logo.
@bigcommerce/apex-integrations  @bigcommerce/checkout
> feat(payment): INT-4242 Add Quadpay payment method

- package-lock.json
- package.json
Getting the following change out:
https://github.com/bigcommerce/checkout-sdk-js/pull/1119
See this PR https://github.com/bigcommerce/checkout-sdk-js/pull/1119
@bigcommerce/checkout @bigcommerce/apex-integrations @bigcommerce/payments
> feat(payment): INT-4205 Bump checkout-sdk

- package-lock.json
- package.json
Getting the following change out:
https://github.com/bigcommerce/checkout-sdk-js/pull/1074
before
after
> feat(payment): PAYPAL-863 bump checkout-sdk-js version

- package-lock.json
- package.json
Bump Checkout-sdk version 
checkout-sdk-js [PR](https://jira.bigcommerce.com/browse/PAYPAL-1055)
Due to https://jira.bigcommerce.com/browse/PAYPAL-1055
> fix(checkout): PAYPAL-1055 bump checkout-sdk version

- src/app/locale/translations/en.json
- src/app/payment/PaymentForm.spec.tsx
- src/app/payment/PaymentForm.tsx
- src/app/payment/PaymentSubmitButton.spec.tsx
- src/app/payment/PaymentSubmitButton.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
Supersedes: https://github.com/bigcommerce/checkout-js/pull/594
- Add logic to set the Submit button label to `Continue with {methodName}` when a no UI PPSDK payment method is selected
- Guard the above with a experiment feature toggle which maintains current functionality when off
- To convey to consumers that more steps are required with that payment method prior to submitting the order
- New tests
https://user-images.githubusercontent.com/56807262/119301209-7300f380-bca5-11eb-8753-a1604cd8194b.mov
> PAYMENTS-6899 add ppsdk payment method submit button text

- package-lock.json
- package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1140
> feat(payment): INT-4170 Bump SDK.

- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- src/app/payment/paymentMethod/MolliePaymentMethod.tsx
Added Hosted Field schema to HostedWidgetPaymentMethod in order to show error messages on TSV for Mollie
TSV Verification Hosted field was not showing the error messages
> feat(payment): INT-4170 added hosted_field schema for Mollie

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
To disable the payment method depending from the settings we need to update the disabledPaymentMethods array that is sending as configuration to the Digital River JS in the strategy.
To support the checkboxes in Digital River settings page.
> feat(payment): INT-3792 Disabled payment method due to settings

- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Update Mollie APMs Logos
The Mollie APMs Logos were not the current ones 
[BCCAP](https://github.com/bigcommerce/bigcommerce/pull/41490)
By Reverting this PR
ping @bigcommerce/apex-integrations @bigcommerce/checkout
> feat(payment): INT-4441 Update Mollie APMs logos

- src/app/customer/CheckoutButtonList.tsx
- src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
Added Google Pay on Orbital
So that merchants can offer Google Pay as Payment Method using Orbital (CMS) integration
[SDK 1154](https://github.com/bigcommerce/checkout-sdk-js/pull/1154)
bigcommerce/checkout
> feat(payment): INT-4342 added Google Pay for Orbital

- src/app/locale/getDefaultTranslations.spec.ts
- src/app/locale/getDefaultTranslations.ts
Ignore the region identifier if only the language identifier matches with the value inherited from storefront.
For example, if `fr-CA` is the preferred locale, display `fr` instead of `en`.
Unit
> CHECKOUT-5872: Handle locale with region identifier

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/MollieAPMCustomForm.spec.tsx
- src/app/payment/paymentMethod/MollieAPMCustomForm.tsx
Add Select your bank to the en.json as part of [INT-4237](https://jira.bigcommerce.com/browse/INT-4237)
Its a good practice to have these copies in a translatable file
> feat(payments): INT-4237 Added select your bank to json

- src/app/customer/CheckoutButtonList.spec.tsx
- src/app/customer/CheckoutButtonList.tsx
- src/app/customer/Customer.tsx
- src/app/customer/GuestForm.spec.tsx
- src/app/customer/GuestForm.tsx
Pass the `isLoading` variable to the guest component and use it to validate the disabling of 'continue as Guest' button and also the "login" link to prevent it from being clickable when the checkout is loading
As mentioned in the Jira Issues, when a customer clicks on the continue as guest button and the google pay / amazon pay scrips haven't finished loading it triggers an error only visible in the developer console which get logged into sentry.
By disabling the buttons until the scripts have finished loading this error is prevented.
[Demo Video](https://drive.google.com/file/d/1dTN99MLiCYULoxVTJvuUQ5M4JeonLnCC/view?usp=sharing)
> fix(customer): Disable continue as guest button when loading

- src/app/payment/Payment.tsx
- Add PPSDK methods to the before unload warning exemption list
- So that redirect flows are not interrupted by the "Are you sure?" alert
**Before**
**After**
https://user-images.githubusercontent.com/56807262/124855426-43efd880-dfec-11eb-8dbd-61e9998becaa.mov
> feat(payment): PAYMENTS-6812 add PPSDK payment methods to the handleBeforeUnload exemption list

- src/app/checkout/Checkout.tsx
- src/app/shipping/Shipping.spec.tsx
- src/app/shipping/Shipping.tsx
- src/app/shipping/ShippingForm.spec.tsx
- src/app/shipping/ShippingForm.tsx
- src/app/shipping/SingleShippingForm.tsx
When navigating to billing/payment step and back to shipping step, the "My billing address is the same as my shipping address" checkbox always default to `true` 
The state of the checkbox is not saved
https://user-images.githubusercontent.com/22089936/124700192-e17cd680-df1e-11eb-818a-e58fbe3d8233.mov
> fix(shipping): CHECKOUT-5895 Keep billingSameAsShipping state when navigating through steps

- src/app/order/OrderStatus.spec.tsx
- src/app/order/OrderStatus.tsx
As above
Before it was translated as string so not rendering html 
> fix(checkout): CHECKOUT-5916 fix awaiting payment to render TranslatedHtml

- package-lock.json
- package.json
Releasing https://github.com/bigcommerce/checkout-sdk-js/pull/1171
> feat(payment): INT-4141 Bump SDK.

- src/app/checkout/Checkout.tsx
Fix create account flow  from Checkout blocked due to cross origin frame in embedded checkouts.
There is an issue where a CORS origin error happens when a user is redirected from checkout page to customer account creation.
- Screencast
https://user-images.githubusercontent.com/7134802/126460870-ed4d3a2d-3b8b-403c-821d-ac886af83dc4.mov
> fix(customer): CHECKOUT-5862 Fix create account flow from Checkout blocked due to cross origin frame

- src/app/payment/PaymentSubmitButton.spec.tsx
- src/app/payment/PaymentSubmitButton.tsx
Display `Continue with Zip` instead of `Place Order`
It's more accurate since the shopper is redirected to Zip's page.
_Before:_
_After:_
@bigcommerce/apex-integrations  @bigcommerce/checkout
> feat(payment): INT-4605 Zip: Display special text for PaymentSubmitButton

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
added showSavePaymentAgreement dynamically instead of hardcoded
It's a bug that could affect future DigitalRiver users
https://github.com/bigcommerce/checkout-sdk-js/pull/1178
> fix(payment): INT-4598 handle vaulting Enable checkbox for Digital River

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/1178
https://github.com/bigcommerce/checkout-sdk-js/pull/1186
> chore(payment): INT-4598 INT-4661 Bump checkout-sdk

- src/app/payment/Payment.tsx
- Allow the Payments UI to present payment options after a finalization error (i.e. when a payment method returns to the checkout, but the payment failed for some reason)
- Current UI shows payment methods as perpetually loading in this scenario
- Allow customers to try paying again to continue their checkout
- The removed `return` did not seem to offer any functionality, React does not consume returned values from `componentDidMount` methods and the early return only served to stop the component reaching an otherwise valid `ready` state
**Before:**
https://user-images.githubusercontent.com/56807262/127413506-3d146f3f-9cad-456b-8112-02625b2bc6f7.mov
**After**
https://user-images.githubusercontent.com/56807262/127413537-f675ba85-9e0a-437e-9212-ee1944c5ed5a.mov
> fix(payment): PAYMENTS-7169 fix broken UI post finalization error

- src/app/customer/CreateAccountForm.spec.tsx
- src/app/customer/CreateAccountForm.tsx
- src/app/customer/Customer.tsx
If the shopper doesn't require marketing consent, when a customer is created on checkout we should send the value to receive marketing emails
Currently, that value is always false so even if the setting is off, customers won't receive marketing emails
Update test 
> fix(checkout): CUST-1572 accept marketing emails should be true when requires marketing consent is false

- package-lock.json
- package.json
To get 1.170.0 out. See https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#11700-2021-08-04
See screenshots on these PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1165
https://github.com/bigcommerce/checkout-sdk-js/pull/1185
https://github.com/bigcommerce/checkout-sdk-js/pull/1187
https://github.com/bigcommerce/checkout-sdk-js/pull/1194
> chore(payment): INT-4438 INT-4480 INT-4584 INT-4585 Bump checkout-sdk

- src/app/payment/paymentMethod/HostedDropInPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/HostedDropInPaymentMethod.tsx
Fix logic to render on submit button when a discount is applied and the total is 0.
we detected this scenario in our QE phase and was necessary to fix it.
**BEFORE:**
**AFTER:**
> fix(payment): INT-4709 Display "place order button" when payment is not required

- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Removing disabledPaymentMethods for digitalriver
This functionality will be managed from the DigitalRiver dashboard 
https://github.com/bigcommerce/checkout-sdk-js/pull/1198
> feat(payments): INT-4686 removing disabledPaymentMethods for digitalriver

- package-lock.json
- package.json
Due to https://jira.bigcommerce.com/browse/PAYPAL-1100
> chore(checkout): PAYPAL-1100 bump checkout-sdk

- package-lock.json
- package.json
**N.B.** The PPSDK is behind a work in progress feature toggle
- Bump `checkout-sdk` to `1.175.1`
- To inherit the PPSDK fix: https://jira.bigcommerce.com/browse/PAYMENTS-7215
> chore(payment): PAYMENTS-7215 bump checkout-sdk

- package-lock.json
- package.json
Bump checkout-sdk to 1.175.2
We need to release changes from sdk https://github.com/bigcommerce/checkout-sdk-js/commit/9dfe1bdf9598c2acf8eb1ba0e5639b7adbe61d64
Passing tests
> chore(payment): INT-4672 bump checkout-sdk

- package-lock.json
- package.json
- src/app/payment/PaymentSubmitButton.spec.tsx
- src/app/payment/PaymentSubmitButton.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/PPSDKPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/initializationComponentMap.ts
**N.B.** The PPSDK is behind a work in progress feature toggle
- Fix casing of expected PPSDK initialisation strategy value from BE
- BE will be sending lowercase rather than all caps
> fix(payment): PAYMENTS-7214 fix PPSDK initialisation strategy casing

- src/app/locale/translations/en.json
- src/app/payment/PaymentSubmitButton.tsx
Updating the button text message when customers select Klarna as the payment method
New message: Continue with Klarna
Merchant request
> feat(payment): INT-4660 button text update on Checkout for Klarna

- package-lock.json
- package.json
Bump checkout-sdk to 1.175.6
We need to release changes from [SDK](https://github.com/bigcommerce/checkout-sdk-js/commit/e49795db4597f100ca3caa7f3bfd07e9f2481a55), which addresses [Checkout-5757](https://jira.bigcommerce.com/browse/CHECKOUT-5757).
All tests passed.
> chore(checkout): CHECK-5757 bump up checkout-sdk

- package-lock.json
- package.json
**N.B.** The PPSDK is behind a work in progress feature toggle
- Bump `checkout-sdk` to `1.177.1`
- To inherit the PPSDK fix: https://jira.bigcommerce.com/browse/PAYMENTS-7221
> fix(payment): PAYMENTS-7221 bump checkout-sdk

- package-lock.json
- package.json
Bump checkout-js version
SDK PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1217
Release of PAYPAL-1111
> chore(checkout): PAYPAL-1111 bump checkout-sdk-js version

- package-lock.json
- package.json
Bump checkout-js version
Release of BOLT-49
Unit tests
checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/1229
> chore(checkout): BOLT-49 bump checkout-sdk-js version

- src/app/address/googleAutocomplete/GoogleAutocomplete.tsx
- src/app/address/googleAutocomplete/GoogleAutocompleteFormField.tsx
- src/app/address/googleAutocomplete/__snapshots__/GoogleAutocomplete.spec.tsx.snap
- src/app/ui/autocomplete/Autocomplete.tsx
- src/app/ui/autocomplete/__snapshots__/Autocomplete.spec.tsx.snap
- Use `getLabelProps()` from [Downshift](https://www.downshift-js.com) to create a dynamic `id` attribute for an autocomplete input field's label, which aligns with the sample usage of [\<Downshift\> component](https://www.downshift-js.com/downshift).
- Update two snapshots to cover the code change.
As stated in [CHECKOUT-5980](https://jira.bigcommerce.com/browse/CHECKOUT-5980), the screen reader fails now because of  a label's missing dynamic `id` attribute(e.g., `id="downshift-0-label"`). Sometimes, the `id` can be `downshift-2-label`. Therefore,  this fix will create label `id` dynamically with Downshift.
Demo after code change.
https://user-images.githubusercontent.com/88361607/131297982-62e5efe3-3ca1-460c-a51d-99eeb893a2f2.mov
HTML of the address input field. Before:
```HTML
<div …
```
> fix(checkout): CHECKOUT-5980 invalid aria-labelledby values

- src/app/address/googleAutocomplete/GoogleAutocomplete.tsx
- src/app/address/googleAutocomplete/GoogleAutocompleteFormField.tsx
- src/app/address/googleAutocomplete/__snapshots__/GoogleAutocomplete.spec.tsx.snap
- src/app/ui/autocomplete/Autocomplete.tsx
- src/app/ui/autocomplete/__snapshots__/Autocomplete.spec.tsx.snap
##What
Reverts bigcommerce/checkout-js#682
Failing functional tests due to a change in id of autocomplete input.
ping @bigcommerce/checkout
> Revert "fix(checkout): CHECKOUT-5980 invalid aria-labelledby values"

- src/app/checkout/Checkout.tsx
- src/app/checkout/CheckoutStep.spec.tsx
- src/app/checkout/CheckoutStep.tsx
- src/app/checkout/CheckoutStepHeader.spec.tsx
- src/app/checkout/CheckoutStepHeader.tsx
- src/app/common/dom/index.ts
- src/app/common/dom/stopPropagation.ts
- src/app/config/config.mock.ts
- src/app/customer/Customer.spec.tsx
- src/app/customer/Customer.tsx
- src/app/customer/GuestForm.spec.tsx
- src/app/customer/GuestForm.tsx
- src/app/customer/LoginForm.spec.tsx
- src/app/customer/LoginForm.tsx
- src/app/customer/__snapshots__/Customer.spec.tsx.snap
- src/app/customer/checkoutSuggestion/BoltCheckoutSuggestion.spec.tsx
- src/app/customer/checkoutSuggestion/BoltCheckoutSuggestion.tsx
- src/app/customer/checkoutSuggestion/CheckoutSuggestion.spec.tsx
- src/app/customer/checkoutSuggestion/CheckoutSuggestion.tsx
- src/app/customer/checkoutSuggestion/index.tsx
- src/app/customer/index.ts
- src/app/locale/translations/en.json
- src/scss/components/_components.scss
- src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
- src/scss/components/checkout/checkoutSuggestion/_checkoutSuggestion.scss
- src/scss/components/checkout/checkoutSuggestion/_component.scss
feat(payment): BOLT-19 added Bolt Embedded One Click Checkout implementation and new generic CheckoutSuggestion component
Add Bolt Embedded One Click Checkout implementation.
Because of the task: https://jira.bigcommerce.com/browse/BOLT-19
- Extracted `CheckoutStep` component with `suggestion` prop to render `BoltCheckoutSuggestion` in collapsed Customer step;
- Changed 'Continue as guest' click handler to execute priority payment provider checkout;
- Created new generic `CheckoutSuggestion` component;
- Created new `BoltCheckoutSuggestion` component;
- Changed 'Continue as guest' button label to 'Continue' for cases if the shop has enabled interaction with provider's checkout.
To add Bolt Embedded One Click Checkout implementation I needed to handle next cases:
- customer should not …
> feat(payment): BOLT-19 added Bolt Embedded One Click Checkout implementation

- package-lock.json
- package.json
**N.B.** The PPSDK is behind a work in progress feature toggle
- Bump `checkout-sdk` to `1.180.1`
- To inherit the PPSDK fix: https://jira.bigcommerce.com/browse/PAYMENTS-7252
> chore(payment): PAYMENTS-7252 bump checkout-sdk-js version

- package-lock.json
- package.json
According to https://jira.bigcommerce.com/browse/PAYPAL-954
> feat(payment): PAYPAL-954 bump checkout sdk version

- package-lock.json
- package.json
- src/app/locale/translations/en.json
- src/app/payment/PaymentForm.spec.tsx
- src/app/payment/PaymentForm.tsx
- src/app/payment/paymentMethod/BoltCustomForm.spec.tsx
- src/app/payment/paymentMethod/BoltCustomForm.tsx
- src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.tsx
- src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
Added Bolt account creation checkbox under mounted Bolt filed in BoltEmbeddedPaymentMethod
Because of the task: https://jira.bigcommerce.com/browse/BOLT-24
Unit tests
Manual test
Here is a screenshot of the checkbox:
checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/1235
> feat(payment): BOLT-24 added Bolt account creation checkbox into Bolt EmbeddedPaymentMethod component

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Add custom error message for all drop-in errors using Digital River
Digital River requested this message "There was an error while processing your payment. Please try again or contact us." should be displayed for all cases that DR drop-in send an error
> feat(payment): INT-4828 Adding custom error message for all dropin error

- package-lock.json
- package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1242 out
CircleCI + see the videos on above PR
> chore(checkout): CHECKOUT-5777 Bump checkout-sdk v1.183.0

- src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.tsx
Fixed an issue with Bolt customer strategy deinitialisation when closing payment step.
Videos of the problem:
The first one is about closing payment step by going to the billing tab and trying to use customer suggestion block.
https://user-images.githubusercontent.com/25133454/133968716-21927042-6a61-4e05-a9ce-00704fdc3ad2.mov
The second one is about closing payment step by opening customer step and trying to use customer strategy by click on 'Continue' button.
https://user-images.githubusercontent.com/25133454/133968737-28489066-bfbe-497d-90d3-3ffe8a572aa6.mov
HostedWidgetPaymentMethod asynchronously deinitialize bolt customer strategy that was initialized in customer step. Deinitialize and initialize customer strategies unnecessary for Bolt payment provider in HostedWidgetPaymentMethod. …
> fix(payment): BOLT-54 fixed an issue with customer strategy deinitialisation

- package-lock.json
- package.json
Due to the https://jira.bigcommerce.com/browse/ADYEN-260
SDK PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1244
Tested manually. GooglePay didn't change customer email in checkout
> chore(checkout): ADYEN-260 bump checkout-sdk version

- src/app/cart/Redeemable.spec.tsx
- src/app/cart/Redeemable.tsx
Adding an aria-label attribute to the coupon/gift certificate input field. The value will be populated by existing language already being used as the label for coupon/gift certificate input.
To allow customers using screen reader software to more accurately navigate and input gift certificates/coupon codes during checkout. 
Before:
After:
> fix(checkout): CHECKOUT-5823 Add label attribute for screen readers on coupon/gift certificate input field in cart summary at checkout

- src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
Fixed an issue with checkout step header with large font-size
Because of the task:
https://jira.bigcommerce.com/browse/BOLT-60
And because of the issue:
https://github.com/bigcommerce/checkout-js/issues/703
Here are some screenshots of the result
Default title font size:
Title font size 32px:
Title font size 65px:
> fix(payment): BOLT-60 fixed an issue with checkout step header with large font-size

- package-lock.json
- package.json
According to task https://jira.bigcommerce.com/browse/PAYPAL-972
SDK PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1240
> feat(payment): PAYPAL-972 bump checkout sdk js

- src/app/payment/paymentMethod/StripePaymentMethod.spec.tsx
- src/app/payment/paymentMethod/StripePaymentMethod.tsx
Added hosted fields on verification fields on StripeV3
Currently, we have some payment methods that are not using hosted credit card fields for stored instrument verifications (card number and CVV). This presents a security vulnerability as malicious JS can easily scrape credit card information.
[SDK #1179](https://github.com/bigcommerce/checkout-sdk-js/pull/1179)
- Manual
- Unit
@bigcommerce/apex-integrations @bigcommerce/checkout
> feat(payment): INT-4170 Stripe: use hosted fields for verification fields for stored instruments

- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Update `PaymentMethodTitle` logo URL for Openpay.
Openpay wants us to display this logo instead. 🤷🏻‍♂️
**_Before:_**
**_After:_**
☝️😅 This PR depends on https://github.com/bigcommerce/bigcommerce/pull/42979.
> feat(payment): INT-4836 Openpay: New logo on checkout page

- package-lock.json
- package.json
According to task https://jira.bigcommerce.com/browse/PAYPAL-1103
SDK PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1245
Tested on integration
> feat(payment): PAYPAL-1103 bump checkout-sdk-js

- package-lock.json
- package.json
Release of https://jira.bigcommerce.com/browse/ADYEN-260
SDK PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1251
Due to the https://github.com/bigcommerce/checkout-sdk-js/pull/1251
Look for testing / proof section at this PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/1251
> chore(payment): ADYEN-260 bump checkout-sdk version

- src/app/ui/alert/Alert.tsx
- src/app/ui/alert/__snapshots__/Alert.spec.tsx.snap
- Add attributes `role="alert"`, `aria-live="assertive"` to alert text.
- With these two attributes, a screen reader can announce error messages on Checkout page automatically and immediately.  [Checkout-6032](https://jira.bigcommerce.com/browse/Checkout-5928)
- `role="alert"` : https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role
- `aria-live="assertive"`: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
Tested on MAC's voice over. The alert message will be read out as soon as it appears.
Also, it is mentioned on [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) that using `role="alert"` and `aria-live="assertive"` together may cause double speaking on iOS. Can confirm …
> feat(checkout): CHECKOUT-6032 Assert error banners on checkout page

- package-lock.json
- package.json
- Bump checkout-sdk version to `1.187.1`
- To release: https://jira.bigcommerce.com/browse/PAYMENTS-7322 -  an incremental change to the PPSDK strategy (itself behind a WIP feature toggle)
> chore(payment) PAYMENTS-7322 bump checkout-sdk version

- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Add alias mapping for credit_card as card
Because method will change name from credit_card to card on Bigpay, both names will be keep to be able to merge without issues
[Demo](https://drive.google.com/file/d/1EmTIw2wTqmYpYERm_a4GIWqjivYbNlt6/view?usp=sharing)
https://github.com/bigcommerce/bigpay/pull/4051
https://github.com/bigcommerce/checkout-sdk-js/pull/1202
> fix(payment): INT-4489 cko add method supported 'card'

- src/app/payment/mapSubmitOrderErrorMessage.spec.ts
- src/app/payment/mapSubmitOrderErrorMessage.ts
For Ayden V2,  when a shopper clicks "Place order" without card details, UCO will provide a localised user-friendly message,  `An error occurred while processing your payment. Please try again`.
Before, the error message was `Unable to proceed because the payment step of checkout has not been initialized`, which was not for a shopper([CHECKOUT-6082](https://jira.bigcommerce.com/browse/CHECKOUT-6082)).
UCO payment step has a mechanism to catch and display any errors thrown by SDK at [Payment.tsx#L179](https://github.com/bigcommerce/checkout-js/blob/95dde2b82caf07ed99f44d4dc23514ee956274a5/src/app/payment/Payment.tsx#L179). The missing part here is mapping error type `not_initialized` to a localised message in `mapSubmitOrderErrorMessage.ts`. …
> fix(checkout): CHECKOUT-6082 localized message for the payment step initialization failure

- package-lock.json
- package.json
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/PaymentMethodType.ts
Display applepay in payment step of checkout
Support apple pay in checkout payment steps.
- Tests
- Screenshots
> feat(payment): CHECKOUT-6067 Display applepay in payment step of checkout

- src/app/locale/translations/de.json
- src/app/locale/translations/en.json
- src/app/locale/translations/fr.json
- src/app/locale/translations/it.json
- src/app/locale/translations/nl.json
- src/app/locale/translations/pt-BR.json
- src/app/locale/translations/pt.json
- src/app/locale/translations/sv.json
Error message change for error code- invalid_address
A generic message is shown in case of invalid billing address
For consistency changed in BigPay and BcApp:
https://github.com/bigcommerce/bigpay/pull/4573
https://github.com/bigcommerce/bigcommerce/pull/43614
Manual
> fix(payment): PAYMENTS-4915 Changing error message for invalid_address

- src/app/checkout/CheckoutStep.spec.tsx
- src/app/checkout/CheckoutStep.tsx
- src/app/checkout/CheckoutStepHeader.spec.tsx
- src/app/checkout/CheckoutStepHeader.tsx
- src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
Fix bug: [BOLT-77](https://jira.bigcommerce.com/browse/BOLT-77) Bolt checkout button doesn't appear on mobile
Because of the task: [https://jira.bigcommerce.com/browse/BOLT-77](https://jira.bigcommerce.com/browse/BOLT-77)
Before:
After:
Tests:
> fix(payment): BOLT-77 Fix the issue with store styling

- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.spec.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
- src/app/payment/paymentMethod/index.ts
When merchant changes display name in Control Panel, the display name doesn't show
Because we need to add an ability to chose what payment title will be shown on Checkout page
Manual tests
Unit tests
Tests:
Screenshots of the changes:
> feat(payment): BOLT-92 shows 'display name' value from method config

- src/app/payment/paymentMethod/CCAvenueMarsPaymentMethod.spec.tsx
Add CCAvenueMarsPaymentMethod missing code coverage
To Increase code coverage
@bigcommerce/apex-integrations
> test(payment): INT-4854 Increase CCAvenueMarsPaymentMethod code coverage

- src/app/payment/paymentMethod/BarclaycardPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/PaymentMethod.spec.tsx
Increase BarclaycardPaymentMethod code coverage
To increase code coverage
> test(payment): INT-4853 increase code coverage on BarclaycardPaymentMethod

- src/app/locale/translations/de.json
- src/app/locale/translations/en.json
- src/app/locale/translations/fr.json
- src/app/locale/translations/it.json
- src/app/locale/translations/nl.json
- src/app/locale/translations/pt-BR.json
- src/app/locale/translations/pt.json
- src/app/locale/translations/sv.json
- src/app/payment/PaymentSubmitButton.spec.tsx
- src/app/payment/PaymentSubmitButton.tsx
Changed PaymentSubmitButtonText for Bolt payment provider
Because of the task: https://jira.bigcommerce.com/browse/BOLT-95
Unit tests
Manual tests
Here is a screenshot:
> feat(payment): BOLT-95 changed PaymentSubmitButtonText for Bolt payment provider

- package-lock.json
- package.json
- Bump checkout-sdk version from `^1.196.0` to `^1.199.0`
- To release: https://github.com/bigcommerce/checkout-sdk-js/pull/1285 (the ability to cancel abandoned PPSDK redirects)
> chore(payment): PAYMENTS-7391 bump checkout-sdk

- src/app/ui/form/Form.tsx
...
Add a try... catch... to handle this error produced in Sentry - "Error:” 'block' member of ScrollIntoViewOptions 'center' is not a valid value for enumeration ScrollLogicalPosition.“ - https://sentry.io/organizations/bigcommerce/issues/2751428755/events/10bc9b4d64254fc79a96615bb7adca79/events/?cursor=0%3A0%3A1&project=1542560
This error began after - https://github.com/bigcommerce/checkout-js/pull/732/commits/d5455c92cdff412d3249bf075b4ed0d056f6629f
This error seems to occur in older versions of Chrome, Firefox, and Safari. I've been able to replicate the error in Firefox 57. The error does not replicate in Firefox 58. I could not replicate the issue on Safari 13.1.2.  The issue replicated once on 85.0.4103 but not after. 
3% - Chrome <= 85.0.4103 OR Firefox <= 57.0 OR Safari <= …
> fix(CHECKOUT) : CHECKOUT-5322 - Sentry CHECKOUT-JS-4VG

- package-lock.json
- package.json
- src/app/payment/paymentMethod/ApplePayPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/ApplePayPaymentMethod.tsx
- src/app/payment/paymentMethod/HostedPaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
Add apple pay payment method component
In order to complete payment via apple pay we need to add a component that is responsible for initializing the apple pay payment method.
- Screencast
https://user-images.githubusercontent.com/7134802/144144889-4f705c6d-6ae4-455e-b9f7-edc1f4fcea80.mov
> feat(payment): CHECKOUT-6066 Add apple pay payment method component

- src/app/payment/Payment.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Adding humm as payment method, specifying the logo, humm is a external payment method then we going to redirect the pay.
it's need it to support it when we want to pay.
> feat(payment): INT-4897 Humm - Show Humm as payment method

- package-lock.json
- package.json
Due to the release of https://jira.bigcommerce.com/browse/ADYEN-320
https://github.com/bigcommerce/checkout-sdk-js/pull/1298
> chore(checkout): ADYEN-320 bump sdk version

- src/app/shipping/shippingOption/StaticShippingOption.scss
Wrap the long descriptions of shipping methods.
Long texts in `ShippingOptionAdditionalDescription` component ([link](https://github.com/bigcommerce/checkout-js/blob/40e8b28cbdf55353e5887cb5267af8e85b83e926/src/app/shipping/shippingOption/ShippingOptionAdditionalDescription.tsx#L28
)) are breaking the checkout page now.
Before:
https://user-images.githubusercontent.com/88361607/144783655-7b5dcacf-dd9d-4470-a051-3bd8c57de43d.mov
After:
https://user-images.githubusercontent.com/88361607/144943746-ee6b3740-060d-48a4-9b7f-8a5930007817.mov
> fix(checkout): CHECKOUT-6215 Display long descriptions of shipping methods properly

- package-lock.json
- package.json
Bump up checkout-sdk-js version
To release the task: https://jira.bigcommerce.com/browse/BOLT-109
All tests and proofs available here: https://github.com/bigcommerce/checkout-sdk-js/pull/1304
> chore(payment): BOLT-109 bump up checkout-sdk-js version

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Populate onUnhandledError correctly to show up the error message we sent from the strategy when the payment method isn't available.
Digital River requested it because the shopper doesn't know what happened if the drop in element isn't rendered
https://github.com/bigcommerce/checkout-sdk-js/pull/1286
> feat(payment): INT-5000 DigitalRiver: populate onUnhandledError correctly

- package-lock.json
- package.json
Bump checkout-sdk to 1.205.0
To get the following changes released:
- https://github.com/bigcommerce/checkout-sdk-js/pull/1287
- https://github.com/bigcommerce/checkout-sdk-js/pull/1288
See videos on the above PRs
> chore(payment): INT-4893 INT-4926 Bump checkout-sdk

- src/app/locale/translations/en.json
- src/app/payment/mapSubmitOrderErrorMessage.spec.ts
- src/app/payment/mapSubmitOrderErrorMessage.ts
Add support to translate, if necessary, error messages from the execute step in the payment strategy
We need to translate the messages that are shown to customer to achieve a successful internationalization
@bigcommerce/apex-integrations
> feat(payment): INT-4893 Add translations for errors from SDK - Humm

- src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
- src/app/payment/paymentMethod/MolliePaymentMethod.tsx
[INT-5153](https://jira.bigcommerce.com/browse/INT-5153)
Dismiss trusted shipping address validation in Mollie
Every time there was a third payment with a previously save card this attempt failed.
Test coverage
QA test document can be checked in the following [link](https://docs.google.com/document/d/12bWdmuB7bDRei322Ii1VH6P1jQAk9tpK/edit?usp=sharing&ouid=101974547372968961334&rtpof=true&sd=true)
ping @bigcommerce/apex-integrations @bigcommerce/checkout
> fix(payment): INT-5153 Mollie: added card code validation

- src/app/billing/StaticBillingAddress.spec.tsx
- src/app/billing/StaticBillingAddress.tsx
[INT-5331](https://jira.bigcommerce.com/browse/INT-5331): Remove validation for Amazon Pay and all the time show an specific label
Amazon requested to use shipping address when billing address is empty, however the shipping address was displaying as billing address an address is provided. The `Managed by Amazon` legend should be displayed in all cases in the billing address space instead.
- https://github.com/bigcommerce/bigcommerce/pull/44369
> feat(payment): INT-5331 Remove validation for Amazon Pay and all the time show an specific label

- .circleci/config.yml
Update the node image, so Circle Ci can be back on track.
Circle Ci is not working now due to missing the proper node image.
> chore(checkout): CHECKOUT-0000 Update Node Image

- package-lock.json
- package.json
- src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
Replace Bolt single line payment component to the multi-field component
Because of task: [https://jira.bigcommerce.com/browse/BOLT-135](https://jira.bigcommerce.com/browse/BOLT-135)
Before:
After:
Tests:
From PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/1318](https://github.com/bigcommerce/checkout-sdk-js/pull/1318)
> feat(payment): BOLT-135 multi-field component

- src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
Added a reinitialize function when Google Pay payment is selected
So the wallet button works for changing the selected card when Google pay is selected
https://drive.google.com/file/d/1rsx-TU__hCeUxXce05YdYAGXLqXBP1D8/view?usp=sharing
> fix(payment): INT-4674 GooglePay: reinitialize payment on payment select

- package-lock.json
- package.json
- src/app/checkout/index.ts
- src/app/customer/CheckoutButtonList.tsx
- src/app/customer/customWalletButton/ApplePayButton.spec.tsx
- src/app/customer/customWalletButton/ApplePayButton.tsx
- src/app/customer/customWalletButton/index.ts
Add apple pay wallet method component
In order to complete payment via apple pay as a wallet button, we need to create a component to render apple pay with it's extra config.
- Screencast
- Test
https://user-images.githubusercontent.com/7134802/146874158-8d39a584-d572-4f9f-b4e5-77117ee67673.mov
> feat(payment): CHECKOUT-6070 Add applepay button component

- src/app/locale/translations/de.json
- src/app/locale/translations/en.json
- src/app/locale/translations/es-MX.json
- src/app/locale/translations/es.json
- src/app/locale/translations/fr.json
- src/app/locale/translations/it.json
- src/app/locale/translations/nl.json
- src/app/locale/translations/pt-BR.json
- src/app/locale/translations/pt.json
- src/app/locale/translations/sv.json
- src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
When DR dropin doesn't load because zip code on shipping step is invalid, for the error displayed to the shopper, remove the word "payment" in the title of the error
Digital River requested
Before: 
After: 
> feat(payment): INT-5460 Remove the word Payment from error title

- src/app/order/OrderStatus.tsx
- Add option to display OXXO Ticket and Boleto Ticket links on confirmation pago for Stripe UPE
- Display the link for the OXXO ticket and Boleto ticket to the shopper
> INT-5036 Enable to show oxxo ticket and boleto ticket link for StripeUPE

- package-lock.json
- package.json
- src/app/locale/translations/en.json
- src/app/order/OrderStatus.spec.tsx
- src/app/order/OrderStatus.tsx
- src/app/order/orders.mock.ts
Display mandate reference ID  as text only when mandate url is empty.
Also remove the part of the code that searched for the mandate text and used it to build the mandate text, instead use the new method Id to use it as a key and map it to the correct mandate text.
So the mandate link does not redirect to a 404 page.
Also the translation of the mandate text is done properly and not built into the code.
[Demo Videos](https://drive.google.com/drive/folders/1VcyX_5nMpL3Ri0nMPOcgDqWWBq0Kmzvx?usp=sharing)
https://github.com/bigcommerce/bigcommerce/pull/42364
https://github.com/bigcommerce/bigpay/pull/4234
https://github.com/bigcommerce/checkout-sdk-js/pull/1220
1) https://github.com/bigcommerce/checkout-sdk-js/pull/1220
2) https://github.com/bigcommerce/bigcommerce/pull/42364 …
> feat(order): INT-4776 Create a new field for the mandate reference ID

- src/app/address/AddressForm.spec.tsx
- src/app/address/AddressForm.tsx
This PR will restore a country dropdown menu's instructional text placeholder.
In the previous PR, [CHECKOUT-6081](https://github.com/bigcommerce/checkout-js/pull/729), we have used the default value as an instructional message for a text input field and a dropdown menu.
It turns out that this does not work well for a dropdown menu, particularly a country menu. Because `checkout-sdk-js` updates the default value of the `countryCode` field every time a user makes a selection. 
https://user-images.githubusercontent.com/88361607/155430516-c348ce48-0d9d-4dc0-b9d8-b0ae64b85b69.mov
There's also a new dropdown menu unit test.
> fix(checkout): CHECKOUT-6334 Restore Instructional Text in Country Dropdown Menu

- src/app/checkout/CheckoutStep.spec.tsx
- src/app/checkout/CheckoutStep.tsx
Always return `<CSStransition>` to avoid rerendering the payment step when the window is resizing.
Previously, when the window width is smaller than `968px`, `checkout-js` renders `<div>`; when the window gets bigger, `checkout-js` renders  `<CSStransition>`. 
This results in the loss of information entered for the payment step. This bugfix will always return `<CSStransition>` while keeping the same logic that we only present CSS effects on larger screens.
Related doc: `enter` and `exit` control whether the `<CSStransition>` displays animations ([link](http://reactcommunity.org/react-transition-group/transition#Transition-prop-enter)).
https://user-images.githubusercontent.com/88361607/155924316-40d4a19b-66bb-4c8d-8f16-ab9620937061.mov
> fix(checkout): CHECKOUT-6207 entered information lost after window resizing

- src/app/payment/payment-methods.mock.ts
- src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.spec.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
- src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Different naming for PPCP on checkout page
According to task https://jira.bigcommerce.com/browse/PAYPAL-1284
> feat(payment): PAYPAL-1284 different naming for PPCP on checkout page

- src/app/formFields/getFormFieldsValidationSchema.ts
Trim address field values before validating
At the moment we don't trim values entered in required string fields for shipping form. So we need to trim the input field for whitespaces before validating.
- Screenshot
Before
After
> fix(shipping): CHECKOUT-6370 Trim address field value before validating

- package-lock.json
- package.json
What?
Bump checkout-sdk.
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1373 out
CircleCI + see the videos on above PR
> chore(checkout): CHECKOUT-6125 Bump checkout-sdk v1.227.2

- src/app/locale/translations/en.json
- src/app/payment/paymentMethod/OpyPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/OpyPaymentMethod.tsx
- src/app/payment/paymentMethod/__snapshots__/OpyPaymentMethod.spec.tsx.snap
- Display a localized error message for an invalid cart error.
- Also, fixes the widget's overflow. 😁
To display a custom error message based on location. The Openpay team wants us to use the following messages:
- For AU/UK/NZ: "Cart price is different to Openpay plan amount."
- For US merchants: "Cart price is different to Opy plan amount."
_Before:_
_Now:_
_Before:_
_Now:_
👉 https://github.com/bigcommerce/checkout-sdk-js/pull/1367
> fix(payment): INT-5645 Openpay: Localized message for invalid cart error

- package-lock.json
- package.json
Bump checkout-sdk.
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1369 released.
Please refer to video proof on the mentioned PR.
@bigcommerce/checkout @bigcommerce/checkout @bigcommerce/apex-integrations
> chore(checkout): INT-5619 Bump checkout-sdk v1.230.0

- src/app/common/utility/index.ts
- src/app/common/utility/is-apple-pay-window.ts
- src/app/customer/CheckoutButtonList.tsx
- src/app/customer/customWalletButton/ApplePayButton.tsx
- Add check before rendering component if apple pay is supported in the browser or not
- Bump checkout-sdk to get apple pay shipping fix
If a browser doesn't support apple pay, at the moment there is an empty container rendered, therefore return nothing from the component if apple pay is not supported 
Also bump SDK https://github.com/bigcommerce/checkout-sdk-js/commit/e79f27b7727222b155677b84541926aff4859529
- Tests
> fix(payment): CHECKOUT-6549 Add check if window has apple pay supported

- src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
Added branding name logic for BT
According to task https://jira.bigcommerce.com/browse/PAYPAL-1298
> feat(payment): PAYPAL-1298 added branding names logic for BT

- src/app/locale/translations/en.json
- src/app/payment/PaymentSubmitButton.spec.tsx
- src/app/payment/PaymentSubmitButton.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
Fixed branding for BT on checkout page
According to task https://jira.bigcommerce.com/browse/PAYPAL-1298
> feat(payment): PAYPAL-1298 fixed branding on checkout page

- package-lock.json
- package.json
- src/app/payment/Payment.tsx
Add Checkout.com's GooglePay to the list of providers that require a redirect but are not a Hosted Payment Method.
So the Prompt for leaving the page does not interfere with the offsite redirection that Google Pay requires.
[Demo Video](https://drive.google.com/file/d/1FTuDYjBL7YUgdXZWVCeLN4lxuASvZEqz/view?usp=sharing)
> fix(checkout): INT-5543 [CKO] Update to 3DS on Google Pay

- package-lock.json
- package.json
- src/app/shipping/MultiShippingForm.tsx
- src/app/shipping/Shipping.tsx
As above
As part of refactoring for MLI we have updated the interface for consignment create to replace shippingAddress property with address property. 
[SDK PR ](https://github.com/bigcommerce/checkout-sdk-js/pull/1386)
- Tests
- Screencast
https://user-images.githubusercontent.com/7134802/162135711-4dd6327b-4607-479d-8580-e515c3c25967.mov
> feat(shipping): CHECKOUT-6544 Update consignment methods to use address

- package-lock.json
- package.json
Change the card number data type to avoid skipping digits after converting a string to a number
Because of task: [https://jira.bigcommerce.com/browse/BOLT-203](https://jira.bigcommerce.com/browse/BOLT-203)
https://user-images.githubusercontent.com/9430298/161246306-b2950358-ba05-457c-8677-6fc8878d64ee.mov
> fix(payment): BOLT-203 Bump checkout-sdk v1.237.1

- src/app/payment/Payment.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
Add MPGS as a payment method Id and add it to the providers that require a redirect but are not a Hosted Payment Method.
So a redirection can happen without triggering a warning when using MPGS as payment method
Demo Video:
https://drive.google.com/file/d/1RKs3W7-oRx5pP0XAa9JCX_VxqcWyEQpQ/view?usp=sharing
https://github.com/bigcommerce/checkout-sdk-js/pull/1359
https://github.com/bigcommerce/bigcommerce/pull/45233
https://github.com/bigcommerce/bigpay/pull/5055
> feat(checkout): INT-5126 [MPGS] Add 3ds support for MPGS

- package-lock.json
- package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1402 out
CircleCI + see the videos on above PR
> chore(checkout): CHECKOUT-6563 Bump checkout-sdk v1.237.3

- .circleci/config.yml
Update circle config for sentry
We always pull the latest sentry CLI. There is an update for cli where the default behaviour will be to rewrite source maps before uploading.
- Circle
> chore(common): CHECKOUT-0000 Update circle config for sentry

- src/app/shipping/hasSelectedShippingOptions.spec.ts
- src/app/shipping/hasSelectedShippingOptions.ts
Hello, during testing of our checkout we noticed that sometimes we could progress through checkout when there wasn't a shipping method selected.
On investigation, the checkout state persists the selected shipping method across address updates. Our configuration has different shipping options for different countries, and some countries with no options. We would expect these address to shipping method combinations to be recognised as invalid, and for the customer to be unable to progress.
Currently, the customer will be able to progress beyond the shipping address stage. However, the final checkout submit will fail due to an invalid shipping option being selected. A local error is a better experience for the customer.
Additional tests for hasSelectedShippingOptions.spec.ts. These fail …
> fix(shipping): CHECKOUT-6607 Only mark the currently selected shipping option as valid if it is available for the current address

- package-lock.json
- package.json
- src/app/payment/paymentMethod/PPSDKPaymentMethod/NoUI.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/PPSDKPaymentMethod.tsx
- src/app/payment/paymentMethod/PPSDKPaymentMethod/initializationComponentMap.ts
When a PPSDK card payment method is selected, we want the UI to load the PPSDK hosted fields credit card view of PPSDK that uses its own strategy instead of the generic `CreditCardPaymentStrategy`. 
To allow handling of different credit card payment features that will be available via PPSDK, like human verification, 3D security check, vaulting credit cards, save as default payment method.
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1396
Unit tests
Screenshots
**Hosted form is rendered when PPSDK integration type experiment is turned on:**
**Method returns from bcapp as PAYMENT_TYPE_SDK:**
**The new payment endpoint is used:**
> feat(payment): PAYMENTS-7403 Add PPSDK Credit Card payment method UI

- jest.config.js
Configure Jest to Ignore the `tests` folder which is suppose to be run by `Playwright`.
Related doc: https://jestjs.io/docs/configuration#testpathignorepatterns-arraystring
> testPathIgnorePatterns [array<string>]
>
> An array of regexp pattern strings that are matched against all test paths before executing the test. If the test path matches any of the patterns, it will be skipped.
Unblock `checkout-js` CI pipeline.
CI checks of this PR.
> feat(checkout): CHECKOUT-6340 Configure Jest to Ignore Integration Tests

- package-lock.json
- package.json
To get https://github.com/bigcommerce/checkout-sdk-js/pull/1425 out
CircleCI + see the PR above.
> chore(checkout): CHECKOUT-6631 Bump checkout-js v1.242.2

- README.md
Update `Node` and `npm` requirements documentation.
The current description is inaccurate and out of date, which may confuse developers.
> docs(checkout): CHECKOUT-0000 Update requirements in README

- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Remove startCase method of Lodash to avoid the formatting of payment method names.
According with the last call with Mollie's team, we shouldn't modify the payment method name in any way, we need to trust the mollie api source.
> feat(payment): INT-5904 Remove formatting for payment method when Mollie

- src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
Gets the store theme checkout styles to change the appearance of the Stripe UPE
To have the payment element style match with the store style
https://github.com/bigcommerce/checkout-sdk-js/pull/1382
> feat(payment): INT-5060 Stripe UPE Look and Feel - Get styles from store theme styles

- package-lock.json
- package.json
- src/app/checkout/Checkout.tsx
- src/app/config/config.mock.ts
Allows store admin to enable/disable "Billing Address same as Shipping Address" check when a shopper is using checkout process. This can be checked within the admin panel of the store under the Checkout Settings.
Store admin suggestion to BC as the customer would sometimes skip or ignore the check where it could be incorrect
8-7316e97b9f82.png)
ping @bigcommerce/checkout
> feat(checkout): CHECKOUT-6643 add checkoutBillingSameAsShipping check for checkout

- src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
Added onError so subscriber errors can be thrown
So the customer sees error messages if adding coupons makes the order have an unsupported amount for stripe methods
https://drive.google.com/file/d/1AAsEr5KsNoS6WgeY_fAvR-z43j6b_TSh/view?usp=sharing
https://github.com/bigcommerce/checkout-sdk-js/pull/1385
https://github.com/bigcommerce/bigcommerce/pull/45506
https://github.com/bigcommerce/bigpay/pull/5145
https://github.com/bigcommerce/bigpay-client-php/pull/244
> feat(payment): INT-5754 Stripe UPE Added onError to initialize options

- package-lock.json
- package.json
To release the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1465
Unit tests
> chore(payment): PAYPAL-1465 bump checkout-sdk version

- src/app/locale/translations/da.json
- src/app/locale/translations/de.json
- src/app/locale/translations/en.json
- src/app/locale/translations/es-419.json
- src/app/locale/translations/es-AR.json
- src/app/locale/translations/es-CL.json
- src/app/locale/translations/es-CO.json
- src/app/locale/translations/es-MX.json
- src/app/locale/translations/es-PE.json
- src/app/locale/translations/es.json
- src/app/locale/translations/fr.json
- src/app/locale/translations/it.json
- src/app/locale/translations/nl.json
- src/app/locale/translations/pt-BR.json
- src/app/locale/translations/pt.json
- src/app/locale/translations/sv.json
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
- src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.spec.tsx
- src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
adds worldpay as payment method in the checkout and a div tag later we could add 3ds section
we need to allow pay as a credit card
https://github.com/bigcommerce/checkout-sdk-js/pull/1424
> feat(payment): INT-5481 Worldpay component

- src/app/checkout/Checkout.tsx
Remove `||` check for billing same as shipping flag
The `||` check disrespects the value of the store setting and always defaults to true.
- Tests
> fix(shipping): CHECKOUT-6643 Remove or check for billingSameAsShipping Flag

- package-lock.json
- package.json
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1466
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1457
> feat(payment): PAYPAL-1466 bump checkout-sdk-js version

- package-lock.json
- package.json
According to task [CHECKOUT-6679](https://bigcommercecloud.atlassian.net/browse/CHECKOUT-6679)
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1457
> chore(checkout): CHECKOUT-6703 bump checkout-sdk-js version 1.248.0

- package-lock.json
- package.json
To update the checkout-sdk-js verion that include the fix of the next PR
checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/1459
> feat(payment): INT-6055 bump checkout-sdk-js version

- src/app/ui/icon/IconCardDinersClub.tsx
Diners Club text was incorrectly spelt as Dinners Club. Updated text to Diners
Updated IconCardDinersClub.tsx to correct spelling from Dinners to Diners
The spelling was incorrect.
Text Label change only
> fix(payment): CHECKOUT-0000 Update Diners IconCardDinersClub.tsx spelling mistake

- src/app/cart/CartSummary.spec.tsx
- src/app/cart/CartSummary.tsx
- src/app/cart/__snapshots__/CartSummary.spec.tsx.snap
Remove the edit cart button on the checkout page for buy now carts
Shoppers shouldn't need to edit the cart if they use the buy now button for items
> feat(checkout): CHECKOUT-6595 remove the edit cart button for buy now carts

- src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
Renders elements needed to get optimizedCheckout styles
It's failing because renderContainer() function sets the display to none when certain conditions are met, and this elements need to always be rendered
> fix(payment): INT-6061 StripeUPE Vaulting selecting new card is failing

- package-lock.json
- package.json
Bump checkout-sdk-js version to 1.254.0 to apply [those changes](https://github.com/bigcommerce/checkout-sdk-js/commit/bfedf7c42dd913fc5f155425d82d678880950862).
To support human verification for PPSDK card payment.
Unit tests.
Manual tests.
> feat(payment): PAYMENTS-7524 Bump checkout-sdk version to 1.254.0

- package-lock.json
- package.json
- src/app/locale/translations/en.json
- src/app/payment/PaymentSubmitButton.tsx
- src/app/payment/paymentMethod/PaymentMethod.tsx
- src/app/payment/paymentMethod/PaymentMethodId.ts
- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/PaymentMethodType.ts
A separate module was created for the Venmo payment method on the backend side. The common button strategy for all PPCP SPBs has now been expanded. In the future, a separate strategy will be created for each spb, including for Venmo. These tasks are already planned.
We need a module for the Venmo payment method to create separate button strategy for it
https://github.com/bigcommerce/bigpay/pull/5495
https://github.com/bigcommerce/bigcommerce/pull/46631
https://github.com/bigcommerce/bigpay-client-js/pull/132
https://github.com/bigcommerce/checkout-sdk-js/pull/1458
New approach
Old approach
> feat(payment): PAYPAL-1487 Add paypal-venmo payment method

- package-lock.json
- package.json
To release checkout sdk changes due the task: 
https://bigcommercecloud.atlassian.net/browse/PAYPAL-1508
Unit tests
Manual tests
> chore(payment): PAYPAL-1508 bump checkout-sdk version

- src/app/order/OrderSummaryDrawer.spec.tsx
- src/app/order/OrderSummaryDrawer.tsx
- src/app/ui/modal/Modal.tsx
- src/app/ui/modal/ModalTrigger.spec.tsx
- src/app/ui/modal/ModalTrigger.tsx
...
When screen width is narrowed, it moves to the cart summary to the bottom of the page. For accessibility purposes, this should be accessible with the 'tab' key, and the modal should display when clicking the "enter" key.  
...
For better accessibility for screen reader users
https://bigcommercecloud.atlassian.net/browse/CHECKOUT-6653
Before:
(cannot tab to modal trigger)
https://user-images.githubusercontent.com/5630999/171290143-94c10a7e-e581-4543-8c73-fb906fc89442.mp4
After: 
(tab to modal trigger, press enter to open modal)
https://user-images.githubusercontent.com/5630999/171289101-00569788-6324-41e0-8da4-cd44ad311d6e.mp4
...
POC for now (5/25) , will need to update this to only use the enter key to bring up the modal. With these immediate changes it becomes accessible via the tab …
> feat(checkout): CHECKOUT-6653 make cart drawer interactable via keyboard

- package.json
- scripts/webpack/get-next-version.js
Fix issue with creating alpha prerelease
As part of webpack upgrade, alpha prerelease is broken.  Which is an important part of dev cycle. Hence fix it so we can test changes in functional tests before releasing code.
https://webpack.js.org/guides/environment-variables/
- Screenshot
> fix(common): CHECKOUT-6674 Fix issue with alpha prerelease

- package-lock.json
- package.json
Release the change of checkout SDK
https://github.com/bigcommerce/checkout-sdk-js/pull/1477
> chore(checkout): CHECKOUT-6765 bump checkout-sdk-js version 1.259.0

- src/app/checkout/Checkout.tsx
- src/app/checkout/navigateToOrderConfirmation.spec.tsx
- src/app/checkout/navigateToOrderConfirmation.tsx
Add buy now cart experiment to wrap up the related changes.
To control the risk of rolling out buy now cart.
- Circle
- When `CHECKOUT-3190.enable_buy_now_cart` is on and a shopper is signed-in, the order confirmation page will be `/checkout/order-confirmation/:id/`.
https://user-images.githubusercontent.com/88361607/175231095-613295b7-8690-4fdd-b034-fd6400fad4df.mov
> feat(checkout): CHECKOUT-6711 Add buy now cart experiment

- src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- src/app/payment/paymentMethod/PaymentMethodType.ts
- src/scss/components/checkout/paymentProvider/_paymentProvider.scss
ADYEN-497 Googlepay icon fix
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-497
And added fix for the font weight https://bigcommercecloud.atlassian.net/browse/ADYEN-434
Before fix:
After fix:
> fix(checkout): ADYEN-497 Googlepay icon fix

- package.json
Use nx to build `checkout-js`.
Improve building efficiency.
CI.
> feat(checkout): CHECKOUT-6269 Use nx to run build

- .gitignore
- package.json
- packages/core/src/app/address/googleAutocomplete/AddressSelector.spec.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelector.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteResult.mock.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteTypes.ts
Fix issue with google address auto complete
As of now if an address with a subpremise is returned we don't map it to the shipping address form. Hence we need to add subpremise to address mapper that can place the form value correctly.
- Circle
- Screencast
https://user-images.githubusercontent.com/7134802/177555440-d3a97b46-7cf9-46c7-a5f5-98ebfdd9e8f7.mov
> fix(shipping): CHECKOUT-6773 Fix bug with address auto complete

- package-lock.json
- package.json
Release the change: https://github.com/bigcommerce/checkout-sdk-js/releases/tag/v1.265.0
> chore(checkout): INT-6276 bump checkout-sdk-js version 1.265.0

- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- packages/core/src/scss/components/bigcommerce/credit-card-types/_credit-card-types.scss
- packages/core/src/scss/components/checkout/checklist/_checklist.scss
- packages/core/src/scss/components/checkout/paymentProvider/_paymentProvider.scss
- packages/core/src/scss/settings/bigcommerce/credit-card-types/_settings.scss
- packages/core/src/scss/settings/checkout/checklist/_settings.scss
Fix up alignment for payment logos
The credit card icons in the payment step are misaligned when there are many icons. This is creating a poor shopper experience at the checkout. Merchants have reported that this UX is underwhelming.
> fix(checkout): CHECKOUT-6756 fix up alignment for paymentProviders

- packages/core/src/scss/settings/checkout/customer/_settings.scss
Setting margin-top to 0 and removing the `$customerView-actions-marginTop--large` variable since it will no longer be used.
Users with low vision who require zoom in order to view page content will have the sign out button overlap content on the checkout page.
Before:
After:
I am not sure that this is the best way to resolve this. We could add more breakpoints but I did not see `$customerView-actions-marginTop--large` being used anywhere else in checkout.
> fix(checkout): CHECKOUT-6657 Ensure pages reflow without requiring two-dimensional scrolling without loss of  content or functionality

- package-lock.json
- package.json
Bump checkout sdk version.
PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/1497](https://github.com/bigcommerce/checkout-sdk-js/pull/1497)
Because of task: https://bigcommercecloud.atlassian.net/browse/BOLT-255
[https://github.com/bigcommerce/checkout-sdk-js/pull/1497](https://github.com/bigcommerce/checkout-sdk-js/pull/1497)
> feat(payment): BOLT-255 bump checkout sdk version

- playwright.config.ts
- tests/fixture/pageObject/playwright/PlaywrightHelper.ts
Change local e2e testing environment entry point from `http://localhost:port` to `http://localhost:port/checkout`.
The local testing environment is more in line with a dev store environment.
Checkout page always has a path name, `checkout`.
https://user-images.githubusercontent.com/88361607/179891322-fd310ea4-da9f-4580-b18a-86dfa19ac375.mov
> feat(checkout): CHECKOUT-0000 Update e2e tests local env entry point

- package-lock.json
- package.json
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1567
Unit tests
Manual tests
CI tests
> chore(payment): PAYPAL-1567 bump checkout-sdk version

- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- packages/core/src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Fixed styles for the payment provider title.
Markup breaks when there are multiple rows of accepted cards 
Markup breaks when there are multiple rows of accepted cards 
before
after
> fix(checkout): ADYEN-0000 fixed payment provider title css

- package-lock.json
- package.json
Bump checkout-sdk release to 1.272.1
To apply this fix: https://github.com/bigcommerce/checkout-sdk-js/pull/1536
Unit tests
> chore(payment): PAYMENTS-8045 Bump Checkout SDK release

- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
Fixed storeCredit checkbox behaviour
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1445
https://user-images.githubusercontent.com/56301104/180470438-a24fd5a7-6158-4433-bd2a-d3f4bb746d7f.mov
> feat(payment): PAYPAL-1445 fixed storeCredit checkbox

- packages/core/src/app/customer/__snapshots__/Customer.spec.tsx.snap
- packages/core/src/app/customer/__snapshots__/GuestForm.spec.tsx.snap
- packages/core/src/app/customer/__snapshots__/LoginForm.spec.tsx.snap
- packages/core/src/app/guestSignup/__snapshots__/GuestSignUpForm.spec.tsx.snap
- packages/core/src/app/payment/creditCard/__snapshots__/CreditCardFieldset.spec.tsx.snap
- packages/core/src/app/ui/form/CheckboxFormField.tsx
- packages/core/src/app/ui/form/CheckboxGroupFormField.tsx
- packages/core/src/app/ui/form/DynamicFormField.tsx
- packages/core/src/app/ui/form/FormField.tsx
- packages/core/src/app/ui/form/FormFieldError.tsx
Input fields should be associated with their errors for the purposes of accessibility / screen readers. This will ensure that errors are re-stated to the user as they tab through the input fields. This will also ensure that errors are read to the user initially.
...
https://bigcommercecloud.atlassian.net/browse/CHECKOUT-6655
...
Before:
https://user-images.githubusercontent.com/5630999/180852211-6b424db3-7c81-4918-b65a-f6e6b4a15df5.mp4
After:
https://user-images.githubusercontent.com/5630999/180852250-e163d8b4-9991-41e8-9cb7-e8282786bed1.mp4
Previously similar changes had to be reverted - https://bigcommerce.slack.com/archives/C5370C9PH/p1656376812564639 - Unable to clear element that cannot be edited: <label id="countryCodeInput" class="form-label optimizedCheckout-form-label">
Deploying …
> feat(checkout): CHECKOUT-6655 Make Screen reader say each error

- packages/core/auto-export.config.json
- packages/workspace-tools/src/generators/auto-export/__fixtures__/tsconfig.json
- packages/workspace-tools/src/generators/auto-export/__snapshots__/auto-export.spec.ts.snap
- packages/workspace-tools/src/generators/auto-export/auto-export-config.ts
- packages/workspace-tools/src/generators/auto-export/auto-export.spec.ts
- packages/workspace-tools/src/generators/auto-export/auto-export.ts
- packages/workspace-tools/src/generators/auto-export/generator.ts
- packages/workspace-tools/src/generators/auto-export/is-auto-export-config.ts
Use package name rather than relative path in generated files.
To conform with the import rules.
**Before**
```ts
export { ApplePayPaymentMethod } from '../../../../../apple-pay-integration/src';
```
**After**
```ts
export { ApplePayPaymentMethod } from '@bigcommerce/checkout-js/apple-pay-integration';
```
> CHECKOUT-6781: Use package name rather than relative path in generated files

- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Add images between list for payments providers
Display the payment method’s logo next the payment method radio selector label for the following payment methods
> feat(payment): STRIPE-82 Add code to show images on the list

- packages/core/src/app/payment/Payment.tsx
- packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Remove unecessary code to pay
the iframe is going to be insert using sdk code
https://drive.google.com/file/d/1zfe8vvwITn2uoZ-RKOjXuabQcnK2fpcf/view?usp=sharing
> feat(payment): INT-6115 Worldpay - remove unnecessary iframe

- package-lock.json
- package.json
Bump checkout-sdk from [version 1.274.0](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#12740-2022-08-08) to [version 1.278.0](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#12780-2022-08-12).
To release:
- https://github.com/bigcommerce/checkout-sdk-js/pull/1489
- https://github.com/bigcommerce/checkout-sdk-js/pull/1491
- https://github.com/bigcommerce/checkout-sdk-js/pull/1502
- https://github.com/bigcommerce/checkout-sdk-js/pull/1521
- https://github.com/bigcommerce/checkout-sdk-js/pull/1540
- https://github.com/bigcommerce/checkout-sdk-js/pull/1541
- https://github.com/bigcommerce/checkout-sdk-js/pull/1552
- https://github.com/bigcommerce/checkout-sdk-js/pull/1556
CircleCI + testing section on the above PRs
> chore(common): CHECKOUT-6855 INT-6023 INT-6115 INT-6128 STRF-9829 Bump checkout-sdk

- tests/fixture/StoreUrlHelper.ts
- tests/fixture/index.ts
- tests/fixture/pageObject/Checkout.ts
- tests/fixture/pageObject/playwright/PlaywrightHelper.ts
- tests/fixture/pageObject/playwright/PollyObject.ts
- tests/fixture/pagePreset/ApiRequestsSender.ts
- tests/fixture/pagePreset/CustomerStepAsGuest.ts
- tests/fixture/pagePreset/PaymentStepAsGuest.ts
- tests/fixture/pagePreset/UseAUD.ts
- tests/har/sample-Bigpay-Test-Payment-Provider_3530407662/recording.har
- tests/sampleTests/Afterpay.spec.ts
- tests/sampleTests/BigpayTestPaymentProvider.spec.ts
- tests/sampleTests/GooglePayInCustomerStep.spec.ts
- tests/sampleTests/template.ts
- Add `STOREURL` as an env variable, eliminating the need to hardcode `storeUrl` in a test file.
- Add a `getStoreUrl()` helper.
- All HAR files now record the same generic store URL.
- As a benefit of removing `storeUrl` from a test, the template becomes lighter.
```
test.describe('xxxxxxxxxxxxxxxxxxxxxxx', () => {
test('xxxxxxxxxxxxxxxxxxxxxxx', async ({assertions, checkout, page}) => {
// Testing environment setup
await checkout.use(new PaymentStepAsGuestPreset());
await checkout.start('name of the HAR file, which can be reused');
// Playwright actions
await checkout.goto();
// await page.locator('text=Test Payment ProviderVisaAmexMaster').click();
await checkout.placeOrder();
// Assertions
await assertions.shouldSeeOrderConfirmation();
});
});
```
`storeUrl` is unnecessary data stored …
> feat(checkout): CHECKOUT-6896 Add STOREURL as env variable

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
Fix issue with an error modal being displayed if an element is detached
At the moment we have an error modal displayed while a user transitions while hosted payment form is being loaded step to another step in checkout. 
Instead of showing the error modal and blocking the UX we can log the error using errorLogger.
- Circle
https://user-images.githubusercontent.com/7134802/184576337-236008ac-62aa-4906-8f43-7e9ef6b94763.mov
> fix(payment): CHECKOUT-5889 Fix issue with element detach modal

- packages/apple-pay-integration/src/ApplePayPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodV2.tsx
- packages/core/src/app/payment/resolvePaymentMethod.ts
- packages/payment-integration-api/src/PaymentMethodResolveId.ts
- packages/payment-integration-api/src/index.ts
Export `PaymentMethodResolveId` through payment integration API package.
So it can be referenced by payment integration packages and core.
CircleCI
> CHECKOUT-6899: Export PaymentMethodResolveId through payment integration API package

- packages/apple-pay-integration/src/ApplePayPaymentMethod.spec.tsx
- packages/apple-pay-integration/src/paymentMethods.mock.ts
- packages/payment-integration-api/src/index.ts
Move mocks out of payment integration API package.
Mocks used in tests should either belong to method-specific packages or exported from a "test utils" package.
CircleCI
> CHECKOUT-6899: Move mocks out of payment integration API package

- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/payment/paymentMethod/StripePaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/StripePaymentMethod.tsx
Alteration of error message when stripe 3DS auth fails
To give more information to the user about the failure
@bigcommerce/checkout 
https://github.com/bigcommerce/checkout-sdk-js/pull/1488
> Fix(payment): STRIPE-53 Give more information on payment authentication with 3ds failure error message

- scripts/webpack/get-loader-packages.js
- scripts/webpack/index.js
- webpack.config.js
Add script to derive for webpack configuration, and reduce overhead when creating a new package
- package alias mapping
- ts loader includes
At the moment when adding a new package a developer has to update webpack config file, add a script to automate this process. Reducing package creation overhead
- circle
> chore(common): CHECKOUT-000 Add script to derive package list and aliases

- packages/core/src/app/locale/translations/da.json
- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/locale/translations/es-419.json
- packages/core/src/app/locale/translations/es-AR.json
- packages/core/src/app/locale/translations/es-CL.json
- packages/core/src/app/locale/translations/es-CO.json
- packages/core/src/app/locale/translations/es-PE.json
- packages/core/src/app/locale/translations/no.json
- packages/core/src/app/payment/PaymentSubmitButton.spec.tsx
- packages/core/src/app/payment/PaymentSubmitButton.tsx
- Removed unnecessary Braintree Venmo logic from PaymentSubmitButton component;
- added `paypal_venmo_continue_action` translations for other languages;
Because we don't need it anymore.
Unit tests
> feat(payment): PAYPAL-1613 removed unnecessary Braintree Venmo logic from PaymentSubmitButton component

- package-lock.json
- package.json
- packages/core/src/app/locale/translations/da.json
- packages/core/src/app/locale/translations/de.json
- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/locale/translations/es-419.json
- packages/core/src/app/locale/translations/es-AR.json
- packages/core/src/app/locale/translations/es-CL.json
- packages/core/src/app/locale/translations/es-CO.json
- packages/core/src/app/locale/translations/es-MX.json
- packages/core/src/app/locale/translations/es-PE.json
- packages/core/src/app/locale/translations/es.json
- packages/core/src/app/locale/translations/fr.json
- packages/core/src/app/locale/translations/it.json
- packages/core/src/app/locale/translations/nl.json
- packages/core/src/app/locale/translations/no.json
- packages/core/src/app/locale/translations/pt-BR.json
- packages/core/src/app/locale/translations/pt.json
- packages/core/src/app/locale/translations/sv.json
- packages/core/src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/MolliePaymentMethod.tsx
I want to hide any Klarna Pay Later and Klarna Slice It from shoppers if their cart contains digital products
So that I can prevent shoppers from trying to pay for an ineligible cart and getting an error
Before
https://user-images.githubusercontent.com/104527753/180102690-63e27651-3e1d-466b-bc3d-24f71aaf2b78.mov
After
https://user-images.githubusercontent.com/104527753/180099759-592b8826-6aea-4258-a53c-4835332259d4.mov
Dependency of 
- https://github.com/bigcommerce/checkout-js/pull/969
> fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products

- packages/core/src/app/checkout/Checkout.spec.tsx
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/mapToCheckoutProps.ts
- packages/core/src/app/config/config.mock.ts
- https://github.com/bigcommerce/checkout-sdk-js/pull/1521
When a user clicks the "Sign Out" button during checkout while the "HidePriceFromGuests" configuration is turned on, they will be redirected to the cart page.
**STRF-9829** will move the "Hide pricing for guests" functionality into store/channel configuration. While prices are restricted to login, we should redirect a user to the cart page if the log out during the checkout. This ensures stability and will prevent prices from being exposed if a customer signs out during the checkout.
Typically, a merchant would use the checkout setting to require an account. However, if prices should be hidden for guests, we should redirect back to the cart page on sign-out to ensure prices are not visible to the guest.
- Added Unit Tests
- Video …
> feat(checkout): STRF-9829 Redirect to cart on sign-out if prices are hidden from guests

- package-lock.json
- package.json
Bump up checkout sdk js version
To release the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1537
Unit tests
Manual tests
> chore(payment): PAYPAL-1537 bump up checkout sdk js version

- packages/core/src/app/shipping/StaticConsignment.tsx
- packages/core/src/app/shipping/__snapshots__/StaticConsignment.spec.tsx.snap
- packages/core/src/app/shipping/shippingOption/StaticShippingOption.scss
Make the shipping address and the shipping method separate.
Currently, shipping method is appended at the end of the address. This makes it hard for shoppers to quickly identify it. We want the checkout flow to be less cluttered.
Before:
After:
> feat(checkout): CHECKOUT-6851 Separate shipping option from address

- packages/core/src/app/shipping/StaticConsignment.scss
- packages/core/src/app/shipping/StaticConsignment.tsx
- packages/core/src/app/shipping/__snapshots__/StaticConsignment.spec.tsx.snap
Improve the multi-shipping details look.
We want the checkout flow to be less cluttered.
Before:
After:
> feat(checkout): CHECKOUT-6851 Improve multi-shipping form look

- packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodList.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodV2.spec.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodV2.tsx
- packages/core/src/app/payment/resolvePaymentMethod.ts
As above
Add fallback to v1 payment method component if a component cannot be resolved via the `resolveComponent` method
- tests 
- manual
> chore(payment): CHECKOUT-6904 Update resolver component to return method v1 as fallback

- packages/core/src/app/customer/CreateAccountForm.spec.tsx
- packages/core/src/app/customer/getCreateCustomerValidationSchema.ts
Reversing order for description and custom errors for password related error messages in the create customer form validation.
Currently custom password related errors are not rendered on the create customer form during checkout. This is because the default description is evaluated and used first. This change will first check for a custom error message instead.
Before:
(note that the password error message is the default one)
After:
(password error message is now read from the locale language file and updates based on what condition is failing)
> fix(checkout): CHECKOUT-6760 [Accessibility] - simplymedical.com - Ensure color is not the sole means of indicating error messages

- packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Allow to pay with hosted payment 
the payment was failing when Feature_HostedPaymentForm was enabled
[Video](https://drive.google.com/file/d/1hv8EayUMZ80jKXQBJjnuz8n4tqL_yqRQ/view?usp=sharing)
https://github.com/bigcommerce/checkout-sdk-js/pull/1583
> fix(payment): INT-6115 Payment with hosted credit card

- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/customer/customWalletButton/AmazonPayV2Button.spec.tsx
- packages/core/src/app/customer/customWalletButton/AmazonPayV2Button.tsx
- packages/core/src/app/customer/customWalletButton/index.ts
- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
Wrap the Amazon Pay button in a container with a specific size to prevent it from flickering.
The size of the button's container is calculated by Amazon's JS every time the window resizes, that's why it flickers. We prevent the script from doing that by providing a parent container with a specific size. Therefore, the button's container inherits this size instead of doing all the math.
https://user-images.githubusercontent.com/4843328/184449774-27043fe6-9bf8-4ffe-a2cd-33c5adf16040.mov
https://user-images.githubusercontent.com/4843328/184711992-a61f3880-b2d0-4eaa-8c4b-8eb5ce1b90ec.mov
@bigcommerce/apex-integrations @bigcommerce/checkout
> fix(payment): INT-6404 AmazonPayV2: Prevent button flickering

- packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.tsx
Added a LoadingOverlay inside the modal
Related to [PR 1578](https://github.com/bigcommerce/checkout-sdk-js/pull/1578)
The loading of the bluesnap checkout inside the modal may take some time.
Before
After
Ping
@bigcommerce/apex-integrations  @bigcommerce/payments
> fix(payment) INT-6328 Bluesnap open a new tab insted of using iframe to complete order

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/CheckoutStep.tsx
- packages/core/src/app/checkout/CheckoutStepStatus.ts
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
- packages/core/src/app/ui/loading/LoadingNotification.tsx
- packages/core/src/app/ui/loading/__snapshots__/LoadingNotification.spec.tsx.snap
We want to use `aria-busy="true"` to prevent a screen reader from using the modified content when there is an ongoing API request. Additionally, the loading state should be immediately announced by the screen reader.
Part I: https://github.com/bigcommerce/checkout-js/pull/996
BC merchants can benefit from the ADA-compliant native checkout and order confirmation pages.
Please notice the `aria-busy` changes on the right side of the video.
https://user-images.githubusercontent.com/88361607/187326520-18697916-3cba-4a7e-9c94-fc2b23e50216.mov
> feat(checkout): CHECKOUT-6875 Improve accessibility part II

- package-lock.json
- package.json
This release contains next checkout-sdk changes:
https://github.com/bigcommerce/checkout-sdk-js/pull/1494
https://github.com/bigcommerce/checkout-sdk-js/pull/1530
https://github.com/bigcommerce/checkout-sdk-js/pull/1518
https://github.com/bigcommerce/checkout-sdk-js/pull/1585
Unit tests
Manual tests
Screenshots of the result:
> chore(payment): PAYPAL-1474 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk-js what contains pr below:
https://github.com/bigcommerce/checkout-sdk-js/pull/1589
https://github.com/bigcommerce/checkout-sdk-js/pull/1587
https://github.com/bigcommerce/checkout-sdk-js/pull/1570
To have last checkout-sdk-js changes up to date
Unit tests
CI tests
> chore(payment): PAYPAL-1538 bump checkout-sdk-js version

- package-lock.json
- packages/core/src/app/checkout/Checkout.spec.tsx
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/CheckoutApp.tsx
- packages/core/src/app/order/OrderConfirmation.spec.tsx
- packages/core/src/app/order/OrderConfirmation.tsx
- packages/core/src/app/order/OrderConfirmationApp.tsx
- Called checkout begin event for BODL on checkout page load
- Called order purchsed event for BODL on order confirmation page load 
It's required for BODL phase 1 
> feat(checkout): STRF-9858 Integrate Bodl Service with Checkout Begin and Order Purchased

- packages/core/src/app/order/OrderSummaryDrawer.spec.tsx
- packages/core/src/app/ui/modal/ModalTrigger.spec.tsx
- packages/core/src/app/ui/modal/ModalTrigger.tsx
Add `scrollIntoView` to embedded checkout, so a shopper can always see the content of a modal.
A shopper cannot see the content of a modal without scrolling to the top of the iframe when an embedded checkout's iframe is too long.
Before:
https://user-images.githubusercontent.com/88361607/189245953-1258db75-7244-4999-96b5-674ae1b393c3.mov
After:
https://user-images.githubusercontent.com/88361607/189245959-1027d53c-e962-4d27-9872-30de307b1a31.mov
> fix(checkout): CHECKOUT-6365 Add scrollIntoView to embedded checkout

- packages/core/src/app/customer/LoginForm.tsx
- packages/core/src/app/customer/__snapshots__/Customer.spec.tsx.snap
Wrap the "creating account" text as a span to improve login form spacing.
Merchants' own wordings make the login form less concise.
Before:
After:
> feat(checkout): CHECKOUT-0000 Improve login form spacing

- packages/core/src/app/ui/form/DynamicFormField.spec.tsx
- packages/core/src/app/ui/form/DynamicFormField.tsx
Using a numeric keypad to enter tel numbers.
Speed up the checkout.
> fix(checkout): CHECKOUT-6860 Use numeric keypad to type phone number

- package-lock.json
- package.json
Fixed Adyen 3ds2 challenge on googlepay
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/1596
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-540
There was a problem with adyen script load on live mode due to the wrong name of mode. Instead of test/live, was used TEST/PRODUCTION
**Now script loads without any errors:** 
> fix(payment): ADYEN-540 fixed adyen 3ds2 challenge on googlepay

- package-lock.json
- package.json
To deploy last checkout-sdk changes:
https://github.com/bigcommerce/checkout-sdk-js/pull/1584
https://github.com/bigcommerce/checkout-sdk-js/pull/1576
https://github.com/bigcommerce/checkout-sdk-js/pull/1599
Unit tests
CI tests
> chore(payment): PAYPAL-1541 bump checkout-sdk version

- package-lock.json
- package.json
Bump `checkout-sdk v1.286.0`.
Release https://github.com/bigcommerce/checkout-sdk-js/pull/1595.
CI.
> chore(checkout): CHECKOUT-6860 Bump checkout-sdk v1.286.0

- package-lock.json
- package.json
To release related pr:
https://github.com/bigcommerce/checkout-sdk-js/pull/1606
Unit tests
Manual tests
CI tests
> chore(payment): PAYPAL-1673 bump checkout sdk

- packages/core/src/app/ui/modal/ModalTrigger.tsx
For iOS, when a user clicks on "show details" button, the parent page will scroll to the top of the checkout iframe.
`ScrollIntoView` does not work in iOS due to CSS conflicts with the Bigcommerce WordPress plug-in. Therefore, adding a method specific to the Bigcommerce WordPress plug-in.
iOS Safari:
https://user-images.githubusercontent.com/88361607/192404635-4e7d93d5-9eec-43b9-bb7e-38b422c2ae47.mov
iOS Chrome:
https://user-images.githubusercontent.com/88361607/192404642-8fb877ec-b795-4d44-8aad-7f7c106ed538.mov
> fix(checkout): CHECKOUT-6365 Scroll to modal in WordPress

- package-lock.json
- package.json
To make checkout-js be in line with last checkout sdk changes:
https://github.com/bigcommerce/checkout-sdk-js/pull/1588
https://github.com/bigcommerce/checkout-sdk-js/pull/1586
https://github.com/bigcommerce/checkout-sdk-js/pull/1604
Unit tests
Manual tests
CI tests
> chore(payment): PAYPAL-1625 bump checkout-sdk version

- packages/core/src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.tsx
Send 'create_bolt_account: false' for shoppers with registered Bolt account
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-105](https://bigcommercecloud.atlassian.net/browse/BOLT-105)
> fix(payment): BOLT-105 Send 'create_bolt_account: false' for shoppers with registered Bolt account

- packages/core/src/app/order/OrderSummaryDrawer.spec.tsx
- packages/core/src/app/ui/modal/ModalTrigger.spec.tsx
- packages/core/src/app/ui/modal/ModalTrigger.tsx
- packages/core/src/scss/components/foundation/modal/_modal.scss
Revert previous PR https://github.com/bigcommerce/checkout-js/pull/1036
Not scroll any more, display cart summary at bottom.
By default, modern browsers prevent cross-domain iframes from accessing anything in the parent window. 
The previous PR is unable to work in a cross domain scenario, which is the most common use case for the embedded checkout.
As a result, this PR provides a pure CSS solution to the problem that a shopper cannot see the cart summary when clicking on the cart button.
Android - Chrome
https://user-images.githubusercontent.com/88361607/192906250-e95d8b48-2015-4ff8-a6e3-e010e4159a60.MP4
iOS - Safari
https://user-images.githubusercontent.com/88361607/192906254-eb203e66-109b-4ba6-ac61-d6d87c562059.mov
iOS - Chrome …
> fix(checkout): CHECKOUT-6969 Display cart summary at bottom

- package-lock.json
- package.json
Update SDK version
We need to use the latest version of SDK to be able to implement the StripeLink checkout
https://github.com/bigcommerce/checkout-sdk-js/commit/b08223022940cdd0fdf495743719ed82eb8cffdf
- Circle
> chore(payment): STRIPE-52 bump to 1.292.0 SDK version (#1616)

- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodId.ts
GooglePay implementation for Bank of New Zealand
So that customers can pay with their google pay wallets
...
> feat(payment): INT-6297 BNZ GooglePay

- package-lock.json
- package.json
The release contains this checkout sdk PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1622
https://github.com/bigcommerce/checkout-sdk-js/pull/1624
To make checkout js have latest checkout sdk version
Unit tests
Manual tests
> chore(payment): PAYPAL-1628 bump checkout sdk version

- packages/apple-pay-integration/e2e/__har__/ApplePay-in-Customer-Step_453200396/recording.har
- packages/core/src/app/checkout/Checkout.spec.tsx
- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/StripeGuestForm.spec.tsx
- packages/core/src/app/customer/StripeGuestForm.tsx
- packages/core/src/app/customer/__snapshots__/StripeGuestForm.spec.tsx.snap
- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
- packages/core/src/app/payment/paymentMethod/HostedPaymentMethod.spec.tsx
- packages/core/src/scss/components/checkout/customer/_customer.scss
- Create logic to render Stripeupe customer component
- Create auto-step logic
- Look and feel
- logic to show only credit card in case StripeLink is activated and is an authenticated Stripe customer
As a Guest Shopper, I want to use the Stripe link experience.
**HOW TO SETUP**
https://drive.google.com/file/d/1Y6T-hohrbhelYQeupL754KRo6vLz7DPF/view?usp=sharing
**PURCHASE USING STRIPE CUSTOMER**
https://drive.google.com/file/d/1brzLC7kAXcC7YGz1BMrvA5BXUZTpHF7J/view?usp=sharing
**WHAT HAPPENS IF A BC CUSTOMER TRY TO USE LINK**  (spoiler, we are using BC components if It's a BC customer, Link experience is just for guest)
**- AS A BC CUSTOMER AT THE BEGINNING**
https://drive.google.com/file/d/14tUb6mmXuJWMzneNdhXM7tG8EX0_xQ5O/view?usp=sharing
**- AS A BC GUEST AT THE BEGINNING BUT BC CUSTOMER …
> feat(payment): STRIPE-25 create a custom guest form for Stripe link

- packages/core/src/app/checkout/CheckoutStep.tsx
In the case of mobile devices, after we pressed **EXIT CHECKOUT BOLT**, we do not have a BOLT account because we had a problem initializing `handleTransitionEnd` on mobile device.
This fix resolves the problem
According to task [BOLT-332](https://bigcommercecloud.atlassian.net/browse/BOLT-332)
Before
https://user-images.githubusercontent.com/99336044/192528904-38b184b4-c470-4233-9942-2361a416a8b9.mov
After
https://user-images.githubusercontent.com/99336044/191573281-781389fb-317f-4918-9df1-7b244ae95c47.mov
Works on desktop
https://user-images.githubusercontent.com/99336044/193060288-e003050a-fe83-450d-a259-1088ea28b1e2.mov
> feat(payment): BOLT-332 fixed issue with initialize Bolt client on mobile

- packages/core/src/app/address/googleAutocomplete/AddressSelector.spec.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelector.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteResult.mock.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteTypes.ts
Set `sublocality` as street 2 for NZ based addresses. 
Set `sublocality` as street 2 for NZ based addresses, since NZ has a concept of a sublocality which is not captured in our shipping form as part of google autocomplete.
- Tests
- Screenshot
> fix(shipping): CHECKOUT-5034 Update autocomplete address set for NZ address

- packages/core/src/app/embeddedCheckout/createEmbeddedCheckoutSupport.ts
Add applepay to the list of unsupported payment methods in embedded checkout.
Applepay is not supported in embedded checkout, updating the list accordingly.
- circle
> chore(common): CHECKOUT-000 Add applepay to unsupported methods

- package-lock.json
- package.json
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1607
Checkout-sdk-js PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1610
https://github.com/bigcommerce/checkout-sdk-js/pull/1607
Tested on dev and Integration
> feat(payment): PAYPAL-1607 bump checkout-sdk

- package-lock.json
- package.json
Bump checkout-sdk from [version 1.297.0](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#12970-2022-10-17) to [version 1.298.0](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#12980-2022-10-18).
To release:
- https://github.com/bigcommerce/checkout-sdk-js/pull/1591
- https://github.com/bigcommerce/checkout-sdk-js/pull/1618
CircleCI + testing section on the above PRs
> chore(common): INT-6478 STRIPE-99 Bump checkout-sdk

- packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.tsx
Refactoring to catch a bug and disable the place order button when provider scripts fail.
If you decide to make the purchase with square even though it did not show the capture fields (Checkout section). Throws a modal with an error you can't get out of.
https://drive.google.com/file/d/1Yu3xmSnwiiCQBGlzN7yaV-VV6mEu-Iq2/view?usp=sharing
> fix(payment): INT-6478 SquareV2 - Fail Gracefully when payment provider unavailable

- packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
**WorldpayCreditCardPaymentMethod.tsx**
- validate if getHostedFormOptions exists before to be called
with **Feature_HostedPaymentForm** disabled and we initialize the payment method we was getting a error message 
**Before:** [Video](https://drive.google.com/file/d/1JhcXSNP5DYy-J1utu0pBMLGdy-sbAevN/view?usp=sharing)
**After:** [Video](https://drive.google.com/file/d/1ok71cibs5B1k0hz2WYAigVsol5I0x7CJ/view?usp=sharing)
> fix(payment): INT-6789 Worldpay Support payment without hosted form

- packages/core/src/app/locale/translations/en.json
Change the displayed text to **Buy Now Pay Later with Sezzle**
Sezzle prefer the another text
@bigcommerce/checkout. @bigcommerce/apex-integrations
> feat(payment): INT-6637 Sezzle change displayed text

- packages/core/src/app/address/googleAutocomplete/AddressSelector.spec.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelectorUk.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteResult.mock.ts
Allow checkout to not automatically fill in the `postcode` and `state/province` fields for UK shipping addresses.
We have discovered that Google does not return UK postcodes reliably.
Furthermore, UK addresses do not have “State/Province”. 
Added two unit tests.
> feat(checkout): CHECKOUT-6835 Address autocomplete for UK

- package-lock.json
- package.json
Bump checkout sdk version.
To keep checkout sdk version as newest as possible in checkout js.
Checkout sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/1611
https://github.com/bigcommerce/checkout-sdk-js/pull/1645
https://github.com/bigcommerce/checkout-sdk-js/pull/1648
https://github.com/bigcommerce/checkout-sdk-js/pull/1653
Unit tests
Manual tests
> chore(payment): PAYPAL-1742 bump checkout sdk version

- package-lock.json
- package.json
This version includes several PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1629
https://github.com/bigcommerce/checkout-sdk-js/pull/1650
https://github.com/bigcommerce/checkout-sdk-js/pull/1644
New checkout sdk version
Unit tests
Manual tests
> chore(payment): PAYPAL-1630 bump checkout sdk version

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/CheckoutStepStatus.ts
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
Fix `<Shipping />` component memory leak.
The `finally` block inside `componentDidMount` will always run even after `<Shipping />` is unmounted.
Therefore, before running setState, we need to check the mount status.
Before:
After:
> fix(checkout): CHECKOUT-0000 Fix shipping component memory leak

- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
Prevent calling properties on undefined `error.body` when handling closing modals
There are some errors (like `PaymentMethodFailedError` which is thrown by Cardinal) that include a `type` but not a `body`, which breaks the close modal functionality when accessing the property type of undefined.
Without changes:
https://drive.google.com/file/d/1D2XU594smtrOOG6rtp-zVeOP5QM1UEG1/view?usp=sharing
After changes:
https://drive.google.com/file/d/1zgatOvL6gSxGSLLVT11IDLTewdK9N9Tf/view?usp=sharing
@bigcommerce/apex-integrations @bigcommerce/checkout
> fix(payment): INT-6720 prevent calls on undefined error body

- packages/core/src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
Fix the problem where Safari always displays 1 as the payment step number instead of 4.
Safari's CSS counter function differs from Chrome's.
iOS Safari
Also tested on iOS Chrome, Android Chrome, and Firefox, all of which behaved as expected.
> fix(checkout): CHECKOUT-6840 Fix payment step counter in Safari

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/CheckoutStepStatus.ts
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
Reverts bigcommerce/checkout-js#1073
When a shopper completes the customer step and reloads the checkout page, or modifies the cart content, `step.activeStepType` can become `undefined`. 
Therefore, the shipping address form will never show up.
// The current BCapp's `checkout-js` version does not contain related changes.
> Revert "fix(checkout): CHECKOUT-0000 Fix shipping component memory leak"

- package-lock.json
- package.json
Update a new version in the package checkout-sdk to  1.299.1 
To update the new changes with https://github.com/bigcommerce/checkout-sdk-js/pull/1647
> chore(payment): INT-6772 Bump checkout-sdk to 1.299.1

- package-lock.json
- package.json
This bump contains:
https://github.com/bigcommerce/checkout-sdk-js/pull/1632
https://github.com/bigcommerce/checkout-sdk-js/pull/1664
https://github.com/bigcommerce/checkout-sdk-js/pull/1665
To keep checkout js as fresh as possible with latest checkout sdk updates 
Unit tests
Manual tests
> chore(payment): PAYPAL-1758 bump checkout-sdk version

- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
Fix the bug that `shouldSaveAddress` was not saved when a shopper made an explicit change to it.
Prevously, we only updated `shouldSaveAddress` value on the server if an address change occurred. 
Now, whenever the value of `shouldSaveAddress` is changed, it is sent to the server.
Manual testing:
https://user-images.githubusercontent.com/88361607/199401949-035be053-e0b0-453d-b50c-19b8311c08df.mov
> fix(checkout): CHECKOUT-5742 shouldSaveAddress is not saved

- package-lock.json
- package.json
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingForm.spec.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingForm.tsx
- packages/core/src/app/shipping/stripeUPE/StripeStateMapper.spec.ts
- packages/core/src/app/shipping/stripeUPE/StripeStateMapper.ts
- Persisting data to use when checkout is reloaded, to achieve this we are forcing to load again shipping and customer steps on checkout to refill Stripe components and preserve Stripe behavior, in addition to improving the user experience, we make these steps auto-skip once it finishes loading
- update SDK version 1.304.0
For **STRIPE-183**, Link Enrollment Opt-In Disappears If Shopper Navigates Away From Checkout because the information is not persisting & for **STRIPE-195** I want to allow shoppers whose email address is both enrolled in Link and has a merchant registered account to skip the sign-in prompt if they successfully authenticate with Link so that they are not asked to authenticate with two different accounts
[VIDEO STRIPE-183](https://drive.google.com/file/d/1ccuz-hfTxp-3mSgf …
> feat(payment): STRIPE-183 persisting stripe components when reloads the page

- packages/core/src/app/payment/paymentMethod/PaymentMethodV2.spec.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodV2.tsx
Add a validation to force to use PaymentMethod V1 when the gateway is mollie.
This to use the MolliePaymentStrategy.
As a momentarily solution to support Apple Pay on Mollie and using the MolliePaymentMethod, and meanwhile an enhancement to support Mollie as Payment Method V2.
https://github.com/bigcommerce/checkout-sdk-js/pull/1671
> feat(payment): INT-5953-T Force to use Payment Method V1 when Mollie and ApplePay

- packages/core/src/app/common/error/SentryErrorLogger.spec.ts
- packages/core/src/app/common/error/SentryErrorLogger.ts
Filter out convertcart-related issues on Sentry.
Reduce the amount of noisy errors we receive, such as [3505225940](https://sentry.io/organizations/bigcommerce/issues/3505225940/?project=1542560).
- Added one unit test.
- CI
> feat(checkout): CHECKOUT-7036 Filter out convertcart-related issues on Sentry.

- package-lock.json
- package.json
According to task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1722
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1667
> feat(payment): PAYPAL-1722 bump checkout-sdk-js version

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
Fix the bugs:
- A shopper cannot actually opt out marketing newsletter on the checkout page.
- The newsletter option always displays its default state rather than a shopper's actual choice.
The limitation of this bugfix is when a shopper reloads the page, the state will lose.
The subscription state of a shopper's email address is currently unavailable through our API endpoints. 
There will be a server-side ticket made as a follow-up. (update: [CHECKOUT-7095](https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7095))
Manual testing:
https://user-images.githubusercontent.com/88361607/200476203-8c21e6e7-4d47-41dd-95d0-b2cb2232576d.mov
> fix(checkout): CHECKOUT-6672 Maintain subscription checkbox state

- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
Add more validations to avoid infinite spinner in the StripeLink shipping component
If a non-Link enrolled guest shopper gets to the payment step but then exits checkout and increases items in her cart, when he/she returns o the checkout, the shipping address loading gif spins indefinitely.
[DEMO](https://drive.google.com/file/d/1Mus_en2JJTyBFjhOlunjAxxTPkCRJIg_/view?usp=sharing)
> feat(payment): STRIPE-215 add more validation to avoid Shipping Steps Loads Indefinitely for stripe link

- packages/core/src/app/common/error/SentryErrorLogger.spec.ts
- packages/core/src/app/common/error/SentryErrorLogger.ts
Reverts bigcommerce/checkout-js#1092
This seems to be causing:
```
TypeError: undefined is not an object (evaluating 't.url.includes')
at ? (./packages/core/src/app/common/error/SentryErrorLogger.ts:139:72)
at filter([native code])
at ? (./packages/core/src/app/common/error/SentryErrorLogger.ts:139:32)
```
ping @bigcommerce/checkout
> Revert "feat(checkout): CHECKOUT-7036 Filter out convertcart-related issues on Sentry."

- packages/core/src/app/common/error/SentryErrorLogger.spec.ts
- packages/core/src/app/common/error/SentryErrorLogger.ts
The previous PR did help reduce the number of the convertcart-related issues, it also introduced a new one because it failed to realise that the `url` property is optional.
This PR expands the optional chaining to include `url`.
The updated unit test captures the case where `data` and `url` are optional.
Reduce the amount of noisy errors we receive, such as [3505225940](https://sentry.io/organizations/bigcommerce/issues/3505225940/?project=1542560).
- CI.
> feat(checkout): CHECKOUT-7036 Filter out convertcart-related issues

- packages/core/src/app/locale/translations/da.json
- packages/core/src/app/locale/translations/de.json
- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/locale/translations/es-419.json
- packages/core/src/app/locale/translations/es-AR.json
- packages/core/src/app/locale/translations/es-CL.json
- packages/core/src/app/locale/translations/es-CO.json
- packages/core/src/app/locale/translations/es-MX.json
- packages/core/src/app/locale/translations/es-PE.json
- packages/core/src/app/locale/translations/es.json
- packages/core/src/app/locale/translations/fr.json
- packages/core/src/app/locale/translations/it.json
- packages/core/src/app/locale/translations/nl.json
- packages/core/src/app/locale/translations/no.json
- packages/core/src/app/locale/translations/pt-BR.json
- packages/core/src/app/locale/translations/pt.json
- packages/core/src/app/locale/translations/sv.json
- packages/locale/src/en.json
Removed the string `(Quadpay)` from all the translation files.
A Zip team request.
@bigcommerce/apex-integrations  @bigcommerce/checkout
> refactor(payments): INT-6930 Zip: remove "(Quadpay)" from checkout

- packages/core/src/scss/components/checkout/paymentProvider/_paymentProvider.scss
The CSS class name that gives style to the APMs' checkout section now includes "white-space: nowrap;."
On the payment step of checkout, the Apple Pay logo is misaligned and the text is broken into separate lines on the radio button payment method selection.
Revert PR
> fix(checkout): INT-6968 fix for the misaligned text when it has spaces in between on APMs name

- packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.tsx
- packages/hosted-field-integration/.eslintrc.json
- packages/hosted-field-integration/README.md
- packages/hosted-field-integration/jest.config.js
- packages/hosted-field-integration/project.json
- packages/hosted-field-integration/src/index.ts
- packages/hosted-field-integration/src/lib/hosted-field-integration.spec.tsx
- packages/hosted-field-integration/src/lib/hosted-field-integration.tsx
- packages/hosted-field-integration/tsconfig.json
- packages/hosted-field-integration/tsconfig.lib.json
- packages/hosted-field-integration/tsconfig.spec.json
- packages/test-utils/src/checkout.mock.ts
- packages/ui/src/form/index.ts
- packages/ui/src/index.ts
- tsconfig.base.json
- workspace.json
Refactor the existing `HostedField` component as a shared payment integration package.
Support payment method monorepo packages, such as `Square`, that compose with `<HostedFieldPaymentComponent />`.
- CI.
> feat(checkout): CHECKOUT-6438 Refactor `HostedField` component

- package-lock.json
- package.json
Bump checkout-sdk from 1.306.0 to [1.309.0](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#13090-2022-11-28)
To release https://github.com/bigcommerce/checkout-sdk-js/pull/1642
> chore(payment): INT-6716 Bump checkout-sdk from 1.306.0 to 1.309.0

- package-lock.json
- package.json
Fixes for the tickets:
[STRIPE-160](https://bigcommercecloud.atlassian.net/browse/STRIPE-160), PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1690
[STRIPE-167](https://bigcommercecloud.atlassian.net/browse/STRIPE-167), PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1695
[STRIPE-183](https://bigcommercecloud.atlassian.net/browse/STRIPE-183)
[STRIPE-195](https://bigcommercecloud.atlassian.net/browse/STRIPE-195), PR: https://github.com/bigcommerce/checkout-sdk-js/pull/1649
> fix(payment): STRIPE-0000 bump checkout-sdk-js v1.309.6

- packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.spec.tsx
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.tsx
Logged in shoppers who saved their card previously are not able to select the option of using a different card and entering their new credit card details.
When the shopper selects “use a different card” they should see the credit card fields 
https://user-images.githubusercontent.com/104527753/203615753-1b3be81e-4fe2-4cfb-8de1-edf9049227a7.mov
https://user-images.githubusercontent.com/104527753/203615803-0205ef7e-3f38-41a6-bf89-76d34ff4de47.mov
- https://github.com/bigcommerce/checkout-sdk-js/pull/1702
> fix(payment): INT-6928 [Mollie] No Ability To Use A Different Card To Pay

- package-lock.json
- package.json
Bump `checkout-sdk` version.
Release lastest SDK changes.
- https://github.com/bigcommerce/checkout-sdk-js/commit/18fa2176b800e648b1ba26ed424b4ced8d964a52
- https://github.com/bigcommerce/checkout-sdk-js/commit/7eb83cd6db9bcd2280c92f6609902e0aa95e9e18
- https://github.com/bigcommerce/checkout-sdk-js/commit/971378b159bbd764ddcabd0bd2c6b72b5c4500a7
- https://github.com/bigcommerce/checkout-sdk-js/commit/555556811a82c728f691c90a303342a388cb0858
- https://github.com/bigcommerce/checkout-sdk-js/commit/7a039ba34671492f1633ca6fc9ebed12ab142ceb
- CircleCI
> chore(checkout): CHECKOUT-0000 Bump SDK version

- packages/core/src/app/payment/paymentMethod/HostedFieldPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/HostedFieldPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.tsx
As above
While migrating square payment method to use the `HostedPaymentComponent`  from separate monorepo package. We realised that the translations provider needs to be built correctly, otherwise the component seems to be missing translation context. 
Once we update the locale package with correct translation setup, we can migrate square to use monorepo package component.
- circle
> fix(checkout): CHECKOUT-0000 Revert square to use previous hosted payment component

- package-lock.json
- package.json
Bump checkout-sdk `v1.313.1`.
Release lastest changes:
https://github.com/bigcommerce/checkout-sdk-js/commit/1c07aadfd41ae21b265db9ee2fda400cbcb16c06
https://github.com/bigcommerce/checkout-sdk-js/commit/32148c2a4f9596fbf02d72ada2fcad14392fdd95
https://github.com/bigcommerce/checkout-sdk-js/commit/e946565d2b122687411e03b6507519d6fa5d870a
https://github.com/bigcommerce/checkout-sdk-js/commit/85e9cbfa52d90a9a711519daf6cd1e608c8582b8
https://github.com/bigcommerce/checkout-sdk-js/commit/adb845c3d602bfaa277f5eabd1587869723d16ac
https://github.com/bigcommerce/checkout-sdk-js/commit/9465d7d9f532c65d50d15f7e42839be70befebb1
https://github.com/bigcommerce/checkout-sdk-js/commit/6a20e416428595bf79b4d6b64cf68b3f521e28da
- CI checks.
> chore(checkout): CHECKOUT-0000 bump checkout-sdk v1.313.1

- packages/core/src/app/payment/storedInstrument/isInstrumentFeatureAvailable.spec.ts
- packages/core/src/app/payment/storedInstrument/isInstrumentFeatureAvailable.ts
Adds an experiment to the condition that determines if a payment instrument can be vaulted if the order has multi-shipping. 
Because we want to enable vaulting for multiple shipping addresses. Which would mean that we won't need `isUsingMultiShipping` prop to determine if the payment method should allow vaulting or not. 
Instead of getting rid of the prop right-away, we are using an experiment to control the rollout.
Additional specs
* Without experiment, we don't see the vaulting checkbox for the multi-shipping. This is the current behaviour.
* With experiment we see the vaulting checkbox for the multi-shipping. 
> feat(payment): PAYMENTS-8376 Adds ability to enable vaulting for multi-shipping

- package-lock.json
- package.json
Bump checkout-sdk to `1.313.2`.
Release recent changes, again.
- CI checks.
- Launchbay functional tests:
https://app.circleci.com/pipelines/github/bigcommerce/bigcommerce?branch=pull%2F50362
> chore(checkout): CHECKOUT-7184 bump checkout-sdk v1.313.2

- packages/analytics/src/AnalyticsContext.ts
- packages/analytics/src/AnalyticsProvider.mock.tsx
- packages/analytics/src/AnalyticsProvider.spec.tsx
- packages/analytics/src/AnalyticsProvider.tsx
- packages/core/src/app/customer/checkoutSuggestion/BoltCheckoutSuggestion.spec.tsx
- packages/core/src/app/customer/checkoutSuggestion/BoltCheckoutSuggestion.tsx
Add new Bodl analytics event to Bolt customer suggestion initialization
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-408](https://bigcommercecloud.atlassian.net/browse/BOLT-408)
> feat(payment): BOLT-408 Add BODL event for customer suggestion init

- package-lock.json
- package.json
- packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.spec.tsx
- packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.tsx
Fix issue with empty Bolt payment fields after disabling store credits
Checkout-sdk-js changes: [https://github.com/bigcommerce/checkout-sdk-js/pull/1716](https://github.com/bigcommerce/checkout-sdk-js/pull/1716)
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-268](https://bigcommercecloud.atlassian.net/browse/BOLT-268)
Before:
https://user-images.githubusercontent.com/9430298/205292685-ae7ce077-bce6-4cea-8c16-078c62152da4.mov
After:
https://user-images.githubusercontent.com/9430298/205292732-77c8321a-263a-4ebe-b5bf-331e51191705.mov
Test:
> fix(payment): BOLT-268 Bolt payment fields with store credits

- package-lock.json
- package.json
Bump checkout-sdk `v1.315.0`.
- https://github.com/bigcommerce/checkout-sdk-js/pull/1696
- CI checks.
> chore(payment): INT-6957 Bump checkout-SDK 1.315.0

- packages/core/src/scss/components/foundation/forms/_forms.scss
Fixed cvv tooltip being cut off on braintree credit card
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1828
> feat(payment): PAYPAL-1828 fixed cvv tooltip

- package-lock.json
- package.json
Bump checkout-sdk `v1.316.1`.
- https://github.com/bigcommerce/checkout-sdk-js/pull/1749
- CI checks.
> chore(checkout): CHECKOUT-7202 Bump checkout-sdk v1.316.1

- package-lock.json
- package.json
Bump checkout-sdk `v1.316.2.`
https://github.com/bigcommerce/checkout-sdk-js/pull/1747
CI checks.
> chore(payment): STRIPE-281 Bump checkout-SDK 1.316.2

- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/shipping/Shipping.spec.tsx
- packages/core/src/app/shipping/Shipping.tsx
Remove functionality to loadPaymentMethods in the customer and shipping step added for stripeLink flow
We are using a flag called providerWithCustomCheckout to determine if StripeLink is available instead of pre-reload payment providers in the checkout
https://user-images.githubusercontent.com/42154828/207467614-d36e323a-116e-4adb-b08d-5ce6670d702b.mp4
> fix(payment): STRIPE-175 remove extra payment call and extra code on core

- package-lock.json
- package.json
- packages/core/src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
To help in the release of the PR, https://github.com/bigcommerce/checkout-js/pull/1080, I created this PR to include the related SDK change, https://github.com/bigcommerce/checkout-sdk-js/pull/1662.
Due to permission restrictions, I was unable to rebase the related JS PR, https://github.com/bigcommerce/checkout-js/pull/1080.
As a result, I copied the content and made this one.
- CI checks.
> feat(payment): STRIPE-178 Loading Submit button after card loads

- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/customer/customWalletButton/PayPalCommerceButton.spec.tsx
- packages/core/src/app/customer/customWalletButton/PayPalCommerceButton.tsx
- packages/core/src/app/customer/customWalletButton/index.ts
Added PayPalCommerce button to customer step
To give customer an ability to use PayPal to reduce amount of time on filling the data on checkout page
Here is how it looks like:
Here is a video of the result:
https://user-images.githubusercontent.com/25133454/207329128-0a3e051d-a49a-4d0c-adc6-e850b0c23051.mov
bigcommerce: https://github.com/bigcommerce/bigcommerce/pull/50236
checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/1730
> feat(payment): PAYPAL-1836 added PayPalCommerce button to customer step

- packages/core/src/app/checkout/getCheckoutStepStatuses.spec.ts
- packages/core/src/app/checkout/getCheckoutStepStatuses.ts
Exclude wallet from custom stripeLinkFlow
Could affect functionality and UX 
BUG:
https://drive.google.com/file/d/1cw6iNp2HL-StziDoiNc3ZaVAHqZgm7K2/view?usp=share_link
FIX:
https://drive.google.com/file/d/1BuaMZEVnCQKhpOlNlN9TuodBNZf8L1cl/view?usp=share_link
> fix(payment): STRIPE-269 exclude wallets from the custom customer step status for stripeLink

- packages/core/src/scss/components/foundation/modal/_modal.scss
Fix the issue when multiple items are added to checkout, the cart summary modal cannot be exited or scrolled.
Previously, the modal had a fixed position, so when its height exceeds the height of the screen, the close button is not visible.
- Manual testing:
https://user-images.githubusercontent.com/88361607/210693686-15c2d7de-2c21-4760-9149-ad253d482435.mov
> fix(checkout): CHECKOUT-7047 Unable to scroll Cart Summary on Mobile

- package-lock.json
- package.json
- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/payment/Payment.spec.tsx
- packages/core/src/app/payment/Payment.tsx
- packages/core/src/app/payment/mapSubmitOrderErrorMessage.ts
- packages/locale/src/en.json
Handle `CartConsistencyError` by displaying an error modal when it is thrown and reloading checkout data when the shopper dismisses the modal.
Requires https://github.com/bigcommerce/checkout-sdk-js/pull/1746
So shoppers are informed about any changes to their cart (e.g.: price changes) and have a chance to review them before placing their order.
Unit + Manual
https://user-images.githubusercontent.com/667603/209247483-95eb339e-494a-40f4-8ad0-fe04a7d30f5d.mov
> CHECKOUT-7148: Handle cart inconsistency error and display appropriate message to shopper

- package-lock.json
- package.json
- packages/core/src/app/customer/checkoutSuggestion/BoltCheckoutSuggestion.spec.tsx
- packages/core/src/app/customer/checkoutSuggestion/BoltCheckoutSuggestion.tsx
Modify BODL analytics event for Bolt suggestion on customer step
Checkout-sdk-js PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/1752](https://github.com/bigcommerce/checkout-sdk-js/pull/1752)
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-437](https://bigcommercecloud.atlassian.net/browse/BOLT-437)
Checkout-sdk-js test:
Checkout-js test:
> feat(payment): BOLT-437 Modify analytics event for Bolt suggestion on customer step

- package-lock.json
- package.json
To release several updates on checkout-sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/1767
https://github.com/bigcommerce/checkout-sdk-js/pull/1694
https://github.com/bigcommerce/checkout-sdk-js/pull/1751
Unit tests
> chore(payment): PAYPAL-1904 bump checkout-sdk version

- package-lock.json
- package.json
- packages/core/src/app/customer/CheckoutButtonList.tsx
Create braintree-paypal customer button strategy
Checkout-sdk-js PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/1750](https://github.com/bigcommerce/checkout-sdk-js/pull/1750)
Because of task:  [https://bigcommercecloud.atlassian.net/browse/PAYPAL-1839](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1839)
Manual testing a unit test
> feat(payment): PAYPAL-1839 Create braintreepaypal customer button strategy

- package-lock.json
- package.json
3ds2 redirect for vaulted cards fix release
Due to the release of https://github.com/bigcommerce/checkout-sdk-js/pull/1771
> chore(checkout): ADYEN-688 3ds2 redirect for vaulted cards fix release

- package-lock.json
- package.json
Bump checkout-sdk from `1.324.1` to [`1.324.2`](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#13242-2023-01-17)
To release https://github.com/bigcommerce/checkout-sdk-js/pull/1765
> chore(payment): INT-7103 Bump checkout-sdk from 1.324.1 to 1.324.2

- package-lock.json
- package.json
As above
Release fix for billing address
- https://github.com/bigcommerce/checkout-sdk-js/commit/5cde3c3c557b0a6591992b3443f02ebb8fef0ea2
- https://github.com/bigcommerce/checkout-sdk-js/pull/1700
- circle
> chore(common): CHECKOUT-000 Bump checkout sdk to 1.326.2

- package-lock.json
- package.json
As above
Release fix for order finalisation for barclaycard
- https://github.com/bigcommerce/checkout-sdk-js/pull/1786
- circle
> chore(common): CHECKOUT-000 Bump checkout-sdk to 1.326.3

- package-lock.json
- package.json
Bumped checkout-sdk version due to last merged prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1784
https://github.com/bigcommerce/checkout-sdk-js/pull/1791
https://github.com/bigcommerce/checkout-sdk-js/pull/1782
To release latest checkout-sdk updates
Unit tests
> chore(payment): PAYPAL-1898 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout sdk js version due to next prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1794
To keep checkout js up to date
Unit tests
Manual tests
> chore(payment): PAYPAL-1923 bump checkout js version

- package-lock.json
- package.json
To release several checkout-sdk prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1780
https://github.com/bigcommerce/checkout-sdk-js/pull/1742
https://github.com/bigcommerce/checkout-sdk-js/pull/1804
https://github.com/bigcommerce/checkout-sdk-js/pull/1803
https://github.com/bigcommerce/checkout-sdk-js/pull/1806
Unit tests
> chore(payment): PAYPAL-000 bump checkout-sdk version

- package-lock.json
- package.json
To release several checkout-sdk prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1802
https://github.com/bigcommerce/checkout-sdk-js/pull/1800
https://github.com/bigcommerce/checkout-sdk-js/pull/1798
https://github.com/bigcommerce/checkout-sdk-js/pull/1793
Unit tests
> chore(payment): PAYMENTS-000 bump checkout-sdk version from 1.331.0 to 1.332.2

- package-lock.json
- package.json
Bump for checkout-sdk version 1.355.0
To create a bump
> chore(payment): STRIPE-0 checkout-sdk bump version 1.355.0

- .circleci/config.yml
- jest.preset.js
- package-lock.json
- package.json
- packages/core/project.json
- Move lint to a separate process
- Remove test artifact uploads
- Split test runs into two jobs one for core package and one for the rest of the packages
- Split test runs of core package into two parallel streams
At the moment circlet CI runs take around 10 mins approximately, we can optimise this and have a quicker turn around in our CI steps.
- Circle
Updated CI times for PRs
> chore(common): CHECKOUT-6271 Make changes to circle config

- .circleci/config.yml
- Remove small as a resource for test core jobs
Need to remove small as resource since fresh node install fails most of the time, causing flakiness to the pipeline.
- circle
> chore(common): CHECKOUT-000 Remove small resource

- package-lock.json
- package.json
Bump checkout sdk dependency version
To keep project up to date.
Here is a list of updates related to new checkout sdk version:
https://github.com/bigcommerce/checkout-sdk-js/pull/1817
https://github.com/bigcommerce/checkout-sdk-js/pull/1813
https://github.com/bigcommerce/checkout-sdk-js/pull/1815
https://github.com/bigcommerce/checkout-sdk-js/pull/1801
https://github.com/bigcommerce/checkout-sdk-js/pull/1820
https://github.com/bigcommerce/checkout-sdk-js/pull/1816
https://github.com/bigcommerce/checkout-sdk-js/pull/1779
Unit tests
> chore(payment): PAYPAL-000 bump checkout sdk version

- package-lock.json
- package.json
To keep project up to date with last checkout-sdk release:
https://github.com/bigcommerce/checkout-sdk-js/pull/1823
https://github.com/bigcommerce/checkout-sdk-js/pull/1822
https://github.com/bigcommerce/checkout-sdk-js/pull/1821
Unit tests
> chore(payment): PAYPAL-1959 bump checkout sdk version

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/scss/components/checkout/checkoutSteps/_checkoutSteps.scss
Removing all checkout step numbers.
- Remove the step counter of each unfinished checkout step.
- Remove the circle, check mark of each finished checkout step.
- Change the step header’s left padding to zero.
- Putting all changes behind an experiment so that we can roll out changes incrementally.
Once we introduce wallet buttons on the top of the checkout page, the step numbers are no longer accurate progress indicators.
https://user-images.githubusercontent.com/88361607/216851440-9d7db6c9-6f80-4427-8cd9-02e18ff33442.mov
> feat(checkout): CHECKOUT-7255 Remove checkout step numbers

- package-lock.json
- package.json
- packages/core/src/app/customer/CheckoutButtonList.tsx
Add PayPal Commerce Venmo customer strategy which will be used as button on customer step
PayPal Commerce Venmo button was added to make ability for shoppers to use venmo payment method on first step and simplify checkout process.
PR for checkout-sdk-js: [https://github.com/bigcommerce/checkout-sdk-js/pull/1824](https://github.com/bigcommerce/checkout-sdk-js/pull/1824)
https://user-images.githubusercontent.com/9430298/217316025-da535674-8ab6-4330-a387-244731bf6e11.mov
> feat(payment): PAYPAL-1838 Create paypalcommercevenmo customer button strategy

- package-lock.json
- package.json
- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/customer/customWalletButton/PayPalCommerceButton.tsx
Add PayPal Commerce Credit (PayLater) customer strategy which will be used as button on customer step
PayPal Commerce Credit (PayLater) button was added to make ability for shoppers to use PayLater payment method on first step and simplify checkout process.
PR for checkout-sdk-js: [https://github.com/bigcommerce/checkout-sdk-js/pull/1829](https://github.com/bigcommerce/checkout-sdk-js/pull/1829)
PR for BCapp: [https://github.com/bigcommerce/bigcommerce/pull/51145](https://github.com/bigcommerce/bigcommerce/pull/51145)
> feat(payment): PAYPAL-1837 Create paypalcommercecredit customer button strategy

- packages/core/src/app/customer/StripeGuestForm.tsx
- packages/core/src/app/customer/__snapshots__/StripeGuestForm.spec.tsx.snap
- packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
The spinner is to be replaced by addressFormSkeleton in order to get the same UX
The Checkout team introduced new CSS loading skeletons to the checkout, replacing the loading spinners so that the checkout feels faster and more responsive.
**Customer**
**Shipping**
Demo https://drive.google.com/file/d/16S0D8f_iRUExQcSebj3bSViJhN5S56JN/view?usp=sharing
Coverage: [Customer](https://output.circle-artifacts.com/output/job/1a3e45d6-2a4e-4dcd-ac74-d892e6aff652/artifacts/0/coverage/packages/core/app/customer/StripeGuestForm.tsx.html) [Shipping](https://output.circle-artifacts.com/output/job/1a3e45d6-2a4e-4dcd-ac74-d892e6aff652/artifacts/0/coverage/packages/core/app/shipping/stripeUPE/StripeShipping.tsx.html)
@bigcommerce/checkout @bigcommerce/apex-integrations 
[STRIPE-280]: …
> feat(payment): STRIPE-280 using addressFormSkeleton instead spinner for stripeLink components

- package-lock.json
- package.json
- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
After removing Apple Pay button inline styles from `checkout-sdk`, add those styles to `checkout-js`'s SCSS file.
Will bump SDK version in this PR once the below is merged.
- https://github.com/bigcommerce/checkout-sdk-js/pull/1836
`checkout-js` can manage the appearance of an Apple Pay wallet button in the new wallet button container.
> refactor(checkout): CHECKOUT-7291 Add ApplePay button style

- package-lock.json
- package.json
To keep checkout-sdk-js in checkout-js project up to date
Here are checkout-sdk prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1840
https://github.com/bigcommerce/checkout-sdk-js/pull/1842
https://github.com/bigcommerce/checkout-sdk-js/pull/1838
https://github.com/bigcommerce/checkout-sdk-js/pull/1681
Unit tests
> chore(payment): PAYPAL-1919 bump checkout-sdk-js version

- package-lock.json
- package.json
Bump checkout-sdk version due to the google pay balance fix
Due to the release of https://github.com/bigcommerce/checkout-sdk-js/pull/1839
Units/manually
> chore(checkout): ADYEN-588 bump checkout-sdk version due to the google pay balance fix

- package-lock.json
- package.json
To keep checkout-js project dependency up to date.
Here is a list of checkout-sdk changes:
https://github.com/bigcommerce/checkout-sdk-js/pull/1856
https://github.com/bigcommerce/checkout-sdk-js/pull/1855
Unit tests
> chore(payment): PAYPAL-000 bump checkout-sdk-js version

- package-lock.json
- package.json
To keep checkout-sdk-js dependency version up to date.
Here is a list of updates:
https://github.com/bigcommerce/checkout-sdk-js/pull/1852
https://github.com/bigcommerce/checkout-sdk-js/pull/1853
https://github.com/bigcommerce/checkout-sdk-js/pull/1858
https://github.com/bigcommerce/checkout-sdk-js/pull/1859
Unit tests
> chore(payment): PAYPAL-1978 bump checkout sdk js version

- packages/squarev2-integration/src/SquareV2PaymentMethod.spec.tsx
- packages/squarev2-integration/src/SquareV2PaymentMethod.tsx
Disable submit only if payment data is required.
To allow checkout with $0 orders while SquareV2 is selected.
https://user-images.githubusercontent.com/4843328/220398749-09c05577-4e20-4614-8187-8d456706eebf.mov
---
[INT-7522]: https://bigcommercecloud.atlassian.net/browse/INT-7522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payment): INT-7522 SquareV2: Disable submit only if payment data is required

- packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.tsx
Add modal and page content test case for BluesnapV2 payment method.
Also in the payment method, add listener first then append to page.
Test missing case and increase the test coverage for the payment method.
If listener is added after appending content, 'load' would have been already fired and method can't be tested properly.
> test(payment): INT-6517 Increase BluesnapV2 payment method coverage

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/index.ts
As above
As we are moving wallet buttons to top of checkout, we can render the form straightaway while the buttons are rendered in their own container. 
Therefore checkout page can have a perception that it loads faster.
- Circle
https://user-images.githubusercontent.com/7134802/220211072-3d721c57-16e2-4c62-9ceb-44d4a7e8a118.mov
https://user-images.githubusercontent.com/7134802/220211130-fdcbdc51-a6aa-4636-805a-03fbef391582.mov
> feat(common): CHECKOUT-7234 Remove loading for customer guest form

- commit-validation.json
Change commit scopes
`other` is a standard scope in most BC Respos. 
N/A
> CHECKOUT-000 Change commit validation rule

- packages/core/src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
Add a Stripe phone field
It's required by Stripe to support new fields
https://github.com/bigcommerce/checkout-sdk-js/pull/1681
> feat(payment): STRIPE-200 add phone number for stripe link

- package-lock.json
- package.json
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
- packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
Split name input into First and Last name
To have a better input field design
[stripe_doc](https://stripe.com/docs/js/elements_object/create_address_element)
Noticed that there was a missing space in the stripe-upe-payment-strategy.ts so I added it to be more readable
[1675](https://github.com/bigcommerce/checkout-sdk-js/pull/1675)
> fix(shipping): STRIPE-202 Split name input into First and Last name

- packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
The pr contains some style fixes for wallet buttons in customer step of checkout page:
- fixed the issue with paypal buttons z-index
- added extra vertical space between buttons in customer step
To make wallet buttons look better for customer and reduce amount of style glitches in mobile view.
Manual tests
Before:
After:
> fix(payment): PAYPAL-2011 fixed the issue with paypal buttons z-index and added extra vertical space between buttons in customer step

- packages/squarev2-integration/src/SquareV2PaymentMethod.tsx
Don't hide the Square card component container when loading.
Because if it's hidden, the Square card component can't calculate its sizes correctly.
[INT-7183]: https://bigcommercecloud.atlassian.net/browse/INT-7183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payment): INT-7183 SquareV2: Don't hide content when loading

- package-lock.json
- package.json
To keep checkout-sdk-js dependency version up to date.
PR with changes in cherckout-sdk-js:
[https://github.com/bigcommerce/checkout-sdk-js/pull/1860](https://github.com/bigcommerce/checkout-sdk-js/pull/1860)
Unit tests
> feat(payment): BOLT-409 Bump checkout-sdk-js version

- packages/core/src/scss/components/checkout/customer/_customer.scss
Rename Google Pay button class name.
Google Pay ended A/B testing and discontinued using `new_style` in its class name. 
To keep our style overrides working, we also need to remove it.
> fix(checkout): CHECKOUT-0000 Change Google Pay button class name

- packages/core/src/app/cart/mapToOrderSummarySubtotalsProps.ts
- packages/core/src/app/locale/translations/en.json
- packages/core/src/app/order/OrderSummary.spec.tsx
- packages/core/src/app/order/OrderSummary.tsx
- packages/core/src/app/order/OrderSummaryDrawer.tsx
- packages/core/src/app/order/OrderSummaryModal.spec.tsx
- packages/core/src/app/order/OrderSummaryModal.tsx
- packages/core/src/app/order/OrderSummarySubtotals.spec.tsx
- packages/core/src/app/order/OrderSummarySubtotals.tsx
- packages/core/src/app/order/__snapshots__/OrderSummary.spec.tsx.snap
- packages/core/src/app/order/__snapshots__/OrderSummaryModal.spec.tsx.snap
- packages/core/src/app/order/__snapshots__/OrderSummarySubtotals.spec.tsx.snap
- packages/core/src/app/order/mapToOrderSummarySubtotalsProps.ts
- packages/core/src/app/order/orders.mock.ts
- packages/core/src/scss/components/checkout/checkoutCart/_checkoutCart.scss
- packages/locale/src/en.json
If tax is set as inclusive, display tax total under total cart price.
Order Summary shows the Total price of the order as (Subtotal + Shipping). Although it might be clear to the merchant about inclusive tax, however for the customer it's not apparent. The customer can evaluate the price of the cart as (Subtotal + Shipping + tax) which is not true.
- Circle
@bigcommerce/checkout @theromulans
> feat(checkout): CHECKOUT-3430 Display inclusive tax below subtotal

- package-lock.json
- package.json
Bump checkout-sdk from `1.363.0` to [`1.367.2`](https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md#13672-2023-03-21)
To release all these:
- https://github.com/bigcommerce/checkout-sdk-js/pull/1893
- https://github.com/bigcommerce/checkout-sdk-js/pull/1894
- https://github.com/bigcommerce/checkout-sdk-js/pull/1899
- https://github.com/bigcommerce/checkout-sdk-js/pull/1903
- https://github.com/bigcommerce/checkout-sdk-js/pull/1904
- https://github.com/bigcommerce/checkout-sdk-js/pull/1811
- https://github.com/bigcommerce/checkout-sdk-js/pull/1907
- https://github.com/bigcommerce/checkout-sdk-js/pull/1808
- https://github.com/bigcommerce/checkout-sdk-js/pull/1882
- https://github.com/bigcommerce/checkout-sdk-js/pull/1916
- …
> chore(payment): INT-7044 Bump checkout-sdk from `1.363.0` to `1.367.2`

- package-lock.json
- package.json
- packages/core/src/app/payment/paymentMethod/PaypalCommerceCreditCardPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/PaypalCommerceCreditCardPaymentMethod.tsx
**CI tests can be failed due to the unmerged changes of this PR:**
https://github.com/bigcommerce/checkout-sdk-js/pull/1887
Updated initialize payment option from paypalcommerce to paypalcommercecreditcards in PaypalCommerceCreditCardPaymentMethod
`paypalcommerce` initialization option key is deprecated for `paypalcommercecreditcards` gateway id.
It still works for custom checkouts, but the developers will see a warning message in console about `paypalcommerce` key deprecation.
Unit tests
Manual tests
> feat(payment): PAYPAL-1893 updated initialize payment option from paypalcommerce to paypalcommercecreditcards in PaypalCommerceCreditCardPaymentMethod

- package-lock.json
- package.json
To keep checkout-sdk-js dependency version up to date.
PR with changes in cherckout-sdk-js:
[https://github.com/bigcommerce/checkout-sdk-js/pull/1915](https://github.com/bigcommerce/checkout-sdk-js/pull/1915)
unit tests & manual testing
> feat(payment): BOLT-483 Bump checkout-sdk-js version

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.spec.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.tsx
- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
Hide wallet buttons when a shopper enters the payment step.
`paypalcommerce` does not support simultaneously display wallet buttons and payment methods.
- CI.
> feat(checkout): CHECKOUT-0000 Hide wallet buttons during payment step

- packages/core/src/app/checkout/Checkout.tsx
- packages/core/src/app/checkout/navigateToOrderConfirmation.spec.tsx
- packages/core/src/app/checkout/navigateToOrderConfirmation.tsx
Remove `CHECKOUT-3190.enable_buy_now_cart` experiment
Since this experiment already ramped out for long time, we decided to remove it. 
BCApp PR related to the experiment removal
https://github.com/bigcommerce/bigcommerce/pull/52032
CI tests
> refactor(checkout): CHECKOUT-7421 remove CHECKOUT-3190.enable_buy_now_cart experiment

- package-lock.json
- package.json
Due to the last checkout-sdk changes:
https://github.com/bigcommerce/checkout-sdk-js/pull/1954
https://github.com/bigcommerce/checkout-sdk-js/pull/1953
https://github.com/bigcommerce/checkout-sdk-js/pull/1947
https://github.com/bigcommerce/checkout-sdk-js/pull/1941
Unit tests
CI tests
Manual tests
> chore(payment): PAYPAL-1895 bump checkout-sdk-js version

- package-lock.json
- package.json
Due to the last changes on checkout-sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/1960
https://github.com/bigcommerce/checkout-sdk-js/pull/1955
Unit tests
Manual tests
CI tests
> chore(payment): PAYPAL-1895 bump checkout-sdk version

- .gitignore
- packages/core/src/scss/components/checkout/cartModal/_cartModal.scss
As above
The continue to checkout button is cut in half in mobile screens. Adjust styles to fix that.
- Screenshot
> feat(cart): CHECKOUT-7403 Fix layout for updated modal

- package-lock.json
- package.json
To keep checkout-sdk dependency up to date.
The release contains changes from this pr:
https://github.com/bigcommerce/checkout-sdk-js/pull/1962
Unit tests
Manual tests
CI tests
> chore(payment): PAYPAL-2036 bump checkout-sdk version

- package-lock.json
- package.json
checkout-sdk-js [PR](https://github.com/bigcommerce/checkout-sdk-js/pull/1958)
Tested on dev and integration
> feat(payment): PAYPAL-2013 bump checkout-sdk-js version

- packages/core/src/app/order/OrderSummary.tsx
- packages/core/src/app/order/OrderSummaryItems.spec.tsx
- packages/core/src/app/order/OrderSummaryItems.tsx
- packages/core/src/app/order/OrderSummaryModal.tsx
- packages/core/src/app/order/__snapshots__/OrderSummary.spec.tsx.snap
- packages/core/src/app/order/__snapshots__/OrderSummaryModal.spec.tsx.snap
- packages/core/src/scss/components/checkout/cartModal/_cartModal.scss
- Remove redundant line items count in cart modal.
- Remove box shadow for cart modal header.
We have the item count in modal header hence the item count in modal is redundant.
- Screenshot
> fix(cart): CHECKOUT-7403 Remove redundant line items count in updated cart modal

- packages/squarev2-integration/src/SquareV2PaymentMethod.spec.tsx
- packages/squarev2-integration/src/SquareV2PaymentMethod.tsx
Unsubscribe from Square form validation to keep the "Place Order" button always enabled.
`onValidationChange` is having some troubles at the moment with auto-fill mechanisms and does not enable the "Place Order" button. Therefore, we want to remove this validation and instead show the tokenization errors that may occur product of the user submitting empty or invalid data.
https://user-images.githubusercontent.com/4843328/236931834-4e573e93-0b9b-42ff-b9cf-fde122042f29.mov
👉 https://github.com/bigcommerce/checkout-sdk-js/pull/1971 to show a more user-friendly message.
[INT-7516]: https://bigcommercecloud.atlassian.net/browse/INT-7516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(payment): INT-7516 SquareV2: Unsubscribe from Square form validation

- package-lock.json
- package.json
- packages/braintree-integration/src/BraintreeAchPaymentMethod.spec.tsx
- packages/braintree-integration/src/BraintreeAchPaymentMethod.tsx
1. Bump checkout-sdk-js version
2. Updated ACH initialization options for the `initializePayment` method
https://github.com/bigcommerce/checkout-sdk-js/pull/1973
Unit tests
CI tests
Manual tests
> chore(payment): PAYPAL-2370 bump checkout-sdk-js version

- packages/core/src/app/common/hoc/createMappableInjectHoc.tsx
- packages/core/src/app/shipping/SingleShippingForm.spec.tsx
- packages/core/src/app/shipping/SingleShippingForm.tsx
Add available options include to consignment call when custom fields are changed
We do refresh shipping rates when custom form fields are changed in the backend, so it does make sense to refresh the rates in the client as well. 
The driver for this is some partner integrations who are using CFF's for adding things like insurance etc.
https://github.com/bigcommerce/checkout-js/assets/7134802/1589c766-f0e8-4d33-b187-f5fe6372b9f1
> fix(shipping): CHECKOUT-7338 Add available options include if custom fields change

- package-lock.json
- package.json
Update checkout-js with this PR:
[https://github.com/bigcommerce/checkout-sdk-js/pull/1978](https://github.com/bigcommerce/checkout-sdk-js/pull/1978)
unit tests and manual testing
> fix(payment): BOLT-577 Bump checkout sdk version

- packages/core/src/app/customer/CheckoutButtonList.tsx
- packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx
- packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodId.ts
Created and modified files necessary for google pay initialization.
As a Merchant I want to enable Google Pay with Worldpay Access so that I can offer shoppers Google Pay as a payment method to my shoppers.
https://github.com/bigcommerce/checkout-sdk-js/pull/1966
@bigcommerce/checkout @bigcommerce/payments 
[INT-7573]: https://bigcommercecloud.atlassian.net/browse/INT-7573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(payment): INT-7573 Add config of Access Worldpay GooglePay

- packages/core/src/app/payment/paymentMethod/AdyenV2CardValidation.spec.tsx
- packages/core/src/app/payment/paymentMethod/AdyenV2CardValidation.tsx
- packages/core/src/app/payment/paymentMethod/AdyenV3CardValidation.spec.tsx
- packages/core/src/app/payment/paymentMethod/AdyenV3CardValidation.tsx
I removed the behavior to automatically disable the submit button when the form loads
Place Order button on checkout is disabled when a customer with a stored credit card deletes, and re-adds card on checkout. The issue also occurs if deleting the stored card, and trying to use a different card with Adyen(non-stored).
[video how it worked before the changes](https://github.com/bigcommerce/checkout-js/assets/130754705/b7ac8249-2e1e-44d9-becf-434c81a5fcd4)
After the changes:
[Here's the behavior now](https://github.com/bigcommerce/checkout-js/assets/130754705/1a4d05df-78cb-4dd2-a774-54723b9849d6)
> fix(checkout): PI-48 Place Order button is disabled when customer with stored credit card deletes and re-adds card

- package-lock.json
- package.json
Update checkout-js with this PR:
https://github.com/bigcommerce/checkout-sdk-js/pull/1989
> feat(payment): PAYPAL-2451 bump checkout-sdk

- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Text "Pay over time" removed from the Clearpay
In the BigCommerce payment integration we currently use the copy “Pay over time” next to the Clearpay logo (see image below). This is no longer approved language for Clearpay UK merchants and needs to be removed before the FCA June 1st deadline. No need to replace the language with something else
> fix(checkout): PI-147 remove "Pay over time" text from the Clearpay

- package-lock.json
- package.json
Add swc core to dev dependency as it is used for builds
Builds fail on different machine types due to swc core not being compatible with operating systems. Need to order this to dev dependencies to get builds working as expected.
- CI
> chore(other): CHECKOUT-000 Add swc core to dev dependency as it is used for builds

- package-lock.json
- package.json
Release of the  https://github.com/bigcommerce/checkout-sdk-js/pull/1988
Due to the absence of the redirect on the adyen v2 3ds2 check
tested manually
> fix(checkout): PI-101 3ds2 redirect fix for adyen v3

- packages/paypal-commerce-integration/src/index.ts
Updated import path for papal commerce venmo payment strategy in paypal commerce integration package index file
There was an issue with PayPalCommerceVenmoPaymentMethod component rendering (it could not be defined due to the mistake in import groups)
Unit tests
Manual tests
> fix(payment): PAYPAL-2575 fixed the issue with PayPalCommerceVenmoPaymentMethod component rendering

- package-lock.json
- package.json
To release changes in the prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/2007
https://github.com/bigcommerce/checkout-sdk-js/pull/1993
https://github.com/bigcommerce/checkout-sdk-js/pull/1998
Unit tests
CI tests
> chore(payment): PAYPAL-2575 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout sdk to latest version
Release https://github.com/bigcommerce/checkout-sdk-js/commit/9e849d82259f8322bed0b71311ec4c11572b7dd9
CI 
> chore(other): CHECKOUT-000 Update checkout SDK

- packages/checkout-button-integration/src/CheckoutButton.tsx
- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
Remove default fallback for button resolving.
SInce we have moved to using buttons from packages, the default button is always rendered. This can cause an issue for custom buttons such as apple pay.
- CI
> fix(payment): CHECKOUT-000 Remove default button rendering for V2 components

- jest-setup.ts
- packages/braintree-integration/src/components/BraintreeAchPaymentForm/BraintreeAchPaymentForm.tsx
- packages/braintree-integration/src/components/MandateText/MandateText.tsx
- packages/core/src/app/payment/PaymentSubmitButton.tsx
- packages/core/src/app/payment/paymentMethod/CreditCardPaymentMethod.tsx
- packages/core/src/app/payment/storedInstrument/AccountInstrumentSelect.tsx
- packages/core/src/app/ui/dropdown/DropdownTrigger.test.tsx
- packages/core/src/app/ui/icon/IconBolt.tsx
- packages/instrument-utils/src/storedInstrument/AccountInstrumentFieldset/AccountInstrumentFieldset.tsx
- packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.tsx
- packages/instrument-utils/src/storedInstrument/ManageAccountInstrumentsTable/ManageAccountInstrumentsTable.tsx
- packages/instrument-utils/src/storedInstrument/ManageAccountInstrumentsTable/__snapshots__/ManageAccountInstrumentsTable.spec.tsx.snap
- packages/instrument-utils/src/storedInstrument/ManageAchInstrumentsTable/ManageAchInstrumentsTable.tsx
- packages/instrument-utils/src/storedInstrument/ManageAchInstrumentsTable/__snapshots__/ManageAchInstrumentsTable.test.tsx.snap
- packages/instrument-utils/src/storedInstrument/ManageCardInstrumentsTable/ManageCardInstrumentsTable.tsx
- packages/instrument-utils/src/storedInstrument/ManageCardInstrumentsTable/__snapshots__/ManageCardInstrumentsTable.spec.tsx.snap
- packages/instrument-utils/src/storedInstrument/ManageInstrumentsModal/ManageInstrumentsModal.tsx
- packages/paypal-commerce-integration/src/components/PayPalCommercePaymentMethodComponent.test.tsx
- packages/ui/src/dropdown/DropdownTrigger.test.tsx
- packages/ui/src/form/Fieldset/Fieldset.tsx
- packages/ui/src/loading/LoadingOverlay.tsx
- packages/ui/src/modal/Modal.tsx
Re-mapping `data-testid` to `data-test` 
I think that we using testid in wrong way, because we're duplicating usage of same attribute with different name
To avoid maintaining of two test IDs I've done re-mapping `data-testid` to `data-test` 
before:
after:
Units
> tech(checkout): PI-000 re-map test id for RTL

- package-lock.json
- package.json
Bump checkout-sdk from [v1.386.0 to v1.386.1](https://github.com/bigcommerce/checkout-sdk-js/compare/v1.386.0...v1.386.1)
To release https://github.com/bigcommerce/checkout-sdk-js/pull/1992
> chore(payment): INT-7650 Bump @bigcommerce/checkout-sdk to 1.386.1

- package-lock.json
- package.json
To deliver checkout-sdk-js changes 
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2015
> feat(payment): PAYPAL-2449 bump checkout-sdk-js version

- package-lock.json
- package.json
Release of stored cards for bluesnap direct
Due to the release of https://github.com/bigcommerce/checkout-sdk-js/pull/2002
units/manual
> feat(checkout): PI-42 bumped checkout-sdk version

- package-lock.json
- package.json
Bump checkout sdk js version.
https://github.com/bigcommerce/checkout-sdk-js/pull/2013
https://github.com/bigcommerce/checkout-sdk-js/pull/2014
https://github.com/bigcommerce/checkout-sdk-js/pull/1999
To keep checkout sdk js dependency up to date.
> chore(payment): PAYPAL-2618 bump checkout-sdk version

- packages/braintree-integration/src/BraintreeAchPaymentMethod.test.tsx
- packages/braintree-integration/src/BraintreeAchPaymentMethod.tsx
- packages/braintree-integration/src/components/AchFormFields/AchFormFields.tsx
- packages/braintree-integration/src/components/BraintreeAchPaymentForm/BraintreeAchPaymentForm.test.tsx
- packages/braintree-integration/src/components/BraintreeAchPaymentForm/BraintreeAchPaymentForm.tsx
- packages/braintree-integration/src/components/BraintreeAchPaymentForm/braintreeAchPaymentFormConfig.ts
- packages/braintree-integration/src/components/MandateText/MandateText.tsx
- packages/braintree-integration/src/validation-schemas/getBraintreeAchValidationSchema.ts
- packages/braintree-integration/src/validation-schemas/index.tsx
- packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.test.tsx
- packages/instrument-utils/src/storedInstrument/AccountInstrumentSelect/AccountInstrumentSelect.tsx
Removed billing address from Braintree ACH Form
Remove billing address fields from the ACH payment component within Payments step of checkout. Shoppers should use our native billing address form on the checkout page. 
Depends:
https://github.com/bigcommerce/checkout-sdk-js/pull/2014 
https://github.com/bigcommerce/checkout-sdk-js/pull/2013
> fix(payment): PAYPAL-2402 Removed billing address from Braintree ACH Form

- package-lock.json
- package.json
Release of https://github.com/bigcommerce/checkout-sdk-js/pull/2016
Due to the release of https://github.com/bigcommerce/checkout-sdk-js/pull/2016
Manually
> fix(checkout): PI-294 bump sdk for adyen v3 stored card fix

- package-lock.json
- package.json
Release of [bigcommerce/checkout-sdk#2008](https://github.com/bigcommerce/checkout-sdk-js/pull/2008)
To release the above change
See the testing section on the above PR
> chore(payment): bump sdk for PI-120 Autofilling of holderName to be configurable

- package-lock.json
- package.json
- packages/core/src/app/payment/Payment.tsx
- Fire analytics selectedPaymentMethod event when payment methods are loaded
- Bump checkout-sdk-js version
Previously this event was triggered in the `componentDidMount` right away. However, at this point both `selectedMethod` and `defaultMethod` are `undefined`. This causes issue when the `analyticsTracker.selectedPaymentMethod` does not do anything on page loading. This can be fixed by moving this call after payment methods are actually loaded
Manually on dev store
[DATA-10928]: https://bigcommercecloud.atlassian.net/browse/DATA-10928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: DATA-10928 Fire analytics selectedPaymentMethod event when payment methods are loaded

- package-lock.json
- package.json
Bump up checkout-sdk to release recent changes:
[https://github.com/bigcommerce/checkout-sdk-js/pull/2025](https://github.com/bigcommerce/checkout-sdk-js/pull/2025)
manual testing and unit test
> chore(checkout): PAYPAL-2680 bump checkout-sdk-js

- packages/core/src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Sezzle payment text was overflowing from the payment modal on checkout page on mobile devices. Now when text can't be fully displayed it is hidden.
Before changes:
https://github.com/bigcommerce/checkout-js/assets/130039975/339643b0-765a-4e26-bcfd-2f3cbf5c0a75
After changes:
https://github.com/bigcommerce/checkout-js/assets/130039975/a42e4761-6b3f-4d04-a62f-0a453b08b940
> feat(payment): PI-99 [Sezzle] - Text is overflowing and cropped for the Sezzle Payment gateway on mobile.

- package-lock.json
- package.json
checkout-sdk-js PR:https://github.com/bigcommerce/checkout-sdk-js/pull/2031
> fix(payment): PAYPAL-2502 bump checkout-sdk-js version

- package-lock.json
- package.json
Bump checkout-sdk `v1.395.0`.
- https://github.com/bigcommerce/checkout-sdk-js/pull/2028
- CI checks.
> chore(checkout): CHECKOUT-7537 Bump checkout-sdk v1.395.0

- .github/CODEOWNERS
Update checkout team github name in codeowners.
Conform to new standards for team names.
N/A
> chore(other): CHECKOUT-000 Update team name

- package-lock.json
- package.json
to release changes:
[fix(payments): PAYPAL-2634 fixed issue when teardown is called twice](https://github.com/bigcommerce/checkout-sdk-js/pull/2036)
Manually tested and unit test
> chore(checkout): PAYPAL-2502 bump checkout-sdk-js

- package-lock.json
- package.json
- packages/test-framework/src/fixture/pageObject/playwright/PollyObject.ts
- packages/test-utils/src/checkout.mock.ts
Bump checkout-sdk `v1.396.1`.
Release latest SDK change(s):
- https://github.com/bigcommerce/checkout-sdk-js/pull/2042
- CI checks.
> chore(order): DATA-11056 Bump checkout-sdk v1.396.1

- package-lock.json
- package.json
Bump checkout-sdk version from 1.397.0 to 1.398.0.
https://github.com/bigcommerce/checkout-sdk-js/pull/2044
To keep checkout-sdk dependency up to date
Unit tests
Manual tests
> chore(payment): PAYPAL-2690 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout-sdk version to 1.399.0
https://github.com/bigcommerce/checkout-sdk-js/pull/2033
> chore(payment): PAYPAL-2476 bump checkout-sdk version

- packages/core/src/app/payment/storedInstrument/isInstrumentCardCodeRequired.spec.ts
- packages/core/src/app/payment/storedInstrument/isInstrumentCardCodeRequired.ts
- packages/instrument-utils/src/guards/isInstrumentCardCodeRequired/index.ts
- packages/instrument-utils/src/guards/isInstrumentCardCodeRequired/isInstrumentCardCodeRequired.spec.ts
- packages/instrument-utils/src/guards/isInstrumentCardCodeRequired/isInstrumentCardCodeRequired.ts
Do not show cvv validation field for specific providers
Some providers don't require cvv validation for stored cards(like Bluesnap), so that is why I've made these changes
Before:
Previously checkout ask to validate CVV code for digital items
After:
After the changes we can skip CVV for some providers
> feat(checkout): PI-287 hide cvv validation field for specific providers

- package-lock.json
- package.json
Bump checkout-sdk `v1.401.0`.
- https://github.com/bigcommerce/checkout-sdk-js/pull/2050
- https://github.com/bigcommerce/checkout-sdk-js/pull/2061
- CI checks.
> chore(checkout): checkout-7538 Bump checkout-sdk v1.401.0

- package-lock.json
- package.json
Bump **checkout-sdk** version
https://github.com/bigcommerce/checkout-sdk-js/pull/2052
https://github.com/bigcommerce/checkout-sdk-js/pull/2058
To keep **checkout-sdk** dependency up to date
All test passed
> chore(payment): PAYPAL-2719 bump checkout-sdk version

- package-lock.json
- package.json
Bump checkout sdk version.
To keep checkout-sdk dependency up to date.
The release contains: 
https://github.com/bigcommerce/checkout-sdk-js/pull/2065
https://github.com/bigcommerce/checkout-sdk-js/pull/2063
https://github.com/bigcommerce/checkout-sdk-js/pull/2056
Unit tests
CI tests
Manual tests
> chore(payment): PAYPAL-2725 bump checkout sdk version

- package-lock.json
- package.json
Bump checkout-sdk `v1.405.2`.
- https://github.com/bigcommerce/checkout-sdk-js/pull/2069
- CI checks.
> chore(checkout): CHECKOUT-7624 Bump checkout-sdk v1.405.2

- packages/core/src/app/payment/Payment.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceAPMsPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceAPMsPaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCreditPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceCreditPaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommercePaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommercePaymentMethod.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceVenmoPaymentMethod.test.tsx
- packages/paypal-commerce-integration/src/PayPalCommerceVenmoPaymentMethod.tsx
- packages/paypal-commerce-integration/src/components/PayPalCommercePaymentMethodComponent.test.tsx
- packages/paypal-commerce-integration/src/components/PayPalCommercePaymentMethodComponent.tsx
Fixed the issue with PayPal button shows up when the customer tries to buy free product
The issue was about PayPalCommercePaymentMethodComponent re-rendering when user clicks on the Store Credit checkbox, so I added a render logic in a wrapper of this component.
> fix(payment): PAYPAL-2595 PayPal button shows on store credit

- packages/core/src/app/customer/CheckoutButtonContainer.spec.tsx
- packages/core/src/app/customer/CheckoutButtonContainer.tsx
- packages/core/src/app/customer/__snapshots__/CheckoutButtonContainer.spec.tsx.snap
As a shopper who just applied 100% discount coupon during the checkout, we don’t want to see PayPal wallet buttons anymore without having to reload the page manually, so that I can complete the purchase without accidentally clicking on the button that doesn’t work anymore.
https://github.com/bigcommerce/checkout-js/assets/130665807/86c8c1f9-0746-4a4f-a099-2cfd362e6474
> feat(payment): PAYPAL-2752 render wallet buttons depends on coupon

- package-lock.json
- package.json
Bump `checkout-sdk-js` version
To keep up to date
Includes PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2072
> chore(payment): PAYPAL-2634 bump checkout-sdk

- package-lock.json
- package.json
To apply checkout-sdk-js changes
checkout-sdk-js PR : https://github.com/bigcommerce/checkout-sdk-js/pull/2080
> feat(payment): PAYPAL-2744 bump checkout-sdk-js version

- package-lock.json
- package.json
Release of the https://github.com/bigcommerce/checkout-sdk-js/pull/2077
...
...
> chore(payment): PI-585 bump checkout-sdk

- packages/core/src/app/payment/paymentMethod/AdyenV2PaymentMethod.tsx
- packages/core/src/app/payment/paymentMethod/AdyenV3PaymentMethod.tsx
Removed lodash from Adyen files
Lodash imported, but not used
reported here https://github.com/bigcommerce/checkout-js/issues/1400
units
> refactor(checkout): PI-0 removed lodash from Adyen files

- package-lock.json
- package.json
The release contains: 
https://github.com/bigcommerce/checkout-sdk-js/pull/2075
https://github.com/bigcommerce/checkout-sdk-js/pull/2082
https://github.com/bigcommerce/checkout-sdk-js/pull/2083
https://github.com/bigcommerce/checkout-sdk-js/pull/2086
https://github.com/bigcommerce/checkout-sdk-js/pull/2087
https://github.com/bigcommerce/checkout-sdk-js/pull/2078
To keep checkout sdk dependency up to date
Unit tests
Manual tests
> chore(payment): PAYPAL-2731 bump checkout sdk version

- package-lock.json
- package.json
To apply changes from checkout-sdk-js
checkout-sdk-js PR: https://github.com/bigcommerce/checkout-sdk-js/pull/2040
> feat(payment): PAYPAL-1545 bump checkout-sdk-js version

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2093
To keep checkout sdk dependency version up to date
Unit tests
Manual tests
> chore(payment): PAYPAL-2803 bump checkout sdk version

- package-lock.json
- package.json
https://github.com/bigcommerce/checkout-sdk-js/pull/2092
https://github.com/bigcommerce/checkout-sdk-js/pull/2094
To keep checkout sdk dependency up to date
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-2804 bump checkout sdk js version

- packages/core/src/app/address/googleAutocomplete/AddressSelector.spec.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelectorCA.ts
- packages/core/src/app/address/googleAutocomplete/AddressSelectorFactory.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteResult.mock.ts
- packages/core/src/app/address/googleAutocomplete/googleAutocompleteTypes.ts
Fix issue where Google maps API sometimes fills the incorrect value in the city field.
This was raised in an issue here https://github.com/bigcommerce/checkout-js/issues/1390.
- circle
- screenshot
> fix(shipping): CHECKOUT-7627 Google AddressSelector sometimes autofills the wrong city for Canada addresses

- packages/core/src/app/customer/SubscribeField.tsx
- packages/core/src/app/customer/__snapshots__/Customer.spec.tsx.snap
- packages/core/src/app/customer/__snapshots__/GuestForm.spec.tsx.snap
- packages/core/src/app/customer/__snapshots__/StripeGuestForm.test.tsx.snap
Changed TranslatedString to TranslatedHtml on the customer subscribe field.
- Taken from https://github.com/bigcommerce/checkout-js/pull/1271
Raised here https://github.com/bigcommerce/checkout-js/issues/1270
- CI
> fix(customer): CHECKOUT-000 Replace translated string with html

- package-lock.json
- package.json
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.test.tsx
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/BraintreeAcceleratedCheckoutPaymentMethod.tsx
https://github.com/bigcommerce/checkout-sdk-js/pull/2095
https://github.com/bigcommerce/checkout-sdk-js/pull/2098
https://github.com/bigcommerce/checkout-sdk-js/pull/2099
https://github.com/bigcommerce/checkout-sdk-js/pull/2096
https://github.com/bigcommerce/checkout-sdk-js/pull/2088
To keep checkout-sdk dependency up to date
Manual tests
CI
> chore(payment): PAYPAL-2737 bump checkout-sdk version

- packages/core/src/app/address/AddressSelectButton.tsx
Adding an "onBlur" property to the address select button to set the "aria-expanded" property to false when the element loses focus.
Currently when a user changes focus to another element, the aria-expanded property does not change back to false. This causes problems for users who navigate checkout using screen reader software.
Before:
After:
Additional note:
I am not sure if it would be better to track when the user clicks off the address select element instead of when it loses focus.
> fix(checkout): CHECKOUT-7150 aria-expanded property does not toggle based on the associated drop-down

- package-lock.json
- package.json
As above
Update checkout sdk version to latest that bumps sdk dependencies to use node 18.
CI
> chore(others): CHECKOUT-000 Update checkout sdk

- package-lock.json
- package.json
Bump checkout sdk version.
https://github.com/bigcommerce/checkout-sdk-js/pull/2114
https://github.com/bigcommerce/checkout-sdk-js/pull/2112
To keep checkout sdk dependency up to date.
Unit tests
Manual tests
CI
> chore(payment): PAYPAL-2847 bump checkout sdk version

- package-lock.json
- package.json
Release contains changes from checkout sdk:
https://github.com/bigcommerce/checkout-sdk-js/pull/2108
To keep checkout sdk dependency up to date
Unit tests
Manual tests
QA tests
CI
> chore(payment): PAYPAL-2827 bump checkout sdk version

- package-lock.json
- package.json
- packages/hosted-credit-card-integration/src/HostedCreditCardPaymentMethod.tsx
Bluesnapdirect 3ds challenge for stored cards without hosted fields
https://github.com/bigcommerce/checkout-sdk-js/pull/2041
Because 3ds challenge doesn't appear for stored cards without bluesnap hosted fields. That's why we need to implement manual trigger of 3ds challenge for stored card without card number validation
Tested manually/units
> feat(checkout): PI-286 added bigpayToken to the loadPaymentMethod params

- package-lock.json
- package.json
Release contains:
https://github.com/bigcommerce/checkout-sdk-js/pull/2123
https://github.com/bigcommerce/checkout-sdk-js/pull/2119
To keep checkout-sdk dependency up to date
Unit tests
Manual tests
> chore(payment): PAYPAL-2852 bump checkout-sdk version

- packages/core/src/app/address/AddressSelect.spec.tsx
- packages/core/src/app/address/AddressSelect.tsx
- packages/core/src/app/address/AddressSelectButton.tsx
- packages/core/src/app/address/PayPalAxo/index.ts
- packages/core/src/app/address/PayPalAxo/usePayPalConnectAddress.test.tsx
- packages/core/src/app/address/PayPalAxo/usePayPalConnectAddress.ts
- packages/core/src/app/address/PayPalAxo/utils.ts
- packages/core/src/app/address/StaticAddress.scss
- packages/core/src/app/address/StaticAddress.spec.tsx
- packages/core/src/app/address/StaticAddress.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodId.ts
- packages/core/src/app/shipping/ShippingForm.tsx
- packages/core/src/app/shipping/StaticConsignment.spec.tsx
- packages/core/src/app/shipping/StaticConsignment.tsx
- packages/core/src/app/shipping/__snapshots__/StaticConsignment.spec.tsx.snap
- packages/core/src/scss/settings/foundation/forms/_settings.scss
Add labels for PayPal Connect addresses
We need to show for shoppers addresses which we get from PayPal Connect.
BC - guest
PP Connect - guest
https://github.com/bigcommerce/checkout-js/assets/9430298/1027b77f-e1df-4c18-ac96-5bc6bf3c91da
BC - registered
PP Connect - guest
https://github.com/bigcommerce/checkout-js/assets/9430298/6894e174-03ed-4c99-bac2-7a09b3ba5bd5
BC - guest
PP Connect - registered
https://github.com/bigcommerce/checkout-js/assets/9430298/8291b50a-99bb-4f65-9c27-fe50553cdc0d
BC - registered
PP Connect - registered (with address merge)
https://github.com/bigcommerce/checkout-js/assets/9430298/aa14d130-f221-4fbb-805e-c65ee0d44c36
> feat(payment): PAYPAL-2732 PayPalAxo Shipping step

- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeAcceleratedCheckoutCreditCardForm.scss
- packages/braintree-integration/src/BraintreeAcceleratedCheckout/components/BraintreeAcceleratedCheckoutCreditCardForm.tsx
Updated braintree paypal connect form margins to place the form in right place
PayPal Connect Credit Card component has white background and inner padding. The component has some differences between other CC forms that we have in out themes, so we need to make it almost the same as in Cornerstone (remove inner padding + make background color transparent)
Unit tests
Manual tests
> feat(payment): PAYPAL-2856 updated braintree paypal connect form margins to place the form in right place

- package-lock.json
- package.json
To release this changes:
https://github.com/bigcommerce/checkout-sdk-js/pull/2121
https://github.com/bigcommerce/checkout-sdk-js/pull/2127
https://github.com/bigcommerce/checkout-sdk-js/pull/2116
Unit tests
Manual tests
Here is a screenshot of checkout sdk loader:
> chore(payment): PAYPAL-2730 bump checkout sdk js version

- packages/core/src/app/billing/BillingForm.spec.tsx
- packages/core/src/app/billing/BillingForm.tsx
- packages/core/src/app/billing/StaticBillingAddress.spec.tsx
- packages/core/src/app/billing/StaticBillingAddress.tsx
Add labels for PayPal Connect addresses on Billing step
We need to show for shoppers addresses which we get from PayPal Connect.
https://github.com/bigcommerce/checkout-js/assets/9430298/d2487985-c33d-4664-98bf-0d30532a605d
Unit and manually tested
> feat(payment): PAYPAL-2733 PayPalAxo Billing step

- .github/PULL_REQUEST_TEMPLATE.md
- packages/core/src/app/order/OrderSummaryModal.spec.tsx
- packages/core/src/app/order/OrderSummaryModal.tsx
Fix display issue of pick list line items in cart mobile summary view.
Pick list items are displayed as separate line items in mobile view, which leads to a poor and confusing user experience.
- Screenshot
Before
After
> fix(order): CHECKOUT-4355 Fix display issue of pick list items

- package-lock.json
- package.json
To deliver a list of PRs:
https://github.com/bigcommerce/checkout-sdk-js/pull/2120
https://github.com/bigcommerce/checkout-sdk-js/pull/2130
Unit tests
Manual tests
Checkout sdk loader with 1.149 version is available on cdn:
> chore(payment): PAYPAL-2868 bump checkout sdk

- package-lock.json
- package.json
As part of the release last checkout sdk updates:
https://github.com/bigcommerce/checkout-sdk-js/pull/2135
https://github.com/bigcommerce/checkout-sdk-js/pull/2132
https://github.com/bigcommerce/checkout-sdk-js/pull/2133
https://github.com/bigcommerce/checkout-sdk-js/pull/2134
https://github.com/bigcommerce/checkout-sdk-js/pull/2107
Unit tests
Manual tests
Here is a screenshot of [checkout sdk loader](https://checkout-sdk.bigcommerce.com/v1/loader-v1.431.0.js):
> chore(payment): PAYPAL-2873 bump checkout sdk version

- packages/core/src/app/customer/Customer.spec.tsx
- packages/core/src/app/customer/Customer.tsx
- packages/core/src/app/customer/LoginForm.tsx
Added execution method call right after sign in customer for BraintreeAcceleratedCheckout payment method
To be able to trigger PayPal Connect customer authentication
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-js/assets/25133454/9938238c-b159-4a4f-a4b4-22d395413e8f
> feat(payment): PAYPAL-2730 added execution method call after sign in customer for BraintreeAcceleratedCheckout payment method

- packages/core/src/app/payment/paymentMethod/PaymentMethodId.ts
- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.test.tsx
- packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
- packages/locale/src/translations/en.json
Fixed credit card display name localization
Previously we used non-localized version due to the limitation of getPaymentMethodName method
Manully
> fix(checkout): PI-122 fixed credit card display name localization

- packages/core/src/app/address/googleAutocomplete/GoogleAutocomplete.tsx
- packages/core/src/app/ui/autocomplete/Autocomplete.spec.tsx
- packages/core/src/app/ui/autocomplete/Autocomplete.tsx
Update our Google Autocomplete implementation so that an address in the dropdown list is not highlighted automatically.
The shopper believes the highlighted address is selected, but they are unaware that they must click on the item to select it. As a result, several businesses complain that some orders include an incomplete street address.
https://github.com/bigcommerce/checkout-js/assets/88361607/df2f5df9-011f-49bb-8537-66cb1285fafc
> feat(checkout): CHECKOUT-6837 Disable automatic highlighting

- package-lock.json
- package.json
As part of release next pr:
https://github.com/bigcommerce/checkout-sdk-js/pull/2140
Unit tests
Manual tests
Here is a screenshot of checkout sdk loader with current version:
> chore(payment): PAYPAL-2851 bump checkout sdk version

- package-lock.json
- package.json
Release of validation fix for stored bluesnap direct card verification fields
https://github.com/bigcommerce/checkout-sdk-js/pull/2139
Due to the absence UI notifications in validation error cases
units/manually
> fix(checkout): PI-657 fixed validation for stored bluesnap direct card verification fields

- package-lock.json
- package.json
Release https://github.com/bigcommerce/checkout-sdk-js/commit/4417bfc9a3f3b77d312d8785f08957d9a4e29313
> chore(checkout): CHECKOUT-6883 Bump sdk

- packages/core/src/app/checkout/Checkout.tsx
Improve the conditions for throwing `ShippingOptionExpiredError`.
After a shopper refreshes the checkout page, trying to remove a free shipping coupon doesn't work properly because the checkout fails to trigger the expected `ShippingOptionExpiredError`.
This PR fixes the problem above.
https://github.com/bigcommerce/checkout-js/assets/88361607/45323035-479f-4880-babb-b4f8c642a333
https://github.com/bigcommerce/checkout-js/assets/88361607/374bf8f4-5c73-4945-bb92-511bf558a1f0
> fix(checkout): CHECKOUT-7656 Rectify vanishing shipping step
